productTag:
  type: object
  description: 商品タグ情報
  properties:
    id:
      type: string
      description: 商品タグID
    name:
      type: string
      description: 商品タグ名(32文字まで)
    createdAt:
      type: integer
      format: int64
      description: 登録日時 (unixtime)
    updatedAt:
      type: integer
      format: int64
      description: 更新日時 (unixtime)
  required:
  - id
  - name
  - createdAt
  - updatedAt
  example:
    id: 'kSByoE6FetnPs5Byk3a9Zx'
    name: '贈答品'
    createdAt: 1640962800
    updatedAt: 1640962800
