productType:
  type: object
  description: 品目情報
  properties:
    id:
      type: string
      description: 品目ID
    name:
      type: string
      description: 品目名
    iconUrl:
      type: string
      description: アイコンURL
    categoryId:
      type: string
      description: 商品種別ID
    createdAt:
      type: integer
      format: int64
      description: 登録日時 (unixtime)
    updatedAt:
      type: integer
      format: int64
      description: 更新日時 (unixtime)
  required:
  - id
  - name
  - iconUrl
  - categoryId
  - createdAt
  - updatedAt
  example:
    id: 'kSByoE6FetnPs5Byk3a9Zx'
    name: 'じゃがいも'
    iconUrl: 'https://and-period.jp/icon.png'
    categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
    createdAt: 1640962800
    updatedAt: 1640962800
