product:
  type: object
  description: 商品情報
  properties:
    id:
      type: string
      description: 商品ID
    name:
      type: string
      description: 商品名
    description:
      type: string
      description: 商品説明
    public:
      type: boolean
      description: 公開フラグ
    status:
      $ref: './../../../openapi.yaml#/components/schemas/productStatus'
    coordinatorId:
      type: string
      description: コーディネータID
    producerId:
      type: string
      description: 生産者ID
    categoryId:
      type: string
      description: 商品種別ID
    productTypeId:
      type: string
      description: 品目ID
    productTagIds:
      type: array
      description: 商品タグ一覧
      items:
        type: string
        description: 商品タグID
    media:
      type: array
      items:
        type: object
        properties:
          url:
            type: string
            description: メディアURL
          isThumbnail:
            type: boolean
            description: サムネイルとして使用(1つまで)
        required:
        - url
        - isThumbnail
    price:
      type: integer
      format: int64
      description: 販売価格（税込）
    cost:
      type: integer
      format: int64
      description: 原価（税込）
    inventory:
      type: integer
      format: int64
      description: 在庫数
    weight:
      type: number
      format: double
      description: 重量(kg:少数第1位まで)
    itemUnit:
      type: string
      description: 数量単位
    itemDescription:
      type: string
      description: 数量単位説明
    deliveryType:
      $ref: './../../../openapi.yaml#/components/schemas/deliveryType'
    recommendedPoint1:
      type: string
      description: おすすめポイント1(128文字まで)
    recommendedPoint2:
      type: string
      description: おすすめポイント2(128文字まで)
    recommendedPoint3:
      type: string
      description: おすすめポイント3(128文字まで)
    expirationDate:
      type: integer
      format: int64
      description: 賞味期限(単位:日)
    storageMethodType:
      $ref: './../../../openapi.yaml#/components/schemas/storageMethodType'
    box60Rate:
      type: integer
      format: int64
      description: 箱の占有率(サイズ:60)
    box80Rate:
      type: integer
      format: int64
      description: 箱の占有率(サイズ:80)
    box100Rate:
      type: integer
      format: int64
      description: 箱の占有率(サイズ:100)
    originPrefectureCode:
      $ref: './../../../openapi.yaml#/components/schemas/prefecture'
    originCity:
      type: string
      description: 原産地(市区町村)
    startAt:
      type: integer
      format: int64
      description: 販売開始日時 (unixtime)
    endAt:
      type: integer
      format: int64
      description: 販売終了日時 (unixtime)
    createdAt:
      type: integer
      format: int64
      description: 登録日時 (unixtime)
    updatedAt:
      type: integer
      format: int64
      description: 更新日時 (unixtime)
  required:
  - id
  - name
  - description
  - public
  - status
  - coordinatorId
  - producerId
  - categoryId
  - productTypeId
  - productTagIds
  - media
  - price
  - cost
  - inventory
  - weight
  - itemUnit
  - itemDescription
  - deliveryType
  - recommendedPoint1
  - recommendedPoint2
  - recommendedPoint3
  - expirationDate
  - storageMethodType
  - box60Rate
  - box80Rate
  - box100Rate
  - originPrefectureCode
  - originCity
  - startAt
  - endAt
  - createdAt
  - updatedAt
  example:
    id: 'kSByoE6FetnPs5Byk3a9Zx'
    name: '新鮮なじゃがいも'
    description: '新鮮なじゃがいもをお届けします。'
    public: true
    status: 2
    coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
    producerId: 'kSByoE6FetnPs5Byk3a9Zx'
    categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
    productTypeId: 'kSByoE6FetnPs5Byk3a9Zx'
    productTagIds: ['kSByoE6FetnPs5Byk3a9Zx']
    media:
    - url: 'https://and-period.jp/thumbnail01.png'
      isThumbnail: true
    - url: 'https://and-period.jp/thumbnail02.png'
      isThumbnail: false
    price: 2500
    cost: 200
    inventory: 30
    weight: 2.5
    itemUnit: '袋'
    itemDescription: '1袋あたり2.5kgのじゃがいも'
    deliveryType: 1
    recommendedPoint1: 'シャリシャリほろ苦がクセになる！'
    recommendedPoint2: 'シャリシャリほろ苦がクセになる！'
    recommendedPoint3: 'シャリシャリほろ苦がクセになる！'
    expirationDate: 7
    storageMethodType: 1
    box60Rate: 80
    box80Rate: 50
    box100Rate: 40
    originPrefectureCode: 13
    originCity: '彦根市'
    startAt: 1640962800
    endAt: 1640962800
    createdAt: 1640962800
    updatedAt: 1640962800
