producer:
  type: object
  description: 生産者情報
  properties:
    id:
      type: string
      description: 生産者ID
    status:
      $ref: './../../../openapi.yaml#/components/schemas/adminStatus'
    coordinatorId:
      type: string
      description: 担当コーディネータID
    lastname:
      type: string
      description: 姓
    firstname:
      type: string
      description: 名
    lastnameKana:
      type: string
      description: 姓(かな)
    firstnameKana:
      type: string
      description: 名(かな)
    username:
      type: string
      description: 生産者名
    email:
      type: string
      description: メールアドレス
    phoneNumber:
      type: string
      description: 電話番号 (国際番号 + 電話番号)
    postalCode:
      type: string
      description: 郵便番号
    prefecture:
      $ref: './../../../openapi.yaml#/components/schemas/prefecture'
    city:
      type: string
      description: 市区町村
    addressLine1:
      type: string
      description: 町名・番地
    addressLine2:
      type: string
      description: ビル名・号室など
    profile:
      type: string
      description: プロフィール
    thumbnailUrl:
      type: string
      description: サムネイルURL
    thumbnails:
      type: array
      description: リサイズ済みサムネイルURL一覧
      items:
        type: object
        properties:
          url:
            type: string
            description: リサイズ済みサムネイルURL
          size:
            $ref: './../../../openapi.yaml#/components/schemas/imageSize'
        required:
        - url
        - size
    headerUrl:
      type: string
      description: ヘッダー画像URL
    headers:
      type: array
      description: リサイズ済みヘッダー画像URL一覧
      items:
        type: object
        properties:
          url:
            type: string
            description: リサイズ済みヘッダー画像URL
          size:
            $ref: './../../../openapi.yaml#/components/schemas/imageSize'
        required:
        - url
        - size
    promotionVideoUrl:
      type: string
      description: 紹介動画URL
    bonusVideoUrl:
      type: string
      description: 購入特典動画URL
    instagramId:
      type: string
      description: Instagramアカウント
    facebookId:
      type: string
      description: Facebookアカウント
    createdAt:
      type: integer
      format: int64
      description: 登録日時 (unixtime)
    updatedAt:
      type: integer
      format: int64
      description: 更新日時 (unixtime)
  required:
  - id
  - status
  - coordinatorId
  - coordinatorName
  - lastname
  - firstname
  - lastnameKana
  - firstnameKana
  - username
  - email
  - phoneNumber
  - postalCode
  - prefecture
  - city
  - addressLine1
  - addressLine2
  - profile
  - promotionVideoUrl
  - bonusVideoUrl
  - thumbnailUrl
  - thumbnails
  - headerUrl
  - headers
  - instagramId
  - facebookId
  - createdAt
  - updatedAt
  example:
    id: 'kSByoE6FetnPs5Byk3a9Zx'
    status: 2
    coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
    coordinatorName: '&.コーディネータ'
    lastname: '&.'
    firstname: '管理者'
    lastnameKana: 'あんどどっと'
    firstnameKana: 'かんりしゃ'
    username: '&.農園'
    email: 'test-user@and-period.jp'
    phoneNumber: '+819012345678'
    postalCode: '1000014'
    prefecture: 'tokyo'
    city: '千代田区'
    addressLine1: '永田町1-7-1'
    addressLine2: ''
    profile: '紹介文です。'
    thumbnailUrl: 'https://and-period.jp/thumbnail.png'
    thumbnails:
    - url: 'https://and-period.jp/thumbnail_240.png'
      size: 1
    - url: 'https://and-period.jp/thumbnail_675.png'
      size: 2
    - url: 'https://and-period.jp/thumbnail_900.png'
      size: 3
    headerUrl: 'https://and-period.jp/header.png'
    headers:
    - url: 'https://and-period.jp/header_240.png'
      size: 1
    - url: 'https://and-period.jp/header_675.png'
      size: 2
    - url: 'https://and-period.jp/header_900.png'
      size: 3
    promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
    bonusVideoUrl: 'https://and-period.jp/bonus.mp4'
    instagramId: 'instagram-id'
    facebookId: 'facebook-id'
    createdAt: 1640962800
    updatedAt: 1640962800
