name: setup node
description: 'Node.jsのセットアップ'

inputs:
  working-directory:
    description: '作業ディレクトリ'
    required: false
    default: '.'
  service:
    description: 'サービス名'
    required: true
    default: 'web'

runs:
  using: composite
  steps:
  - name: Node Version
    id: set-version
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      NODE_VERSION=$(cat .tool-versions | grep -E '^nodejs [0-9.]+$' | awk '{print substr($0, index($0, " ") + 1)}')
      echo "node-version=${NODE_VERSION}" >> $GITHUB_OUTPUT

  - name: Install pnpm
    uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
    with:
      version: 10.28.2

  - name: Setup Node.js
    uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
    with:
      node-version: ${{ steps.set-version.outputs.node-version }}
      # TODO: pnpm-lock.yaml をコミット後に cache: 'pnpm' を有効化する

  - name: Install
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: pnpm install --ignore-scripts
