version: 2

updates:
# api
- package-ecosystem: 'gomod'
  directory: '/api'
  schedule:
    interval: 'weekly'
    day: 'wednesday'
    time: '19:00'
    timezone: 'Asia/Tokyo'
  allow:
  - dependency-name: '*'
  ignore:
  - dependency-name: '*'
    update-types: ['version-update:semver-major']
  groups:
    dependencies:
      patterns:
      - "*"
  labels:
  - 'backend'
  - 'dependencies'
# web
- package-ecosystem: 'npm'
  directory: '/web/admin'
  schedule:
    interval: 'weekly'
    day: 'wednesday'
    time: '19:00'
    timezone: 'Asia/Tokyo'
  allow:
  - dependency-name: '*'
  ignore:
  - dependency-name: '*'
    update-types: ['version-update:semver-major']
  groups:
    dependencies:
      patterns:
      - "*"
  labels:
  - 'frontend'
  - 'dependencies'
- package-ecosystem: 'npm'
  directory: '/web/user'
  schedule:
    interval: 'weekly'
    day: 'wednesday'
    time: '19:00'
    timezone: 'Asia/Tokyo'
  allow:
  - dependency-name: '*'
  ignore:
  - dependency-name: '@nuxtjs/i18n'
  - dependency-name: '*'
    update-types: ['version-update:semver-major']
  groups:
    dependencies:
      patterns:
      - "*"
  labels:
  - 'frontend'
  - 'dependencies'
# other
- package-ecosystem: 'npm'
  directory: '/docs/swagger'
  schedule:
    interval: 'weekly'
    day: 'wednesday'
    time: '19:00'
    timezone: 'Asia/Tokyo'
  allow:
  - dependency-name: '*'
  groups:
    dependencies:
      patterns:
      - "*"
  labels:
  - 'docs'
  - 'dependencies'
- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: 'weekly'
    day: 'wednesday'
    time: '19:00'
    timezone: 'Asia/Tokyo'
  allow:
  - dependency-name: '*'
  groups:
    dependencies:
      patterns:
      - "*"
  labels:
  - 'workflow'
  - 'dependencies'
