import { defineStore } from 'pinia';

export const useProductStore = defineStore('product', {
  state: () => ({
    productsResponse: {
      products: [
        {
          id: 'vNpfY5NoPfa9iVcyAgS8qU',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: 'maPpNEY2KCDQXu5AKvPtTk',
          categoryId: 'vazPgxgPC6YnTgHHdjZNw1',
          productTypeId: 'cjNk1GPcUj42GVWboKJsUJ',
          productTagIds: [],
          name: '【瀬戸内の名産】赤土じゃがいも5キロ(40〜50個)',
          description: '瀬戸内海を臨む安芸津町(あきつ)は知る人ぞ知るじゃがいもの名産地✨\n\n潮風が運ぶミネラルたっぷりの赤土で育つじゃがいもの、表面が滑らかで白く綺麗な芋肌に目を奪われます👀\n\n5キロでも保存が効くので安心！四角いピンクの箱でお届けします😊\n\n▼3キロ品はこちら\nhttps://www.furumaru.and-period.co.jp/items/8AgsQyJmVevqYwwRDiuvw2\n\n火を通すとホクホク＆しっとり。ほんのり甘くて、食べごたえもバッチリです。\nしかも煮くずれしにくいので、いろんな料理に使いやすいのもポイント！素材のうまみが強いので、シンプルな料理でも大活躍です💪\n\n＜オススメの食べ方＞\n\n📌じゃがバター\n塩とバターだけで、ホクホク食感とやさしい甘みが引き立ちます。濡らしたキッチンペーパーとラップにくるんでレンチンでOK👌\n\n📌肉じゃが\n煮ても形が崩れにくく、だしのうまみがしっかり染み込む！つゆもサラッとしたまま不思議🤔\n\n📌チーズガレット\n香ばしく焼いた外側と、モチモチの中身がクセになる！赤土じゃがいもの濃い味がしっかり楽しめるおつまみ系レシピ。',
          status: 2,
          inventory: 93,
          weight: 5,
          itemUnit: '個',
          itemDescription: '5キロ',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/tic8TSBKJGWqGbdpi3h5z7.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/tic8TSBKJGWqGbdpi3h5z7.jpg',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/rH6Spgp1VbedBnXGn6xBSG.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/6gAETQJWTuXaoFwdL4jCfP.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/xzGvZAekQbWJQPQjr2Aurw.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/3vo31JhMxgs652BGarQWKK.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/4FhGGhJsxbWjryte6YPbQk.jpg',
              isThumbnail: false,
            },
          ],
          price: 2700,
          expirationDate: 30,
          recommendedPoint1: '地元の名産・安芸津の赤土じゃがいも',
          recommendedPoint2: 'ホクホク滑らかで素材の味が濃い',
          recommendedPoint3: 'ピンクの箱が可愛らしい',
          storageMethodType: 2,
          deliveryType: 1,
          box60Rate: 120,
          box80Rate: 100,
          box100Rate: 80,
          originPrefecture: '広島県',
          originCity: '東広島市',
          rate: {
            average: 4.9,
            count: 8,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 1,
              5: 7,
            },
          },
          startAt: 1749319870,
          endAt: 1757861940,
        },
        {
          id: '8AgsQyJmVevqYwwRDiuvw2',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: 'maPpNEY2KCDQXu5AKvPtTk',
          categoryId: 'vazPgxgPC6YnTgHHdjZNw1',
          productTypeId: 'cjNk1GPcUj42GVWboKJsUJ',
          productTagIds: [],
          name: '【瀬戸内の名産】赤土じゃがいも3キロ(20〜30個)',
          description: '瀬戸内海を臨む安芸津町(あきつ)は知る人ぞ知るじゃがいもの名産地✨\n\n潮風が運ぶミネラルたっぷりの赤土で育つじゃがいもの、表面が滑らかで白く綺麗な芋肌に目を奪われます👀\n\n3キロ箱はケーキを入れるような可愛らしいピンクの箱でお届けします😊\n\n▼5キロ品はこちら\nhttps://www.furumaru.and-period.co.jp/items/vNpfY5NoPfa9iVcyAgS8qU\n\n火を通すとホクホク＆しっとり。ほんのり甘くて、食べごたえもバッチリです。\nしかも煮くずれしにくいので、いろんな料理に使いやすいのもポイント！素材のうまみが強いので、シンプルな料理でも大活躍です💪\n\n＜オススメの食べ方＞\n\n📌じゃがバター\n塩とバターだけで、ホクホク食感とやさしい甘みが引き立ちます。濡らしたキッチンペーパーとラップにくるんでレンチンでOK👌\n\n📌肉じゃが\n煮ても形が崩れにくく、だしのうまみがしっかり染み込む！つゆもサラッとしたまま不思議🤔\n\n📌チーズガレット\n香ばしく焼いた外側と、モチモチの中身がクセになる！赤土じゃがいもの濃い味がしっかり楽しめるおつまみ系レシピ。',
          status: 2,
          inventory: 85,
          weight: 3,
          itemUnit: '個',
          itemDescription: '3キロ',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/jGz9QKPXWDKzUYSZQFqQa6.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/jGz9QKPXWDKzUYSZQFqQa6.jpg',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/6gAETQJWTuXaoFwdL4jCfP.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/xzGvZAekQbWJQPQjr2Aurw.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/6NqwDMynnf1cCASnbkBdp1.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/3vo31JhMxgs652BGarQWKK.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/4FhGGhJsxbWjryte6YPbQk.jpg',
              isThumbnail: false,
            },
          ],
          price: 2100,
          expirationDate: 30,
          recommendedPoint1: '地元の名産・安芸津の赤土じゃがいも',
          recommendedPoint2: 'ホクホク滑らかで素材の味が濃い',
          recommendedPoint3: 'ピンクの箱が可愛らしい',
          storageMethodType: 2,
          deliveryType: 1,
          box60Rate: 120,
          box80Rate: 100,
          box100Rate: 80,
          originPrefecture: '広島県',
          originCity: '東広島市',
          rate: {
            average: 4.8,
            count: 13,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 3,
              5: 10,
            },
          },
          startAt: 1749319870,
          endAt: 1757861940,
        },
        {
          id: 'hXuG7C5zAcg2B2UT1zaM1d',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: 'sZhADTu5Z4yUWnKjgcVU5t',
          categoryId: 'vazPgxgPC6YnTgHHdjZNw1',
          productTypeId: 'cjNk1GPcUj42GVWboKJsUJ',
          productTagIds: [],
          name: '【飲食店向け】瀬戸内・青ネギ５キロ',
          description: '東広島・安芸津町の瀬戸内海沿いで育った青ネギ。\n年中出荷可能で、見ただけで生き生きとしたシャキッと食感が特徴です。農家の甲斐さんは地元の牧場の牛糞堆肥を使った循環型農業を目指されています。\n\nお好み焼き、ラーメン、うどん、韓国料理など使い道はたくさん！採れたてなので冷蔵なら1週間ほどは食感も持つとのことです✨',
          status: 2,
          inventory: 100,
          weight: 5,
          itemUnit: '個',
          itemDescription: '５キロ',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/7p3gE94DSaZGeYMzwKgCLt.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/7p3gE94DSaZGeYMzwKgCLt.jpg',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/kfNBcSZVKgt4fnq1AEDX7d.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/xzQ7R3Dap3zpEoz3XjsweT.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/nMK58c2wjcS9GBAeKEzVo4.jpg',
              isThumbnail: false,
            },
          ],
          price: 3000,
          expirationDate: 10,
          recommendedPoint1: '瀬戸内の潮風を浴びた青ネギ',
          recommendedPoint2: 'シャキッと生き生きした食感',
          recommendedPoint3: '年中出荷可能！',
          storageMethodType: 3,
          deliveryType: 2,
          box60Rate: 150,
          box80Rate: 120,
          box100Rate: 100,
          originPrefecture: '広島県',
          originCity: '東広島市',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1746205200,
          endAt: 1767193140,
        },
        {
          id: 'tHs9MWB6z82ygcGZtNZz6R',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: 'abSyW5W7cZLKQoqKFXcW4V',
          categoryId: 'vazPgxgPC6YnTgHHdjZNw1',
          productTypeId: 'cjNk1GPcUj42GVWboKJsUJ',
          productTagIds: [],
          name: '【訳あり】旬のすぃーとアスパラ１キロ',
          description: '日本酒の名産地としても知られる東広島市・西条で、清らかな水と朝晩の寒暖差が大きい自然の中で、のびのびと育った『すぃーとアスパラ』。地元の方々からも人気の甘さとみずみずしさが特徴です。\n\n春のアスパラは、ぎゅっと甘味が凝縮されていて、やさしい柔らかさ。\n夏のアスパラは、シャキッとした歯ごたえと爽やかな風味が楽しめ、サラダや炒め物にもぴったり。\n季節ごとに変わる味わいが、食卓に旬の彩りを添えてくれます。\n\n訳あり品は細かったり、先が曲がっていることが理由で出荷できないものです。\n\n◆おすすめの食べ方\n📌アスパラのごま油ソテー\nごま油でじっくり焼き、塩コショウだけで仕上げた一品。シャキッとした食感とごま油の香ばしさが絶妙で、おつまみや副菜にぴったり。\n\n📌アスパラと鶏の春色炊き込みご飯\n鶏もも肉の旨みが染み込んだご飯に、アスパラの緑が映える春らしい一品。火を通しすぎないよう、アスパラは炊き上がり後に加えるのがポイントです。',
          status: 2,
          inventory: 94,
          weight: 1,
          itemUnit: '個',
          itemDescription: '1キロ(50～70本程度)',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/seCiBw1Hoz8iKLH1drxJPQ.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/qLoLMc9xXZAM6sXUf9dqUJ.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/wmXjpjrtfmXaTM78ohLN6u.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/2xnkGSmQ7UEKEKRdddN4nv.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/xc2FzZtGxxnfc9EEa2jLCw.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/seCiBw1Hoz8iKLH1drxJPQ.jpg',
              isThumbnail: true,
            },
          ],
          price: 2500,
          expirationDate: 7,
          recommendedPoint1: '訳あり品でお買い得！',
          recommendedPoint2: '甘さとみずみずしさが抜群！',
          recommendedPoint3: '季節ごとに変わる味わいを楽しんで！',
          storageMethodType: 3,
          deliveryType: 2,
          box60Rate: 50,
          box80Rate: 20,
          box100Rate: 10,
          originPrefecture: '広島県',
          originCity: '東広島市',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1745946311,
          endAt: 1756573500,
        },
        {
          id: 'qRey93qgfJQj8ib8Xat4mt',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: 'abSyW5W7cZLKQoqKFXcW4V',
          categoryId: 'vazPgxgPC6YnTgHHdjZNw1',
          productTypeId: 'cjNk1GPcUj42GVWboKJsUJ',
          productTagIds: [],
          name: '【旬の味覚セット】アスパラ１キロ＆地鶏の生ハム1パック',
          description: '～自然が育てたごちそうを、おうちで贅沢に～\n\n朝晩の寒暖差が大きく、澄んだ空気ときれいな水に恵まれた地で育った『すい〜とアスパラ』は、地元でも大人気の逸品。\n春はふんわり甘く、夏はシャキッと爽やか。1kgたっぷり入ったボリューム満点のアスパラは、毎日の食卓にも、おもてなしにもぴったりです。\n\nそしてセットでお届けするのは、旨みがぎゅっと詰まった『東広島こい地鶏の生ハム』。\n地鶏ならではのコクとしっとりした食感が、アスパラの甘さと絶妙にマッチ。ちょっと贅沢な前菜や、ワインのお供にぴったりの組み合わせです。\n\n◆おすすめの食べ方\n📌アスパラ×生ハム巻き\nアスパラを茹でて生ハムでくるっと巻くだけ。アスパラの甘みと生ハムの塩気が一体となって、止まらないおいしさ！オリーブオイルなどで焼いても美味しくいただけます！',
          status: 2,
          inventory: 90,
          weight: 1,
          itemUnit: '個',
          itemDescription: 'アスパラガス1キロ(30～50本程度)＆生ハム1パック50g',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/jaxNzXaKaXkP6a9wd6bFbQ.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/jaxNzXaKaXkP6a9wd6bFbQ.jpg',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/j3pDMfg6vKAVijrjJnXghL.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/q19THWiSD9KUsPsDVioAZC.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/j1SJaq4TzJsRkk335316HD.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/s4BKigJFZidJTHJR5i8djW.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/vfT8MtfY2Nqq1SUmqWHPQ3.jpg',
              isThumbnail: false,
            },
          ],
          price: 4200,
          expirationDate: 7,
          recommendedPoint1: '東広島・限定セット！',
          recommendedPoint2: '甘くてみずみずしいアスパラガス！',
          recommendedPoint3: 'なかなか出会えない地鶏の生ハム！',
          storageMethodType: 3,
          deliveryType: 2,
          box60Rate: 50,
          box80Rate: 20,
          box100Rate: 10,
          originPrefecture: '広島県',
          originCity: '東広島市',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1745946311,
          endAt: 1756573500,
        },
        {
          id: '8VkGoxmme775X6kRMPKMy2',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: 'abSyW5W7cZLKQoqKFXcW4V',
          categoryId: 'vazPgxgPC6YnTgHHdjZNw1',
          productTypeId: 'cjNk1GPcUj42GVWboKJsUJ',
          productTagIds: [],
          name: '【今が旬】すぃーとアスパラ１キロ',
          description: '日本酒の名産地としても知られる東広島市・西条で、清らかな水と朝晩の寒暖差が大きい自然の中で、のびのびと育った『すぃーとアスパラ』。地元の方々からも人気の甘さとみずみずしさが特長です。\n\n春のアスパラは、ぎゅっと甘味が凝縮されていて、やさしい柔らかさ。\n夏のアスパラは、シャキッとした歯ごたえと爽やかな風味が楽しめ、サラダや炒め物にもぴったり。\n季節ごとに変わる味わいが、食卓に旬の彩りを添えてくれます。\n\n\n◆おすすめの食べ方\n📌オリーブオイルで焼くだけ！\nアスパラ本来の甘みと香りを楽しむなら、シンプルにオリーブオイルで焼くだけで絶品。軽く塩をふるだけで、立派な一品に。\n\n📌半熟卵と一緒にサラダで\nさっと茹でたアスパラに、とろ〜り半熟卵をのせれば、まろやかなコクが加わってワインにもぴったり。ちょっと贅沢なおうちごはんに。',
          status: 2,
          inventory: 89,
          weight: 1,
          itemUnit: '個',
          itemDescription: '1キロ(30～50本程度)',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/qLoLMc9xXZAM6sXUf9dqUJ.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/qnmxWRHQvxbGvGLnUkZPjt.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/qLoLMc9xXZAM6sXUf9dqUJ.jpg',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/wmXjpjrtfmXaTM78ohLN6u.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/2xnkGSmQ7UEKEKRdddN4nv.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/xc2FzZtGxxnfc9EEa2jLCw.jpg',
              isThumbnail: false,
            },
          ],
          price: 3700,
          expirationDate: 7,
          recommendedPoint1: '甘さとみずみずしさが抜群！',
          recommendedPoint2: '日本酒の名産地・清らかな水で育ちました',
          recommendedPoint3: '季節ごとに変わる味わいを楽しんで！',
          storageMethodType: 3,
          deliveryType: 2,
          box60Rate: 50,
          box80Rate: 20,
          box100Rate: 10,
          originPrefecture: '広島県',
          originCity: '東広島市',
          rate: {
            average: 5,
            count: 5,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 5,
            },
          },
          startAt: 1745946311,
          endAt: 1756573500,
        },
        {
          id: 'nRmkJ7dfdF4ze5bQ2fU9Nd',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: 'rAcvhtctMQhrwcR1wcri7q',
          categoryId: 'v15LHKFHpeobQiN6cmrmB4',
          productTypeId: 'pqdcgCiuk5i8RvNiz5h52b',
          productTagIds: [],
          name: '【野性を味わうBBQに】ジビエ肉セット｜鹿＆猪ロース切り身',
          description: '自然の中でのびのび育った、旨みたっぷりの鹿と猪。そのロース部分だけを厳選した「ちょっと特別なBBQセット」です。\n\n脂身があっさりしていてクセの少ない鹿ロースは、驚くほどやわらか。濃厚でジューシーな猪ロースは、しっかり食べごたえがあってお酒との相性抜群！行楽シーズンなどのアウトドアや家飲みにもぴったりな一品です。\n\n◆生産者・東広島ジビエセンター\n東広島・豊栄町の山で育った鹿や猪を、ジビエ肉として狩猟～加工まで行っています。\n「止め刺し」という職人技で仕留める技術と、臭みを出さない質の高い肉の生産は、日本トップレベルで「国産ジビエ認証」を取得しています。\n\n◆おすすめの食べ方\n📌鹿ロースのレアたたき風\n両面をサッと炙って、スライス。おろしポン酢やにんにく醤油でどうぞ。しっとり食感と赤身の旨みがクセになります。\n\n📌猪ロースの焼肉スタイル\n塩こしょうでさっと焼くだけ！脂が甘くてジューシーだから、タレ要らず。焼きすぎないのがポイントです。',
          status: 2,
          inventory: 99,
          weight: 0.5,
          itemUnit: '個',
          itemDescription: '1パック(200g)×2種',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/178t42vuGpW3EHMZvuCbza.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/178t42vuGpW3EHMZvuCbza.jpg',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/jJ7MCxEKxVF6yejzhug4GM.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/7DhcEjtgGGgnApX8SQ8gNP.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/wwczjTR5aH5UNi3WtQx3v2.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/w4Uo321wwEyzjknYkFXRhZ.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/oECb8qHv8A2b4FkoZ2Pqv2.png',
              isThumbnail: false,
            },
          ],
          price: 2800,
          expirationDate: 180,
          recommendedPoint1: '日本トップレベルのジビエ肉',
          recommendedPoint2: 'クセがなく肉の味が濃い！',
          recommendedPoint3: '行楽シーズンのプチ贅沢に',
          storageMethodType: 4,
          deliveryType: 3,
          box60Rate: 100,
          box80Rate: 80,
          box100Rate: 60,
          originPrefecture: '広島県',
          originCity: '東広島市',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1745946311,
          endAt: 1756573500,
        },
        {
          id: 'sqwmpW3fL6bWPHJWQA5uA5',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: 'atPsdN1g3m5r1axousAWkk',
          categoryId: 'uhCUgQefyxhkGLj3wNEXAN',
          productTypeId: 'ttKFsf29vDZ3EshPqsCSgS',
          productTagIds: [],
          name: '大崎上島産　エクストラバージンオリーブオイル　45g（送料無料）',
          description: '大崎上島産のオーガニックオリーブ100%のエクストラバージンオリーブオイルのご予約受付開始！\n\n数量限定なのでお早めにご予約ください！！\n\n有機JAS認証を取得したオーガニックオリーブは除草剤や化学肥料、化学農薬を一切使用していない丸ごと食べられる果実です。収穫直後のオリーブの実から抽出したオリーブオイルは風味、辛味、舌触りが抜群のオイルに仕上がっています！',
          status: 2,
          inventory: 28,
          weight: 0,
          itemUnit: '瓶',
          itemDescription: '1本あたり45g',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/4XqcATzot1VQ86bMVWTY7v.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/4XqcATzot1VQ86bMVWTY7v.jpg',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/iYxxhCfusEPz8BScznKVbj.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/fszoXoPvcKFgqmbzJiBHt5.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/7e6pj3smEBiCXV3gsweAkr.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/riaUcvzMSNSnq54xcoec5E.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/8hrUX26RJbS4BZoW2qGZRr.jpg',
              isThumbnail: false,
            },
          ],
          price: 1800,
          expirationDate: 365,
          recommendedPoint1: 'オーガニックオリーブ100%',
          recommendedPoint2: '大崎上島という環境に恵まれた産地で丁寧に育てました。',
          recommendedPoint3: '無添加、非加熱、一切の不純物なし！天然の生オリーブオイル！',
          storageMethodType: 1,
          deliveryType: 1,
          box60Rate: 10,
          box80Rate: 10,
          box100Rate: 0,
          originPrefecture: '広島県',
          originCity: '豊田郡　大崎上島町',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1739886420,
          endAt: 1798724820,
        },
        {
          id: 'dVHnrpNCZthLsjgPTCVqwY',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: 'jPGpBAADF81TTv5jbj6uBe',
          categoryId: 'w7FekSnGeMHNcam35LnKew',
          productTypeId: 's9hdTNK5omawq1pJgA6fDY',
          productTagIds: [],
          name: '【農家体験】大崎上島　紅八朔の摘果体験',
          description: '1人　1時間　2000円\n※8月〜10月\n大崎上島の紅八朔の摘果作業のお手伝い体験。\n\nこの時期ならではの農作業を体験できます。\n\n摘果とは…木になりすぎた果実の数を落として減らすことで果実の肥大を促進し品質を安定させる作業。\n体験時間　2時間\n摘果した紅八朔のお土産、フードロスのアップサイクル品「紅八朔の摘果マーマレード」を1瓶プレゼント\n最低催行人数　2人から',
          status: 2,
          inventory: 30,
          weight: 0,
          itemUnit: '件',
          itemDescription: '2時間　2000円',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/8CCmGUnvN66W5NzCzoBSaC.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/8CCmGUnvN66W5NzCzoBSaC.jpg',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/h2izFUs4iJjfYJB8VYMbrs.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/bY6BugaJJsUhaHwTmesKHC.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/njfvbAN2QapmZpAy8XfTBj.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/tZUEkWdPUdXGUUeWW9zjMe.jpg',
              isThumbnail: false,
            },
          ],
          price: 2000,
          expirationDate: 0,
          recommendedPoint1: '柑橘栽培の重要な作業をお手伝い体験！',
          recommendedPoint2: 'お土産に摘果紅八朔を使用したマーマレードをプレゼント！',
          recommendedPoint3: '摘果した紅八朔は自由にお持ち帰り可能！',
          storageMethodType: 1,
          deliveryType: 1,
          box60Rate: 0,
          box80Rate: 0,
          box100Rate: 0,
          originPrefecture: '広島県',
          originCity: '豊田郡　大崎上島町',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1729250309,
          endAt: 1759231080,
        },
        {
          id: 'h2M1C6RiUQ2XVCkWh2MXB5',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: '2UovNPfYhWFmMyU6VFPsQm',
          categoryId: 'w7FekSnGeMHNcam35LnKew',
          productTypeId: 's9hdTNK5omawq1pJgA6fDY',
          productTagIds: [],
          name: '【予約受付開始】 大崎上島産グリーンレモン　2キロ',
          description: '※こちらの発送は10月初旬からです。\n\n越智農園の初物「グリーンレモン」が登場！！\n防腐剤・ワックス不使用：自然そのままのレモンだから、家族全員に安心して楽しんでもらえます。\n離島の贈り物：大崎上島の澄んだ空気と温暖な気候が育んだ特別なレモン。都会の喧騒から離れた自然の恵みをお届けします。\n\n「旬の初物」\nこの季節ならではの新鮮なグリーンレモンで、家庭の食卓に爽やかさをプラス。\n\n「家族で楽しむポイント」\n家族団らんの時間に、このグリーンレモンを加えてみませんか？無添加・無農薬だから、皮ごと使えるので、お料理の幅も広がります。魚料理やパスタ、サラダに絞るだけでなく、夫婦で作る自家製レモネードや、子どもたちと一緒に楽しむレモンピール作りにも最適。家族みんなで安心して口にできる自然な味わいが、特別なひとときを演出します。\n\nおすすめシーン\n週末の夫婦の時間に：二人でゆったりと過ごすティータイムに、手作りのレモンドリンクやお菓子を楽しんで。\n家族みんなでお料理を：子どもたちと一緒にレモンを使った料理やデザート作りに挑戦し、楽しい思い出をいかがでしょうか？',
          status: 2,
          inventory: 50,
          weight: 2,
          itemUnit: '個',
          itemDescription: '2kg',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/xnVXgDBxiBK7WGFCjgtm4X.png',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/s4RpHw2wX5CHeHeYyFdixr.png',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/v8NjEyVCoDE8PuG7pZsniX.png',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/2JSda6f6rvz6an4AyxDH45.png',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/xnVXgDBxiBK7WGFCjgtm4X.png',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/cKqugzXvhv5cXPT2dB1Nhh.png',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/q9WFhGiVKrUUBNWMmK4PQL.jpg',
              isThumbnail: false,
            },
          ],
          price: 3300,
          expirationDate: 40,
          recommendedPoint1: '防腐剤やワックスを一切使用していないため、皮まで安心して使えます',
          recommendedPoint2: '大崎上島で育まれた、今しか手に入らない新鮮なグリーンレモン',
          recommendedPoint3: '料理やドリンク、デザートまで幅広く使えるので、家族みんなで楽しめる食材です',
          storageMethodType: 1,
          deliveryType: 1,
          box60Rate: 100,
          box80Rate: 50,
          box100Rate: 25,
          originPrefecture: '広島県',
          originCity: '豊田郡　大崎上島町',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1726674366,
          endAt: 1764514740,
        },
        {
          id: '6P4BvG7iiegTHxtVt8mLvQ',
          coordinatorId: '72UsTvLWapHx1KsXZ4XFTX',
          producerId: '3NAJgJ7jLxKj287ckrcS4X',
          categoryId: 'w7FekSnGeMHNcam35LnKew',
          productTypeId: 'f93K71F7CDjo78W1GiKrX3',
          productTagIds: [],
          name: '【夏だけの極上果実】大崎上島産メロン「ミライノ夏」西田農園',
          description: '今年も大注目！！大崎上島産メロンをご紹介！！\n\n\n\n健康と美容を保つためには、食生活が重要な役割を果たします。その中でも、果物はビタミンやミネラルが豊富で、美容と健康に欠かせない存在です。特にメロンは、豊かな甘みとジューシーさが特徴で、リラックスしたいときや贅沢なひとときを楽しむ際にぴったりです！\n\n1. 大崎上島メロンの特別な生産環境\n\n広島県の大崎上島は、瀬戸内海に浮かぶ自然豊かな島です。この島は温暖な気候と豊富な日照量に恵まれており、メロンの栽培に理想的な環境が整っています。特に、大崎上島の農家は、地元の気候と土壌の特性を最大限に活かした栽培方法を採用しており、他の地域では味わえないメロンを生み出しています。\n\n2. 美味しさの秘密：丹念に育てられたメロン\n\n大崎上島メロンは、島の南部に位置する西田農園で一つ一つ丁寧に手間暇をかけて育てています。例えば、栄養分が果実にしっかり行き渡るように、適切な間隔で栽培を行い、均等に日光を浴びせることで、甘みが凝縮されます。また、成長過程での水分管理も徹底されており、果肉の滑らかさとジューシーさが保たれています。これにより、大崎上島メロンは、ひと口食べるだけで口の中いっぱいに広がる豊かな甘さと香りが特徴の、極上のメロンに仕上がります。\n\n3. 栄養価が高く、美容と健康に最適\n\nメロンは、ビタミンCやカリウム、食物繊維が豊富に含まれており、美容と健康に多くのメリットをもたらします。ビタミンCは抗酸化作用が強く、肌のハリやツヤを保つために重要です。また、カリウムは体内のナトリウムバランスを整えることで、むくみ解消に役立ちます。さらに、メロンに含まれる食物繊維は、腸内環境を整え、デトックス効果も期待できます。特に40代女性にとって、これらの栄養素は健康維持に欠かせないものです。\n\n4. 大崎上島メロンの楽しみ方\n\n大崎上島メロンは、そのまま食べても十分に美味しいですが、さらに楽しむためのアイデアもあります。例えば、朝食にヨーグルトと一緒に食べると、爽やかな酸味と甘みのバランスが絶妙で、心地よい一日のスタートを切ることができます。また、メロンを使ったデザートやスムージーもおすすめです。特に夏場には、冷たく冷やしたメロンをシャーベットやサラダにアレンジすると、清涼感あふれる一品に仕上がります。\n\n5. 大崎上島メロンを選ぶ理由\n\nさまざまな種類のメロンがありますが、大崎上島メロンが特におすすめできる理由は、その品質と栄養価の高さにあります。栽培から収穫まで、細部にまでこだわり抜かれたこのメロンは、他のメロンにはない豊かな風味と栄養を兼ね備えています。さらに、厳選された生産者による安心・安全な管理体制が整っており、毎回同じクオリティのメロンをお届けできる点も魅力です。\n\n6. 大崎上島メロンの購入方法と保存方法\n\n大崎上島メロンは、オンライン通販で手軽に購入できます。新鮮な状態で自宅に届けられるので、忙しい方でも簡単に楽しむことができます。購入後は、冷暗所に保存し、食べ頃を見計らって楽しんでください。特に、食べる直前に冷蔵庫で冷やすと、甘みがより一層引き立ちます。\n\n7. まとめ：心と体に贅沢なひとときを、大崎上島メロンで\n\n広島県大崎上島で育まれたメロンは、味わい深く、栄養価も高い理想的なフルーツです。特に、美容と健康をサポートする強い味方となることでしょう。自然の恵みをたっぷり受けた大崎上島メロンで、日々の生活に贅沢なひとときを取り入れてみませんか？一房の彩りを通じて、ぜひこの極上のメロンを体験してみてください。',
          status: 2,
          inventory: 20,
          weight: 1.5,
          itemUnit: '個',
          itemDescription: '1箱あたり1個のメロンが入っています。',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/7RkNiMHEDBgkbXbetvyw1C.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/7RkNiMHEDBgkbXbetvyw1C.jpg',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/jQL8Tfi9Rn4W8WvvuBgrSu.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/7qYwnAsY1NFvaHCyTVqCNa.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/pEShunWJAiDiG8n8qTT1qy.jpg',
              isThumbnail: false,
            },
          ],
          price: 3300,
          expirationDate: 14,
          recommendedPoint1: '潮風をを浴びて育った極上メロン',
          recommendedPoint2: '芳醇な香りと深い味わい',
          recommendedPoint3: '鮮度抜群とれたてをお届け',
          storageMethodType: 1,
          deliveryType: 1,
          box60Rate: 100,
          box80Rate: 100,
          box100Rate: 50,
          originPrefecture: '広島県',
          originCity: '豊田郡　大崎上島町',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1725495600,
          endAt: 1759203000,
        },
        {
          id: 'vNzKLMtQaVm4nwBh4ttAmy',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: '2zpxeuo9fS11gEwCDihx3x',
          categoryId: 'aPZNRJbsWHxze6DMzyHDUU',
          productTypeId: 'aRGjN1PYzPXPbffN2gm6pY',
          productTagIds: [],
          name: '瀬戸内・牡蠣セット（殻付き10～15個＆剥き身500g）',
          description: '広島県東広島市・安芸津町の豊かな海で育った、マルキン水産のこだわりの牡蠣。  \n3代目の牡蠣漁師・伊豫谷さんが、伝統の技と最新の工夫を活かしながら、一年を通じて美味しい牡蠣を生産しています。  \n水揚げ後すぐに海水を使った氷で鮮度を保ち、ぷりぷりの食感をそのままお届けします。  \n\n＜商品内容＞\n・殻付き牡蠣（10～15個 / サイズによる）  \n・剥き身（500g / 使いやすいパック入り）  \n\n\n＜おすすめの楽しみ方＞  \n\n📌殻付き牡蠣の楽しみ方  \n・焼き牡蠣：殻ごとグリルやフライパンで蒸し焼きに。殻が開いたら食べ頃  \n・生牡蠣（※加熱推奨）：レモンやポン酢をかけて、シンプルに味わう  \n・牡蠣の酒蒸し：日本酒や白ワインと一緒に蒸して、ふっくらジューシーに  \n\n📌剥き身牡蠣のアレンジ  \n・カキフライ：外はサクサク、中はジューシーな定番の美味しさ  \n・牡蠣のバターソテー：バターとガーリックで炒めて濃厚な味わいに  \n・牡蠣のクリームパスタ：牡蠣の旨みが溶け込んだソースが絶品  \n・牡蠣ご飯：牡蠣の出汁を活かした炊き込みご飯で旨みたっぷり  \n\n\n一年中楽しめる新鮮な広島の牡蠣をご家庭で！',
          status: 2,
          inventory: 0,
          weight: 3,
          itemUnit: '個',
          itemDescription: '殻付き牡蠣10～15個＆剥き身500g',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/wUxTZvC51N1yovEJnR1W8A.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/wUxTZvC51N1yovEJnR1W8A.jpg',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/q7fUVJgwebmBW71jZdPArJ.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/vmTPE7CP21g1PQVvtze65j.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/bfbthbiWziCFkCrkmBT2vg.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/6VCWN8VggXFRQtVjsvMufB.jpg',
              isThumbnail: false,
            },
          ],
          price: 5200,
          expirationDate: 4,
          recommendedPoint1: '徹底した鮮度維持によるぷりぷり食感',
          recommendedPoint2: '清浄な海域で夏も食べられる',
          recommendedPoint3: 'じっくり育てて濃厚な旨みに',
          storageMethodType: 3,
          deliveryType: 2,
          box60Rate: 100,
          box80Rate: 100,
          box100Rate: 80,
          originPrefecture: '広島県',
          originCity: '東広島市',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1741368837,
          endAt: 1759244340,
        },
        {
          id: 'd2DbJwgXQ68WdoUsTrctH6',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: '2zpxeuo9fS11gEwCDihx3x',
          categoryId: 'aPZNRJbsWHxze6DMzyHDUU',
          productTypeId: 'aRGjN1PYzPXPbffN2gm6pY',
          productTagIds: [],
          name: 'お店の味をご家庭で！牡蠣レモンパスタセット',
          description: '東広島・西条で30年近く地元で愛されるパスタ専門店「Pasta amare」の店長が開発した、特別なレシピを再現できるセット。  \n瀬戸内海を臨む安芸津町で育まれた、新鮮な牡蠣とレモンを使い、ご家庭で本格的なパスタとマリネを楽しめます。  \nふるマル制作番組「ひろしま青空レストラン」でも紹介された、シェフが生産現場を訪れ、畑で調理した2品のレシピ付き。  \n\n＜セット内容＞\n・殻付き牡蠣：10～15個（サイズによる）  \n・完熟春レモン：3個  \n・生パスタ麺：3パック（3人前）\n・特製レシピ：パスタ＆マリネの2品 \n\n※牡蠣、生麺ともに消費期限が短いのでご注意ください。\n\n\n＜作れる料理＞  \n📌牡蠣とレモンの白みそクリームパスタ \n濃厚な牡蠣の旨みと、爽やかなレモンの酸味を白みそが包み込む、コク深いクリームパスタ  \n\n📌牡蠣とレモンのイタリアンマリネ  \n牡蠣の旨みを引き出すレモンの香りとオリーブオイルのマリアージュ\n\nPasta amare専用のモチモチ生麺とともに、本格イタリアンの味をご家庭で気軽にお楽しみください。',
          status: 2,
          inventory: 0,
          weight: 3,
          itemUnit: '個',
          itemDescription: '殻付き牡蠣、レモン、生麺セット',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/hbM1QB68Go4dzpfsUeUS5N.png',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/hbM1QB68Go4dzpfsUeUS5N.png',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/4YjQjPNb2zZDUH6Baw3b4q.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/hH4Zahpsz6empGxzoKfZCM.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/69hCJmrhBtVxjtpbuqn9mi.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/gV6ha87RSv1poVxNPPiXGj.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/hZt5vpaDFcXQVHNVvameyF.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/t4PXwSzar9PzV5nWNyb3Ev.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/xojsixSLmTWw1NLSs3QayE.jpg',
              isThumbnail: false,
            },
          ],
          price: 5200,
          expirationDate: 4,
          recommendedPoint1: 'お店の味を自宅で再現できる！',
          recommendedPoint2: '新鮮な牡蠣とレモンを一度に楽しみたい方',
          recommendedPoint3: 'パスタ屋・特製のモチモチ生麺',
          storageMethodType: 3,
          deliveryType: 2,
          box60Rate: 100,
          box80Rate: 100,
          box100Rate: 80,
          originPrefecture: '広島県',
          originCity: '東広島市',
          rate: {
            average: 4.7,
            count: 15,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 4,
              5: 11,
            },
          },
          startAt: 1741368837,
          endAt: 1761922740,
        },
        {
          id: 'kEY38i63igvSuJVcyDoVfQ',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: 'sZhADTu5Z4yUWnKjgcVU5t',
          categoryId: 'w7FekSnGeMHNcam35LnKew',
          productTypeId: 'f93K71F7CDjo78W1GiKrX3',
          productTagIds: [],
          name: '完熟・春レモン２キロ（15～20個前後）',
          description: '冬の寒さを乗り越え、ハウスでじっくり完熟した春レモン。\n広島県東広島市・安芸津町で柑橘農家を営む甲斐農園の甲斐さんが、丁寧に育てたレモンをお届けします。  地域の若手農家のリーダーとして、おいしさと安心を追求した、こだわりの逸品です！  \n\n\n🍋春レモンのおすすめの使い方🍋  \n\n📌ドリンクで楽しむ  \n・レモンウォーター：スライスして水に入れるだけで、スッキリ爽やか！  \n・はちみつレモンシロップ：輪切りにしてはちみつ漬けに。お湯や炭酸で割っても◎  \n\n📌料理で使う\n・サラダやカルパッチョに：オリーブオイルと合わせてドレッシングに。  \n・レモンバターソース：魚やチキンのソテーにさっぱりとした風味をプラス！  \n\n📌お菓子作りに \n・レモンケーキやマフィン：果汁も皮も使えて、香り豊かなお菓子に。  \n・レモンゼリー：ぷるんと爽やか、春らしいデザートにぴったり！  \n\n📌保存＆アレンジ  \n・冷凍レモン：輪切りや果汁を冷凍しておけば、長く楽しめます。  \n・レモン酢：レモンをお酢に漬けて、ドリンクやドレッシングに活用！  \n\n\nまろやかでジューシーな春レモン、ぜひご家庭でお楽しみください！',
          status: 2,
          inventory: 0,
          weight: 2,
          itemUnit: '個',
          itemDescription: '２キロ（15～20個ほど）',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/ky6bvyb5BGiKkU2pDYajyn.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/ky6bvyb5BGiKkU2pDYajyn.jpg',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/d3TefUyqZoQYRyP4Cy5fFt.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/mC1Tp4VYVWsJYysiqg1xvv.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/8Ukd9XkZPwfhXyyEWPbWwY.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/eDWevSvZHfiCiPkQDVgv1W.jpg',
              isThumbnail: false,
            },
          ],
          price: 2700,
          expirationDate: 30,
          recommendedPoint1: 'ハウス栽培だからこその完熟レモン',
          recommendedPoint2: '爽やかな香りとやさしい酸味',
          recommendedPoint3: '防腐剤・ワックス不使用で皮まで使える！',
          storageMethodType: 1,
          deliveryType: 1,
          box60Rate: 100,
          box80Rate: 80,
          box100Rate: 80,
          originPrefecture: '広島県',
          originCity: '東広島市',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1741366821,
          endAt: 1759244340,
        },
        {
          id: 'hCtZhbZ6KTi45kKUXWqJYJ',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: '2UovNPfYhWFmMyU6VFPsQm',
          categoryId: 'w7FekSnGeMHNcam35LnKew',
          productTypeId: 's9hdTNK5omawq1pJgA6fDY',
          productTagIds: [],
          name: '【希少な品種！】大崎上島産プリンス清見　5キロ（1キロ約5玉前後）',
          description: '大崎上島から旬の贈り物「プリンス清見」\n爽やかな甘さと豊かな香りが広がる、特別な柑橘の味わいをご家庭で。\n\n大崎上島の自然が育んだ逸品\n瀬戸内海に浮かぶ大崎上島は、温暖な気候と海風に恵まれた農業の宝庫。この島で大切に育てられた「プリンス清見」は、果実の一つ一つが丁寧に手入れされ、最高の状態でお届けします。\n\n🍊「プリンス清見」の特長\n\n甘さと酸味の絶妙なバランス\n一口かじれば、爽やかな甘さが口いっぱいに広がり、心地よい酸味が後を引きます。お子様から大人まで楽しめるフルーツです。\n\nたっぷりジューシーな果肉\n口に含むたびに溢れる果汁は、まるで贅沢なデザートのよう。朝食やおやつ、贈り物にもぴったりです。\n\nベテラン農家の栽培で安心・安全\n大崎上島の農家が化学薬品を最小限に抑え、自然に優しい栽培方法で育てました。皮まで安心してお使いいただけます。\n\nこんな方におすすめ\n✔️ 家族の健康を気遣う主婦の方\n✔️ 季節感のあるフルーツを探している方\n✔️ 贈り物として喜ばれる柑橘をお求めの方\n\n使い方いろいろ！\n\nそのまま食べて贅沢なおやつに\nヨーグルトやサラダのトッピングに\n皮を使ってお菓子作りやドリンクに\n今だけの季節限定販売！\n旬のフルーツは今しか味わえません。ご注文はお早めにどうぞ。\n\nあなたの食卓に、瀬戸内の恵みを\n大崎上島の「プリンス清見」で、毎日のひとときを少し贅沢にしてみませんか？\n\n\n◆大崎上島ってどんなとこ？\n\n瀬戸内海の真ん中に浮かぶ小さな離島です。\n\nこの地は温暖で降雨の少ない気候が特徴です。\nそんな環境を活かして古くから柑橘栽培が盛んで、余分な水分を含まない味の濃い柑橘の生産が可能となります。',
          status: 2,
          inventory: 0,
          weight: 5,
          itemUnit: '件',
          itemDescription: '1キロあたり3個前後',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/n9RfmL3BmuMXM9RrHVwewr.png',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/9WtzsKbAEnRPEaMtY5GRhD.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/xeeB2maVRdU3VoAMY8WWFx.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/kx2gW7pC2akyPQEnZyZ3zP.png',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/n9RfmL3BmuMXM9RrHVwewr.png',
              isThumbnail: true,
            },
          ],
          price: 4800,
          expirationDate: 14,
          recommendedPoint1: '島の希少な果実！真っ赤な宝物！',
          recommendedPoint2: '急傾斜地で品質の高さが自慢！',
          recommendedPoint3: '手で皮がむけてお子様も食べやすい！',
          storageMethodType: 1,
          deliveryType: 1,
          box60Rate: 100,
          box80Rate: 100,
          box100Rate: 50,
          originPrefecture: '広島県',
          originCity: '豊田郡　大崎上島町',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1737372060,
          endAt: 1772277660,
        },
        {
          id: '6P2XHMhK2qYJoYXNtoZkmc',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: 'jPGpBAADF81TTv5jbj6uBe',
          categoryId: 'w7FekSnGeMHNcam35LnKew',
          productTypeId: 's9hdTNK5omawq1pJgA6fDY',
          productTagIds: [],
          name: '【クセになる食感！】大崎上島産　紅八朔　5キロ（1キロ約4玉前後）',
          description: '大崎上島から旬の贈り物\n爽やかな甘さと豊かな香りが広がる、特別な柑橘の味わいをご家庭で。\n\n大崎上島の自然が育んだ逸品\n瀬戸内海に浮かぶ大崎上島は、温暖な気候と海風に恵まれた農業の宝庫。この島で大切に育てられた「紅八朔」は、果実の一つ一つが丁寧に手入れされ、最高の状態でお届けします。\n\n🍊「紅八朔」の特長\n\n甘さと酸味の絶妙なバランス\n一口かじれば、爽やかな甘さが口いっぱいに広がり、心地よい酸味が後を引きます。お子様から大人まで楽しめるフルーツです。\n\nたっぷりジューシーな果肉\n口に含むたびに溢れる果汁は、まるで贅沢なデザートのよう。朝食やおやつ、贈り物にもぴったりです。\n\nベテラン農家の栽培で安心・安全\n大崎上島の農家が化学薬品を最小限に抑え、自然に優しい栽培方法で育てました。皮まで安心してお使いいただけます。\n\nこんな方におすすめ\n✔️ 家族の健康を気遣う主婦の方\n✔️ 季節感のあるフルーツを探している方\n✔️ 贈り物として喜ばれる柑橘をお求めの方\n\n使い方いろいろ！\n\nそのまま食べて贅沢なおやつに\nヨーグルトやサラダのトッピングに\n皮を使ってお菓子作りやドリンクに\n今だけの季節限定販売！\n旬のフルーツは今しか味わえません。ご注文はお早めにどうぞ。\n\nあなたの食卓に、瀬戸内の恵みを\n大崎上島の「紅八朔」で、毎日のひとときを少し贅沢にしてみませんか？\n\n\n◆大崎上島ってどんなとこ？\n\n瀬戸内海の真ん中に浮かぶ小さな離島です。\n\nこの地は温暖で降雨の少ない気候が特徴です。\nそんな環境を活かして古くから柑橘栽培が盛んで、余分な水分を含まない味の濃い柑橘の生産が可能となります。',
          status: 2,
          inventory: 0,
          weight: 5,
          itemUnit: '件',
          itemDescription: '1キロあたり4個前後',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/npH4jwuoUvd5yWCbt2FPEn.png',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/npH4jwuoUvd5yWCbt2FPEn.png',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/3pWiFth9eXB5U1A2GgRCvc.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/gU37Q7GzWgFGoHFzc8Tivq.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/fi7XjABFp6CkpeDJ8DTXSv.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/ebekCuGqCrJ9Vh3RCqeqZK.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/cUrrvd8bN8UiWqaMuVZBG9.jpg',
              isThumbnail: false,
            },
          ],
          price: 3800,
          expirationDate: 14,
          recommendedPoint1: '甘さと酸味の黄金比！',
          recommendedPoint2: 'ほろ苦いビターな味わいが癖になる！',
          recommendedPoint3: '何個も食べられるくどくない美味しさ！',
          storageMethodType: 1,
          deliveryType: 1,
          box60Rate: 100,
          box80Rate: 100,
          box100Rate: 50,
          originPrefecture: '広島県',
          originCity: '豊田郡　大崎上島町',
          rate: {
            average: 4.3,
            count: 14,
            detail: {
              1: 0,
              2: 1,
              3: 2,
              4: 3,
              5: 8,
            },
          },
          startAt: 1737372060,
          endAt: 1782818460,
        },
        {
          id: '3taB1pt4971eh95rxHcUGh',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: '2UovNPfYhWFmMyU6VFPsQm',
          categoryId: 'w7FekSnGeMHNcam35LnKew',
          productTypeId: 's9hdTNK5omawq1pJgA6fDY',
          productTagIds: [],
          name: '【甘さの爆弾！】大崎上島産　不知火　4キロ（1キロ4約玉前後）',
          description: '※こちらは2月下旬ごろから発送です。\n\n🍊 大崎上島が誇る極上柑橘「不知火」\n独特なフォルムと濃厚な甘さが自慢の「不知火」を、瀬戸内海に浮かぶ美しい島、大崎上島から直送！\n\n大崎上島：柑橘栽培の理想郷\n瀬戸内海に位置する大崎上島は、年間を通じて温暖で穏やかな気候と、適度な雨量に恵まれた農業の理想郷。この独自の環境が、柑橘類にとって絶好の成育条件を提供しています。さらに、昼夜の寒暖差が大きい冬の時期には、柑橘の甘みがより凝縮され、濃厚で香り豊かな果実が生まれます。\n\n私たちの「不知火」は、この自然環境の恵みを最大限に活かし、丹精込めて育てられた逸品です。\n\n不知火の特徴\n🍊 濃厚な甘さとジューシーな果汁\n不知火は糖度が高く、甘みの中にほのかな酸味が絶妙に調和しています。一口食べれば、たっぷりの果汁が口いっぱいに広がり、幸せな気分に。\n\n🍊 特有のコブ形状と大きな果実\n愛らしいコブのあるユニークな見た目は、不知火ならではのチャームポイント。見た目のインパクトに加え、剥きやすく食べやすい点も人気の理由です。\n\n🍊 栄養たっぷりでヘルシー\nビタミンCを豊富に含み、美容や健康維持にぴったり！特に冬の季節には、風邪予防や疲労回復にも役立ちます。\n\n大崎上島産不知火のこだわり\n自然に優しい栽培方法\n大崎上島の農家は、環境に配慮した持続可能な農業を実践。化学農薬や肥料を極力抑え、安心・安全な不知火を育てています。\n\n完熟収穫で最高の状態をお届け\n樹上でじっくり完熟させた不知火だけを厳選。食べごろの状態でお届けするので、届いた瞬間から美味しさをお楽しみいただけます。\n\nおすすめの食べ方\n✔ そのまま剥いてフレッシュな美味しさをそのまま楽しむ\n✔ ジュースやスムージーにして朝食の一品に\n✔ デザートのトッピングやお菓子作りに活用\n✔ 大崎上島の自然を感じる贈り物として\n\n旬の味わいを逃さない！\n「不知火」の旬は冬から春にかけて。期間限定の味覚をぜひお楽しみください！\n\n📦 商品詳細\n\n内容量：1箱（約4kg）\n価格：4500円（税込・送料込）\n発送：注文から5日以内に発送いたします',
          status: 2,
          inventory: 0,
          weight: 5,
          itemUnit: '件',
          itemDescription: '1キロあたり3個前後',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/iqG9epMFsgDV1PVs26pm7n.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/iqG9epMFsgDV1PVs26pm7n.jpg',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/99ddZqathJ55qwHSd41bVm.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/5emMsuhwABYSgLRqB6ymjT.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/2pHpt3cDqYFQVHYVg21FU2.png',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/qnZV5uaw8JdyXoF9xKq9KP.png',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/9duYTtVKbwacVSjLEbdreo.png',
              isThumbnail: false,
            },
          ],
          price: 4500,
          expirationDate: 14,
          recommendedPoint1: '甘さの爆弾！！高級柑橘！！',
          recommendedPoint2: '急傾斜地で品質の高さが自慢！',
          recommendedPoint3: 'かわいいフォルムで贈り物にも最適！',
          storageMethodType: 1,
          deliveryType: 1,
          box60Rate: 100,
          box80Rate: 100,
          box100Rate: 50,
          originPrefecture: '広島県',
          originCity: '豊田郡　大崎上島町',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1737372060,
          endAt: 1774956060,
        },
        {
          id: '8PGbqxTuCtpaXBKgubmrH9',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: '63LnH5NhCJCqC8xResqyPG',
          categoryId: 'w7FekSnGeMHNcam35LnKew',
          productTypeId: 's9hdTNK5omawq1pJgA6fDY',
          productTagIds: [],
          name: '【高級！高糖度！】大崎上島産ハウスせとか　3キロ（1キロ約3玉前後）',
          description: '今回は大注目！！新商品の大崎上島産ハウスせとかをご紹介！！\n\n\n\n健康と美容を保つためには、食生活が重要な役割を果たします。その中でも、果物はビタミンやミネラルが豊富で、美容と健康に欠かせない存在です。特にせとかは、豊かで濃い甘みとジューシーさが特徴で、リラックスしたいときや贅沢なひとときを楽しむ際にぴったりです！\n\n\n\n1. 大崎上島せとかの特別な生産環境\n\n広島県の大崎上島は、瀬戸内海に浮かぶ自然豊かな島です。この島は温暖な気候と豊富な日照量に恵まれており、せとかの栽培に理想的な環境が整っています。特に、大崎上島の農家は、地元の気候と土壌の特性を最大限に活かした栽培方法を採用しており、他の地域では味わえない柑橘を生み出しています。\n\n\n\n\n\n2. 美味しさの秘密：丹念に育てられたハウスせとか\n\n大崎上島せとかは、島の中心部に位置するファーム陽の当たる場所で一つ一つ丁寧に手間暇をかけて育てています。ハウスでは栄養分が果実にしっかり行き渡るように、適切な間隔で栽培を行い、均等に日光を浴びせることで、甘みが凝縮されます。また、成長過程での水分管理も徹底することができるので濃く味わい深い果肉とジューシーさが保たれています。これにより、大崎上島せとかは、ひと口食べるだけで口の中いっぱいに広がる豊かな甘さと香りが特徴の、極上な果実に仕上がります。\n\n\n\n\n\n3. 栄養価が高く、美容と健康に最適\n\nビタミンCやカリウム、食物繊維が豊富に含まれており、美容と健康に多くのメリットをもたらします。ビタミンCは抗酸化作用が強く、肌のハリやツヤを保つために重要です。また、カリウムは体内のナトリウムバランスを整えることで、むくみ解消に役立ちます。さらに、せとかに含まれる食物繊維は、腸内環境を整え、デトックス効果も期待できます。特に40代女性にとって、これらの栄養素は健康維持に欠かせないものです。\n\n\n\n\n\n4. 大崎上島せとかの楽しみ方\n\n大崎上島せとかは、そのまま食べても十分に美味しいですが、さらに楽しむためのアイデアもあります。例えば、朝食にヨーグルトと一緒に食べると、爽やかな酸味と甘みのバランスが絶妙で、心地よい一日のスタートを切ることができます。また、せとかを使ったデザートやスムージーもおすすめです。特に春先には、せとかをシャーベットやサラダにアレンジすると、清涼感あふれる一品に仕上がります。\n\n\n\n\n\n5. 大崎上島せとかを選ぶ理由\n\nこの季節はさまざまな種類の柑橘がありますが、大崎上島せとかが特におすすめできる理由は、その品質と栄養価の高さにあります。栽培から収穫まで、細部にまでこだわり抜かれたこのせとかは、他の柑橘にはない豊かな風味と上品な味わいを兼ね備えています。さらに、厳選された生産者による安心・安全な管理体制が整っており、毎回同じクオリティのせとかをお届けできる点も魅力です。\n\n\n\n\n\n6. 大崎上島せとかの購入方法と保存方法\n\n大崎上島せとかは、オンライン通販で手軽に購入できます。新鮮な状態で自宅に届けられるので、忙しい方でも簡単に楽しむことができます。購入後は、冷暗所に保存し、食べ頃を調整し楽しんでください。特に、食べる直前に冷蔵庫で冷やすと、甘みがより一層引き立ちます。\n\n\n\n\n\n7. まとめ：心と体に贅沢なひとときを、大崎上島産せとかで\n\n広島県大崎上島で育まれたせとかは、味わい深く、栄養価も高い理想的な島の宝石とも呼べるフルーツです。特に、美容と健康をサポートする強い味方となることでしょう。自然の恵みをたっぷり受けた大崎上島せとかで\n\n\n◆大崎上島ってどんなとこ？\n\n瀬戸内海の真ん中に浮かぶ小さな離島です。\n\nこの地は温暖で降雨の少ない気候が特徴です。\nそんな環境を活かして古くから柑橘栽培が盛んで、余分な水分を含まない味の濃い柑橘の生産が可能となります。',
          status: 2,
          inventory: 0,
          weight: 3,
          itemUnit: '件',
          itemDescription: '1キロあたり3個前後',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/jEwnp1siWY1dfVyhh91TvF.png',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/dFKfx5Ei5BYyWUoqnnxocV.png',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/7LV5u25gETAQcSAFutRxgK.png',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/jEwnp1siWY1dfVyhh91TvF.png',
              isThumbnail: true,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/tbXB6PLjFFpYM355dBoFL6.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/wWbPJuzyjkR1GXZ3nsFiDp.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/qYbrJnGnLmQ6kAhLAoNHD9.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/mrCGFrn2KzUz6BwuwsWHkG.jpg',
              isThumbnail: false,
            },
          ],
          price: 7500,
          expirationDate: 14,
          recommendedPoint1: '島の宝石！柑橘の大トロせとか！',
          recommendedPoint2: 'ハウスで管理された品質の高さが自慢！',
          recommendedPoint3: '贈り物にも最適！老若男女誰にでも最上級の柑橘！！',
          storageMethodType: 1,
          deliveryType: 1,
          box60Rate: 100,
          box80Rate: 100,
          box100Rate: 50,
          originPrefecture: '広島県',
          originCity: '豊田郡　大崎上島町',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1737372060,
          endAt: 1772277660,
        },
        {
          id: 'ugMaGktzqT6JN8pzLmBofx',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: '2UovNPfYhWFmMyU6VFPsQm',
          categoryId: 'w7FekSnGeMHNcam35LnKew',
          productTypeId: 's9hdTNK5omawq1pJgA6fDY',
          productTagIds: [],
          name: '【島の誇り】越智さんの晩生みかん　2キロ',
          description: '一年間手塩にかけて育てた島のみかんを是非ご賞味くださいませ。\n\n◆大崎上島ってどんなとこ？\n\n瀬戸内海の真ん中に浮かぶ小さな離島です。\n\nこの地は温暖で降雨の少ない気候が特徴です。\n\nそんな環境を活かして古くから柑橘栽培が盛んで、余分な水分を含まない味の濃いミカンの生産が可能となります。\n\n◆晩生みかんとは？\n\n晩生とは12月にシーズンを迎える最後の時期のおみかんです。一般的に普通温州みかんと呼ばれるみかんはこの時期のものからを指すことが多いです。見た目にも橙色が濃く鮮やかです。味わいは秋のおみかんに比べ甘味が強く感じられる濃い味わいが特徴です。果肉もジューシーで食べ応えもあり「じょうのう」という内側の膜も比較的薄く食べやすいのも特徴です。収穫直後のものは特に酸味も強めですので、少し寝かせてからお召し上がりいただくと良いかもしれません。\n\nこの時期は凍結を避けるよう保管場所には要注意で、日光のあたらない風通しの良い冷暗所に寝かせるようにしましょう。\n\n \n\n◆おいしい食べ方\n\n皮をむいてそのままが1番！今年の初こたつでみかん！間違いなしです！\n\nそのほかお菓子作り、ジャム作りにもピッタリです！シーズン到来の晩生みかん。是非一度ご賞味くださいませ！！',
          status: 2,
          inventory: 0,
          weight: 2,
          itemUnit: '件',
          itemDescription: '1キロあたり10個前後',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/waiRvHpAR5zNa2iYD637ZS.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/vy6Xj4ZNHVbxoMZfGVduFi.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/pukASkeAHbnEHMVDrw8fXi.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/rZV8Yc2L5gnrNf7sndsety.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/5YEfwkm9vttvwjK1NwLiZC.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/3i6M5YWoRNhRTxvM5PDVi6.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/5Fh8vMgbCbSBGbvvD14fXv.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/waiRvHpAR5zNa2iYD637ZS.jpg',
              isThumbnail: true,
            },
          ],
          price: 3200,
          expirationDate: 14,
          recommendedPoint1: '島の宝物！普通温州みかん！',
          recommendedPoint2: '島の南部の急傾斜地でつくる高品質なみかん！',
          recommendedPoint3: '贈り物にも最適！老若男女誰にでも喜ばれること間違いなし！',
          storageMethodType: 1,
          deliveryType: 1,
          box60Rate: 100,
          box80Rate: 50,
          box100Rate: 20,
          originPrefecture: '広島県',
          originCity: '豊田郡　大崎上島町',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1735730460,
          endAt: 1769858460,
        },
        {
          id: '4JeD2wKSQmGf9ZmtfMxUKh',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          producerId: '2UovNPfYhWFmMyU6VFPsQm',
          categoryId: 'w7FekSnGeMHNcam35LnKew',
          productTypeId: 's9hdTNK5omawq1pJgA6fDY',
          productTagIds: [],
          name: '【島の誇り】越智さんの晩生みかん　5キロ',
          description: '一年間手塩にかけて育てた島のみかんを是非ご賞味くださいませ。\n\n◆大崎上島ってどんなとこ？\n\n瀬戸内海の真ん中に浮かぶ小さな離島です。\n\nこの地は温暖で降雨の少ない気候が特徴です。\n\nそんな環境を活かして古くから柑橘栽培が盛んで、余分な水分を含まない味の濃いミカンの生産が可能となります。\n\n◆晩生みかんとは？\n\n晩生とは12月にシーズンを迎える最後の時期のおみかんです。一般的に普通温州みかんと呼ばれるみかんはこの時期のものからを指すことが多いです。見た目にも橙色が濃く鮮やかです。味わいは秋のおみかんに比べ甘味が強く感じられる濃い味わいが特徴です。果肉もジューシーで食べ応えもあり「じょうのう」という内側の膜も比較的薄く食べやすいのも特徴です。収穫直後のものは特に酸味も強めですので、少し寝かせてからお召し上がりいただくと良いかもしれません。\n\nこの時期は凍結を避けるよう保管場所には要注意で、日光のあたらない風通しの良い冷暗所に寝かせるようにしましょう。\n\n \n\n◆おいしい食べ方\n\n皮をむいてそのままが1番！今年の初こたつでみかん！間違いなしです！\n\nそのほかお菓子作り、ジャム作りにもピッタリです！シーズン到来の晩生みかん。是非一度ご賞味くださいませ！！',
          status: 2,
          inventory: 0,
          weight: 5,
          itemUnit: '件',
          itemDescription: '1キロあたり10個前後',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/products/media/image/waiRvHpAR5zNa2iYD637ZS.jpg',
          media: [
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/vy6Xj4ZNHVbxoMZfGVduFi.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/pukASkeAHbnEHMVDrw8fXi.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/rZV8Yc2L5gnrNf7sndsety.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/5YEfwkm9vttvwjK1NwLiZC.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/3i6M5YWoRNhRTxvM5PDVi6.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/5Fh8vMgbCbSBGbvvD14fXv.jpg',
              isThumbnail: false,
            },
            {
              url: 'https://assets.furumaru.and-period.co.jp/products/media/image/waiRvHpAR5zNa2iYD637ZS.jpg',
              isThumbnail: true,
            },
          ],
          price: 4500,
          expirationDate: 14,
          recommendedPoint1: '島の宝物！普通温州みかん！',
          recommendedPoint2: '島の南部の急傾斜地でつくる高品質なみかん！',
          recommendedPoint3: '贈り物にも最適！老若男女誰にでも喜ばれること間違いなし！',
          storageMethodType: 1,
          deliveryType: 1,
          box60Rate: 100,
          box80Rate: 100,
          box100Rate: 50,
          originPrefecture: '広島県',
          originCity: '豊田郡　大崎上島町',
          rate: {
            average: 0,
            count: 0,
            detail: {
              1: 0,
              2: 0,
              3: 0,
              4: 0,
              5: 0,
            },
          },
          startAt: 1735730460,
          endAt: 1769858460,
        },
      ],
      coordinators: [
        {
          id: '72UsTvLWapHx1KsXZ4XFTX',
          marcheName: '大崎上島農園',
          username: '藤中 拓弥',
          profile: '',
          productTypeIds: [
            'qV9VzHQBuNgEqRYhUgRvjh',
          ],
          businessDays: [],
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/coordinators/thumbnail/tQXNpDMK7PnBrEkQwspcrF.jpg',
          headerUrl: 'https://assets.furumaru.and-period.co.jp/coordinators/header/2YVqbKCmXJTpPkivpJ1LUw.jpg',
          promotionVideoUrl: '',
          instagramId: '',
          facebookId: '',
          prefecture: '広島県',
          city: '豊田郡大崎上島町',
        },
        {
          id: 'hbr2xWpD5ozitaNkHDe5wp',
          marcheName: 'レモ兄商店',
          username: 'レモ兄',
          profile: '野菜ソムリエでレモン大好き「レモ兄」が、広島に眠っている美味しい食べ物を掘り起こしていきます！',
          productTypeIds: [],
          businessDays: [],
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/coordinators/thumbnail/qXfBoAEQW25doECp2noXp6.jpg',
          headerUrl: 'https://assets.furumaru.and-period.co.jp/coordinators/header/ukYKSoDoTJLZ1Fgo8ymSaF.jpg',
          promotionVideoUrl: '',
          instagramId: 'kamijimafarm',
          facebookId: '',
          prefecture: '広島県',
          city: '',
        },
      ],
      producers: [
        {
          id: '2zpxeuo9fS11gEwCDihx3x',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          username: 'マルキン水産',
          profile: '広島県の瀬戸内海を臨む安芸津町で養殖を営む、3代目牡蠣漁師。海水の氷を使ったぷりぷり食感の維持など徹底した鮮度管理と、夏場でも食べられる「かき小町」の生産にも力を入れています！',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/producers/thumbnail/sXLtRKnDjpT1QccQtfJcFk.jpg',
          headerUrl: '',
          promotionVideoUrl: '',
          instagramId: '',
          facebookId: '',
          prefecture: '広島県',
          city: '東広島市',
        },
        {
          id: 'atPsdN1g3m5r1axousAWkk',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          username: 'ふじやファーム',
          profile: '大崎上島の有機JAS認証を取得したオーガニックレモンを栽培するオーガニックレモン農家。\n女性ならではの丁寧な仕事で高品質な果実の栽培を実現する。',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/producers/thumbnail/pqnUibxaKsKadHpi95FxJu.jpg',
          headerUrl: 'https://assets.furumaru.and-period.co.jp/producers/header/b2qSpkgbsriHKiAjzAzkKs.jpg',
          promotionVideoUrl: '',
          instagramId: '',
          facebookId: '',
          prefecture: '',
          city: '',
        },
        {
          id: '2UovNPfYhWFmMyU6VFPsQm',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          username: '越智農園',
          profile: '瀬戸内海の大崎上島で長年、柑橘農家を営んでいます。急斜面で陽の光に照らされたみかんやレモンは島・随一の絶品です。',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/producers/thumbnail/qDAjQpfY4bzsBWPENMATVT.jpg',
          headerUrl: '',
          promotionVideoUrl: '',
          instagramId: '',
          facebookId: '',
          prefecture: '広島県',
          city: '豊田郡大崎上島町外表',
        },
        {
          id: '63LnH5NhCJCqC8xResqyPG',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          username: '松井農園',
          profile: '広島県大崎上島の柑橘農家。\n音楽と柑橘をこよなく愛するご夫婦の作る絶品柑橘は数量限定での出品で大注目！！\n',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/producers/thumbnail/4X4X7tPNvUodNXSF86HUp8.jpg',
          headerUrl: '',
          promotionVideoUrl: '',
          instagramId: '',
          facebookId: '',
          prefecture: '',
          city: '',
        },
        {
          id: 'sZhADTu5Z4yUWnKjgcVU5t',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          username: '甲斐農園',
          profile: '広島県・安芸津町で瀬戸内海を臨む温暖な畑で柑橘などを育てる甲斐さん。地域の若手農家のリーダーとして、レモンやみかん、特産の新じゃがいもを育てています。',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/producers/thumbnail/4rKmWGmbyCvrpPBAy6WxoY.jpg',
          headerUrl: '',
          promotionVideoUrl: '',
          instagramId: '',
          facebookId: '',
          prefecture: '広島県',
          city: '東広島市',
        },
        {
          id: 'rAcvhtctMQhrwcR1wcri7q',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          username: '東広島ジビエセンター',
          profile: '「栄肉」というブランドで鹿・猪のジビエ肉の狩猟から加工まで行います！日本トップレベルの処理技術で国産ジビエ認証も取得。',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/producers/thumbnail/j9eHsRJHQfeE1CkKMyTwmT.jpg',
          headerUrl: '',
          promotionVideoUrl: '',
          instagramId: '',
          facebookId: '',
          prefecture: '',
          city: '',
        },
        {
          id: 'jPGpBAADF81TTv5jbj6uBe',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          username: '西田農園',
          profile: '大崎上島の明石地区にある歴史ある農園。\n野菜から柑橘、野菜苗と幅広い技術を持っているのが特徴。\n紅八朔やみかんなど他品目を安定的に生産する。',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/producers/thumbnail/dWFV74dkUdT7Tg3QhBhYrq.jpg',
          headerUrl: 'https://assets.furumaru.and-period.co.jp/producers/header/9T4t8WvF8jqVWtQrJBGXGA.jpg',
          promotionVideoUrl: '',
          instagramId: '',
          facebookId: '',
          prefecture: '',
          city: '',
        },
        {
          id: '3NAJgJ7jLxKj287ckrcS4X',
          coordinatorId: '72UsTvLWapHx1KsXZ4XFTX',
          username: '西田農園',
          profile: '',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/producers/thumbnail/hg8umYMzqujCNykwbKQodQ.jpg',
          headerUrl: 'https://assets.furumaru.and-period.co.jp/producers/header/sunsGTGUrvzJReonPPwbH1.jpg',
          promotionVideoUrl: '',
          instagramId: '',
          facebookId: '',
          prefecture: '広島県',
          city: '豊田郡大崎上島町明石',
        },
        {
          id: 'maPpNEY2KCDQXu5AKvPtTk',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          username: 'はやて農園',
          profile: '瀬戸内海を臨む安芸津町で、夫婦で赤土じゃがいも作りに力を入れています！ピンク色の可愛い箱でお届けします！',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/producers/thumbnail/dRBW7huMx2bur7U9KT8a6x.jpg',
          headerUrl: '',
          promotionVideoUrl: '',
          instagramId: '',
          facebookId: '',
          prefecture: '',
          city: '',
        },
        {
          id: 'abSyW5W7cZLKQoqKFXcW4V',
          coordinatorId: 'hbr2xWpD5ozitaNkHDe5wp',
          username: 'ファーム西田口',
          profile: '朝晩の寒暖差が大きな地域で、澄んだ空気と綺麗な水をたっぷりと吸い込んだ『すぃーとアスパラ』を生産。春は甘味が強く、夏はシャキシャキとした歯ごたえがあり、シーズンで味が変わります。',
          thumbnailUrl: 'https://assets.furumaru.and-period.co.jp/producers/thumbnail/tvq3jGrwH66xnbFQpKB7VH.jpg',
          headerUrl: '',
          promotionVideoUrl: '',
          instagramId: '',
          facebookId: '',
          prefecture: '',
          city: '',
        },
      ],
      categories: [
        {
          id: 'uhCUgQefyxhkGLj3wNEXAN',
          name: '調味料・香辛料',
        },
        {
          id: 'v15LHKFHpeobQiN6cmrmB4',
          name: '肉類',
        },
        {
          id: 'vazPgxgPC6YnTgHHdjZNw1',
          name: '野菜',
        },
        {
          id: 'w7FekSnGeMHNcam35LnKew',
          name: '果物',
        },
        {
          id: 'aPZNRJbsWHxze6DMzyHDUU',
          name: '魚介類',
        },
      ],
      productTypes: [
        {
          id: 'ttKFsf29vDZ3EshPqsCSgS',
          name: 'その他・調味料',
          iconUrl: '',
          categoryId: 'uhCUgQefyxhkGLj3wNEXAN',
        },
        {
          id: 'pqdcgCiuk5i8RvNiz5h52b',
          name: 'その他・肉類',
          iconUrl: '',
          categoryId: 'v15LHKFHpeobQiN6cmrmB4',
        },
        {
          id: 'cjNk1GPcUj42GVWboKJsUJ',
          name: 'あしたば',
          iconUrl: '',
          categoryId: 'vazPgxgPC6YnTgHHdjZNw1',
        },
        {
          id: 's9hdTNK5omawq1pJgA6fDY',
          name: 'カンキツ類',
          iconUrl: '',
          categoryId: 'w7FekSnGeMHNcam35LnKew',
        },
        {
          id: 'aRGjN1PYzPXPbffN2gm6pY',
          name: 'その他・貝類',
          iconUrl: '',
          categoryId: 'aPZNRJbsWHxze6DMzyHDUU',
        },
        {
          id: 'f93K71F7CDjo78W1GiKrX3',
          name: 'その他',
          iconUrl: '',
          categoryId: 'w7FekSnGeMHNcam35LnKew',
        },
      ],
      productTags: [],
      total: 27,
    },
  }),

  getters: {
    products: (state) => {
      return state.productsResponse.products;
    },

    getProductById: state => (id: string) => {
      return state.productsResponse.products.find(product => product.id === id);
    },
  },

  actions: {},
});
