version: '3.9'

services:
  user_web:
    container_name: user_web
    build:
      context: ./infra/docker/web/user
      dockerfile: Dockerfile.development
    working_dir: /var/web
    volumes:
      - ./web/user:/var/web:cached
    ports:
      - 3000:3000
    command: yarn dev -H 0.0.0.0 -p 3000

  admin_web:
    container_name: admin_web
    build:
      context: ./infra/docker/web/admin
      dockerfile: Dockerfile.development
    working_dir: /var/web
    volumes:
      - ./web/admin:/var/web:cached
    ports:
      - 3020:3000
    command: yarn dev -H 0.0.0.0 -p 3000

  user_gateway:
    container_name: user_gateway
    build:
      context: .
      dockerfile: ./infra/docker/api/Dockerfile.development
    working_dir: /go/src/github.com/and-period/marche/api
    volumes:
      - ./api:/go/src/github.com/and-period/marche/api:cached
      - ./tmp/data/go/pkg/mod:/go/pkg/mod:delegated
      - ./tmp/logs/api/gateway/user:/var/log/api:delegated
    environment:
      - PORT=9000
      - METRICS_PORT=9001
      - SHUTDOWN_DELAY_SEC=0
      - LOG_LEVEL=debug
      - LOG_PATH=/var/log/api
      - DB_STORE_HOST=${MYSQL_STORE_HOST}
      - DB_STORE_PORT=${MYSQL_STORE_PORT}
      - DB_STORE_USERNAME=${MYSQL_STORE_USERNAME}
      - DB_STORE_PASSWORD=${MYSQL_STORE_PASSWORD}
      - DB_STORE_TIMEZONE=${MYSQL_STORE_TIMEZONE}
      - DB_STORE_ENABLED_TLS=${MYSQL_STORE_ENABLED_TLS}
      - DB_USER_HOST=${MYSQL_USER_HOST}
      - DB_USER_PORT=${MYSQL_USER_PORT}
      - DB_USER_USERNAME=${MYSQL_USER_USERNAME}
      - DB_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - DB_USER_TIMEZONE=${MYSQL_USER_TIMEZONE}
      - DB_USER_ENABLED_TLS=${MYSQL_USER_ENABLED_TLS}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - S3_USER_BUCKET=${S3_USER_BUCKET}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_USER_CLIENT_ID=${COGNITO_USER_CLIENT_ID}
    ports:
      - 18000:9000
      - 18001:9001
    command: make dev SERVICE=gateway/user

  admin_gateway:
    container_name: admin_gateway
    build:
      context: .
      dockerfile: ./infra/docker/api/Dockerfile.development
    working_dir: /go/src/github.com/and-period/marche/api
    volumes:
      - ./api:/go/src/github.com/and-period/marche/api:cached
      - ./tmp/data/go/pkg/mod:/go/pkg/mod:delegated
      - ./tmp/logs/api/gateway/admin:/var/log/api:delegated
    environment:
      - PORT=9000
      - METRICS_PORT=9001
      - SHUTDOWN_DELAY_SEC=0
      - LOG_LEVEL=debug
      - LOG_PATH=/var/log/api
      - DB_STORE_HOST=${MYSQL_STORE_HOST}
      - DB_STORE_PORT=${MYSQL_STORE_PORT}
      - DB_STORE_USERNAME=${MYSQL_STORE_USERNAME}
      - DB_STORE_PASSWORD=${MYSQL_STORE_PASSWORD}
      - DB_STORE_TIMEZONE=${MYSQL_STORE_TIMEZONE}
      - DB_STORE_ENABLED_TLS=${MYSQL_STORE_ENABLED_TLS}
      - DB_USER_HOST=${MYSQL_USER_HOST}
      - DB_USER_PORT=${MYSQL_USER_PORT}
      - DB_USER_USERNAME=${MYSQL_USER_USERNAME}
      - DB_USER_PASSWORD=${MYSQL_USER_PASSWORD}
      - DB_USER_TIMEZONE=${MYSQL_USER_TIMEZONE}
      - DB_USER_ENABLED_TLS=${MYSQL_USER_ENABLED_TLS}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - S3_STORE_BUCKET=${S3_STORE_BUCKET}
      - S3_USER_BUCKET=${S3_USER_BUCKET}
      - COGNITO_ADMIN_POOL_ID=${COGNITO_ADMIN_POOL_ID}
      - COGNITO_ADMIN_CLIENT_ID=${COGNITO_ADMIN_CLIENT_ID}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_USER_CLIENT_ID=${COGNITO_USER_CLIENT_ID}
      - RBAC_POLICY_PATH=/go/src/github.com/and-period/marche/api/config/gateway/admin/rbac/policy.csv
      - RBAC_MODEL_PATH=/go/src/github.com/and-period/marche/api/config/gateway/admin/rbac/model.conf
    ports:
      - 18010:9000
      - 18011:9001
    command: make dev SERVICE=gateway/admin

  mysql_test:
    container_name: mysql_test
    platform: linux/x86_64
    build:
      context: ./infra/docker/infra/mysql
      dockerfile: Dockerfile
    volumes:
      - ./infra/mysql/test.cnf:/etc/mysql/conf.d/my.cnf
      - ./infra/mysql/schema:/docker-entrypoint-initdb.d
      - ./tmp/logs/mysql_test:/var/log/mysql:delegated
      - ./tmp/data/mysql_test:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - 3326:3306

  executor:
    container_name: executor
    build:
      context: .
      dockerfile: ./infra/docker/api/hack/Dockerfile
    working_dir: /go/src/github.com/and-period/marche/api
    volumes:
      - ./api:/go/src/github.com/and-period/marche/api:cached
      - ./infra:/go/src/github.com/and-period/marche/infra:cached
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=12345678

  swagger_generator:
    container_name: swagger_generator
    build:
      context: ./infra/docker/docs/swagger/generator
      dockerfile: Dockerfile
    working_dir: /var/swagger
    volumes:
      - ./docs/swagger:/var/swagger:cached
      - ./tmp/data/swagger:/tmp/data/swagger:cached
      - ./web:/web:cached
    command: yarn watch

  swagger_user:
    container_name: swagger_user
    build:
      context: ./infra/docker/docs/swagger/viewer
      dockerfile: Dockerfile
    volumes:
      - ./tmp/data/swagger/user/docs/openapi:/var/swagger:cached
    ports:
      - 9000:8080
    environment:
      SWAGGER_JSON: /var/swagger/openapi.yaml
    depends_on:
      - swagger_generator

  swagger_admin:
    container_name: swagger_admin
    build:
      context: ./infra/docker/docs/swagger/viewer
      dockerfile: Dockerfile
    volumes:
      - ./tmp/data/swagger/admin/docs/openapi:/var/swagger:cached
    ports:
      - 9020:8080
    environment:
      SWAGGER_JSON: /var/swagger/openapi.yaml
    depends_on:
      - swagger_generator
