version: '3.9'

services:
  user_web:
    container_name: user_web
    build:
      context: ./infra/docker/web/user
      dockerfile: Dockerfile.development
    working_dir: /var/web
    volumes:
      - ./web/user:/var/web:cached
    ports:
      - 3000:3000
    command: yarn dev -H 0.0.0.0 -p 3000

  admin_web:
    container_name: admin_web
    build:
      context: ./infra/docker/web/admin
      dockerfile: Dockerfile.development
    working_dir: /var/web
    volumes:
      - ./web/admin:/var/web:cached
    ports:
      - 3010:3000
    command: yarn dev -H 0.0.0.0 -p 3000

  user_gateway:
    container_name: user_gateway
    build:
      context: .
      dockerfile: ./infra/docker/api/Dockerfile.development
    working_dir: /go/src/github.com/and-period/furumaru/api
    volumes:
      - ./api:/go/src/github.com/and-period/furumaru/api:cached
      - ./tmp/data/go/pkg/mod:/go/pkg/mod:delegated
      - ./tmp/logs/api/gateway/user:/var/log/api:delegated
    environment:
      - PORT=9000
      - METRICS_PORT=9001
      - SHUTDOWN_DELAY_SEC=0
      - LOG_LEVEL=debug
      - LOG_PATH=/var/log/api
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_USER_CLIENT_ID=${COGNITO_USER_CLIENT_ID}
      - SQS_MOCK_ENABLED=true
      - USER_WEB_URL=http://127.0.0.1:3000
    ports:
      - 18000:9000
      - 18001:9001
    depends_on:
      - mysql
    command: make start-dev SERVICE=gateway/user

  admin_gateway:
    container_name: admin_gateway
    build:
      context: .
      dockerfile: ./infra/docker/api/Dockerfile.development
    working_dir: /go/src/github.com/and-period/furumaru/api
    volumes:
      - ./api:/go/src/github.com/and-period/furumaru/api:cached
      - ./tmp/data/go/pkg/mod:/go/pkg/mod:delegated
      - ./tmp/logs/api/gateway/admin:/var/log/api:delegated
    environment:
      - PORT=9000
      - METRICS_PORT=9001
      - SHUTDOWN_DELAY_SEC=0
      - ENV=development
      - LOG_LEVEL=debug
      - LOG_PATH=/var/log/api
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
      - NEW_RELIC_LICENSE=${NEW_RELIC_LICENSE}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_KEY=${STRIPE_WEBHOOK_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_TMP_BUCKET=${S3_TMP_BUCKET}
      - COGNITO_ADMIN_POOL_ID=${COGNITO_ADMIN_POOL_ID}
      - COGNITO_ADMIN_CLIENT_ID=${COGNITO_ADMIN_CLIENT_ID}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_USER_CLIENT_ID=${COGNITO_USER_CLIENT_ID}
      - SQS_MOCK_ENABLED=true
      - ADMIN_WEB_URL=http://127.0.0.1:3010
      - USER_WEB_URL=http://127.0.0.1:3000
      - RBAC_POLICY_PATH=/go/src/github.com/and-period/furumaru/api/config/gateway/admin/rbac/policy.csv
      - RBAC_MODEL_PATH=/go/src/github.com/and-period/furumaru/api/config/gateway/admin/rbac/model.conf
    ports:
      - 18010:9000
      - 18011:9001
    depends_on:
      - mysql
    command: make start-dev SERVICE=gateway/admin

  mysql:
    container_name: mysql
    platform: linux/x86_64
    build:
      context: ./infra/docker/infra/mysql
      dockerfile: Dockerfile
    volumes:
      - ./infra/mysql/dev.cnf:/etc/mysql/conf.d/my.cnf
      - ./infra/mysql/schema:/docker-entrypoint-initdb.d
      - ./tmp/logs/mysql:/var/log/mysql:delegated
      - ./tmp/data/mysql:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - 3316:3306

  executor:
    container_name: executor
    build:
      context: .
      dockerfile: ./infra/docker/api/hack/Dockerfile
    working_dir: /go/src/github.com/and-period/furumaru/api
    volumes:
      - ./api:/go/src/github.com/and-period/furumaru/api:cached
      - ./infra:/go/src/github.com/and-period/furumaru/infra:cached
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=12345678

  function_node_builder:
    container_name: function_node_builder
    platform: linux/amd64
    build:
      context: ./infra/docker/func/node
      dockerfile: Dockerfile
    working_dir: /var/func
    volumes:
      - ./func:/var/func:cached
      - ./tmp/data/func:/tmp/data/func:cached

  swagger_generator:
    container_name: swagger_generator
    build:
      context: .
      dockerfile: ./infra/docker/docs/swagger/generator/Dockerfile
    working_dir: /var/swagger
    volumes:
      - ./docs/swagger:/var/swagger:cached
      - ./tmp/data/swagger:/tmp/data/swagger:cached
      - ./web:/web:cached
    command: yarn watch

  swagger_user:
    container_name: swagger_user
    build:
      context: ./infra/docker/docs/swagger/viewer
      dockerfile: Dockerfile
    volumes:
      - ./tmp/data/swagger/user/docs/openapi:/var/swagger:cached
    ports:
      - 9000:8080
    environment:
      SWAGGER_JSON: /var/swagger/openapi.yaml
    depends_on:
      - swagger_generator

  swagger_admin:
    container_name: swagger_admin
    build:
      context: ./infra/docker/docs/swagger/viewer
      dockerfile: Dockerfile
    volumes:
      - ./tmp/data/swagger/admin/docs/openapi:/var/swagger:cached
    ports:
      - 9010:8080
    environment:
      SWAGGER_JSON: /var/swagger/openapi.yaml
    depends_on:
      - swagger_generator
