package master

import (
	"github.com/and-period/furumaru/api/internal/user/entity"
)

var AdminPolicies = entity.AdminPolicies{
	{
		ID:          "administrator_list",
		Name:        "管理者 一覧取得",
		Description: "管理者の一覧取得権限です。",
		Priority:    1,
		Path:        "/v1/administrators",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "administrator_get",
		Name:        "管理者 詳細取得",
		Description: "管理者の詳細取得権限です。",
		Priority:    2,
		Path:        "/v1/administrators/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "administrator_create",
		Name:        "管理者 登録",
		Description: "管理者の登録権限です。",
		Priority:    3,
		Path:        "/v1/administrators",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "administrator_update",
		Name:        "管理者 更新",
		Description: "管理者の更新権限です。",
		Priority:    4,
		Path:        "/v1/administrators/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "administrator_delete",
		Name:        "管理者 削除",
		Description: "管理者の削除権限です。",
		Priority:    5,
		Path:        "/v1/administrators/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "auth_login",
		Name:        "ログイン",
		Description: "ログイン関連の権限です。",
		Priority:    6,
		Path:        "/v1/auth",
		Method:      "(GET)|(POST)|(DELETE)",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "auth_user",
		Name:        "認証 取得・操作",
		Description: "認証情報の取得・操作の権限です。",
		Priority:    7,
		Path:        "/v1/auth/*",
		Method:      "(GET)|(POST)|(PATCH)",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "broadcast_get",
		Name:        "ライブ配信 詳細取得",
		Description: "ライブ配信の詳細取得権限です。",
		Priority:    8,
		Path:        "/v1/schedules/*/broadcasts",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "broadcast_update",
		Name:        "ライブ配信 登録・更新・削除",
		Description: "ライブ配信の更新権限です。",
		Priority:    9,
		Path:        "/v1/schedules/*/broadcasts",
		Method:      "(POST)|(PATCH)|(DELETE)",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "broadcast_action",
		Name:        "ライブ配信 操作",
		Description: "ライブ配信の操作権限です。",
		Priority:    10,
		Path:        "/v1/schedules/*/broadcasts/*",
		Method:      "(POST)|(DELETE)",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "category_list",
		Name:        "商品カテゴリ 一覧取得",
		Description: "商品カテゴリの一覧取得権限です。",
		Priority:    11,
		Path:        "/v1/categories",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "category_create",
		Name:        "商品カテゴリ 登録",
		Description: "商品カテゴリの登録権限です。",
		Priority:    12,
		Path:        "/v1/categories",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "category_update",
		Name:        "商品カテゴリ 更新",
		Description: "商品カテゴリの更新権限です。",
		Priority:    13,
		Path:        "/v1/categories/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "category_delete",
		Name:        "商品カテゴリ 削除",
		Description: "商品カテゴリの削除権限です。",
		Priority:    14,
		Path:        "/v1/categories/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "contact_list",
		Name:        "お問い合わせ 一覧取得",
		Description: "お問い合わせの一覧取得権限です。",
		Priority:    15,
		Path:        "/v1/contacts",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "contact_get",
		Name:        "お問い合わせ 詳細取得",
		Description: "お問い合わせの詳細取得権限です。",
		Priority:    16,
		Path:        "/v1/contacts/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "contact_create",
		Name:        "お問い合わせ 登録",
		Description: "お問い合わせの登録権限です。",
		Priority:    17,
		Path:        "/v1/contacts",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "contact_update",
		Name:        "お問い合わせ 更新",
		Description: "お問い合わせの更新権限です。",
		Priority:    18,
		Path:        "/v1/contacts/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "contact_delete",
		Name:        "お問い合わせ 削除",
		Description: "お問い合わせの削除権限です。",
		Priority:    19,
		Path:        "/v1/contacts/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "contact_category_list",
		Name:        "お問い合わせ種別 一覧取得",
		Description: "お問い合わせ種別の一覧取得権限です。",
		Priority:    20,
		Path:        "/vi/contact-categories",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "contact_category_get",
		Name:        "お問い合わせ種別 詳細取得",
		Description: "お問い合わせ種別の詳細取得権限です。",
		Priority:    21,
		Path:        "/v1/contact-categories/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "contact_read_create",
		Name:        "お問い合わせ種別 登録",
		Description: "お問い合わせ種別の登録権限です。",
		Priority:    22,
		Path:        "/v1/contact-reads",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "coordinator_list",
		Name:        "コーディネータ 一覧取得",
		Description: "コーディネータの一覧取得権限です。",
		Priority:    23,
		Path:        "/v1/coordinators",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "coordinator_get",
		Name:        "コーディネータ 詳細取得",
		Description: "コーディネータの詳細取得権限です。",
		Priority:    24,
		Path:        "/v1/coordinators/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "coordinator_create",
		Name:        "コーディネータ 登録",
		Description: "コーディネータの登録権限です。",
		Priority:    25,
		Path:        "/v1/coordinators",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "coordinator_update",
		Name:        "コーディネータ 更新",
		Description: "コーディネータの更新権限です。",
		Priority:    26,
		Path:        "/v1/coordinators/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "coordinator_delete",
		Name:        "コーディネータ 削除",
		Description: "コーディネータの削除権限です。",
		Priority:    27,
		Path:        "/v1/coordinators/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "coordinator_upload",
		Name:        "コーディネータ アップロード",
		Description: "コーディネータのアップロード権限です。",
		Priority:    28,
		Path:        "/v1/upload/coordinators/*",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "experience_type_list",
		Name:        "体験種別 一覧取得",
		Description: "体験種別の一覧取得権限です。",
		Priority:    29,
		Path:        "/v1/experience-types",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "experience_type_create",
		Name:        "体験種別 登録",
		Description: "体験種別の登録権限です。",
		Priority:    30,
		Path:        "/v1/experience-types",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "experience_type_update",
		Name:        "体験種別 更新",
		Description: "体験種別の更新権限です。",
		Priority:    31,
		Path:        "/v1/experience-types/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "experience_type_delete",
		Name:        "体験種別 削除",
		Description: "体験種別の削除権限です。",
		Priority:    32,
		Path:        "/v1/experience-types/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "experience_list",
		Name:        "体験 一覧取得",
		Description: "体験の一覧取得権限です。",
		Priority:    33,
		Path:        "/v1/experiences",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "experience_get",
		Name:        "体験 詳細取得",
		Description: "体験の詳細取得権限です。",
		Priority:    34,
		Path:        "/v1/experiences/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "experience_create",
		Name:        "体験 登録",
		Description: "体験の登録権限です。",
		Priority:    35,
		Path:        "/v1/experiences",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "experience_update",
		Name:        "体験 更新",
		Description: "体験の更新権限です。",
		Priority:    36,
		Path:        "/v1/experiences/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "experience_delete",
		Name:        "体験 削除",
		Description: "体験の削除権限です。",
		Priority:    37,
		Path:        "/v1/experiences/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "experience_upload",
		Name:        "体験 アップロード",
		Description: "体験のアップロード権限です。",
		Priority:    38,
		Path:        "/v1/upload/experiences/*",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "live_list",
		Name:        "ライブタイムテーブル 一覧取得",
		Description: "ライブタイムテーブルの一覧取得権限です。",
		Priority:    39,
		Path:        "/v1/schedules/*/lives",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "live_get",
		Name:        "ライブタイムテーブル 詳細取得",
		Description: "ライブタイムテーブルの詳細取得権限です。",
		Priority:    40,
		Path:        "/v1/schedules/*/lives/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "live_create",
		Name:        "ライブタイムテーブル 登録",
		Description: "ライブタイムテーブルの登録権限です。",
		Priority:    41,
		Path:        "/v1/schedules/*/lives",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "live_update",
		Name:        "ライブタイムテーブル 更新",
		Description: "ライブタイムテーブルの更新権限です。",
		Priority:    42,
		Path:        "/v1/schedules/*/lives/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "live_delete",
		Name:        "ライブタイムテーブル 削除",
		Description: "ライブタイムテーブルの削除権限です。",
		Priority:    43,
		Path:        "/v1/schedules/*/lives/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "message_list",
		Name:        "メッセージ 一覧取得",
		Description: "メッセージの一覧取得権限です。",
		Priority:    44,
		Path:        "/v1/messages",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "message_get",
		Name:        "メッセージ 詳細取得",
		Description: "メッセージの詳細取得権限です。",
		Priority:    45,
		Path:        "/v1/messages/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "notification_list",
		Name:        "お知らせ 一覧取得",
		Description: "お知らせの一覧取得権限です。",
		Priority:    46,
		Path:        "/v1/notifications",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "notification_get",
		Name:        "お知らせ 詳細取得",
		Description: "お知らせの詳細取得権限です。",
		Priority:    47,
		Path:        "/v1/notifications/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "notification_create",
		Name:        "お知らせ 登録",
		Description: "お知らせの登録権限です。",
		Priority:    48,
		Path:        "/v1/notifications",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "notification_update",
		Name:        "お知らせ 更新",
		Description: "お知らせの更新権限です。",
		Priority:    49,
		Path:        "/v1/notifications/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "notification_delete",
		Name:        "お知らせ 削除",
		Description: "お知らせの削除権限です。",
		Priority:    50,
		Path:        "/v1/notifications/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "order_list",
		Name:        "注文履歴 一覧取得",
		Description: "注文履歴の一覧取得権限です。",
		Priority:    51,
		Path:        "/v1/orders",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "order_get",
		Name:        "注文履歴 詳細取得",
		Description: "注文履歴の詳細取得権限です。",
		Priority:    52,
		Path:        "/v1/orders/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "order_update",
		Name:        "注文履歴 更新",
		Description: "注文履歴の更新権限です。",
		Priority:    53,
		Path:        "/v1/orders/*",
		Method:      "(POST)|(PATCH)",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "payment_system_list",
		Name:        "支払いシステム状態 一覧取得",
		Description: "支払いシステム状態の一覧取得権限です。",
		Priority:    54,
		Path:        "/v1/payment-systems",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "payment_system_update",
		Name:        "支払いシステム状態 更新",
		Description: "支払いシステム状態の更新権限です。",
		Priority:    55,
		Path:        "/v1/payment-systems/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "producer_list",
		Name:        "生産者 一覧取得",
		Description: "生産者の一覧取得権限です。",
		Priority:    56,
		Path:        "/v1/producers",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "producer_get",
		Name:        "生産者 詳細取得",
		Description: "生産者の詳細取得権限です。",
		Priority:    57,
		Path:        "/v1/producers/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "producer_create",
		Name:        "生産者 登録",
		Description: "生産者の登録権限です。",
		Priority:    58,
		Path:        "/v1/producers",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "producer_update",
		Name:        "生産者 更新",
		Description: "生産者の更新権限です。",
		Priority:    59,
		Path:        "/v1/producers/*",
		Method:      "(POST)|(PATCH)",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "producer_delete",
		Name:        "生産者 削除",
		Description: "生産者の削除権限です。",
		Priority:    60,
		Path:        "/v1/producers/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "producer_upload",
		Name:        "生産者 アップロード",
		Description: "生産者のアップロード権限です。",
		Priority:    61,
		Path:        "/v1/upload/producers/*",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_list",
		Name:        "商品 一覧取得",
		Description: "商品の一覧取得権限です。",
		Priority:    62,
		Path:        "/v1/products",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_get",
		Name:        "商品 詳細取得",
		Description: "商品の詳細取得権限です。",
		Priority:    63,
		Path:        "/v1/products/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_create",
		Name:        "商品 登録",
		Description: "商品の登録権限です。",
		Priority:    64,
		Path:        "/v1/products",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_update",
		Name:        "商品 更新",
		Description: "商品の更新権限です。",
		Priority:    65,
		Path:        "/v1/products/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_delete",
		Name:        "商品 削除",
		Description: "商品の削除権限です。",
		Priority:    66,
		Path:        "/v1/products/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_upload",
		Name:        "商品 アップロード",
		Description: "商品のアップロード権限です。",
		Priority:    67,
		Path:        "/v1/upload/products/*",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_tag_list",
		Name:        "商品タグ 一覧取得",
		Description: "商品タグの一覧取得権限です。",
		Priority:    68,
		Path:        "/v1/product-tags",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_tag_create",
		Name:        "商品タグ 登録",
		Description: "商品タグの登録権限です。",
		Priority:    69,
		Path:        "/v1/product-tags",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_tag_update",
		Name:        "商品タグ 更新",
		Description: "商品タグの更新権限です。",
		Priority:    70,
		Path:        "/v1/product-tags/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_tag_delete",
		Name:        "商品タグ 削除",
		Description: "商品タグの削除権限です。",
		Priority:    71,
		Path:        "/v1/product-tags/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_type_list",
		Name:        "商品種別 一覧取得",
		Description: "商品種別の一覧取得権限です。",
		Priority:    72,
		Path:        "/v1/categories/*/product-types",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_type_create",
		Name:        "商品種別 登録",
		Description: "商品種別の登録権限です。",
		Priority:    73,
		Path:        "/v1/categories/*/product-types",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_type_update",
		Name:        "商品種別 更新",
		Description: "商品種別の更新権限です。",
		Priority:    74,
		Path:        "/v1/categories/*/product-types/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_type_delete",
		Name:        "商品種別 削除",
		Description: "商品種別の削除権限です。",
		Priority:    75,
		Path:        "/v1/categories/*/product-types/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_type_upload",
		Name:        "商品種別 アップロード",
		Description: "商品種別のアップロード権限です。",
		Priority:    76,
		Path:        "/v1/upload/product-types/*",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "promotion_list",
		Name:        "プロモーション 一覧取得",
		Description: "プロモーションの一覧取得権限です。",
		Priority:    77,
		Path:        "/v1/promotions",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "promotion_get",
		Name:        "プロモーション 詳細取得",
		Description: "プロモーションの詳細取得権限です。",
		Priority:    78,
		Path:        "/v1/promotions/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "promotion_create",
		Name:        "プロモーション 登録",
		Description: "プロモーションの登録権限です。",
		Priority:    79,
		Path:        "/v1/promotions",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "promotion_update",
		Name:        "プロモーション 更新",
		Description: "プロモーションの更新権限です。",
		Priority:    80,
		Path:        "/v1/promotions/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "promotion_delete",
		Name:        "プロモーション 削除",
		Description: "プロモーションの削除権限です。",
		Priority:    81,
		Path:        "/v1/promotions/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "schedule_list",
		Name:        "ライブスケジュール 一覧取得",
		Description: "ライブスケジュールの一覧取得権限です。",
		Priority:    82,
		Path:        "/v1/schedules",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "schedule_get",
		Name:        "ライブスケジュール 詳細取得",
		Description: "ライブスケジュールの詳細取得権限です。",
		Priority:    83,
		Path:        "/v1/schedules/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "schedule_create",
		Name:        "ライブスケジュール 登録",
		Description: "ライブスケジュールの登録権限です。",
		Priority:    84,
		Path:        "/v1/schedules",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "schedule_update",
		Name:        "ライブスケジュール 更新",
		Description: "ライブスケジュールの更新権限です。",
		Priority:    85,
		Path:        "/v1/schedules/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "schedule_delete",
		Name:        "ライブスケジュール 削除",
		Description: "ライブスケジュールの削除権限です。",
		Priority:    86,
		Path:        "/v1/schedules/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "schedule_upload",
		Name:        "ライブスケジュール アップロード",
		Description: "ライブスケジュールのアップロード権限です。",
		Priority:    87,
		Path:        "/v1/upload/schedules/*",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "shipping_get",
		Name:        "配送設定 詳細取得",
		Description: "配送設定の詳細取得権限です。",
		Priority:    88,
		Path:        "/v1/coordinators/*/shippings/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "shipping_upsert",
		Name:        "配送設定 登録・削除",
		Description: "配送設定の登録・削除権限です。",
		Priority:    89,
		Path:        "/v1/coordinators/*/shippings",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "default_shipping_get",
		Name:        "配送設定 詳細取得",
		Description: "配送設定の詳細取得権限です。",
		Priority:    90,
		Path:        "/v1/shippings/default",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "default_shipping_update",
		Name:        "配送設定 更新",
		Description: "配送設定の更新権限です。",
		Priority:    91,
		Path:        "/v1/shippings/default",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "spot_type_list",
		Name:        "スポット種別 一覧取得",
		Description: "スポット種別の一覧取得権限です。",
		Priority:    92,
		Path:        "/v1/spot-types",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "spot_type_create",
		Name:        "スポット種別 登録",
		Description: "スポット種別の登録権限です。",
		Priority:    93,
		Path:        "/v1/spot-types",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "spot_type_update",
		Name:        "スポット種別 更新",
		Description: "スポット種別の更新権限です。",
		Priority:    94,
		Path:        "/v1/spot-types/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "spot_type_delete",
		Name:        "スポット種別 削除",
		Description: "スポット種別の削除権限です。",
		Priority:    95,
		Path:        "/v1/spot-types/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "spot_list",
		Name:        "スポット 一覧取得",
		Description: "スポットの一覧取得権限です。",
		Priority:    96,
		Path:        "/v1/spots",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "spot_get",
		Name:        "スポット 詳細取得",
		Description: "スポットの詳細取得権限です。",
		Priority:    97,
		Path:        "/v1/spots/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "spot_create",
		Name:        "スポット 登録",
		Description: "スポットの登録権限です。",
		Priority:    98,
		Path:        "/v1/spots",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "spot_update",
		Name:        "スポット 更新",
		Description: "スポットの更新権限です。",
		Priority:    99,
		Path:        "/v1/spots/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "spot_delete",
		Name:        "スポット 削除",
		Description: "スポットの削除権限です。",
		Priority:    100,
		Path:        "/v1/spots/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "spot_upload",
		Name:        "スポット アップロード",
		Description: "スポットのアップロード権限です。",
		Priority:    101,
		Path:        "/v1/upload/spots/*",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "thread_get",
		Name:        "お問い合わせ履歴 詳細取得",
		Description: "お問い合わせ履歴の詳細取得権限です。",
		Priority:    102,
		Path:        "/v1/contacts/*/threads/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "thread_list_by_contactId",
		Name:        "お問い合わせ履歴 一覧取得",
		Description: "お問い合わせ履歴の一覧取得権限です。",
		Priority:    103,
		Path:        "/v1/contacts/*/threads",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "thread_create",
		Name:        "お問い合わせ履歴 登録",
		Description: "お問い合わせ履歴の登録権限です。",
		Priority:    104,
		Path:        "/v1/contacts/*/threads",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "thread_update",
		Name:        "お問い合わせ履歴 更新",
		Description: "お問い合わせ履歴の更新権限です。",
		Priority:    105,
		Path:        "/v1/contacts/*/threads/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "thread_delete",
		Name:        "お問い合わせ履歴 削除",
		Description: "お問い合わせ履歴の削除権限です。",
		Priority:    106,
		Path:        "/v1/contacts/*/threads/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "user_list",
		Name:        "ユーザー 一覧取得",
		Description: "ユーザーの一覧取得権限です。",
		Priority:    107,
		Path:        "/v1/users",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "user_get",
		Name:        "ユーザー 詳細取得",
		Description: "ユーザーの詳細取得権限です。",
		Priority:    108,
		Path:        "/v1/users/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "user_delete",
		Name:        "ユーザー 削除",
		Description: "ユーザーの削除権限です。",
		Priority:    109,
		Path:        "/v1/users/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "video_list",
		Name:        "オンデマンド配信 一覧取得",
		Description: "オンデマンド配信の一覧取得権限です。",
		Priority:    110,
		Path:        "/v1/videos",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "video_get",
		Name:        "オンデマンド配信 詳細取得",
		Description: "オンデマンド配信の詳細取得権限です。",
		Priority:    111,
		Path:        "/v1/videos/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "video_create",
		Name:        "オンデマンド配信 登録",
		Description: "オンデマンド配信の登録権限です。",
		Priority:    112,
		Path:        "/v1/videos",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "video_update",
		Name:        "オンデマンド配信 更新",
		Description: "オンデマンド配信の更新権限です。",
		Priority:    113,
		Path:        "/v1/videos/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "video_delete",
		Name:        "オンデマンド配信 削除",
		Description: "オンデマンド配信の削除権限です。",
		Priority:    114,
		Path:        "/v1/videos/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "video_upload",
		Name:        "オンデマンド配信 アップロード",
		Description: "オンデマンド配信のアップロード権限です。",
		Priority:    115,
		Path:        "/v1/upload/videos/*",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "postal_code_search",
		Name:        "住所 検索",
		Description: "住所の検索権限です。",
		Priority:    116,
		Path:        "/v1/postal-codes/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "upload_get",
		Name:        "アップロード 詳細取得",
		Description: "アップロードの詳細取得権限です。",
		Priority:    117,
		Path:        "/v1/upload/state",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "shop_list",
		Name:        "店舗 一覧取得",
		Description: "店舗の一覧取得権限です。",
		Priority:    118,
		Path:        "/v1/shops",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "shop_get",
		Name:        "店舗 詳細取得",
		Description: "店舗の詳細取得権限です。",
		Priority:    119,
		Path:        "/v1/shops/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "shop_update",
		Name:        "店舗 更新",
		Description: "店舗の更新権限です。",
		Priority:    120,
		Path:        "/v1/shops/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "shipping_list",
		Name:        "配送設定 一覧取得",
		Description: "配送設定の一覧取得権限です。",
		Priority:    121,
		Path:        "/v1/coordinators/*/shippings",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "shipping_get_activated",
		Name:        "配送設定 有効な配送取得",
		Description: "配送設定の有効な配送取得権限です。",
		Priority:    122,
		Path:        "/v1/coordinators/*/shippings/activation",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "shipping_create",
		Name:        "配送設定 作成",
		Description: "配送設定の作成権限です。",
		Priority:    123,
		Path:        "/v1/coordinators/*/shippings",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "shipping_update",
		Name:        "配送設定 更新",
		Description: "配送設定の更新権限です。",
		Priority:    124,
		Path:        "/v1/coordinators/*/shippings/*",
		Method:      "PATCH",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "shipping_delete",
		Name:        "配送設定 削除",
		Description: "配送設定の削除権限です。",
		Priority:    125,
		Path:        "/v1/coordinators/*/shippings/*",
		Method:      "DELETE",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "shipping_activate",
		Name:        "配送設定 有効化",
		Description: "配送設定の有効化権限です。",
		Priority:    126,
		Path:        "/v1/coordinators/*/shippings/*/activation",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "top_get",
		Name:        "トップ 取得",
		Description: "トップの取得権限です。",
		Priority:    127,
		Path:        "/v1/top/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_review_list",
		Name:        "商品レビュー 一覧取得",
		Description: "商品レビューの一覧取得権限です。",
		Priority:    128,
		Path:        "/v1/products/*/reviews",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_review_get",
		Name:        "商品レビュー 詳細取得",
		Description: "商品レビューの詳細取得権限です。",
		Priority:    129,
		Path:        "/v1/products/*/reviews/*",
		Method:      "GET",
		Action:      entity.AdminPolicyActionAllow,
	},
	{
		ID:          "product_review_create",
		Name:        "商品レビュー ダミー作成",
		Description: "ダミー商品レビューの作成権限です。",
		Priority:    130,
		Path:        "/v1/products/*/reviews",
		Method:      "POST",
		Action:      entity.AdminPolicyActionAllow,
	},
}

type AdminRole struct {
	entity.AdminRole
	PolicyIDs []string
}

var AdminRoles = []AdminRole{
	{
		AdminRole: entity.AdminRole{
			ID:          "general",
			Name:        "一般 共通",
			Description: "一般のロールです。",
		},
		PolicyIDs: []string{
			"auth_user",
			"auth_login",
			"message_list",
			"message_get",
			"postal_code_search",
			"upload_get",
			"top_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "general_coordinator",
			Name:        "一般 コーディネータ",
			Description: "一般のコーディネータ用ロールです。",
		},
		PolicyIDs: []string{
			"coordinator_upload",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "general_producer",
			Name:        "一般 生産者",
			Description: "一般の生産者用ロールです。",
		},
		PolicyIDs: []string{
			"producer_upload",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "administrator_editor",
			Name:        "管理者 編集者",
			Description: "管理者の編集者ロールです。",
		},
		PolicyIDs: []string{
			"administrator_list",
			"administrator_get",
			"administrator_create",
			"administrator_update",
			"administrator_delete",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "administrator_viewer",
			Name:        "管理者 閲覧者",
			Description: "管理者の閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"administrator_list",
			"administrator_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "broadcast_editor",
			Name:        "ライブ配信 編集者",
			Description: "ライブ配信の編集者ロールです。",
		},
		PolicyIDs: []string{
			"broadcast_get",
			"broadcast_update",
			"broadcast_action",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "broadcast_viewer",
			Name:        "ライブ配信 閲覧者",
			Description: "ライブ配信の閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"broadcast_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "category_editor",
			Name:        "商品カテゴリ 編集者",
			Description: "商品カテゴリの編集者ロールです。",
		},
		PolicyIDs: []string{
			"category_list",
			"category_create",
			"category_update",
			"category_delete",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "category_viewer",
			Name:        "商品カテゴリ 閲覧者",
			Description: "商品カテゴリの閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"category_list",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "coordinator_editor",
			Name:        "コーディネータ 編集者",
			Description: "コーディネータの編集者ロールです。",
		},
		PolicyIDs: []string{
			"coordinator_list",
			"coordinator_get",
			"coordinator_create",
			"coordinator_update",
			"coordinator_delete",
			"coordinator_upload",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "coordinator_viewer",
			Name:        "コーディネータ 閲覧者",
			Description: "コーディネータの閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"coordinator_list",
			"coordinator_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "experience_editor",
			Name:        "体験 編集者",
			Description: "体験の編集者ロールです。",
		},
		PolicyIDs: []string{
			"experience_list",
			"experience_get",
			"experience_create",
			"experience_update",
			"experience_delete",
			"experience_upload",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "experience_viewer",
			Name:        "体験 閲覧者",
			Description: "体験の閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"experience_list",
			"experience_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "experience_type_editor",
			Name:        "体験種別 編集者",
			Description: "体験種別の編集者ロールです。",
		},
		PolicyIDs: []string{
			"experience_type_list",
			"experience_type_create",
			"experience_type_update",
			"experience_type_delete",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "experience_type_viewer",
			Name:        "体験種別 閲覧者",
			Description: "体験種別の閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"experience_type_list",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "live_editor",
			Name:        "ライブタイムテーブル 編集者",
			Description: "ライブタイムテーブルの編集者ロールです。",
		},
		PolicyIDs: []string{
			"live_list",
			"live_get",
			"live_create",
			"live_update",
			"live_delete",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "live_viewer",
			Name:        "ライブタイムテーブル 閲覧者",
			Description: "ライブタイムテーブルの閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"live_list",
			"live_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "notification_editor",
			Name:        "お知らせ 編集者",
			Description: "お知らせの編集者ロールです。",
		},
		PolicyIDs: []string{
			"notification_list",
			"notification_get",
			"notification_create",
			"notification_update",
			"notification_delete",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "notification_viewer",
			Name:        "お知らせ 閲覧者",
			Description: "お知らせの閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"notification_list",
			"notification_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "order_editor",
			Name:        "注文履歴 編集者",
			Description: "注文履歴の編集者ロールです。",
		},
		PolicyIDs: []string{
			"order_list",
			"order_get",
			"order_update",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "order_viewer",
			Name:        "注文履歴 閲覧者",
			Description: "注文履歴の閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"order_list",
			"order_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "payment_system_editor",
			Name:        "支払いシステム 編集者",
			Description: "支払いシステムの編集者ロールです。",
		},
		PolicyIDs: []string{
			"payment_system_list",
			"payment_system_update",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "producer_editor",
			Name:        "生産者 編集者",
			Description: "生産者の編集者ロールです。",
		},
		PolicyIDs: []string{
			"producer_list",
			"producer_get",
			"producer_create",
			"producer_update",
			"producer_delete",
			"producer_upload",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "producer_viewer",
			Name:        "生産者 閲覧者",
			Description: "生産者の閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"producer_list",
			"producer_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "product_editor",
			Name:        "商品 編集者",
			Description: "商品の編集者ロールです。",
		},
		PolicyIDs: []string{
			"product_list",
			"product_get",
			"product_create",
			"product_update",
			"product_delete",
			"product_upload",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "product_viewer",
			Name:        "商品 閲覧者",
			Description: "商品の閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"product_list",
			"product_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "product_review_editor",
			Name:        "商品レビュー 編集者",
			Description: "商品レビューの編集者ロールです。",
		},
		PolicyIDs: []string{
			"product_review_list",
			"product_review_get",
			"product_review_create",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "product_review_viewer",
			Name:        "商品レビュー 閲覧者",
			Description: "商品レビューの閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"product_review_list",
			"product_review_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "product_tag_editor",
			Name:        "商品タグ 編集者",
			Description: "商品タグの編集者ロールです。",
		},
		PolicyIDs: []string{
			"product_tag_list",
			"product_tag_create",
			"product_tag_update",
			"product_tag_delete",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "product_tag_viewer",
			Name:        "商品タグ 閲覧者",
			Description: "商品タグの閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"product_tag_list",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "product_type_editor",
			Name:        "商品種別 編集者",
			Description: "商品種別の編集者ロールです。",
		},
		PolicyIDs: []string{
			"product_type_list",
			"product_type_create",
			"product_type_update",
			"product_type_delete",
			"product_type_upload",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "product_type_viewer",
			Name:        "商品種別 閲覧者",
			Description: "商品種別の閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"product_type_list",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "promotion_editor",
			Name:        "プロモーション 編集者",
			Description: "プロモーションの編集者ロールです。",
		},
		PolicyIDs: []string{
			"promotion_list",
			"promotion_get",
			"promotion_create",
			"promotion_update",
			"promotion_delete",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "promotion_viewer",
			Name:        "プロモーション 閲覧者",
			Description: "プロモーションの閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"promotion_list",
			"promotion_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "schedule_editor",
			Name:        "ライブスケジュール 編集者",
			Description: "ライブスケジュールの編集者ロールです。",
		},
		PolicyIDs: []string{
			"schedule_list",
			"schedule_get",
			"schedule_create",
			"schedule_update",
			"schedule_delete",
			"schedule_upload",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "schedule_viewer",
			Name:        "ライブスケジュール 閲覧者",
			Description: "ライブスケジュールの閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"schedule_list",
			"schedule_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "shipping_admin",
			Name:        "配送設定 管理者",
			Description: "配送設定の管理者ロールです。",
		},
		PolicyIDs: []string{
			"default_shipping_get",
			"default_shipping_update",
			"shipping_list",
			"shipping_get",
			"shipping_create",
			"shipping_update",
			"shipping_delete",
			"shipping_activate",
			// Deprecated
			"shipping_get_activated",
			"shipping_upsert",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "shipping_editor",
			Name:        "配送設定 編集者",
			Description: "配送設定の編集者ロールです。",
		},
		PolicyIDs: []string{
			"default_shipping_get",
			"shipping_list",
			"shipping_get",
			"shipping_create",
			"shipping_update",
			"shipping_delete",
			"shipping_activate",
			// Deprecated
			"shipping_get_activated",
			"shipping_upsert",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "shipping_viewer",
			Name:        "配送設定 閲覧者",
			Description: "配送設定の閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"default_shipping_get",
			"shipping_list",
			"shipping_get",
			// Deprecated
			"shipping_get_activated",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "shop_editor",
			Name:        "店舗 編集者",
			Description: "店舗の編集者ロールです。",
		},
		PolicyIDs: []string{
			"shop_list",
			"shop_get",
			"shop_update",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "shop_viewer",
			Name:        "店舗 閲覧者",
			Description: "店舗の閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"shop_list",
			"shop_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "spot_editor",
			Name:        "スポット 編集者",
			Description: "スポットの編集者ロールです。",
		},
		PolicyIDs: []string{
			"spot_list",
			"spot_get",
			"spot_update",
			"spot_delete",
			"spot_upload",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "spot_viewer",
			Name:        "スポット 閲覧者",
			Description: "スポットの閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"spot_list",
			"spot_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "spot_type_editor",
			Name:        "スポット種別 編集者",
			Description: "スポット種別の編集者ロールです。",
		},
		PolicyIDs: []string{
			"spot_type_list",
			"spot_type_create",
			"spot_type_update",
			"spot_type_delete",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "spot_type_viewer",
			Name:        "スポット種別 閲覧者",
			Description: "スポット種別の閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"spot_type_list",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "user_editor",
			Name:        "ユーザー 編集者",
			Description: "ユーザーの編集者ロールです。",
		},
		PolicyIDs: []string{
			"user_list",
			"user_get",
			"user_delete",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "user_viewer",
			Name:        "ユーザー 閲覧者",
			Description: "ユーザーの閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"user_list",
			"user_get",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "video_editor",
			Name:        "オンデマンド配信 編集者",
			Description: "オンデマンド配信の編集者ロールです。",
		},
		PolicyIDs: []string{
			"video_list",
			"video_get",
			"video_create",
			"video_update",
			"video_delete",
			"video_upload",
		},
	},
	{
		AdminRole: entity.AdminRole{
			ID:          "video_viewer",
			Name:        "オンデマンド配信 閲覧者",
			Description: "オンデマンド配信の閲覧者ロールです。",
		},
		PolicyIDs: []string{
			"video_list",
			"video_get",
		},
	},
}

type AdminGroup struct {
	entity.AdminGroup
	RoleIDs []string
}

var AdminGroups = []AdminGroup{
	{
		AdminGroup: entity.AdminGroup{
			ID:          "default-administrator",
			Type:        entity.AdminTypeAdministrator,
			Name:        "デフォルト 管理者",
			Description: "デフォルトの管理者グループです。",
		},
		RoleIDs: []string{
			"general",
			"administrator_editor",
			"broadcast_editor",
			"category_editor",
			"coordinator_editor",
			"experience_editor",
			"experience_type_editor",
			"live_editor",
			"notification_editor",
			"order_editor",
			"payment_system_editor",
			"producer_editor",
			"product_editor",
			"product_review_editor",
			"product_tag_editor",
			"product_type_editor",
			"promotion_editor",
			"schedule_editor",
			"shipping_admin",
			"shop_editor",
			"spot_editor",
			"spot_type_editor",
			"user_editor",
			"video_editor",
		},
	},
	{
		AdminGroup: entity.AdminGroup{
			ID:          "default-coordinator",
			Type:        entity.AdminTypeCoordinator,
			Name:        "デフォルト コーディネータ",
			Description: "デフォルトのコーディネータグループです。",
		},
		RoleIDs: []string{
			"general",
			"general_coordinator",
			"broadcast_editor",
			"category_viewer",
			"experience_editor",
			"experience_type_viewer",
			"live_editor",
			"notification_editor",
			"order_editor",
			"producer_editor",
			"product_editor",
			"product_review_editor",
			"product_tag_viewer",
			"product_type_viewer",
			"promotion_editor",
			"schedule_editor",
			"shipping_editor",
			"shop_editor",
			"spot_editor",
			"spot_type_viewer",
			"user_viewer",
			"video_editor",
		},
	},
	{
		AdminGroup: entity.AdminGroup{
			ID:          "default-producer",
			Type:        entity.AdminTypeProducer,
			Name:        "デフォルト 生産者",
			Description: "デフォルトの生産者グループです。",
		},
		RoleIDs: []string{
			"general",
			"general_producer",
			"broadcast_viewer",
			"category_viewer",
			"experience_viewer",
			"experience_type_viewer",
			"live_viewer",
			"notification_viewer",
			"order_viewer",
			"product_viewer",
			"product_review_viewer",
			"product_tag_viewer",
			"product_type_viewer",
			"schedule_viewer",
			"shop_viewer",
			"spot_editor",
			"spot_type_viewer",
			"video_viewer",
		},
	},
}
