/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAuthUserWithLINERequest
 */
export interface CreateAuthUserWithLINERequest {
    /**
     * ユーザーID(検索名)
     * @type {string}
     * @memberof CreateAuthUserWithLINERequest
     */
    accountId: string;
    /**
     * 認証コード
     * @type {string}
     * @memberof CreateAuthUserWithLINERequest
     */
    code: string;
    /**
     * 名
     * @type {string}
     * @memberof CreateAuthUserWithLINERequest
     */
    firstname: string;
    /**
     * 名（かな）
     * @type {string}
     * @memberof CreateAuthUserWithLINERequest
     */
    firstnameKana: string;
    /**
     * 姓
     * @type {string}
     * @memberof CreateAuthUserWithLINERequest
     */
    lastname: string;
    /**
     * 姓（かな）
     * @type {string}
     * @memberof CreateAuthUserWithLINERequest
     */
    lastnameKana: string;
    /**
     * セキュア文字列（リプレイアタック対策）
     * @type {string}
     * @memberof CreateAuthUserWithLINERequest
     */
    nonce: string;
    /**
     * 電話番号
     * @type {string}
     * @memberof CreateAuthUserWithLINERequest
     */
    phoneNumber: string;
    /**
     * リダイレクトURI
     * @type {string}
     * @memberof CreateAuthUserWithLINERequest
     */
    redirectUri: string;
    /**
     * ユーザー名(表示名)
     * @type {string}
     * @memberof CreateAuthUserWithLINERequest
     */
    username: string;
}

/**
 * Check if a given object implements the CreateAuthUserWithLINERequest interface.
 */
export function instanceOfCreateAuthUserWithLINERequest(value: object): value is CreateAuthUserWithLINERequest {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('firstname' in value) || value['firstname'] === undefined) return false;
    if (!('firstnameKana' in value) || value['firstnameKana'] === undefined) return false;
    if (!('lastname' in value) || value['lastname'] === undefined) return false;
    if (!('lastnameKana' in value) || value['lastnameKana'] === undefined) return false;
    if (!('nonce' in value) || value['nonce'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('redirectUri' in value) || value['redirectUri'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function CreateAuthUserWithLINERequestFromJSON(json: any): CreateAuthUserWithLINERequest {
    return CreateAuthUserWithLINERequestFromJSONTyped(json, false);
}

export function CreateAuthUserWithLINERequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAuthUserWithLINERequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'code': json['code'],
        'firstname': json['firstname'],
        'firstnameKana': json['firstnameKana'],
        'lastname': json['lastname'],
        'lastnameKana': json['lastnameKana'],
        'nonce': json['nonce'],
        'phoneNumber': json['phoneNumber'],
        'redirectUri': json['redirectUri'],
        'username': json['username'],
    };
}

export function CreateAuthUserWithLINERequestToJSON(json: any): CreateAuthUserWithLINERequest {
    return CreateAuthUserWithLINERequestToJSONTyped(json, false);
}

export function CreateAuthUserWithLINERequestToJSONTyped(value?: CreateAuthUserWithLINERequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountId': value['accountId'],
        'code': value['code'],
        'firstname': value['firstname'],
        'firstnameKana': value['firstnameKana'],
        'lastname': value['lastname'],
        'lastnameKana': value['lastnameKana'],
        'nonce': value['nonce'],
        'phoneNumber': value['phoneNumber'],
        'redirectUri': value['redirectUri'],
        'username': value['username'],
    };
}

