/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
} from './Order';
import type { Experience } from './Experience';
import {
    ExperienceFromJSON,
    ExperienceFromJSONTyped,
    ExperienceToJSON,
} from './Experience';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';
import type { Coordinator } from './Coordinator';
import {
    CoordinatorFromJSON,
    CoordinatorFromJSONTyped,
    CoordinatorToJSON,
} from './Coordinator';
import type { Promotion } from './Promotion';
import {
    PromotionFromJSON,
    PromotionFromJSONTyped,
    PromotionToJSON,
} from './Promotion';

/**
 * 
 * @export
 * @interface OrderResponse
 */
export interface OrderResponse {
    /**
     * 
     * @type {Coordinator}
     * @memberof OrderResponse
     */
    coordinator?: Coordinator;
    /**
     * 
     * @type {Experience}
     * @memberof OrderResponse
     */
    experience?: Experience;
    /**
     * 
     * @type {Order}
     * @memberof OrderResponse
     */
    order?: Order;
    /**
     * 商品一覧
     * @type {Array<Product>}
     * @memberof OrderResponse
     */
    products?: Array<Product>;
    /**
     * 
     * @type {Promotion}
     * @memberof OrderResponse
     */
    promotion?: Promotion;
}

/**
 * Check if a given object implements the OrderResponse interface.
 */
export function instanceOfOrderResponse(value: object): value is OrderResponse {
    return true;
}

export function OrderResponseFromJSON(json: any): OrderResponse {
    return OrderResponseFromJSONTyped(json, false);
}

export function OrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinator': json['coordinator'] == null ? undefined : CoordinatorFromJSON(json['coordinator']),
        'experience': json['experience'] == null ? undefined : ExperienceFromJSON(json['experience']),
        'order': json['order'] == null ? undefined : OrderFromJSON(json['order']),
        'products': json['products'] == null ? undefined : ((json['products'] as Array<any>).map(ProductFromJSON)),
        'promotion': json['promotion'] == null ? undefined : PromotionFromJSON(json['promotion']),
    };
}

export function OrderResponseToJSON(value?: OrderResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'coordinator': CoordinatorToJSON(value['coordinator']),
        'experience': ExperienceToJSON(value['experience']),
        'order': OrderToJSON(value['order']),
        'products': value['products'] == null ? undefined : ((value['products'] as Array<any>).map(ProductToJSON)),
        'promotion': PromotionToJSON(value['promotion']),
    };
}

