/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestCreateAuthUserWithLINERequest
 */
export interface RequestCreateAuthUserWithLINERequest {
    /**
     * ユーザーID(検索名)
     * @type {string}
     * @memberof RequestCreateAuthUserWithLINERequest
     */
    accountId?: string;
    /**
     * 認証コード
     * @type {string}
     * @memberof RequestCreateAuthUserWithLINERequest
     */
    code?: string;
    /**
     * 名
     * @type {string}
     * @memberof RequestCreateAuthUserWithLINERequest
     */
    firstname?: string;
    /**
     * 名（かな）
     * @type {string}
     * @memberof RequestCreateAuthUserWithLINERequest
     */
    firstnameKana?: string;
    /**
     * 姓
     * @type {string}
     * @memberof RequestCreateAuthUserWithLINERequest
     */
    lastname?: string;
    /**
     * 姓（かな）
     * @type {string}
     * @memberof RequestCreateAuthUserWithLINERequest
     */
    lastnameKana?: string;
    /**
     * セキュア文字列（リプレイアタック対策）
     * @type {string}
     * @memberof RequestCreateAuthUserWithLINERequest
     */
    nonce?: string;
    /**
     * 電話番号
     * @type {string}
     * @memberof RequestCreateAuthUserWithLINERequest
     */
    phoneNumber?: string;
    /**
     * リダイレクトURI
     * @type {string}
     * @memberof RequestCreateAuthUserWithLINERequest
     */
    redirectUri?: string;
    /**
     * ユーザー名(表示名)
     * @type {string}
     * @memberof RequestCreateAuthUserWithLINERequest
     */
    username?: string;
}

/**
 * Check if a given object implements the RequestCreateAuthUserWithLINERequest interface.
 */
export function instanceOfRequestCreateAuthUserWithLINERequest(value: object): value is RequestCreateAuthUserWithLINERequest {
    return true;
}

export function RequestCreateAuthUserWithLINERequestFromJSON(json: any): RequestCreateAuthUserWithLINERequest {
    return RequestCreateAuthUserWithLINERequestFromJSONTyped(json, false);
}

export function RequestCreateAuthUserWithLINERequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestCreateAuthUserWithLINERequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'code': json['code'] == null ? undefined : json['code'],
        'firstname': json['firstname'] == null ? undefined : json['firstname'],
        'firstnameKana': json['firstnameKana'] == null ? undefined : json['firstnameKana'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'lastnameKana': json['lastnameKana'] == null ? undefined : json['lastnameKana'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'redirectUri': json['redirectUri'] == null ? undefined : json['redirectUri'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function RequestCreateAuthUserWithLINERequestToJSON(value?: RequestCreateAuthUserWithLINERequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountId': value['accountId'],
        'code': value['code'],
        'firstname': value['firstname'],
        'firstnameKana': value['firstnameKana'],
        'lastname': value['lastname'],
        'lastnameKana': value['lastnameKana'],
        'nonce': value['nonce'],
        'phoneNumber': value['phoneNumber'],
        'redirectUri': value['redirectUri'],
        'username': value['username'],
    };
}

