/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestUpdateExperienceReviewRequest
 */
export interface RequestUpdateExperienceReviewRequest {
    /**
     * コメント
     * @type {string}
     * @memberof RequestUpdateExperienceReviewRequest
     */
    comment?: string;
    /**
     * 評価
     * @type {number}
     * @memberof RequestUpdateExperienceReviewRequest
     */
    rate?: number;
    /**
     * タイトル
     * @type {string}
     * @memberof RequestUpdateExperienceReviewRequest
     */
    title?: string;
}

/**
 * Check if a given object implements the RequestUpdateExperienceReviewRequest interface.
 */
export function instanceOfRequestUpdateExperienceReviewRequest(value: object): value is RequestUpdateExperienceReviewRequest {
    return true;
}

export function RequestUpdateExperienceReviewRequestFromJSON(json: any): RequestUpdateExperienceReviewRequest {
    return RequestUpdateExperienceReviewRequestFromJSONTyped(json, false);
}

export function RequestUpdateExperienceReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestUpdateExperienceReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        'rate': json['rate'] == null ? undefined : json['rate'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function RequestUpdateExperienceReviewRequestToJSON(value?: RequestUpdateExperienceReviewRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comment': value['comment'],
        'rate': value['rate'],
        'title': value['title'],
    };
}

