/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseProductReview } from './ResponseProductReview';
import {
    ResponseProductReviewFromJSON,
    ResponseProductReviewFromJSONTyped,
    ResponseProductReviewToJSON,
} from './ResponseProductReview';

/**
 * 
 * @export
 * @interface ResponseProductReviewsResponse
 */
export interface ResponseProductReviewsResponse {
    /**
     * 次の取得開始位置
     * @type {string}
     * @memberof ResponseProductReviewsResponse
     */
    nextToken?: string;
    /**
     * 商品レビュー一覧
     * @type {Array<ResponseProductReview>}
     * @memberof ResponseProductReviewsResponse
     */
    reviews?: Array<ResponseProductReview>;
}

/**
 * Check if a given object implements the ResponseProductReviewsResponse interface.
 */
export function instanceOfResponseProductReviewsResponse(value: object): value is ResponseProductReviewsResponse {
    return true;
}

export function ResponseProductReviewsResponseFromJSON(json: any): ResponseProductReviewsResponse {
    return ResponseProductReviewsResponseFromJSONTyped(json, false);
}

export function ResponseProductReviewsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseProductReviewsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nextToken': json['nextToken'] == null ? undefined : json['nextToken'],
        'reviews': json['reviews'] == null ? undefined : ((json['reviews'] as Array<any>).map(ResponseProductReviewFromJSON)),
    };
}

export function ResponseProductReviewsResponseToJSON(value?: ResponseProductReviewsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nextToken': value['nextToken'],
        'reviews': value['reviews'] == null ? undefined : ((value['reviews'] as Array<any>).map(ResponseProductReviewToJSON)),
    };
}

