/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseAuthGoogleAccountResponse
 */
export interface ResponseAuthGoogleAccountResponse {
    /**
     * Googleアカウント連携URL
     * @type {string}
     * @memberof ResponseAuthGoogleAccountResponse
     */
    url?: string;
}

/**
 * Check if a given object implements the ResponseAuthGoogleAccountResponse interface.
 */
export function instanceOfResponseAuthGoogleAccountResponse(value: object): value is ResponseAuthGoogleAccountResponse {
    return true;
}

export function ResponseAuthGoogleAccountResponseFromJSON(json: any): ResponseAuthGoogleAccountResponse {
    return ResponseAuthGoogleAccountResponseFromJSONTyped(json, false);
}

export function ResponseAuthGoogleAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseAuthGoogleAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ResponseAuthGoogleAccountResponseToJSON(value?: ResponseAuthGoogleAccountResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

