/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseCreateAuthUserResponse
 */
export interface ResponseCreateAuthUserResponse {
    /**
     * ユーザーID
     * @type {string}
     * @memberof ResponseCreateAuthUserResponse
     */
    id?: string;
}

/**
 * Check if a given object implements the ResponseCreateAuthUserResponse interface.
 */
export function instanceOfResponseCreateAuthUserResponse(value: object): value is ResponseCreateAuthUserResponse {
    return true;
}

export function ResponseCreateAuthUserResponseFromJSON(json: any): ResponseCreateAuthUserResponse {
    return ResponseCreateAuthUserResponseFromJSONTyped(json, false);
}

export function ResponseCreateAuthUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseCreateAuthUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ResponseCreateAuthUserResponseToJSON(value?: ResponseCreateAuthUserResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

