/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Producer } from './Producer';
import {
    ProducerFromJSON,
    ProducerFromJSONTyped,
    ProducerToJSON,
} from './Producer';
import type { Schedule } from './Schedule';
import {
    ScheduleFromJSON,
    ScheduleFromJSONTyped,
    ScheduleToJSON,
} from './Schedule';
import type { Live } from './Live';
import {
    LiveFromJSON,
    LiveFromJSONTyped,
    LiveToJSON,
} from './Live';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';
import type { Coordinator } from './Coordinator';
import {
    CoordinatorFromJSON,
    CoordinatorFromJSONTyped,
    CoordinatorToJSON,
} from './Coordinator';

/**
 * 
 * @export
 * @interface ScheduleResponse
 */
export interface ScheduleResponse {
    /**
     * 
     * @type {Coordinator}
     * @memberof ScheduleResponse
     */
    coordinator?: Coordinator;
    /**
     * ライブ配信一覧
     * @type {Array<Live>}
     * @memberof ScheduleResponse
     */
    lives?: Array<Live>;
    /**
     * 生産者一覧
     * @type {Array<Producer>}
     * @memberof ScheduleResponse
     */
    producers?: Array<Producer>;
    /**
     * 商品一覧
     * @type {Array<Product>}
     * @memberof ScheduleResponse
     */
    products?: Array<Product>;
    /**
     * 
     * @type {Schedule}
     * @memberof ScheduleResponse
     */
    schedule?: Schedule;
}

/**
 * Check if a given object implements the ScheduleResponse interface.
 */
export function instanceOfScheduleResponse(value: object): value is ScheduleResponse {
    return true;
}

export function ScheduleResponseFromJSON(json: any): ScheduleResponse {
    return ScheduleResponseFromJSONTyped(json, false);
}

export function ScheduleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinator': json['coordinator'] == null ? undefined : CoordinatorFromJSON(json['coordinator']),
        'lives': json['lives'] == null ? undefined : ((json['lives'] as Array<any>).map(LiveFromJSON)),
        'producers': json['producers'] == null ? undefined : ((json['producers'] as Array<any>).map(ProducerFromJSON)),
        'products': json['products'] == null ? undefined : ((json['products'] as Array<any>).map(ProductFromJSON)),
        'schedule': json['schedule'] == null ? undefined : ScheduleFromJSON(json['schedule']),
    };
}

export function ScheduleResponseToJSON(value?: ScheduleResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'coordinator': CoordinatorToJSON(value['coordinator']),
        'lives': value['lives'] == null ? undefined : ((value['lives'] as Array<any>).map(LiveToJSON)),
        'producers': value['producers'] == null ? undefined : ((value['producers'] as Array<any>).map(ProducerToJSON)),
        'products': value['products'] == null ? undefined : ((value['products'] as Array<any>).map(ProductToJSON)),
        'schedule': ScheduleToJSON(value['schedule']),
    };
}

