/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesProductReview } from './TypesProductReview';
import {
    TypesProductReviewFromJSON,
    TypesProductReviewFromJSONTyped,
    TypesProductReviewToJSON,
} from './TypesProductReview';

/**
 * 
 * @export
 * @interface TypesProductReviewResponse
 */
export interface TypesProductReviewResponse {
    /**
     * 
     * @type {TypesProductReview}
     * @memberof TypesProductReviewResponse
     */
    review?: TypesProductReview;
}

/**
 * Check if a given object implements the TypesProductReviewResponse interface.
 */
export function instanceOfTypesProductReviewResponse(value: object): value is TypesProductReviewResponse {
    return true;
}

export function TypesProductReviewResponseFromJSON(json: any): TypesProductReviewResponse {
    return TypesProductReviewResponseFromJSONTyped(json, false);
}

export function TypesProductReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesProductReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'review': json['review'] == null ? undefined : TypesProductReviewFromJSON(json['review']),
    };
}

export function TypesProductReviewResponseToJSON(value?: TypesProductReviewResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'review': TypesProductReviewToJSON(value['review']),
    };
}

