/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesVideoComment } from './TypesVideoComment';
import {
    TypesVideoCommentFromJSON,
    TypesVideoCommentFromJSONTyped,
    TypesVideoCommentToJSON,
} from './TypesVideoComment';

/**
 * 
 * @export
 * @interface TypesVideoCommentsResponse
 */
export interface TypesVideoCommentsResponse {
    /**
     * コメント一覧
     * @type {Array<TypesVideoComment>}
     * @memberof TypesVideoCommentsResponse
     */
    comments?: Array<TypesVideoComment>;
    /**
     * 次の取得開始位置
     * @type {string}
     * @memberof TypesVideoCommentsResponse
     */
    nextToken?: string;
}

/**
 * Check if a given object implements the TypesVideoCommentsResponse interface.
 */
export function instanceOfTypesVideoCommentsResponse(value: object): value is TypesVideoCommentsResponse {
    return true;
}

export function TypesVideoCommentsResponseFromJSON(json: any): TypesVideoCommentsResponse {
    return TypesVideoCommentsResponseFromJSONTyped(json, false);
}

export function TypesVideoCommentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesVideoCommentsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': json['comments'] == null ? undefined : ((json['comments'] as Array<any>).map(TypesVideoCommentFromJSON)),
        'nextToken': json['nextToken'] == null ? undefined : json['nextToken'],
    };
}

export function TypesVideoCommentsResponseToJSON(value?: TypesVideoCommentsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comments': value['comments'] == null ? undefined : ((value['comments'] as Array<any>).map(TypesVideoCommentToJSON)),
        'nextToken': value['nextToken'],
    };
}

