/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesCreateLiveCommentRequest
 */
export interface TypesCreateLiveCommentRequest {
    /**
     * コメント
     * @type {string}
     * @memberof TypesCreateLiveCommentRequest
     */
    comment: string;
}

/**
 * Check if a given object implements the TypesCreateLiveCommentRequest interface.
 */
export function instanceOfTypesCreateLiveCommentRequest(value: object): value is TypesCreateLiveCommentRequest {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function TypesCreateLiveCommentRequestFromJSON(json: any): TypesCreateLiveCommentRequest {
    return TypesCreateLiveCommentRequestFromJSONTyped(json, false);
}

export function TypesCreateLiveCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesCreateLiveCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'],
    };
}

export function TypesCreateLiveCommentRequestToJSON(value?: TypesCreateLiveCommentRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comment': value['comment'],
    };
}

