/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesVideoComment
 */
export interface TypesVideoComment {
    /**
     * アカウントID
     * @type {string}
     * @memberof TypesVideoComment
     */
    accountId?: string;
    /**
     * コメント
     * @type {string}
     * @memberof TypesVideoComment
     */
    comment?: string;
    /**
     * 投稿日時
     * @type {number}
     * @memberof TypesVideoComment
     */
    publishedAt?: number;
    /**
     * サムネイルURL
     * @type {string}
     * @memberof TypesVideoComment
     */
    thumbnailUrl?: string;
    /**
     * ユーザーID
     * @type {string}
     * @memberof TypesVideoComment
     */
    userId?: string;
    /**
     * ユーザー名
     * @type {string}
     * @memberof TypesVideoComment
     */
    username?: string;
}

/**
 * Check if a given object implements the TypesVideoComment interface.
 */
export function instanceOfTypesVideoComment(value: object): value is TypesVideoComment {
    return true;
}

export function TypesVideoCommentFromJSON(json: any): TypesVideoComment {
    return TypesVideoCommentFromJSONTyped(json, false);
}

export function TypesVideoCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesVideoComment {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'publishedAt': json['publishedAt'] == null ? undefined : json['publishedAt'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function TypesVideoCommentToJSON(value?: TypesVideoComment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountId': value['accountId'],
        'comment': value['comment'],
        'publishedAt': value['publishedAt'],
        'thumbnailUrl': value['thumbnailUrl'],
        'userId': value['userId'],
        'username': value['username'],
    };
}

