/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 商品評価
 * @export
 * @interface TypesProductRate
 */
export interface TypesProductRate {
    /**
     * 平均評価
     * @type {number}
     * @memberof TypesProductRate
     */
    average?: number;
    /**
     * 合計評価数
     * @type {number}
     * @memberof TypesProductRate
     */
    count?: number;
    /**
     * 評価詳細
     * @type {{ [key: string]: number; }}
     * @memberof TypesProductRate
     */
    detail?: { [key: string]: number; };
}

/**
 * Check if a given object implements the TypesProductRate interface.
 */
export function instanceOfTypesProductRate(value: object): value is TypesProductRate {
    return true;
}

export function TypesProductRateFromJSON(json: any): TypesProductRate {
    return TypesProductRateFromJSONTyped(json, false);
}

export function TypesProductRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesProductRate {
    if (json == null) {
        return json;
    }
    return {
        
        'average': json['average'] == null ? undefined : json['average'],
        'count': json['count'] == null ? undefined : json['count'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function TypesProductRateToJSON(value?: TypesProductRate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'average': value['average'],
        'count': value['count'],
        'detail': value['detail'],
    };
}

