/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesUpdateAuthUserUsernameRequest
 */
export interface TypesUpdateAuthUserUsernameRequest {
    /**
     * ユーザー名(表示名)
     * @type {string}
     * @memberof TypesUpdateAuthUserUsernameRequest
     */
    username: string;
}

/**
 * Check if a given object implements the TypesUpdateAuthUserUsernameRequest interface.
 */
export function instanceOfTypesUpdateAuthUserUsernameRequest(value: object): value is TypesUpdateAuthUserUsernameRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function TypesUpdateAuthUserUsernameRequestFromJSON(json: any): TypesUpdateAuthUserUsernameRequest {
    return TypesUpdateAuthUserUsernameRequestFromJSONTyped(json, false);
}

export function TypesUpdateAuthUserUsernameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesUpdateAuthUserUsernameRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function TypesUpdateAuthUserUsernameRequestToJSON(value?: TypesUpdateAuthUserUsernameRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
    };
}

