/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * オンデマンド動画情報
 * @export
 * @interface Video
 */
export interface Video {
    /**
     * コーディネータID
     * @type {string}
     * @memberof Video
     */
    coordinatorId: string;
    /**
     * 説明
     * @type {string}
     * @memberof Video
     */
    description: string;
    /**
     * 体験ID一覧
     * @type {Array<string>}
     * @memberof Video
     */
    experienceIds: Array<string>;
    /**
     * オンデマンド動画ID
     * @type {string}
     * @memberof Video
     */
    id: string;
    /**
     * 商品ID一覧
     * @type {Array<string>}
     * @memberof Video
     */
    productIds: Array<string>;
    /**
     * 公開日時
     * @type {number}
     * @memberof Video
     */
    publishedAt: number;
    /**
     * サムネイルURL
     * @type {string}
     * @memberof Video
     */
    thumbnailUrl: string;
    /**
     * タイトル
     * @type {string}
     * @memberof Video
     */
    title: string;
    /**
     * 動画URL
     * @type {string}
     * @memberof Video
     */
    videoUrl: string;
}

/**
 * Check if a given object implements the Video interface.
 */
export function instanceOfVideo(value: object): value is Video {
    if (!('coordinatorId' in value) || value['coordinatorId'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('experienceIds' in value) || value['experienceIds'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('productIds' in value) || value['productIds'] === undefined) return false;
    if (!('publishedAt' in value) || value['publishedAt'] === undefined) return false;
    if (!('thumbnailUrl' in value) || value['thumbnailUrl'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('videoUrl' in value) || value['videoUrl'] === undefined) return false;
    return true;
}

export function VideoFromJSON(json: any): Video {
    return VideoFromJSONTyped(json, false);
}

export function VideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Video {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinatorId': json['coordinatorId'],
        'description': json['description'],
        'experienceIds': json['experienceIds'],
        'id': json['id'],
        'productIds': json['productIds'],
        'publishedAt': json['publishedAt'],
        'thumbnailUrl': json['thumbnailUrl'],
        'title': json['title'],
        'videoUrl': json['videoUrl'],
    };
}

export function VideoToJSON(json: any): Video {
    return VideoToJSONTyped(json, false);
}

export function VideoToJSONTyped(value?: Video | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coordinatorId': value['coordinatorId'],
        'description': value['description'],
        'experienceIds': value['experienceIds'],
        'id': value['id'],
        'productIds': value['productIds'],
        'publishedAt': value['publishedAt'],
        'thumbnailUrl': value['thumbnailUrl'],
        'title': value['title'],
        'videoUrl': value['videoUrl'],
    };
}

