service: mediaService

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  account: ${self:custom.envMap.${self:provider.stage}.accountId}
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${self:custom.envMap.${self:provider.stage}.region}
  vpc:
    securityGroupIds: ${self:custom.envMap.${self:provider.stage}.vpc.securityGroups}
    subnetIds: ${self:custom.envMap.${self:provider.stage}.vpc.subnetIds}
  iam:
    role: defaultRole
  profile: ${env:AWS_PROFILE, 'default'}

custom:
  defaultStage: stg
  envMap:
    prd: ${file(env/prd.yaml)}
    stg: ${file(env/stg.yaml)}

resources:
  Resources:
    defaultRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                AWS:
                  - '*'
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: defaultPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - lambda:InvokeFunction
                  Resource:
                    - '*'
          - PolicyName: automateMediaServicePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - mediaLive:CreateInput
                    - mediaLive:CreateChannel
                    - mediaStore:CreateContainer
                    - mediaStore:DescribeContainer
                    - mediaStore:PutContainerPolicy
                    - mediaStore:PutCorsPolicy
                    - cloudFront:CreateDistribution
                  Resource:
                    - '*'
    lambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: automateMediaServiceLambdaPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DeleteNetworkInterface
                  Resource:
                    - '*'
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - '*'
                - Effect: Allow
                  Action:
                    - mediaStore:DescribeContainer
                  Resource:
                    - '*'

functions:
  extractMediaStoreDomain:
    role: lambdaRole
    handler: functions/extractMediaStoreDomain/handler.extractDomainName
    memorySize: 128
    timeout: 10

stepFunctions:
  stateMachines:
    mediaLiveStateMachine:
      name: mediaLiveStepFunction
      role:
        Fn::GetAtt: [defaultRole, Arn]
      definition:
        Comment: AutomateMediaServiceFunction
        StartAt: CreateMediaLiveInputAndContainer
        States:
          CreateMediaLiveInputAndContainer:
            Type: Parallel
            Comment: MediaLive入力とコンテナの作成を並列で実行
            InputPath: $
            Branches:
              - StartAt: CreateInput(RTMP)
                States:
                  CreateInput(RTMP):
                    Type: Task
                    End: true
                    Comment: ライブ配信 - ライブ配信入力用
                    Resource: arn:aws:states:::aws-sdk:medialive:createInput
                    InputPath: $.RtmpInput
                    ResultPath: $.RtmpResult
                    Parameters:
                      Name.$: $.Name
                      Type: RTMP_PUSH
                      Destinations:
                        - StreamName: live/a
                      InputSecurityGroups:
                        - '4361039'
              - StartAt: CreateInput(MP4)
                States:
                  CreateInput(MP4):
                    Type: Task
                    End: true
                    Comment: ライブ配信 - オープニング動画入力用
                    Resource: arn:aws:states:::aws-sdk:medialive:createInput
                    InputPath: $.MP4Input
                    ResultPath: $.MP4Result
                    Parameters:
                      Name.$: $.Name
                      Type: MP4_FILE
                      Sources.$: $.Sources
              - StartAt: CreateContainer
                States:
                  CreateContainer:
                    Type: Task
                    Comment: ライブ配信 - 配信用ストレージを作成
                    Resource: arn:aws:states:::aws-sdk:mediastore:createContainer
                    ResultPath: $.ContainerResult
                    Parameters:
                      ContainerName.$: $.ContainerName
                    Next: DescribeContainer
                  DescribeContainer:
                    Type: Task
                    Comment: ライブ配信 - 配信用ストレージのステータスを取得する
                    ResultPath: $.ContainerStatus
                    Resource: arn:aws:states:::aws-sdk:mediastore:describeContainer
                    Parameters:
                      ContainerName.$: $.ContainerName
                    Next: WaitActive
                  WaitActive:
                    Type: Wait
                    Seconds: 1
                    Next: CheckContainerActive
                  CheckContainerActive:
                    Type: Choice
                    InputPath: $
                    Choices:
                      - Variable: $.ContainerStatus.Container.Status
                        StringEquals: "ACTIVE"
                        Next: success
                      - Variable: $.ContainerStatus.Container.Status
                        StringEquals: "CREATING"
                        Next: DescribeContainer
                    Default: failed
                  success:
                    Type: Succeed
                  failed:
                    Type: Fail
            Next: CreateStreamingResoures
          CreateStreamingResoures:
            Type: Parallel
            End: true
            Comment: 配信リソースの作成を並列で実行
            InputPath: $
            Branches:
              - StartAt: CreateChannel
                States:
                  CreateChannel:
                    Type: Task
                    Comment: ライブ配信 - チャンネルを作成
                    InputPath: $
                    Resource: arn:aws:states:::aws-sdk:medialive:createChannel
                    Parameters:
                      Name.$: $[0].ChannelInput.Name
                      ChannelClass.$: $[0].ChannelInput.ChannelClass
                      InputAttachments:
                        - InputId.$: $[0].RtmpResult.Input.Id
                          InputAttachmentName.$: $[0].RtmpResult.Input.Name
                        - InputId.$: $[1].MP4Result.Input.Id
                          InputAttachmentName.$: $[1].MP4Result.Input.Name
                      Destinations.$: $[0].ChannelInput.Destinations
                      EncoderSettings.$: $[0].ChannelInput.EncoderSettings
                    End: true
              - StartAt: ExtractMediaStoreDomain
                States:
                  ExtractMediaStoreDomain:
                    Type: Task
                    Comment: ライブ配信 - MediaStoreのドメイン名を抽出
                    InputPath: $
                    Resource:
                      Fn::GetAtt: [extractMediaStoreDomain, Arn]
                    ResultPath: $[2].ContainerStatus.Container.Endpoint
                    Next: CreateDistribution
                  CreateDistribution:
                    Type: Task
                    Comment: ライブ配信 - MediaStoreをオリジンにするCloudFrontディストリビューションを作成
                    InputPath: $
                    ResultPath: $[2].DistributionResult
                    Resource: arn:aws:states:::aws-sdk:cloudfront:createDistribution
                    Parameters:
                      DistributionConfig:
                        CallerReference.$: $[2].ContainerResult.Container.Name
                        Comment: MediaStoreをオリジンにするCloudFrontディストリビューション
                        Enabled: true
                        HttpVersion: http2
                        Origins:
                          Quantity: 1
                          Items:
                          - Id.$: States.Format('{}.data.mediastore.ap-northeast-1.amazonaws.com', $[2].ContainerResult.Container.Name)
                            DomainName.$: $[2].ContainerStatus.Container.Endpoint
                            CustomOriginConfig:
                              HttpPort: 80
                              HttpsPort: 443
                              OriginProtocolPolicy: https-only
                        DefaultCacheBehavior:
                          TargetOriginId.$: States.Format('{}.data.mediastore.ap-northeast-1.amazonaws.com', $[2].ContainerResult.Container.Name)
                          ViewerProtocolPolicy: redirect-to-https
                          AllowedMethods:
                            Quantity: 7
                            Items:
                              - GET
                              - HEAD
                              - OPTIONS
                              - PUT
                              - POST
                              - PATCH
                              - DELETE
                          ForwardedValues:
                            QueryString: false
                            Cookies:
                              Forward: none
                            Headers:
                              Quantity: 2
                              Items:
                                - Origin
                                - Access-Con
                          MinTTL: 1
                    Next: PutContainerPolicy
                  PutContainerPolicy:
                    Type: Task
                    Comment: ライブ配信 - チャンネルに対するポリシーを設定
                    InputPath: $
                    Resource: arn:aws:states:::aws-sdk:mediastore:putContainerPolicy
                    Parameters:
                      ContainerName.$: $[2].ContainerResult.Container.Name
                      Policy:
                        Version: '2012-10-17'
                        Statement:
                          - Sid: AllowCloudFrontServicePrincipalReadOnly
                            Effect: Allow
                            Principal:
                              AWS: '*'
                            Action:
                              - mediastore:GetObject
                              - mediastore:DescribeObject
                            Resource.$: States.Format('{}/*', $[2].ContainerResult.Container.Arn)
                            Condition:
                              StringEquals:
                                AWS:SourceArn.$: $[2].DistributionResult.Distribution.Arn
                              Bool:
                                aws:SecureTransport: 'true'
                    End: true
              - StartAt: PutCorsPolicy
                States:
                  PutCorsPolicy:
                    Type: Task
                    Comment: ライブ配信 - チャンネルに対するCORSポリシーを設定
                    InputPath: $
                    Resource: arn:aws:states:::aws-sdk:mediastore:putCorsPolicy
                    Parameters:
                      ContainerName.$: $[2].ContainerResult.Container.Name
                      CorsPolicy:
                        - AllowedOrigins:
                            - '*'
                          AllowedMethods:
                            - GET
                            - HEAD
                          AllowedHeaders:
                            - '*'
                          MaxAgeSeconds: 3000
                    End: true
plugins:
  - serverless-step-functions
