get:
  summary: デフォルト配送設定取得
  operationId: v1GetDefaultShipping
  tags:
  - Shipping
  security:
  - bearerAuth: []
  responses:
    200:
      description: 成功
      content:
        application/json:
          schema:
            $ref: './../../../openapi.yaml#/components/schemas/v1ShippingResponse'
patch:
  summary: デフォルト配送設定更新
  operationId: v1UpdateDefaultShipping
  tags:
  - Shipping
  security:
  - bearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: './../../../openapi.yaml#/components/schemas/v1UpdateDefaultShippingRequest'
  responses:
    204:
      description: 成功
      content:
        application/json:
          schema: {}
    400:
      description: バリデーションエラー
      content:
        application/json:
          schema:
            $ref: './../../../openapi.yaml#/components/schemas/errorResponse'
