/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 外部宿泊施設向け
 * 外部宿泊施設向けのふるマルAPIです。（公開エンドポイントについては「ふるマルAPI - 購入者向け」を参照してください）
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthResponse
 */
export interface AuthResponse {
    /**
     * アクセストークン
     * @type {string}
     * @memberof AuthResponse
     */
    accessToken?: string;
    /**
     * 有効期限
     * @type {number}
     * @memberof AuthResponse
     */
    expiresIn?: number;
    /**
     * 更新トークン
     * @type {string}
     * @memberof AuthResponse
     */
    refreshToken?: string;
    /**
     * トークン種別
     * @type {string}
     * @memberof AuthResponse
     */
    tokenType?: string;
    /**
     * ユーザーID
     * @type {string}
     * @memberof AuthResponse
     */
    userId?: string;
}

/**
 * Check if a given object implements the AuthResponse interface.
 */
export function instanceOfAuthResponse(value: object): value is AuthResponse {
    return true;
}

export function AuthResponseFromJSON(json: any): AuthResponse {
    return AuthResponseFromJSONTyped(json, false);
}

export function AuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'expiresIn': json['expiresIn'] == null ? undefined : json['expiresIn'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'tokenType': json['tokenType'] == null ? undefined : json['tokenType'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function AuthResponseToJSON(value?: AuthResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accessToken': value['accessToken'],
        'expiresIn': value['expiresIn'],
        'refreshToken': value['refreshToken'],
        'tokenType': value['tokenType'],
        'userId': value['userId'],
    };
}

