/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 外部宿泊施設向け
 * 外部宿泊施設向けのふるマルAPIです。（公開エンドポイントについては「ふるマルAPI - 購入者向け」を参照してください）
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * クレジットカード決済情報
 * @export
 * @interface CheckoutCreditCard
 */
export interface CheckoutCreditCard {
    /**
     * 有効期限（月）
     * @type {number}
     * @memberof CheckoutCreditCard
     */
    month?: number;
    /**
     * カード名義
     * @type {string}
     * @memberof CheckoutCreditCard
     */
    name: string;
    /**
     * カード番号
     * @type {string}
     * @memberof CheckoutCreditCard
     */
    number: string;
    /**
     * セキュリティコード
     * @type {string}
     * @memberof CheckoutCreditCard
     */
    verificationValue?: string;
    /**
     * 有効期限（年）
     * @type {number}
     * @memberof CheckoutCreditCard
     */
    year?: number;
}

/**
 * Check if a given object implements the CheckoutCreditCard interface.
 */
export function instanceOfCheckoutCreditCard(value: object): value is CheckoutCreditCard {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    return true;
}

export function CheckoutCreditCardFromJSON(json: any): CheckoutCreditCard {
    return CheckoutCreditCardFromJSONTyped(json, false);
}

export function CheckoutCreditCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutCreditCard {
    if (json == null) {
        return json;
    }
    return {
        
        'month': json['month'] == null ? undefined : json['month'],
        'name': json['name'],
        'number': json['number'],
        'verificationValue': json['verificationValue'] == null ? undefined : json['verificationValue'],
        'year': json['year'] == null ? undefined : json['year'],
    };
}

export function CheckoutCreditCardToJSON(value?: CheckoutCreditCard | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'month': value['month'],
        'name': value['name'],
        'number': value['number'],
        'verificationValue': value['verificationValue'],
        'year': value['year'],
    };
}

