/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 外部宿泊施設向け
 * 外部宿泊施設向けのふるマルAPIです。（公開エンドポイントについては「ふるマルAPI - 購入者向け」を参照してください）
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderItem
 */
export interface OrderItem {
    /**
     * 配送情報ID
     * @type {string}
     * @memberof OrderItem
     */
    fulfillmentId: string;
    /**
     * 購入価格(税込)
     * @type {number}
     * @memberof OrderItem
     */
    price: number;
    /**
     * 商品ID
     * @type {string}
     * @memberof OrderItem
     */
    productId: string;
    /**
     * 購入数量
     * @type {number}
     * @memberof OrderItem
     */
    quantity: number;
}

/**
 * Check if a given object implements the OrderItem interface.
 */
export function instanceOfOrderItem(value: object): value is OrderItem {
    if (!('fulfillmentId' in value) || value['fulfillmentId'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function OrderItemFromJSON(json: any): OrderItem {
    return OrderItemFromJSONTyped(json, false);
}

export function OrderItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItem {
    if (json == null) {
        return json;
    }
    return {
        
        'fulfillmentId': json['fulfillmentId'],
        'price': json['price'],
        'productId': json['productId'],
        'quantity': json['quantity'],
    };
}

export function OrderItemToJSON(json: any): OrderItem {
    return OrderItemToJSONTyped(json, false);
}

export function OrderItemToJSONTyped(value?: OrderItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fulfillmentId': value['fulfillmentId'],
        'price': value['price'],
        'productId': value['productId'],
        'quantity': value['quantity'],
    };
}

