/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 外部宿泊施設向け
 * 外部宿泊施設向けのふるマルAPIです。（公開エンドポイントについては「ふるマルAPI - 購入者向け」を参照してください）
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 注文キャンセル情報
 * @export
 * @interface OrderRefund
 */
export interface OrderRefund {
    /**
     * 注文キャンセルフラグ
     * @type {boolean}
     * @memberof OrderRefund
     */
    canceled?: boolean;
    /**
     * 注文キャンセル日時
     * @type {number}
     * @memberof OrderRefund
     */
    canceledAt?: number;
    /**
     * 注文キャンセル理由
     * @type {string}
     * @memberof OrderRefund
     */
    reason?: string;
    /**
     * 返金金額
     * @type {number}
     * @memberof OrderRefund
     */
    total?: number;
    /**
     * 注文キャンセル種別
     * @type {number}
     * @memberof OrderRefund
     */
    type?: number;
}

/**
 * Check if a given object implements the OrderRefund interface.
 */
export function instanceOfOrderRefund(value: object): value is OrderRefund {
    return true;
}

export function OrderRefundFromJSON(json: any): OrderRefund {
    return OrderRefundFromJSONTyped(json, false);
}

export function OrderRefundFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderRefund {
    if (json == null) {
        return json;
    }
    return {
        
        'canceled': json['canceled'] == null ? undefined : json['canceled'],
        'canceledAt': json['canceledAt'] == null ? undefined : json['canceledAt'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'total': json['total'] == null ? undefined : json['total'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function OrderRefundToJSON(value?: OrderRefund | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'canceled': value['canceled'],
        'canceledAt': value['canceledAt'],
        'reason': value['reason'],
        'total': value['total'],
        'type': value['type'],
    };
}

