/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 外部宿泊施設向け
 * 外部宿泊施設向けのふるマルAPIです。（公開エンドポイントについては「ふるマルAPI - 購入者向け」を参照してください）
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductTag
 */
export interface ProductTag {
    /**
     * 商品タグID
     * @type {string}
     * @memberof ProductTag
     */
    id: string;
    /**
     * 商品タグ名
     * @type {string}
     * @memberof ProductTag
     */
    name: string;
}

/**
 * Check if a given object implements the ProductTag interface.
 */
export function instanceOfProductTag(value: object): value is ProductTag {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ProductTagFromJSON(json: any): ProductTag {
    return ProductTagFromJSONTyped(json, false);
}

export function ProductTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductTag {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function ProductTagToJSON(json: any): ProductTag {
    return ProductTagToJSONTyped(json, false);
}

export function ProductTagToJSONTyped(value?: ProductTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

