/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 外部宿泊施設向け
 * 外部宿泊施設向けのふるマルAPIです。（公開エンドポイントについては「ふるマルAPI - 購入者向け」を参照してください）
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestCheckoutCreditCard } from './RequestCheckoutCreditCard';
import {
    RequestCheckoutCreditCardFromJSON,
    RequestCheckoutCreditCardFromJSONTyped,
    RequestCheckoutCreditCardToJSON,
} from './RequestCheckoutCreditCard';

/**
 * 
 * @export
 * @interface RequestCheckoutRequest
 */
export interface RequestCheckoutRequest {
    /**
     * 箱の通番（箱単位で購入する場合）
     * @type {number}
     * @memberof RequestCheckoutRequest
     */
    boxNumber?: number;
    /**
     * 決済完了後のリダイレクト先URL
     * @type {string}
     * @memberof RequestCheckoutRequest
     */
    callbackUrl: string;
    /**
     * コーディネータID
     * @type {string}
     * @memberof RequestCheckoutRequest
     */
    coordinatorId: string;
    /**
     * 
     * @type {RequestCheckoutCreditCard}
     * @memberof RequestCheckoutRequest
     */
    creditCard?: RequestCheckoutCreditCard;
    /**
     * 支払い方法
     * @type {number}
     * @memberof RequestCheckoutRequest
     */
    paymentMethod: number;
    /**
     * プロモーションコード
     * @type {string}
     * @memberof RequestCheckoutRequest
     */
    promotionCode?: string;
    /**
     * 支払いキー(重複判定用)
     * @type {string}
     * @memberof RequestCheckoutRequest
     */
    requestId: string;
    /**
     * 支払い合計金額（誤り検出用）
     * @type {number}
     * @memberof RequestCheckoutRequest
     */
    total?: number;
}

/**
 * Check if a given object implements the RequestCheckoutRequest interface.
 */
export function instanceOfRequestCheckoutRequest(value: object): value is RequestCheckoutRequest {
    if (!('callbackUrl' in value) || value['callbackUrl'] === undefined) return false;
    if (!('coordinatorId' in value) || value['coordinatorId'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function RequestCheckoutRequestFromJSON(json: any): RequestCheckoutRequest {
    return RequestCheckoutRequestFromJSONTyped(json, false);
}

export function RequestCheckoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestCheckoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'boxNumber': json['boxNumber'] == null ? undefined : json['boxNumber'],
        'callbackUrl': json['callbackUrl'],
        'coordinatorId': json['coordinatorId'],
        'creditCard': json['creditCard'] == null ? undefined : RequestCheckoutCreditCardFromJSON(json['creditCard']),
        'paymentMethod': json['paymentMethod'],
        'promotionCode': json['promotionCode'] == null ? undefined : json['promotionCode'],
        'requestId': json['requestId'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function RequestCheckoutRequestToJSON(value?: RequestCheckoutRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'boxNumber': value['boxNumber'],
        'callbackUrl': value['callbackUrl'],
        'coordinatorId': value['coordinatorId'],
        'creditCard': RequestCheckoutCreditCardToJSON(value['creditCard']),
        'paymentMethod': value['paymentMethod'],
        'promotionCode': value['promotionCode'],
        'requestId': value['requestId'],
        'total': value['total'],
    };
}

