/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 外部宿泊施設向け
 * 外部宿泊施設向けのふるマルAPIです。（公開エンドポイントについては「ふるマルAPI - 購入者向け」を参照してください）
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 商品種別情報
 * @export
 * @interface ResponseCategory
 */
export interface ResponseCategory {
    /**
     * 商品種別ID
     * @type {string}
     * @memberof ResponseCategory
     */
    id?: string;
    /**
     * 商品種別名
     * @type {string}
     * @memberof ResponseCategory
     */
    name?: string;
}

/**
 * Check if a given object implements the ResponseCategory interface.
 */
export function instanceOfResponseCategory(value: object): value is ResponseCategory {
    return true;
}

export function ResponseCategoryFromJSON(json: any): ResponseCategory {
    return ResponseCategoryFromJSONTyped(json, false);
}

export function ResponseCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ResponseCategoryToJSON(value?: ResponseCategory | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

