/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 外部宿泊施設向け
 * 外部宿泊施設向けのふるマルAPIです。（公開エンドポイントについては「ふるマルAPI - 購入者向け」を参照してください）
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseAuthUserResponse
 */
export interface ResponseAuthUserResponse {
    /**
     * メールアドレス
     * @type {string}
     * @memberof ResponseAuthUserResponse
     */
    email?: string;
    /**
     * 名
     * @type {string}
     * @memberof ResponseAuthUserResponse
     */
    firstname?: string;
    /**
     * 名（かな）
     * @type {string}
     * @memberof ResponseAuthUserResponse
     */
    firstnameKana?: string;
    /**
     * ユーザーID
     * @type {string}
     * @memberof ResponseAuthUserResponse
     */
    id?: string;
    /**
     * 最新のチェックイン日時
     * @type {number}
     * @memberof ResponseAuthUserResponse
     */
    lastCheckInAt?: number;
    /**
     * 姓
     * @type {string}
     * @memberof ResponseAuthUserResponse
     */
    lastname?: string;
    /**
     * 姓（かな）
     * @type {string}
     * @memberof ResponseAuthUserResponse
     */
    lastnameKana?: string;
    /**
     * 電話番号
     * @type {string}
     * @memberof ResponseAuthUserResponse
     */
    phoneNumber?: string;
}

/**
 * Check if a given object implements the ResponseAuthUserResponse interface.
 */
export function instanceOfResponseAuthUserResponse(value: object): value is ResponseAuthUserResponse {
    return true;
}

export function ResponseAuthUserResponseFromJSON(json: any): ResponseAuthUserResponse {
    return ResponseAuthUserResponseFromJSONTyped(json, false);
}

export function ResponseAuthUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseAuthUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'firstname': json['firstname'] == null ? undefined : json['firstname'],
        'firstnameKana': json['firstnameKana'] == null ? undefined : json['firstnameKana'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastCheckInAt': json['lastCheckInAt'] == null ? undefined : json['lastCheckInAt'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'lastnameKana': json['lastnameKana'] == null ? undefined : json['lastnameKana'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
    };
}

export function ResponseAuthUserResponseToJSON(value?: ResponseAuthUserResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'firstname': value['firstname'],
        'firstnameKana': value['firstnameKana'],
        'id': value['id'],
        'lastCheckInAt': value['lastCheckInAt'],
        'lastname': value['lastname'],
        'lastnameKana': value['lastnameKana'],
        'phoneNumber': value['phoneNumber'],
    };
}

