/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 外部宿泊施設向け
 * 外部宿泊施設向けのふるマルAPIです。（公開エンドポイントについては「ふるマルAPI - 購入者向け」を参照してください）
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseAuthResponse
 */
export interface ResponseAuthResponse {
    /**
     * アクセストークン
     * @type {string}
     * @memberof ResponseAuthResponse
     */
    accessToken?: string;
    /**
     * 有効期限
     * @type {number}
     * @memberof ResponseAuthResponse
     */
    expiresIn?: number;
    /**
     * 更新トークン
     * @type {string}
     * @memberof ResponseAuthResponse
     */
    refreshToken?: string;
    /**
     * トークン種別
     * @type {string}
     * @memberof ResponseAuthResponse
     */
    tokenType?: string;
    /**
     * ユーザーID
     * @type {string}
     * @memberof ResponseAuthResponse
     */
    userId?: string;
}

/**
 * Check if a given object implements the ResponseAuthResponse interface.
 */
export function instanceOfResponseAuthResponse(value: object): value is ResponseAuthResponse {
    return true;
}

export function ResponseAuthResponseFromJSON(json: any): ResponseAuthResponse {
    return ResponseAuthResponseFromJSONTyped(json, false);
}

export function ResponseAuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseAuthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'expiresIn': json['expiresIn'] == null ? undefined : json['expiresIn'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'tokenType': json['tokenType'] == null ? undefined : json['tokenType'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function ResponseAuthResponseToJSON(value?: ResponseAuthResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accessToken': value['accessToken'],
        'expiresIn': value['expiresIn'],
        'refreshToken': value['refreshToken'],
        'tokenType': value['tokenType'],
        'userId': value['userId'],
    };
}

