/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 外部宿泊施設向け
 * 外部宿泊施設向けのふるマルAPIです。（公開エンドポイントについては「ふるマルAPI - 購入者向け」を参照してください）
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 商品評価
 * @export
 * @interface ResponseProductRate
 */
export interface ResponseProductRate {
    /**
     * 平均評価
     * @type {number}
     * @memberof ResponseProductRate
     */
    average?: number;
    /**
     * 合計評価数
     * @type {number}
     * @memberof ResponseProductRate
     */
    count?: number;
    /**
     * 評価詳細
     * @type {{ [key: string]: number; }}
     * @memberof ResponseProductRate
     */
    detail?: { [key: string]: number; };
}

/**
 * Check if a given object implements the ResponseProductRate interface.
 */
export function instanceOfResponseProductRate(value: object): value is ResponseProductRate {
    return true;
}

export function ResponseProductRateFromJSON(json: any): ResponseProductRate {
    return ResponseProductRateFromJSONTyped(json, false);
}

export function ResponseProductRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseProductRate {
    if (json == null) {
        return json;
    }
    return {
        
        'average': json['average'] == null ? undefined : json['average'],
        'count': json['count'] == null ? undefined : json['count'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ResponseProductRateToJSON(value?: ResponseProductRate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'average': value['average'],
        'count': value['count'],
        'detail': value['detail'],
    };
}

