openapi: 3.0.3
info:
  title: Marche Online
  description: マルシェ購入者用API
  version: 0.1.0
servers:
- url: http://localhost:18000
  description: 開発環境
- url: https://api.furumaru-stg.and-period.work
  description: 検証環境
tags:
- name: Auth
  description: 認証関連
- name: AuthUser
  description: 購入者関連
- name: Address
  description: アドレス帳関連
- name: Cart
  description: 買い物かご関連
- name: Checkout
  description: 購入関連
- name: Coordinator
  description: コーディネータ関連
- name: Contact
  description: お問い合わせ関連
- name: Guest
  description: ゲスト関連
- name: Experience
  description: 体験関連
- name: Order
  description: 注文履歴関連
- name: Producer
  description: 生産者関連
- name: Product
  description: 商品関連
- name: Promotion
  description: プロモーション関連
- name: Schedule
  description: マルシェ開催スケジュール関連
- name: Spot
  description: スポット関連
- name: SpotType
  description: スポット種別関連
- name: Status
  description: システム状態関連
- name: Top
  description: トップページ関連
- name: Video
  description: オンデマンド配信関連
- name: Other
  description: その他（外部APIなど）
paths:
  # Auth
  /v1/auth:
    $ref: './paths/v1/auth/index.yaml'
  /v1/auth/refresh-token:
    $ref: './paths/v1/auth/refresh-token.yaml'
  /v1/auth/password:
    $ref: './paths/v1/auth/password.yaml'
  /v1/auth/forgot-password:
    $ref: './paths/v1/auth/forgot-password/index.yaml'
  /v1/auth/forgot-password/verified:
    $ref: './paths/v1/auth/forgot-password/verified.yaml'
  # AuthUser
  /v1/users/me:
    $ref: './paths/v1/users/me/index.yaml'
  /v1/users/me/verified:
    $ref: './paths/v1/users/me/verified.yaml'
  /v1/users/me/oauth:
    $ref: './paths/v1/users/me/oauth.yaml'
  /v1/users/me/username:
    $ref: './paths/v1/users/me/username.yaml'
  /v1/users/me/account-id:
    $ref: './paths/v1/users/me/account-id.yaml'
  /v1/users/me/notification:
    $ref: './paths/v1/users/me/notification.yaml'
  /v1/users/me/thumbnail:
    $ref: './paths/v1/users/me/thumbnail.yaml'
  /v1/users/me/email:
    $ref: './paths/v1/users/me/email/index.yaml'
  /v1/users/me/email/verified:
    $ref: './paths/v1/users/me/email/verified.yaml'
  # Address
  /v1/addresses:
    $ref: './paths/v1/addresses/index.yaml'
  /v1/addresses/{addressId}:
    $ref: './paths/v1/addresses/_addressId/index.yaml'
  # Cart
  /v1/carts:
    $ref: './paths/v1/carts/index.yaml'
  /v1/carts/{coordinatorId}:
    $ref: './paths/v1/carts/_coordinatorId/index.yaml'
  /v1/carts/-/items:
    $ref: './paths/v1/carts/-/items/index.yaml'
  /v1/carts/-/items/{productId}:
    $ref: './paths/v1/carts/-/items/_productId/index.yaml'
  # Checkout
  /v1/checkouts/products:
    $ref: './paths/v1/checkouts/products/index.yaml'
  /v1/checkouts/{transactionId}:
    $ref: './paths/v1/checkouts/_transactionId/index.yaml'
  /v1/checkouts/experiences/{experienceId}:
    $ref: './paths/v1/checkouts/experiences/_experienceId/index.yaml'
  # Contact
  /v1/contacts:
    $ref: './paths/v1/contacts/index.yaml'
  # Coordinator
  /v1/coordinators:
    $ref: './paths/v1/coordinators/index.yaml'
  /v1/coordinators/{coordinatorId}:
    $ref: './paths/v1/coordinators/_coordinatorId/index.yaml'
  # Experience
  /v1/experiences:
    $ref: './paths/v1/experiences/index.yaml'
  /v1/experiences/{experienceId}:
    $ref: './paths/v1/experiences/_experienceId/index.yaml'
  # Guest
  /v1/guests/checkouts/products:
    $ref: './paths/v1/guests/checkouts/products/index.yaml'
  /v1/guests/checkouts/{transactionId}:
    $ref: './paths/v1/guests/checkouts/_transactionId/index.yaml'
  /v1/guests/checkouts/experiences/{experienceId}:
    $ref: './paths/v1/guests/checkouts/experiences/_experienceId/index.yaml'
  /v1/guests/schedules/{scheduleId}/comments:
    $ref: './paths/v1/guests/schedules/_scheduleId/comments/index.yaml'
  /v1/guests/videos/{videoId}/comments:
    $ref: './paths/v1/guests/videos/_videoId/comments/index.yaml'
  # Order
  /v1/orders:
    $ref: './paths/v1/orders/index.yaml'
  /v1/orders/{orderId}:
    $ref: './paths/v1/orders/_orderId/index.yaml'
  # Producer
  /v1/producers:
    $ref: './paths/v1/producers/index.yaml'
  /v1/producers/{producerId}:
    $ref: './paths/v1/producers/_producerId/index.yaml'
  # Product
  /v1/products:
    $ref: './paths/v1/products/index.yaml'
  /v1/products/{productId}:
    $ref: './paths/v1/products/_productId/index.yaml'
  # Promotion
  /v1/promotions/{code}:
    $ref: './paths/v1/promotions/_code/index.yaml'
  # Schedule
  /v1/schedules/lives:
    $ref: './paths/v1/schedules/lives.yaml'
  /v1/schedules/archives:
    $ref: './paths/v1/schedules/archives.yaml'
  /v1/schedules/{scheduleId}:
    $ref: './paths/v1/schedules/_scheduleId/index.yaml'
  /v1/schedules/{scheduleId}/comments:
    $ref: './paths/v1/schedules/_scheduleId/comments/index.yaml'
  # Spot
  /v1/spots:
    $ref: './paths/v1/spots/index.yaml'
  /v1/spots/{spotId}:
    $ref: './paths/v1/spots/_spotId/index.yaml'
  # SpotType
  /v1/spot-types:
    $ref: './paths/v1/spot-types/index.yaml'
  # Status
  /v1/statuses/payments:
    $ref: './paths/v1/statuses/payments.yaml'
  # Top
  /v1/top/common:
    $ref: './paths/v1/top/common.yaml'
  # Video
  /v1/videos:
    $ref: './paths/v1/videos/index.yaml'
  /v1/videos/{videoId}:
    $ref: './paths/v1/videos/_videoId/index.yaml'
  # Upload
  /v1/upload/state:
    $ref: './paths/v1/upload/state.yaml'
  /v1/upload/users/thumbnail:
    $ref: './paths/v1/upload/users/thumbnail.yaml'
  # Other
  /v1/postal-codes/{postalCode}:
    $ref: './paths/v1/postal-codes/_postalCode.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie
      name: session_id
  schemas:
    # Common
    prefecture:
      $ref: './components/schemas/codes/common.yaml#/prefecture'
    weekday:
      $ref: './components/schemas/codes/common.yaml#/weekday'
    experienceStatus:
      $ref: './components/schemas/codes/experience.yaml#/experienceStatus'
    orderStatus:
      $ref: './components/schemas/codes/order.yaml#/orderStatus'
    orderType:
      $ref: './components/schemas/codes/order.yaml#/orderType'
    fulfillmentStatus:
      $ref: './components/schemas/codes/order-fulfillment.yaml#/fulfillmentStatus'
    shippingCarrier:
      $ref: './components/schemas/codes/order-fulfillment.yaml#/shippingCarrier'
    shippingSize:
      $ref: './components/schemas/codes/order-fulfillment.yaml#/shippingSize'
    shippingType:
      $ref: './components/schemas/codes/order-fulfillment.yaml#/shippingType'
    paymentMethodType:
      $ref: './components/schemas/codes/order-payment.yaml#/paymentMethodType'
    paymentStatus:
      $ref: './components/schemas/codes/order-payment.yaml#/paymentStatus'
    orderRefundType:
      $ref: './components/schemas/codes/order-refund.yaml#/orderRefundType'
    productStatus:
      $ref: './components/schemas/codes/product.yaml#/productStatus'
    deliveryType:
      $ref: './components/schemas/codes/product.yaml#/deliveryType'
    storageMethodType:
      $ref: './components/schemas/codes/product.yaml#/storageMethodType'
    promotionStatus:
      $ref: './components/schemas/codes/promotion.yaml#/promotionStatus'
    discountType:
      $ref: './components/schemas/codes/promotion.yaml#/discountType'
    scheduleStatus:
      $ref: './components/schemas/codes/schedule.yaml#/scheduleStatus'
    spotUserType:
      $ref: './components/schemas/codes/spot.yaml#/spotUserType'
    paymentSystemStatus:
      $ref: './components/schemas/codes/status.yaml#/paymentSystemStatus'
    uploadStatus:
      $ref: './components/schemas/codes/upload.yaml#/uploadStatus'
    errorResponse:
      $ref: './components/schemas/common.yaml#/errorResponse'
    # Entity
    address:
      $ref: './components/schemas/entity/address.yaml#/address'
    cart:
      $ref: './components/schemas/entity/cart.yaml#/cart'
    cartItem:
      $ref: './components/schemas/entity/cart.yaml#/cartItem'
    category:
      $ref: './components/schemas/entity/category.yaml#/category'
    coordinator:
      $ref: './components/schemas/entity/coordinator.yaml#/coordinator'
    experience:
      $ref: './components/schemas/entity/experience.yaml#/experience'
    experienceType:
      $ref: './components/schemas/entity/experience-type.yaml#/experienceType'
    live:
      $ref: './components/schemas/entity/live.yaml#/live'
    liveSummary:
      $ref: './components/schemas/entity/live.yaml#/liveSummary'
    liveProduct:
      $ref: './components/schemas/entity/live.yaml#/liveProduct'
    archiveSummary:
      $ref: './components/schemas/entity/live.yaml#/archiveSummary'
    liveComment:
      $ref: './components/schemas/entity/live-comment.yaml#/liveComment'
    order:
      $ref: './components/schemas/entity/order.yaml#/order'
    producer:
      $ref: './components/schemas/entity/producer.yaml#/producer'
    productReview:
      $ref: './components/schemas/entity/product-review.yaml#/productReview'
    productTag:
      $ref: './components/schemas/entity/product-tag.yaml#/productTag'
    productType:
      $ref: './components/schemas/entity/product-type.yaml#/productType'
    product:
      $ref: './components/schemas/entity/product.yaml#/product'
    promotion:
      $ref: './components/schemas/entity/promotion.yaml#/promotion'
    schedule:
      $ref: './components/schemas/entity/schedule.yaml#/schedule'
    spot:
      $ref: './components/schemas/entity/spot.yaml#/spot'
    spotType:
      $ref: './components/schemas/entity/spot-type.yaml#/spotType'
    paymentSystem:
      $ref: './components/schemas/entity/status.yaml#/paymentSystem'
    video:
      $ref: './components/schemas/entity/video.yaml#/video'
    videoSummary:
      $ref: './components/schemas/entity/video.yaml#/videoSummary'
    videoComment:
      $ref: './components/schemas/entity/video-comment.yaml#/videoComment'
    # Request
    v1CreateAddressRequest:
      $ref: './components/schemas/v1/address.request.yaml#/createAddressRequest'
    v1UpdateAddressRequest:
      $ref: './components/schemas/v1/address.request.yaml#/updateAddressRequest'
    v1SignInRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/signInRequest'
    v1RefreshAuthTokenRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/refreshAuthTokenRequest'
    v1UpdateAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthPasswordRequest'
    v1ForgotAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/forgotAuthPasswordRequest'
    v1ResetAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/resetAuthPasswordRequest'
    v1CreateAuthUserRequest:
      $ref: './components/schemas/v1/auth-user.request.yaml#/createAuthUserRequest'
    v1VerifyAuthUserRequest:
      $ref: './components/schemas/v1/auth-user.request.yaml#/verifyAuthUserRequest'
    v1CreateAuthUserWithOAuthRequest:
      $ref: './components/schemas/v1/auth-user.request.yaml#/createAuthUserWithOAuthRequest'
    v1UpdateAuthUserEmailRequest:
      $ref: './components/schemas/v1/auth-user.request.yaml#/updateAuthUserEmailRequest'
    v1VerifyAuthUserEmailRequest:
      $ref: './components/schemas/v1/auth-user.request.yaml#/verifyAuthUserEmailRequest'
    v1UpdateAuthUserUsernameRequest:
      $ref: './components/schemas/v1/auth-user.request.yaml#/updateAuthUserUsernameRequest'
    v1UpdateAuthUserAccountIdRequest:
      $ref: './components/schemas/v1/auth-user.request.yaml#/updateAuthUserAccountIdRequest'
    v1UpdateAuthUserNotificationRequest:
      $ref: './components/schemas/v1/auth-user.request.yaml#/updateAuthUserNotificationRequest'
    v1UpdateAuthUserThumbnailRequest:
      $ref: './components/schemas/v1/auth-user.request.yaml#/updateAuthUserThumbnailRequest'
    v1AddCartItemRequest:
      $ref: './components/schemas/v1/cart.request.yaml#/addCartItemRequest'
    v1CheckoutExperienceRequest:
      $ref: './components/schemas/v1/checkout.request.yaml#/checkoutExperienceRequest'
    v1CheckoutProductRequest:
      $ref: './components/schemas/v1/checkout.request.yaml#/checkoutProductRequest'
    v1CreateContactRequest:
      $ref: './components/schemas/v1/contact.request.yaml#/createContactRequest'
    v1GuestCheckoutExperienceRequest:
      $ref: './components/schemas/v1/guest-checkout.request.yaml#/guestCheckoutExperienceRequest'
    v1GuestCheckoutProductRequest:
      $ref: './components/schemas/v1/guest-checkout.request.yaml#/guestCheckoutProductRequest'
    v1CreateGuestLiveCommentRequest:
      $ref: './components/schemas/v1/guest-live-comment.request.yaml#/createGuestLiveCommentRequest'
    v1CreateGuestVideoCommentRequest:
      $ref: './components/schemas/v1/guest-video-comment.request.yaml#/createGuestVideoCommentRequest'
    v1CreateLiveCommentRequest:
      $ref: './components/schemas/v1/live-comment.request.yaml#/createLiveCommentRequest'
    v1CreateProductReviewRequest:
      $ref: './components/schemas/v1/product-review.request.yaml#/createProductReviewRequest'
    v1UpdateProductReviewRequest:
      $ref: './components/schemas/v1/product-review.request.yaml#/updateProductReviewRequest'
    v1CreateSpotRequest:
      $ref: './components/schemas/v1/spot.request.yaml#/createSpotRequest'
    v1UpdateSpotRequest:
      $ref: './components/schemas/v1/spot.request.yaml#/createSpotRequest'
    v1CreateVideoCommentRequest:
      $ref: './components/schemas/v1/video-comment.request.yaml#/createVideoCommentRequest'
    v1GetUploadUrlRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/getUploadUrlRequest'
    # Response
    v1AuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authResponse'
    v1AuthUserResponse:
      $ref: './components/schemas/v1/auth-user.response.yaml#/authUserResponse'
    v1CreateAuthUserResponse:
      $ref: './components/schemas/v1/auth-user.response.yaml#/createAuthUserResponse'
    v1AddressResponse:
      $ref: './components/schemas/v1/address.response.yaml#/addressResponse'
    v1AddressesResponse:
      $ref: './components/schemas/v1/address.response.yaml#/addressesResponse'
    v1CartResponse:
      $ref: './components/schemas/v1/cart.response.yaml#/cartResponse'
    v1CalcCartResponse:
      $ref: './components/schemas/v1/cart.response.yaml#/calcCartResponse'
    v1CheckoutResponse:
      $ref: './components/schemas/v1/checkout.response.yaml#/checkoutResponse'
    v1CheckoutStateResponse:
      $ref: './components/schemas/v1/checkout.response.yaml#/checkoutStateResponse'
    v1CoordinatorResponse:
      $ref: './components/schemas/v1/coordinator.response.yaml#/coordinatorResponse'
    v1CoordinatorsResponse:
      $ref: './components/schemas/v1/coordinator.response.yaml#/coordinatorsResponse'
    v1ExperienceResponse:
      $ref: './components/schemas/v1/experience.response.yaml#/experienceResponse'
    v1ExperiencesResponse:
      $ref: './components/schemas/v1/experience.response.yaml#/experiencesResponse'
    v1GuestCheckoutResponse:
      $ref: './components/schemas/v1/guest-checkout.response.yaml#/guestCheckoutResponse'
    v1GuestCheckoutStateResponse:
      $ref: './components/schemas/v1/guest-checkout.response.yaml#/guestCheckoutStateResponse'
    v1LiveCommentsResponse:
      $ref: './components/schemas/v1/live-comment.response.yaml#/liveCommentsResponse'
    v1OrderResponse:
      $ref: './components/schemas/v1/order.response.yaml#/orderResponse'
    v1OrdersResponse:
      $ref: './components/schemas/v1/order.response.yaml#/ordersResponse'
    v1ScheduleResponse:
      $ref: './components/schemas/v1/schedule.response.yaml#/scheduleResponse'
    v1LiveSchedulesResponse:
      $ref: './components/schemas/v1/schedule.response.yaml#/liveSchedulesResponse'
    v1ArchiveSchedulesResponse:
      $ref: './components/schemas/v1/schedule.response.yaml#/archiveSchedulesResponse'
    v1ProducerResponse:
      $ref: './components/schemas/v1/producer.response.yaml#/producerResponse'
    v1ProducersResponse:
      $ref: './components/schemas/v1/producer.response.yaml#/producersResponse'
    v1ProductResponse:
      $ref: './components/schemas/v1/product.response.yaml#/productResponse'
    v1ProductsResponse:
      $ref: './components/schemas/v1/product.response.yaml#/productsResponse'
    v1ProductReviewResponse:
      $ref: './components/schemas/v1/product-review.response.yaml#/productReviewResponse'
    v1ProductReviewsResponse:
      $ref: './components/schemas/v1/product-review.response.yaml#/productReviewsResponse'
    v1PromotionResponse:
      $ref: './components/schemas/v1/promotion.response.yaml#/promotionResponse'
    v1SpotResponse:
      $ref: './components/schemas/v1/spot.response.yaml#/spotResponse'
    v1SpotsResponse:
      $ref: './components/schemas/v1/spot.response.yaml#/spotsResponse'
    v1SpotTypesResponse:
      $ref: './components/schemas/v1/spot-type.response.yaml#/spotTypesResponse'
    v1PaymentSystemsResponse:
      $ref: './components/schemas/v1/status.response.yaml#/paymentSystemsResponse'
    v1TopCommonResponse:
      $ref: './components/schemas/v1/top.response.yaml#/topCommonResponse'
    v1VideoResponse:
      $ref: './components/schemas/v1/video.response.yaml#/videoResponse'
    v1VideosResponse:
      $ref: './components/schemas/v1/video.response.yaml#/videosResponse'
    v1VideoCommentsResponse:
      $ref: './components/schemas/v1/video-comment.response.yaml#/videoCommentsResponse'
    v1PostalCodeResponse:
      $ref: './components/schemas/v1/postal-code.response.yaml#/postalCodeResponse'
    v1UploadUrlResponse:
      $ref: './components/schemas/v1/upload.response.yaml#/uploadUrlResponse'
    v1UploadStateResponse:
      $ref: './components/schemas/v1/upload.response.yaml#/uploadStateResponse'
