openapi: 3.0.3
info:
  title: Marche Online
  description: マルシェ購入者用API
  version: 0.1.0
servers:
- url: http://localhost:18000
  description: 開発環境
- url: https://api.furumaru-stg.and-period.work
  description: 検証環境
tags:
- name: Auth
  description: 認証関連
- name: Address
  description: アドレス帳関連
- name: Cart
  description: 買い物かご関連
- name: Checkout
  description: 購入関連
- name: Order
  description: 注文履歴関連
- name: Top
  description: トップページ関連
- name: Schedule
  description: マルシェ開催スケジュール関連
- name: Coordinator
  description: コーディネータ関連
- name: Producer
  description: 生産者関連
- name: Product
  description: 商品関連
- name: Promotion
  description: プロモーション関連
- name: Guest
  description: ゲスト関連
- name: Contact
  description: お問い合わせ関連
- name: Status
  description: システム状態関連
- name: Other
  description: その他（外部APIなど）
paths:
  # Auth
  /v1/auth:
    $ref: './paths/v1/auth/index.yaml'
  /v1/auth/refresh-token:
    $ref: './paths/v1/auth/refresh-token.yaml'
  /v1/auth/email:
    $ref: './paths/v1/auth/email/index.yaml'
  /v1/auth/email/verified:
    $ref: './paths/v1/auth/email/verified.yaml'
  /v1/auth/password:
    $ref: './paths/v1/auth/password.yaml'
  /v1/auth/forgot-password:
    $ref: './paths/v1/auth/forgot-password/index.yaml'
  /v1/auth/forgot-password/verified:
    $ref: './paths/v1/auth/forgot-password/verified.yaml'
  /v1/auth/user:
    $ref: './paths/v1/auth/user/index.yaml'
  /v1/auth/user/oauth:
    $ref: './paths/v1/auth/user/oauth.yaml'
  /v1/auth/user/verified:
    $ref: './paths/v1/auth/user/verified.yaml'
  # Address
  /v1/addresses:
    $ref: './paths/v1/addresses/index.yaml'
  /v1/addresses/{addressId}:
    $ref: './paths/v1/addresses/_addressId/index.yaml'
  # Cart
  /v1/carts:
    $ref: './paths/v1/carts/index.yaml'
  /v1/carts/{coordinatorId}:
    $ref: './paths/v1/carts/_coordinatorId/index.yaml'
  /v1/carts/-/items:
    $ref: './paths/v1/carts/-/items/index.yaml'
  /v1/carts/-/items/{productId}:
    $ref: './paths/v1/carts/-/items/_productId/index.yaml'
  # Checkout
  /v1/checkouts:
    $ref: './paths/v1/checkouts/index.yaml'
  /v1/checkouts/{transactionId}:
    $ref: './paths/v1/checkouts/_transactionId/index.yaml'
  # Order
  /v1/orders:
    $ref: './paths/v1/orders/index.yaml'
  /v1/orders/{orderId}:
    $ref: './paths/v1/orders/_orderId/index.yaml'
  # Contact
  /v1/contacts:
    $ref: './paths/v1/contacts/index.yaml'
  # Top
  /v1/top/common:
    $ref: './paths/v1/top/common.yaml'
  # Schedule
  /v1/schedules/lives:
    $ref: './paths/v1/schedules/lives.yaml'
  /v1/schedules/archives:
    $ref: './paths/v1/schedules/archives.yaml'
  /v1/schedules/{scheduleId}:
    $ref: './paths/v1/schedules/_scheduleId/index.yaml'
  /v1/schedules/{scheduleId}/comments:
    $ref: './paths/v1/schedules/_scheduleId/comments/index.yaml'
  # Coordinator
  /v1/coordinators:
    $ref: './paths/v1/coordinators/index.yaml'
  /v1/coordinators/{coordinatorId}:
    $ref: './paths/v1/coordinators/_coordinatorId/index.yaml'
  # Producer
  /v1/producers:
    $ref: './paths/v1/producers/index.yaml'
  /v1/producers/{producerId}:
    $ref: './paths/v1/producers/_producerId/index.yaml'
  # Product
  /v1/products:
    $ref: './paths/v1/products/index.yaml'
  /v1/products/{productId}:
    $ref: './paths/v1/products/_productId/index.yaml'
  # Promotion
  /v1/promotions/{code}:
    $ref: './paths/v1/promotions/_code/index.yaml'
  # Guest
  /v1/guests/checkouts:
    $ref: './paths/v1/guests/checkouts/index.yaml'
  /v1/guests/checkouts/{transactionId}:
    $ref: './paths/v1/guests/checkouts/_transactionId/index.yaml'
  /v1/guests/schedules/{scheduleId}/comments:
    $ref: './paths/v1/guests/schedules/_scheduleId/comments/index.yaml'
  # Status
  /v1/statuses/payments:
    $ref: './paths/v1/statuses/payments.yaml'
  # Upload
  /v1/upload/state:
    $ref: './paths/v1/upload/state.yaml'
  /v1/upload/users/thumbnail:
    $ref: './paths/v1/upload/users/thumbnail.yaml'
  # Other
  /v1/postal-codes/{postalCode}:
    $ref: './paths/v1/postal-codes/_postalCode.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie
      name: session_id
  schemas:
    # Common
    prefecture:
      $ref: './components/schemas/codes/common.yaml#/prefecture'
    weekday:
      $ref: './components/schemas/codes/common.yaml#/weekday'
    imageSize:
      $ref: './components/schemas/codes/image.yaml#/imageSize'
    orderStatus:
      $ref: './components/schemas/codes/order.yaml#/orderStatus'
    fulfillmentStatus:
      $ref: './components/schemas/codes/order-fulfillment.yaml#/fulfillmentStatus'
    shippingCarrier:
      $ref: './components/schemas/codes/order-fulfillment.yaml#/shippingCarrier'
    shippingSize:
      $ref: './components/schemas/codes/order-fulfillment.yaml#/shippingSize'
    shippingType:
      $ref: './components/schemas/codes/order-fulfillment.yaml#/shippingType'
    paymentMethodType:
      $ref: './components/schemas/codes/order-payment.yaml#/paymentMethodType'
    paymentStatus:
      $ref: './components/schemas/codes/order-payment.yaml#/paymentStatus'
    orderRefundType:
      $ref: './components/schemas/codes/order-refund.yaml#/orderRefundType'
    productStatus:
      $ref: './components/schemas/codes/product.yaml#/productStatus'
    deliveryType:
      $ref: './components/schemas/codes/product.yaml#/deliveryType'
    storageMethodType:
      $ref: './components/schemas/codes/product.yaml#/storageMethodType'
    promotionStatus:
      $ref: './components/schemas/codes/promotion.yaml#/promotionStatus'
    discountType:
      $ref: './components/schemas/codes/promotion.yaml#/discountType'
    scheduleStatus:
      $ref: './components/schemas/codes/schedule.yaml#/scheduleStatus'
    paymentSystemStatus:
      $ref: './components/schemas/codes/status.yaml#/paymentSystemStatus'
    uploadStatus:
      $ref: './components/schemas/codes/upload.yaml#/uploadStatus'
    errorResponse:
      $ref: './components/schemas/common.yaml#/errorResponse'
    # Entity
    address:
      $ref: './components/schemas/entity/address.yaml#/address'
    cart:
      $ref: './components/schemas/entity/cart.yaml#/cart'
    cartItem:
      $ref: './components/schemas/entity/cart.yaml#/cartItem'
    category:
      $ref: './components/schemas/entity/category.yaml#/category'
    thumbnail:
      $ref: './components/schemas/entity/common.yaml#/thumbnail'
    coordinator:
      $ref: './components/schemas/entity/coordinator.yaml#/coordinator'
    live:
      $ref: './components/schemas/entity/live.yaml#/live'
    liveSummary:
      $ref: './components/schemas/entity/live.yaml#/liveSummary'
    liveProduct:
      $ref: './components/schemas/entity/live.yaml#/liveProduct'
    archiveSummary:
      $ref: './components/schemas/entity/live.yaml#/archiveSummary'
    liveComment:
      $ref: './components/schemas/entity/live-comment.yaml#/liveComment'
    order:
      $ref: './components/schemas/entity/order.yaml#/order'
    producer:
      $ref: './components/schemas/entity/producer.yaml#/producer'
    productTag:
      $ref: './components/schemas/entity/product-tag.yaml#/productTag'
    productType:
      $ref: './components/schemas/entity/product-type.yaml#/productType'
    product:
      $ref: './components/schemas/entity/product.yaml#/product'
    promotion:
      $ref: './components/schemas/entity/promotion.yaml#/promotion'
    schedule:
      $ref: './components/schemas/entity/schedule.yaml#/schedule'
    paymentSystem:
      $ref: './components/schemas/entity/status.yaml#/paymentSystem'
    # Request
    v1CreateAddressRequest:
      $ref: './components/schemas/v1/address.request.yaml#/createAddressRequest'
    v1UpdateAddressRequest:
      $ref: './components/schemas/v1/address.request.yaml#/updateAddressRequest'
    v1SignInRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/signInRequest'
    v1RefreshAuthTokenRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/refreshAuthTokenRequest'
    v1CreateAuthRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/createAuthRequest'
    v1VerifyAuthRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/verifyAuthRequest'
    v1CreateAuthWithOAuthRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/createAuthWithOAuthRequest'
    v1UpdateAuthEmailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthEmailRequest'
    v1VerifyAuthEmailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/verifyAuthEmailRequest'
    v1UpdateAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthPasswordRequest'
    v1ForgotAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/forgotAuthPasswordRequest'
    v1ResetAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/resetAuthPasswordRequest'
    v1AddCartItemRequest:
      $ref: './components/schemas/v1/cart.request.yaml#/addCartItemRequest'
    v1CheckoutRequest:
      $ref: './components/schemas/v1/checkout.request.yaml#/checkoutRequest'
    v1CreateContactRequest:
      $ref: './components/schemas/v1/contact.request.yaml#/createContactRequest'
    v1GuestCheckoutRequest:
      $ref: './components/schemas/v1/guest-checkout.request.yaml#/guestCheckoutRequest'
    v1CreateGuestLiveCommentRequest:
      $ref: './components/schemas/v1/guest-live-comment.request.yaml#/createGuestLiveCommentRequest'
    v1CreateLiveCommentRequest:
      $ref: './components/schemas/v1/live-comment.request.yaml#/createLiveCommentRequest'
    v1GetUploadUrlRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/getUploadUrlRequest'
    # Response
    v1AuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authResponse'
    v1AuthUserResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authUserResponse'
    v1CreateAuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/createAuthResponse'
    v1AddressResponse:
      $ref: './components/schemas/v1/address.response.yaml#/addressResponse'
    v1AddressesResponse:
      $ref: './components/schemas/v1/address.response.yaml#/addressesResponse'
    v1CartResponse:
      $ref: './components/schemas/v1/cart.response.yaml#/cartResponse'
    v1CalcCartResponse:
      $ref: './components/schemas/v1/cart.response.yaml#/calcCartResponse'
    v1CheckoutResponse:
      $ref: './components/schemas/v1/checkout.response.yaml#/checkoutResponse'
    v1CheckoutStateResponse:
      $ref: './components/schemas/v1/checkout.response.yaml#/checkoutStateResponse'
    v1CoordinatorResponse:
      $ref: './components/schemas/v1/coordinator.response.yaml#/coordinatorResponse'
    v1CoordinatorsResponse:
      $ref: './components/schemas/v1/coordinator.response.yaml#/coordinatorsResponse'
    v1GuestCheckoutResponse:
      $ref: './components/schemas/v1/guest-checkout.response.yaml#/guestCheckoutResponse'
    v1GuestCheckoutStateResponse:
      $ref: './components/schemas/v1/guest-checkout.response.yaml#/guestCheckoutStateResponse'
    v1LiveCommentsResponse:
      $ref: './components/schemas/v1/live-comment.response.yaml#/liveCommentsResponse'
    v1OrderResponse:
      $ref: './components/schemas/v1/order.response.yaml#/orderResponse'
    v1OrdersResponse:
      $ref: './components/schemas/v1/order.response.yaml#/ordersResponse'
    v1ScheduleResponse:
      $ref: './components/schemas/v1/schedule.response.yaml#/scheduleResponse'
    v1LiveSchedulesResponse:
      $ref: './components/schemas/v1/schedule.response.yaml#/liveSchedulesResponse'
    v1ArchiveSchedulesResponse:
      $ref: './components/schemas/v1/schedule.response.yaml#/archiveSchedulesResponse'
    v1ProducerResponse:
      $ref: './components/schemas/v1/producer.response.yaml#/producerResponse'
    v1ProducersResponse:
      $ref: './components/schemas/v1/producer.response.yaml#/producersResponse'
    v1ProductResponse:
      $ref: './components/schemas/v1/product.response.yaml#/productResponse'
    v1ProductsResponse:
      $ref: './components/schemas/v1/product.response.yaml#/productsResponse'
    v1PromotionResponse:
      $ref: './components/schemas/v1/promotion.response.yaml#/promotionResponse'
    v1PaymentSystemsResponse:
      $ref: './components/schemas/v1/status.response.yaml#/paymentSystemsResponse'
    v1TopCommonResponse:
      $ref: './components/schemas/v1/top.response.yaml#/topCommonResponse'
    v1PostalCodeResponse:
      $ref: './components/schemas/v1/postal-code.response.yaml#/postalCodeResponse'
    v1UploadUrlResponse:
      $ref: './components/schemas/v1/upload.response.yaml#/uploadUrlResponse'
    v1UploadStateResponse:
      $ref: './components/schemas/v1/upload.response.yaml#/uploadStateResponse'
