openapi: 3.0.3
info:
  title: Marche Online
  description: マルシェ購入者用API
  version: 0.1.0
servers:
- url: http://localhost:18000
  description: 開発環境
- url: https://api.furumaru-stg.and-period.work
  description: 検証環境
tags:
- name: Auth
  description: 認証関連
- name: Contact
  description: お問い合わせ関連
paths:
  # Auth
  /v1/auth:
    $ref: './paths/v1/auth/index.yaml'
  /v1/auth/refresh-token:
    $ref: './paths/v1/auth/refresh-token.yaml'
  /v1/auth/initialized:
    $ref: './paths/v1/auth/initialized.yaml'
  /v1/auth/email:
    $ref: './paths/v1/auth/email/index.yaml'
  /v1/auth/email/verified:
    $ref: './paths/v1/auth/email/verified.yaml'
  /v1/auth/password:
    $ref: './paths/v1/auth/password.yaml'
  /v1/auth/forgot-password:
    $ref: './paths/v1/auth/forgot-password/index.yaml'
  /v1/auth/forgot-password/verified:
    $ref: './paths/v1/auth/forgot-password/verified.yaml'
  /v1/auth/user:
    $ref: './paths/v1/auth/user/index.yaml'
  /v1/auth/user/oauth:
    $ref: './paths/v1/auth/user/oauth.yaml'
  /v1/auth/user/verified:
    $ref: './paths/v1/auth/user/verified.yaml'
  # Contact
  /v1/contacts:
    $ref: './paths/v1/contacts/index.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    # Common
    errorResponse:
      $ref: './components/schemas/common.yaml#/errorResponse'
    # Request
    v1SignInRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/signInRequest'
    v1RefreshAuthTokenRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/refreshAuthTokenRequest'
    v1CreateAuthRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/createAuthRequest'
    v1InitializeAuthRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/initializeAuthRequest'
    v1VerifyAuthRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/verifyAuthRequest'
    v1UpdateAuthEmailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthEmailRequest'
    v1VerifyAuthEmailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/verifyAuthEmailRequest'
    v1UpdateAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthPasswordRequest'
    v1ForgotAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/forgotAuthPasswordRequest'
    v1ResetAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/resetAuthPasswordRequest'
    v1CreateContactRequest:
      $ref: './components/schemas/v1/contact.request.yaml#/createContactRequest'
    # Response
    v1AuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authResponse'
    v1AuthUserResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authUserResponse'
    v1CreateAuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/createAuthResponse'
