openapi: 3.0.3
info:
  title: Marche Online
  description: マルシェ購入者用API
  version: 0.1.0
servers:
- url: http://localhost:18000
  description: 開発環境
tags:
- name: Auth
  description: 認証関連
- name: User
  description: 購入者関連
paths:
  # Auth
  /v1/auth:
    $ref: './paths/v1/auth/index.yaml'
  /v1/auth/refresh-token:
    $ref: './paths/v1/auth/refresh-token.yaml'
  # User
  /v1/users:
    $ref: './paths/v1/users/index.yaml'
  /v1/users/me:
    $ref: './paths/v1/users/me/index.yaml'
  /v1/users/me/initialized:
    $ref: './paths/v1/users/me/initialized.yaml'
  /v1/users/me/email:
    $ref: './paths/v1/users/me/email/index.yaml'
  /v1/users/me/email/verified:
    $ref: './paths/v1/users/me/email/verified.yaml'
  /v1/users/me/password:
    $ref: './paths/v1/users/me/password.yaml'
  /v1/users/me/forgot-password:
    $ref: './paths/v1/users/me/forgot-password/index.yaml'
  /v1/users/me/forgot-password/me/verified:
    $ref: './paths/v1/users/me/forgot-password/verified.yaml'
  /v1/users/oauth:
    $ref: './paths/v1/users/oauth.yaml'
  /v1/users/verified:
    $ref: './paths/v1/users/verified.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    # Common
    errorResponse:
      $ref: './components/schemas/common.yaml#/errorResponse'
    # Request
    v1SignInRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/signInRequest'
    v1RefreshAuthTokenRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/refreshAuthTokenRequest'
    v1CreateUserRequest:
      $ref: './components/schemas/v1/users.request.yaml#/createUserRequest'
    v1InitializeUserRequest:
      $ref: './components/schemas/v1/users.request.yaml#/initializeUserRequest'
    v1VerifyUserRequest:
      $ref: './components/schemas/v1/users.request.yaml#/verifyUserRequest'
    v1UpdateUserEmailRequest:
      $ref: './components/schemas/v1/users.request.yaml#/updateUserEmailRequest'
    v1VerifyUserEmailRequest:
      $ref: './components/schemas/v1/users.request.yaml#/verifyUserEmailRequest'
    v1UpdateUserPasswordRequest:
      $ref: './components/schemas/v1/users.request.yaml#/updateUserPasswordRequest'
    v1ForgotUserPasswordRequest:
      $ref: './components/schemas/v1/users.request.yaml#/forgotUserPasswordRequest'
    v1ResetUserPasswordRequest:
      $ref: './components/schemas/v1/users.request.yaml#/resetUserPasswordRequest'
    # Response
    v1AuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authResponse'
    v1CreateUserResponse:
      $ref: './components/schemas/v1/users.response.yaml#/createUserResponse'
    v1UserMeResponse:
      $ref: './components/schemas/v1/users.response.yaml#/userMeResponse'
