productTag:
  type: object
  description: 商品タグ情報
  properties:
    id:
      type: string
      description: 商品タグID
    name:
      type: string
      description: 商品タグ名(32文字まで)
  required:
  - id
  - name
  example:
    id: 'kSByoE6FetnPs5Byk3a9Zx'
    name: '贈答品'
