productType:
  type: object
  description: 品目情報
  properties:
    id:
      type: string
      description: 品目ID
    name:
      type: string
      description: 品目名
    iconUrl:
      type: string
      description: アイコンURL
    categoryId:
      type: string
      description: 商品種別ID
  required:
  - id
  - name
  - iconUrl
  - categoryId
  example:
    id: 'kSByoE6FetnPs5Byk3a9Zx'
    name: 'じゃがいも'
    iconUrl: 'https://and-period.jp/icon.png'
    categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
