productType:
  type: object
  description: 品目情報
  properties:
    id:
      type: string
      description: 品目ID
    name:
      type: string
      description: 品目名
    iconUrl:
      type: string
      description: アイコンURL
    icons:
      type: array
      description: リサイズ済みアイコンURL一覧
      deprecated: true
      items:
        type: object
        properties:
          url:
            type: string
            description: リサイズ済みアイコンURL
          size:
            $ref: './../../../openapi.yaml#/components/schemas/imageSize'
        required:
        - url
        - size
    categoryId:
      type: string
      description: 商品種別ID
  required:
  - id
  - name
  - iconUrl
  - icons
  - categoryId
  example:
    id: 'kSByoE6FetnPs5Byk3a9Zx'
    name: 'じゃがいも'
    iconUrl: 'https://and-period.jp/icon.png'
    icons:
    - url: 'https://and-period.jp/icon_240.png'
      size: 1
    - url: 'https://and-period.jp/icon_675.png'
      size: 2
    - url: 'https://and-period.jp/icon_900.png'
      size: 3
    categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
