producer:
  type: object
  description: 生産者情報
  properties:
    id:
      type: string
      description: 生産者ID
    coordinatorId:
      type: string
      description: 担当コーディネータID
    username:
      type: string
      description: 生産者名
    profile:
      type: string
      description: プロフィール
    thumbnailUrl:
      type: string
      description: サムネイルURL
    headerUrl:
      type: string
      description: ヘッダー画像URL
    promotionVideoUrl:
      type: string
      description: 紹介動画URL
    instagramId:
      type: string
      description: Instagramアカウント
    facebookId:
      type: string
      description: Facebookアカウント
    prefecture:
      type: string
      description: 都道府県
    city:
      type: string
      description: 市区町村
  required:
  - id
  - coordinatorId
  - username
  - profile
  - promotionVideoUrl
  - thumbnailUrl
  - headerUrl
  - instagramId
  - facebookId
  - prefecture
  - city
  example:
    id: 'kSByoE6FetnPs5Byk3a9Zx'
    coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
    username: '&.農園'
    profile: '紹介文です。'
    thumbnailUrl: 'https://and-period.jp/thumbnail.png'
    headerUrl: 'https://and-period.jp/header.png'
    promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
    instagramId: 'instagram-id'
    facebookId: 'facebook-id'
    prefecture: '東京都'
    city: '千代田区'
