/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CoordinatorHeadersInner
 */
export interface CoordinatorHeadersInner {
    /**
     * リサイズ済みヘッダー画像URL
     * @type {string}
     * @memberof CoordinatorHeadersInner
     */
    url: string;
    /**
     * 
     * @type {object}
     * @memberof CoordinatorHeadersInner
     */
    size: object;
}

/**
 * Check if a given object implements the CoordinatorHeadersInner interface.
 */
export function instanceOfCoordinatorHeadersInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "size" in value;

    return isInstance;
}

export function CoordinatorHeadersInnerFromJSON(json: any): CoordinatorHeadersInner {
    return CoordinatorHeadersInnerFromJSONTyped(json, false);
}

export function CoordinatorHeadersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoordinatorHeadersInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'size': json['size'],
    };
}

export function CoordinatorHeadersInnerToJSON(value?: CoordinatorHeadersInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'size': value.size,
    };
}

