/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductType } from './ProductType';
import {
    ProductTypeFromJSON,
    ProductTypeFromJSONTyped,
    ProductTypeToJSON,
} from './ProductType';
import type { Coordinator } from './Coordinator';
import {
    CoordinatorFromJSON,
    CoordinatorFromJSONTyped,
    CoordinatorToJSON,
} from './Coordinator';

/**
 * 
 * @export
 * @interface CoordinatorsResponse
 */
export interface CoordinatorsResponse {
    /**
     * コーディネータ一覧
     * @type {Array<Coordinator>}
     * @memberof CoordinatorsResponse
     */
    coordinators: Array<Coordinator>;
    /**
     * 品目一覧
     * @type {Array<ProductType>}
     * @memberof CoordinatorsResponse
     */
    productTypes: Array<ProductType>;
    /**
     * 合計数
     * @type {number}
     * @memberof CoordinatorsResponse
     */
    total: number;
}

/**
 * Check if a given object implements the CoordinatorsResponse interface.
 */
export function instanceOfCoordinatorsResponse(value: object): value is CoordinatorsResponse {
    if (!('coordinators' in value) || value['coordinators'] === undefined) return false;
    if (!('productTypes' in value) || value['productTypes'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function CoordinatorsResponseFromJSON(json: any): CoordinatorsResponse {
    return CoordinatorsResponseFromJSONTyped(json, false);
}

export function CoordinatorsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CoordinatorsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinators': ((json['coordinators'] as Array<any>).map(CoordinatorFromJSON)),
        'productTypes': ((json['productTypes'] as Array<any>).map(ProductTypeFromJSON)),
        'total': json['total'],
    };
}

export function CoordinatorsResponseToJSON(value?: CoordinatorsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'coordinators': ((value['coordinators'] as Array<any>).map(CoordinatorToJSON)),
        'productTypes': ((value['productTypes'] as Array<any>).map(ProductTypeToJSON)),
        'total': value['total'],
    };
}

