/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderRefundType } from './OrderRefundType';
import {
    OrderRefundTypeFromJSON,
    OrderRefundTypeFromJSONTyped,
    OrderRefundTypeToJSON,
} from './OrderRefundType';

/**
 * 注文キャンセル情報
 * @export
 * @interface OrderRefund
 */
export interface OrderRefund {
    /**
     * 返金金額
     * @type {number}
     * @memberof OrderRefund
     */
    total: number;
    /**
     * 
     * @type {OrderRefundType}
     * @memberof OrderRefund
     */
    type: OrderRefundType;
    /**
     * 注文キャンセル理由
     * @type {string}
     * @memberof OrderRefund
     */
    reason: string;
    /**
     * 注文キャンセルフラグ
     * @type {boolean}
     * @memberof OrderRefund
     */
    canceled: boolean;
    /**
     * 注文キャンセル日時（unixtime）
     * @type {number}
     * @memberof OrderRefund
     */
    canceledAt: number;
}



/**
 * Check if a given object implements the OrderRefund interface.
 */
export function instanceOfOrderRefund(value: object): value is OrderRefund {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('canceled' in value) || value['canceled'] === undefined) return false;
    if (!('canceledAt' in value) || value['canceledAt'] === undefined) return false;
    return true;
}

export function OrderRefundFromJSON(json: any): OrderRefund {
    return OrderRefundFromJSONTyped(json, false);
}

export function OrderRefundFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderRefund {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'type': OrderRefundTypeFromJSON(json['type']),
        'reason': json['reason'],
        'canceled': json['canceled'],
        'canceledAt': json['canceledAt'],
    };
}

export function OrderRefundToJSON(value?: OrderRefund | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'total': value['total'],
        'type': OrderRefundTypeToJSON(value['type']),
        'reason': value['reason'],
        'canceled': value['canceled'],
        'canceledAt': value['canceledAt'],
    };
}

