/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductReviewReactionType } from './ProductReviewReactionType';
import {
    ProductReviewReactionTypeFromJSON,
    ProductReviewReactionTypeFromJSONTyped,
    ProductReviewReactionTypeToJSON,
} from './ProductReviewReactionType';

/**
 * 商品レビューのリアクション情報
 * @export
 * @interface ProductReviewReaction
 */
export interface ProductReviewReaction {
    /**
     * 商品レビューID
     * @type {string}
     * @memberof ProductReviewReaction
     */
    reviewId: string;
    /**
     * 
     * @type {ProductReviewReactionType}
     * @memberof ProductReviewReaction
     */
    reactionType: ProductReviewReactionType;
}



/**
 * Check if a given object implements the ProductReviewReaction interface.
 */
export function instanceOfProductReviewReaction(value: object): value is ProductReviewReaction {
    if (!('reviewId' in value) || value['reviewId'] === undefined) return false;
    if (!('reactionType' in value) || value['reactionType'] === undefined) return false;
    return true;
}

export function ProductReviewReactionFromJSON(json: any): ProductReviewReaction {
    return ProductReviewReactionFromJSONTyped(json, false);
}

export function ProductReviewReactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductReviewReaction {
    if (json == null) {
        return json;
    }
    return {
        
        'reviewId': json['reviewId'],
        'reactionType': ProductReviewReactionTypeFromJSON(json['reactionType']),
    };
}

export function ProductReviewReactionToJSON(value?: ProductReviewReaction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'reviewId': value['reviewId'],
        'reactionType': ProductReviewReactionTypeToJSON(value['reactionType']),
    };
}

