/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductMediaInner
 */
export interface ProductMediaInner {
    /**
     * メディアURL
     * @type {string}
     * @memberof ProductMediaInner
     */
    url: string;
    /**
     * サムネイルとして使用(1つまで)
     * @type {boolean}
     * @memberof ProductMediaInner
     */
    isThumbnail: boolean;
}

/**
 * Check if a given object implements the ProductMediaInner interface.
 */
export function instanceOfProductMediaInner(value: object): value is ProductMediaInner {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('isThumbnail' in value) || value['isThumbnail'] === undefined) return false;
    return true;
}

export function ProductMediaInnerFromJSON(json: any): ProductMediaInner {
    return ProductMediaInnerFromJSONTyped(json, false);
}

export function ProductMediaInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductMediaInner {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'isThumbnail': json['isThumbnail'],
    };
}

export function ProductMediaInnerToJSON(value?: ProductMediaInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'isThumbnail': value['isThumbnail'],
    };
}

