/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 品目情報
 * @export
 * @interface ProductType
 */
export interface ProductType {
    /**
     * 品目ID
     * @type {string}
     * @memberof ProductType
     */
    id: string;
    /**
     * 品目名
     * @type {string}
     * @memberof ProductType
     */
    name: string;
    /**
     * アイコンURL
     * @type {string}
     * @memberof ProductType
     */
    iconUrl: string;
    /**
     * 商品種別ID
     * @type {string}
     * @memberof ProductType
     */
    categoryId: string;
}

/**
 * Check if a given object implements the ProductType interface.
 */
export function instanceOfProductType(value: object): value is ProductType {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('iconUrl' in value) || value['iconUrl'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    return true;
}

export function ProductTypeFromJSON(json: any): ProductType {
    return ProductTypeFromJSONTyped(json, false);
}

export function ProductTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'iconUrl': json['iconUrl'],
        'categoryId': json['categoryId'],
    };
}

export function ProductTypeToJSON(value?: ProductType | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'iconUrl': value['iconUrl'],
        'categoryId': value['categoryId'],
    };
}

