/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Prefecture } from './Prefecture';
import {
    PrefectureFromJSON,
    PrefectureFromJSONTyped,
    PrefectureToJSON,
} from './Prefecture';

/**
 * 配送料情報
 * @export
 * @interface ShippingRate
 */
export interface ShippingRate {
    /**
     * No.
     * @type {number}
     * @memberof ShippingRate
     */
    number: number;
    /**
     * 配送料金設定名
     * @type {string}
     * @memberof ShippingRate
     */
    name: string;
    /**
     * 配送料金（税込）
     * @type {number}
     * @memberof ShippingRate
     */
    price: number;
    /**
     * 対象都道府県一覧
     * @type {Array<string>}
     * @memberof ShippingRate
     */
    prefectures: Array<string>;
    /**
     * 対象都道府県コード一覧
     * @type {Array<Prefecture>}
     * @memberof ShippingRate
     */
    prefectureCodes: Array<Prefecture>;
}

/**
 * Check if a given object implements the ShippingRate interface.
 */
export function instanceOfShippingRate(value: object): value is ShippingRate {
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('prefectures' in value) || value['prefectures'] === undefined) return false;
    if (!('prefectureCodes' in value) || value['prefectureCodes'] === undefined) return false;
    return true;
}

export function ShippingRateFromJSON(json: any): ShippingRate {
    return ShippingRateFromJSONTyped(json, false);
}

export function ShippingRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingRate {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'],
        'name': json['name'],
        'price': json['price'],
        'prefectures': json['prefectures'],
        'prefectureCodes': ((json['prefectureCodes'] as Array<any>).map(PrefectureFromJSON)),
    };
}

export function ShippingRateToJSON(value?: ShippingRate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'number': value['number'],
        'name': value['name'],
        'price': value['price'],
        'prefectures': value['prefectures'],
        'prefectureCodes': ((value['prefectureCodes'] as Array<any>).map(PrefectureToJSON)),
    };
}

