/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 投稿者の種別
 * @export
 */
export const SpotUserType = {
    UNKNOWN: 0,
    USER: 1,
    ADMIN: 2
} as const;
export type SpotUserType = typeof SpotUserType[keyof typeof SpotUserType];


export function instanceOfSpotUserType(value: any): boolean {
    for (const key in SpotUserType) {
        if (Object.prototype.hasOwnProperty.call(SpotUserType, key)) {
            if (SpotUserType[key as keyof typeof SpotUserType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SpotUserTypeFromJSON(json: any): SpotUserType {
    return SpotUserTypeFromJSONTyped(json, false);
}

export function SpotUserTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpotUserType {
    return json as SpotUserType;
}

export function SpotUserTypeToJSON(value?: SpotUserType | null): any {
    return value as any;
}

