/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExperienceReviewReaction } from './ExperienceReviewReaction';
import {
    ExperienceReviewReactionFromJSON,
    ExperienceReviewReactionFromJSONTyped,
    ExperienceReviewReactionToJSON,
} from './ExperienceReviewReaction';
import type { ExperienceReview } from './ExperienceReview';
import {
    ExperienceReviewFromJSON,
    ExperienceReviewFromJSONTyped,
    ExperienceReviewToJSON,
} from './ExperienceReview';

/**
 * 
 * @export
 * @interface UserExperienceReviewsResponse
 */
export interface UserExperienceReviewsResponse {
    /**
     * 体験レビュー一覧
     * @type {Array<ExperienceReview>}
     * @memberof UserExperienceReviewsResponse
     */
    reviews: Array<ExperienceReview>;
    /**
     * 体験レビューのリアクション一覧
     * @type {Array<ExperienceReviewReaction>}
     * @memberof UserExperienceReviewsResponse
     */
    reactions: Array<ExperienceReviewReaction>;
}

/**
 * Check if a given object implements the UserExperienceReviewsResponse interface.
 */
export function instanceOfUserExperienceReviewsResponse(value: object): value is UserExperienceReviewsResponse {
    if (!('reviews' in value) || value['reviews'] === undefined) return false;
    if (!('reactions' in value) || value['reactions'] === undefined) return false;
    return true;
}

export function UserExperienceReviewsResponseFromJSON(json: any): UserExperienceReviewsResponse {
    return UserExperienceReviewsResponseFromJSONTyped(json, false);
}

export function UserExperienceReviewsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserExperienceReviewsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'reviews': ((json['reviews'] as Array<any>).map(ExperienceReviewFromJSON)),
        'reactions': ((json['reactions'] as Array<any>).map(ExperienceReviewReactionFromJSON)),
    };
}

export function UserExperienceReviewsResponseToJSON(value?: UserExperienceReviewsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'reviews': ((value['reviews'] as Array<any>).map(ExperienceReviewToJSON)),
        'reactions': ((value['reactions'] as Array<any>).map(ExperienceReviewReactionToJSON)),
    };
}

