/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductReviewReaction } from './ProductReviewReaction';
import {
    ProductReviewReactionFromJSON,
    ProductReviewReactionFromJSONTyped,
    ProductReviewReactionToJSON,
} from './ProductReviewReaction';
import type { ProductReview } from './ProductReview';
import {
    ProductReviewFromJSON,
    ProductReviewFromJSONTyped,
    ProductReviewToJSON,
} from './ProductReview';

/**
 * 
 * @export
 * @interface UserProductReviewsResponse
 */
export interface UserProductReviewsResponse {
    /**
     * 商品レビュー一覧
     * @type {Array<ProductReview>}
     * @memberof UserProductReviewsResponse
     */
    reviews: Array<ProductReview>;
    /**
     * 商品レビューのリアクション一覧
     * @type {Array<ProductReviewReaction>}
     * @memberof UserProductReviewsResponse
     */
    reactions: Array<ProductReviewReaction>;
}

/**
 * Check if a given object implements the UserProductReviewsResponse interface.
 */
export function instanceOfUserProductReviewsResponse(value: object): value is UserProductReviewsResponse {
    if (!('reviews' in value) || value['reviews'] === undefined) return false;
    if (!('reactions' in value) || value['reactions'] === undefined) return false;
    return true;
}

export function UserProductReviewsResponseFromJSON(json: any): UserProductReviewsResponse {
    return UserProductReviewsResponseFromJSONTyped(json, false);
}

export function UserProductReviewsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProductReviewsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'reviews': ((json['reviews'] as Array<any>).map(ProductReviewFromJSON)),
        'reactions': ((json['reactions'] as Array<any>).map(ProductReviewReactionFromJSON)),
    };
}

export function UserProductReviewsResponseToJSON(value?: UserProductReviewsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'reviews': ((value['reviews'] as Array<any>).map(ProductReviewToJSON)),
        'reactions': ((value['reactions'] as Array<any>).map(ProductReviewReactionToJSON)),
    };
}

