/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AuthLineAccountResponse
 */
export interface V1AuthLineAccountResponse {
    /**
     * LINE認証用のURL
     * @type {string}
     * @memberof V1AuthLineAccountResponse
     */
    url: string;
}

/**
 * Check if a given object implements the V1AuthLineAccountResponse interface.
 */
export function instanceOfV1AuthLineAccountResponse(value: object): value is V1AuthLineAccountResponse {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function V1AuthLineAccountResponseFromJSON(json: any): V1AuthLineAccountResponse {
    return V1AuthLineAccountResponseFromJSONTyped(json, false);
}

export function V1AuthLineAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AuthLineAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function V1AuthLineAccountResponseToJSON(value?: V1AuthLineAccountResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

