/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * オンデマンド配信の概要
 * @export
 * @interface VideoSummary
 */
export interface VideoSummary {
    /**
     * オンデマンド配信ID
     * @type {string}
     * @memberof VideoSummary
     */
    id: string;
    /**
     * コーディネータID
     * @type {string}
     * @memberof VideoSummary
     */
    coordinatorId: string;
    /**
     * タイトル
     * @type {string}
     * @memberof VideoSummary
     */
    title: string;
    /**
     * サムネイルURL
     * @type {string}
     * @memberof VideoSummary
     */
    thumbnailUrl: string;
    /**
     * 公開日時 (unixtime)
     * @type {number}
     * @memberof VideoSummary
     */
    publishedAt: number;
}

/**
 * Check if a given object implements the VideoSummary interface.
 */
export function instanceOfVideoSummary(value: object): value is VideoSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('coordinatorId' in value) || value['coordinatorId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('thumbnailUrl' in value) || value['thumbnailUrl'] === undefined) return false;
    if (!('publishedAt' in value) || value['publishedAt'] === undefined) return false;
    return true;
}

export function VideoSummaryFromJSON(json: any): VideoSummary {
    return VideoSummaryFromJSONTyped(json, false);
}

export function VideoSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'coordinatorId': json['coordinatorId'],
        'title': json['title'],
        'thumbnailUrl': json['thumbnailUrl'],
        'publishedAt': json['publishedAt'],
    };
}

export function VideoSummaryToJSON(value?: VideoSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'coordinatorId': value['coordinatorId'],
        'title': value['title'],
        'thumbnailUrl': value['thumbnailUrl'],
        'publishedAt': value['publishedAt'],
    };
}

