/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Video } from './Video';
import {
    VideoFromJSON,
    VideoFromJSONTyped,
    VideoToJSON,
} from './Video';
import type { Coordinator } from './Coordinator';
import {
    CoordinatorFromJSON,
    CoordinatorFromJSONTyped,
    CoordinatorToJSON,
} from './Coordinator';

/**
 * 
 * @export
 * @interface VideosResponse
 */
export interface VideosResponse {
    /**
     * 動画一覧
     * @type {Array<Video>}
     * @memberof VideosResponse
     */
    videos: Array<Video>;
    /**
     * コーディネータ一覧
     * @type {Array<Coordinator>}
     * @memberof VideosResponse
     */
    coordinators: Array<Coordinator>;
    /**
     * 合計数
     * @type {number}
     * @memberof VideosResponse
     */
    total: number;
}

/**
 * Check if a given object implements the VideosResponse interface.
 */
export function instanceOfVideosResponse(value: object): value is VideosResponse {
    if (!('videos' in value) || value['videos'] === undefined) return false;
    if (!('coordinators' in value) || value['coordinators'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function VideosResponseFromJSON(json: any): VideosResponse {
    return VideosResponseFromJSONTyped(json, false);
}

export function VideosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'videos': ((json['videos'] as Array<any>).map(VideoFromJSON)),
        'coordinators': ((json['coordinators'] as Array<any>).map(CoordinatorFromJSON)),
        'total': json['total'],
    };
}

export function VideosResponseToJSON(value?: VideosResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'videos': ((value['videos'] as Array<any>).map(VideoToJSON)),
        'coordinators': ((value['coordinators'] as Array<any>).map(CoordinatorToJSON)),
        'total': value['total'],
    };
}

