apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        {{- if .Values.image.tag }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- else }}
        image: "{{ .Values.image.repository }}"
        {{- end }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
        ports:
        - name: default
          protocol: TCP
          containerPort: {{ .Values.app.port }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          protocol: TCP
          containerPort: {{ .Values.metrics.port }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if and .Values.health.liveness .Values.health.liveness.enabled }}
        livenessProbe:
          tcpSocket:
            port: {{.Values.health.liveness.port}}
          initialDelaySeconds: {{ default 10 .Values.health.liveness.initialDelay }}
          periodSeconds: {{ default 5 .Values.health.liveness.interval }}
          failureThreshold: 3
        {{- end }}
        {{- if and .Values.health.readiness .Values.health.readiness.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ default 5 .Values.health.readiness.port }}
          initialDelaySeconds: {{ default 10 .Values.health.readiness.initialDelay }}
          periodSeconds: {{ default 5 .Values.health.readiness.interval }}
          periodSeconds: 5
          failureThreshold: 3
        {{- end }}
        env:
        - name: PORT
          value: {{ .Values.app.port | quote }}
        {{- if .Values.metrics.enabled }}
        - name: METRICS_PORT
          value: {{ .Values.metrics.port | quote }}
        {{- end }}
        {{- if .Values.envoy.enabled }}
        - name: PROXY_HOST
          value: {{ .Values.app.proxyHost | quote }}
        {{- end }}
        {{- if .Values.database.enabled }}
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ include "service.fullname" . }}-database-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: {{ include "service.fullname" . }}-database-secret
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "service.fullname" . }}-database-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "service.fullname" . }}-database-secret
              key: DB_PASSWORD
        - name: DB_DATABASE
          value: {{ .Values.database.database | quote }}
        - name: DB_TIMEZONE
          value: {{ .Values.database.timezone | quote }}
        - name: DB_ENABLED_TLS
          value: {{ .Values.database.enabledTls | quote }}
        {{- end }}
        {{- if and .Values.awsCredentials .Values.awsCredentials.enabled }}
        - name: AWS_REGION
          value: "{{ .Values.awsCredentials.region }}"
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "service.fullname" . }}-aws-secret
              key: AWS_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "service.fullname" . }}-aws-secret
              key: AWS_SECRET_KEY
        {{- end }}
        {{- if and .Values.cognitoCredentials .Values.cognitoCredentials.enabled }}
        - name: COGNITO_USER_POOL_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "service.fullname" . }}-cognito-secret
              key: COGNITO_USER_POOL_ID
        - name: COGNITO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "service.fullname" . }}-cognito-secret
              key: COGNITO_CLIENT_ID
        {{- end }}
        {{- toYaml .Values.env | nindent 8 }}
      {{- if .Values.envoy.enabled }}
      - name: envoy
        image: "{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.tag }}"
        imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
        ports:
        - name: default
          protocol: TCP
          containerPort: {{ .Values.service.internalPort }}
        - name: admin
          protocol: TCP
          containerPort: {{ .Values.envoy.admin.port }}
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
          readOnly: true
      {{- end }}
      volumes:
      {{- if .Values.envoy.enabled }}
      - name: envoy-config
        configMap:
          name: {{ include "service.fullname" . }}-envoy-config
      {{- end }}
