{{- if .Values.database.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}-database-secret
  labels:
    {{- include "service.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.database.host | b64enc | quote }}
  DB_PORT: {{ .Values.database.port | b64enc | quote }}
  DB_USERNAME: {{ .Values.database.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
{{- end }}
{{- if and .Values.awsCredentials .Values.awsCredentials.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}-aws-secret
  labels:
    {{- include "service.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY: {{ .Values.awsCredentials.accessKey | b64enc | quote }}
  AWS_SECRET_KEY: {{ .Values.awsCredentials.secretKey | b64enc | quote }}
{{- end }}
{{- if and .Values.cognitoCredentials .Values.cognitoCredentials.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.fullname" . }}-cognito-secret
  labels:
    {{- include "service.labels" . | nindent 4 }}
data:
  COGNITO_USER_POOL_ID: {{ .Values.cognitoCredentials.userPoolId | b64enc | quote }}
  COGNITO_CLIENT_ID: {{ .Values.cognitoCredentials.clientId | b64enc | quote }}
{{- end }}
