name: setup aws
description: 'AWSのセットアップ'

inputs:
  aws-role-arn:
    description: 'IAM Role ARN'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true

runs:
  using: composite
  steps:
  - name: Configure AWS credentials from IAM Role
    uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
    with:
      role-to-assume: ${{ inputs.aws-role-arn }}
      aws-region: ${{ inputs.aws-region }}
