/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 外部宿泊施設向け
 * 外部宿泊施設向けのふるマルAPIです。（公開エンドポイントについては「ふるマルAPI - 購入者向け」を参照してください）
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthResponse,
  RequestSignInRequest,
  UtilErrorResponse,
} from '../models/index';
import {
    AuthResponseFromJSON,
    AuthResponseToJSON,
    RequestSignInRequestFromJSON,
    RequestSignInRequestToJSON,
    UtilErrorResponseFromJSON,
    UtilErrorResponseToJSON,
} from '../models/index';

export interface FacilitiesFacilityIdAuthDeleteRequest {
    facilityId: string;
}

export interface FacilitiesFacilityIdAuthPostRequest {
    facilityId: string;
    requestSignInRequest: RequestSignInRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * ふるマルからサインアウトします。
     * サインアウト
     */
    async facilitiesFacilityIdAuthDeleteRaw(requestParameters: FacilitiesFacilityIdAuthDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['facilityId'] == null) {
            throw new runtime.RequiredError(
                'facilityId',
                'Required parameter "facilityId" was null or undefined when calling facilitiesFacilityIdAuthDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerauth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/facilities/{facilityId}/auth`.replace(`{${"facilityId"}}`, encodeURIComponent(String(requestParameters['facilityId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ふるマルからサインアウトします。
     * サインアウト
     */
    async facilitiesFacilityIdAuthDelete(requestParameters: FacilitiesFacilityIdAuthDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.facilitiesFacilityIdAuthDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * LINEの認証トークンを渡すことで、ふるマルへサインインします。
     * サインイン
     */
    async facilitiesFacilityIdAuthPostRaw(requestParameters: FacilitiesFacilityIdAuthPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthResponse>> {
        if (requestParameters['facilityId'] == null) {
            throw new runtime.RequiredError(
                'facilityId',
                'Required parameter "facilityId" was null or undefined when calling facilitiesFacilityIdAuthPost().'
            );
        }

        if (requestParameters['requestSignInRequest'] == null) {
            throw new runtime.RequiredError(
                'requestSignInRequest',
                'Required parameter "requestSignInRequest" was null or undefined when calling facilitiesFacilityIdAuthPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/facilities/{facilityId}/auth`.replace(`{${"facilityId"}}`, encodeURIComponent(String(requestParameters['facilityId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestSignInRequestToJSON(requestParameters['requestSignInRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
    }

    /**
     * LINEの認証トークンを渡すことで、ふるマルへサインインします。
     * サインイン
     */
    async facilitiesFacilityIdAuthPost(requestParameters: FacilitiesFacilityIdAuthPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthResponse> {
        const response = await this.facilitiesFacilityIdAuthPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
