// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -source=provider.go -package=mock_payment -destination=./../../../mock/store/payment/provider.go
//

// Package mock_payment is a generated GoMock package.
package mock_payment

import (
	context "context"
	reflect "reflect"

	payment "github.com/and-period/furumaru/api/internal/store/payment"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// CancelPayment mocks base method.
func (m *MockProvider) CancelPayment(ctx context.Context, paymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelPayment", ctx, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelPayment indicates an expected call of CancelPayment.
func (mr *MockProviderMockRecorder) CancelPayment(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelPayment", reflect.TypeOf((*MockProvider)(nil).CancelPayment), ctx, paymentID)
}

// CapturePayment mocks base method.
func (m *MockProvider) CapturePayment(ctx context.Context, paymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CapturePayment", ctx, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CapturePayment indicates an expected call of CapturePayment.
func (mr *MockProviderMockRecorder) CapturePayment(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CapturePayment", reflect.TypeOf((*MockProvider)(nil).CapturePayment), ctx, paymentID)
}

// CreateSession mocks base method.
func (m *MockProvider) CreateSession(ctx context.Context, params *payment.CreateSessionParams) (*payment.CreateSessionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, params)
	ret0, _ := ret[0].(*payment.CreateSessionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockProviderMockRecorder) CreateSession(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockProvider)(nil).CreateSession), ctx, params)
}

// GetSession mocks base method.
func (m *MockProvider) GetSession(ctx context.Context, sessionID string) (*payment.GetSessionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(*payment.GetSessionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockProviderMockRecorder) GetSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockProvider)(nil).GetSession), ctx, sessionID)
}

// IsSessionFailed mocks base method.
func (m *MockProvider) IsSessionFailed(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSessionFailed", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSessionFailed indicates an expected call of IsSessionFailed.
func (mr *MockProviderMockRecorder) IsSessionFailed(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSessionFailed", reflect.TypeOf((*MockProvider)(nil).IsSessionFailed), err)
}

// OrderAUPay mocks base method.
func (m *MockProvider) OrderAUPay(ctx context.Context, params *payment.OrderAUPayParams) (*payment.OrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderAUPay", ctx, params)
	ret0, _ := ret[0].(*payment.OrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderAUPay indicates an expected call of OrderAUPay.
func (mr *MockProviderMockRecorder) OrderAUPay(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderAUPay", reflect.TypeOf((*MockProvider)(nil).OrderAUPay), ctx, params)
}

// OrderBankTransfer mocks base method.
func (m *MockProvider) OrderBankTransfer(ctx context.Context, params *payment.OrderBankTransferParams) (*payment.OrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderBankTransfer", ctx, params)
	ret0, _ := ret[0].(*payment.OrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderBankTransfer indicates an expected call of OrderBankTransfer.
func (mr *MockProviderMockRecorder) OrderBankTransfer(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderBankTransfer", reflect.TypeOf((*MockProvider)(nil).OrderBankTransfer), ctx, params)
}

// OrderCreditCard mocks base method.
func (m *MockProvider) OrderCreditCard(ctx context.Context, params *payment.OrderCreditCardParams) (*payment.OrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderCreditCard", ctx, params)
	ret0, _ := ret[0].(*payment.OrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderCreditCard indicates an expected call of OrderCreditCard.
func (mr *MockProviderMockRecorder) OrderCreditCard(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderCreditCard", reflect.TypeOf((*MockProvider)(nil).OrderCreditCard), ctx, params)
}

// OrderKonbini mocks base method.
func (m *MockProvider) OrderKonbini(ctx context.Context, params *payment.OrderKonbiniParams) (*payment.OrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderKonbini", ctx, params)
	ret0, _ := ret[0].(*payment.OrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderKonbini indicates an expected call of OrderKonbini.
func (mr *MockProviderMockRecorder) OrderKonbini(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderKonbini", reflect.TypeOf((*MockProvider)(nil).OrderKonbini), ctx, params)
}

// OrderLinePay mocks base method.
func (m *MockProvider) OrderLinePay(ctx context.Context, params *payment.OrderLinePayParams) (*payment.OrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderLinePay", ctx, params)
	ret0, _ := ret[0].(*payment.OrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderLinePay indicates an expected call of OrderLinePay.
func (mr *MockProviderMockRecorder) OrderLinePay(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderLinePay", reflect.TypeOf((*MockProvider)(nil).OrderLinePay), ctx, params)
}

// OrderMerpay mocks base method.
func (m *MockProvider) OrderMerpay(ctx context.Context, params *payment.OrderMerpayParams) (*payment.OrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderMerpay", ctx, params)
	ret0, _ := ret[0].(*payment.OrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderMerpay indicates an expected call of OrderMerpay.
func (mr *MockProviderMockRecorder) OrderMerpay(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderMerpay", reflect.TypeOf((*MockProvider)(nil).OrderMerpay), ctx, params)
}

// OrderPaidy mocks base method.
func (m *MockProvider) OrderPaidy(ctx context.Context, params *payment.OrderPaidyParams) (*payment.OrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderPaidy", ctx, params)
	ret0, _ := ret[0].(*payment.OrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderPaidy indicates an expected call of OrderPaidy.
func (mr *MockProviderMockRecorder) OrderPaidy(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderPaidy", reflect.TypeOf((*MockProvider)(nil).OrderPaidy), ctx, params)
}

// OrderPayEasy mocks base method.
func (m *MockProvider) OrderPayEasy(ctx context.Context, params *payment.OrderPayEasyParams) (*payment.OrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderPayEasy", ctx, params)
	ret0, _ := ret[0].(*payment.OrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderPayEasy indicates an expected call of OrderPayEasy.
func (mr *MockProviderMockRecorder) OrderPayEasy(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderPayEasy", reflect.TypeOf((*MockProvider)(nil).OrderPayEasy), ctx, params)
}

// OrderPayPay mocks base method.
func (m *MockProvider) OrderPayPay(ctx context.Context, params *payment.OrderPayPayParams) (*payment.OrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderPayPay", ctx, params)
	ret0, _ := ret[0].(*payment.OrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderPayPay indicates an expected call of OrderPayPay.
func (mr *MockProviderMockRecorder) OrderPayPay(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderPayPay", reflect.TypeOf((*MockProvider)(nil).OrderPayPay), ctx, params)
}

// OrderRakutenPay mocks base method.
func (m *MockProvider) OrderRakutenPay(ctx context.Context, params *payment.OrderRakutenPayParams) (*payment.OrderResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderRakutenPay", ctx, params)
	ret0, _ := ret[0].(*payment.OrderResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderRakutenPay indicates an expected call of OrderRakutenPay.
func (mr *MockProviderMockRecorder) OrderRakutenPay(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderRakutenPay", reflect.TypeOf((*MockProvider)(nil).OrderRakutenPay), ctx, params)
}

// RefundPayment mocks base method.
func (m *MockProvider) RefundPayment(ctx context.Context, params *payment.RefundParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefundPayment", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefundPayment indicates an expected call of RefundPayment.
func (mr *MockProviderMockRecorder) RefundPayment(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefundPayment", reflect.TypeOf((*MockProvider)(nil).RefundPayment), ctx, params)
}

// ShowPayment mocks base method.
func (m *MockProvider) ShowPayment(ctx context.Context, paymentID string) (*payment.PaymentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowPayment", ctx, paymentID)
	ret0, _ := ret[0].(*payment.PaymentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowPayment indicates an expected call of ShowPayment.
func (mr *MockProviderMockRecorder) ShowPayment(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowPayment", reflect.TypeOf((*MockProvider)(nil).ShowPayment), ctx, paymentID)
}
