productResponse:
  type: object
  properties:
    product:
      $ref: './../../../openapi.yaml#/components/schemas/product'
    coordinator:
      $ref: './../../../openapi.yaml#/components/schemas/coordinator'
    producer:
      $ref: './../../../openapi.yaml#/components/schemas/producer'
    category:
      $ref: './../../../openapi.yaml#/components/schemas/category'
    productType:
      $ref: './../../../openapi.yaml#/components/schemas/productType'
    productTags:
      type: array
      description: 商品タグ一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/productTag'
  required:
  - product
  - coordinator
  - producer
  - category
  - productType
  - productTags
  example:
    product:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '新鮮なじゃがいも'
      description: '新鮮なじゃがいもをお届けします。'
      status: 2
      producerId: 'kSByoE6FetnPs5Byk3a9Zx'
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      productTypeId: 'kSByoE6FetnPs5Byk3a9Zx'
      productTagIds: ['kSByoE6FetnPs5Byk3a9Zx']
      media:
      - url: 'https://and-period.jp/thumbnail01.png'
        isThumbnail: true
        images:
        - url: 'https://and-period.jp/thumbnail_240.png'
          size: 1
        - url: 'https://and-period.jp/thumbnail_675.png'
          size: 2
        - url: 'https://and-period.jp/thumbnail_900.png'
          size: 3
      - url: 'https://and-period.jp/thumbnail02.png'
        isThumbnail: false
        images: []
      price: 2500
      inventory: 30
      weight: 2.5
      itemUnit: '袋'
      itemDescription: '1袋あたり2.5kgのじゃがいも'
      deliveryType: 1
      recommendedPoint1: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint2: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint3: 'シャリシャリほろ苦がクセになる！'
      expirationDate: 7
      storageMethodType: 1
      box60Rate: 80
      box80Rate: 50
      box100Rate: 40
      originPrefecture: '東京都'
      originCity: '彦根市'
      startAt: 1640962800
      endAt: 1640962800
    coordinator:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      storeName: '&.農園'
      profile: '紹介文です。'
      productTypes: ['kSByoE6FetnPs5Byk3a9Zx']
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      thumbnails:
      - url: 'https://and-period.jp/thumbnail_240.png'
        size: 1
      - url: 'https://and-period.jp/thumbnail_675.png'
        size: 2
      - url: 'https://and-period.jp/thumbnail_900.png'
        size: 3
      headerUrl: 'https://and-period.jp/header.png'
      headers:
      - url: 'https://and-period.jp/header_240.png'
        size: 1
      - url: 'https://and-period.jp/header_675.png'
        size: 2
      - url: 'https://and-period.jp/header_900.png'
        size: 3
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
    producer:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      username: '&.農園'
      profile: '紹介文です。'
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      thumbnails:
      - url: 'https://and-period.jp/thumbnail_240.png'
        size: 1
      - url: 'https://and-period.jp/thumbnail_675.png'
        size: 2
      - url: 'https://and-period.jp/thumbnail_900.png'
        size: 3
      headerUrl: 'https://and-period.jp/header.png'
      headers:
      - url: 'https://and-period.jp/header_240.png'
        size: 1
      - url: 'https://and-period.jp/header_675.png'
        size: 2
      - url: 'https://and-period.jp/header_900.png'
        size: 3
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
    category:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '野菜'
    productType:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: 'じゃがいも'
      iconUrl: 'https://and-period.jp/icon.png'
      icons:
      - url: 'https://and-period.jp/icon_240.png'
        size: 1
      - url: 'https://and-period.jp/icon_675.png'
        size: 2
      - url: 'https://and-period.jp/icon_900.png'
        size: 3
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
    productTags:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '贈答品'
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '有機栽培認証'
productsResponse:
  type: object
  properties:
    products:
      type: array
      description: 商品一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/product'
    coordinators:
      type: array
      description: コーディネータ一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/coordinator'
    producers:
      type: array
      description: 生産者一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/producer'
    categories:
      type: array
      description: 商品種別一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/category'
    productTypes:
      type: array
      description: 品目一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/productType'
    productTags:
      type: array
      description: 商品タグ一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/productTag'
    total:
      type: integer
      format: int64
      description: 合計数
  required:
  - products
  - coordinators
  - producers
  - categories
  - productTypes
  - productTags
  - total
  example:
    products:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '新鮮なじゃがいも'
      description: '新鮮なじゃがいもをお届けします。'
      status: 2
      producerId: 'kSByoE6FetnPs5Byk3a9Zx'
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      productTypeId: 'kSByoE6FetnPs5Byk3a9Zx'
      productTagIds: ['kSByoE6FetnPs5Byk3a9Zx']
      media:
      - url: 'https://and-period.jp/thumbnail01.png'
        isThumbnail: true
        images:
        - url: 'https://and-period.jp/thumbnail_240.png'
          size: 1
        - url: 'https://and-period.jp/thumbnail_675.png'
          size: 2
        - url: 'https://and-period.jp/thumbnail_900.png'
          size: 3
      - url: 'https://and-period.jp/thumbnail02.png'
        isThumbnail: false
        images: []
      price: 2500
      inventory: 30
      weight: 2.5
      itemUnit: '袋'
      itemDescription: '1袋あたり2.5kgのじゃがいも'
      deliveryType: 1
      recommendedPoint1: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint2: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint3: 'シャリシャリほろ苦がクセになる！'
      expirationDate: 7
      storageMethodType: 1
      box60Rate: 80
      box80Rate: 50
      box100Rate: 40
      originPrefecture: '東京都'
      originCity: '彦根市'
      startAt: 1640962800
      endAt: 1640962800
    coordinators:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      marcheName: '&.マルシェ'
      storeName: '&.農園'
      profile: '紹介文です。'
      productTypeIds: ['kSByoE6FetnPs5Byk3a9Zx']
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      thumbnails:
      - url: 'https://and-period.jp/thumbnail_240.png'
        size: 1
      - url: 'https://and-period.jp/thumbnail_675.png'
        size: 2
      - url: 'https://and-period.jp/thumbnail_900.png'
        size: 3
      headerUrl: 'https://and-period.jp/header.png'
      headers:
      - url: 'https://and-period.jp/header_240.png'
        size: 1
      - url: 'https://and-period.jp/header_675.png'
        size: 2
      - url: 'https://and-period.jp/header_900.png'
        size: 3
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
    producers:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      username: '&.農園'
      profile: '紹介文です。'
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      thumbnails:
      - url: 'https://and-period.jp/thumbnail_240.png'
        size: 1
      - url: 'https://and-period.jp/thumbnail_675.png'
        size: 2
      - url: 'https://and-period.jp/thumbnail_900.png'
        size: 3
      headerUrl: 'https://and-period.jp/header.png'
      headers:
      - url: 'https://and-period.jp/header_240.png'
        size: 1
      - url: 'https://and-period.jp/header_675.png'
        size: 2
      - url: 'https://and-period.jp/header_900.png'
        size: 3
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
    categories:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '野菜'
    productTypes:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: 'じゃがいも'
      iconUrl: 'https://and-period.jp/icon.png'
      icons:
      - url: 'https://and-period.jp/icon_240.png'
        size: 1
      - url: 'https://and-period.jp/icon_675.png'
        size: 2
      - url: 'https://and-period.jp/icon_900.png'
        size: 3
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
    productTags:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '贈答品'
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '有機栽培認証'
    total: 1
