producerResponse:
  type: object
  properties:
    producer:
      $ref: './../../../openapi.yaml#/components/schemas/producer'
    lives:
      type: array
      description: 開催中・開催予定のマルシェ一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/liveSummary'
    archives:
      type: array
      description: 過去のマルシェ一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/archiveSummary'
    products:
      type: array
      description: 商品一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/product'
  required:
  - producer
  - lives
  - archives
  - products
  example:
    producer:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      username: '&.農園'
      profile: '紹介文です。'
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
      prefecture: '東京都'
      city: '千代田区'
    lives:
    - scheduleId: 'kSByoE6FetnPs5Byk3a9Zx'
      status: 2
      title: '&.マルシェ'
      thumbnailUrl: 'https://example.com/thumbnail.png'
      startAt: 1640962800
      endAt: 1640962800
      products:
      - id: 'kSByoE6FetnPs5Byk3a9Zx'
        title: '芽が出たじゃがいも'
        price: 1980
        inventory: 30
        thumbnailUrl: 'https://example.com/thumbnail.png'
    archives:
    - scheduleId: 'kSByoE6FetnPs5Byk3a9Zx'
      title: '&.マルシェ'
      thumbnailUrl: 'https://example.com/thumbnail.png'
    products:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '新鮮なじゃがいも'
      description: '新鮮なじゃがいもをお届けします。'
      status: 2
      producerId: 'kSByoE6FetnPs5Byk3a9Zx'
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      productTypeId: 'kSByoE6FetnPs5Byk3a9Zx'
      productTagIds: ['kSByoE6FetnPs5Byk3a9Zx']
      media:
      - url: 'https://and-period.jp/thumbnail01.png'
        isThumbnail: true
      - url: 'https://and-period.jp/thumbnail02.png'
        isThumbnail: false
      price: 2500
      inventory: 30
      weight: 2.5
      itemUnit: '袋'
      itemDescription: '1袋あたり2.5kgのじゃがいも'
      deliveryType: 1
      recommendedPoint1: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint2: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint3: 'シャリシャリほろ苦がクセになる！'
      expirationDate: 7
      storageMethodType: 1
      box60Rate: 80
      box80Rate: 50
      box100Rate: 40
      originPrefecture: '東京都'
      originCity: '彦根市'
      startAt: 1640962800
      endAt: 1640962800
producersResponse:
  type: object
  properties:
    producers:
      type: array
      description: 生産者一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/producer'
    total:
      type: integer
      format: int64
      description: 合計数
  required:
  - producers
  - total
  example:
    producers:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      username: '&.農園'
      profile: '紹介文です。'
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
      prefecture: '東京都'
      city: '千代田区'
  total: 1
