name: setup golang
description: 'Golangのセットアップ'

inputs:
  working-directory:
    description: '作業ディレクトリ'
    required: false
    default: '.'
  service:
    description: 'サービス名'
    required: true
    default: 'backend'

runs:
  using: composite
  steps:
  - name: Setup Golang
    uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
    with:
      go-version-file: ${{ inputs.working-directory }}/go.mod
      cache: false

  - name: Cache go modules and build cache
    id: modules-cache
    uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    with:
      path: |
        ~/.cache/go-build
        ~/go/pkg/mod
      key: ${{ inputs.service }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      restore-keys: |
        ${{ inputs.service }}-${{ runner.os }}-go-

  - name: Cache go test results
    uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    with:
      path: |
        ~/.cache/go-build
      key: ${{ inputs.service }}-${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/*.go') }}
      restore-keys: |
        ${{ inputs.service }}-${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}-
        ${{ inputs.service }}-${{ runner.os }}-go-test-

  - name: Download modules
    if: steps.modules-cache.outputs.cache-hit != 'true'
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: go mod download

  - name: Install tools
    if: steps.modules-cache.outputs.cache-hit != 'true'
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: go get tool

  - name: Generate
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: go generate ./...
