name: setup golang
description: 'Golangのセットアップ'

inputs:
  working-directory:
    description: '作業ディレクトリ'
    required: false
    default: '.'

runs:
  using: composite
  steps:
  - name: Setup Golang
    uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
    with:
      go-version-file: ${{ inputs.working-directory }}/go.mod
      cache: false

  - name: Cache Modules
    uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    with:
      path: |
        ~/go/pkg/mod
      key: ${{ runner.os }}-go-${{ hashFiles(format('{0}/go.mod', inputs.working-directory), format('{0}/go.sum', inputs.working-directory)) }}
      restore-keys: |
        ${{ runner.os }}-go-${{ hashFiles(format('{0}/go.mod', inputs.working-directory), format('{0}/go.sum', inputs.working-directory)) }}
        ${{ runner.os }}-go-

  - name: Download modules
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: go mod download

  - name: Install tools
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: go get tool

  - name: Generate
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: go generate ./...
