name: setup golang
description: 'Golangのセットアップ'

inputs:
  working-directory:
    description: '作業ディレクトリ'
    required: false
    default: '.'
  service:
    description: 'サービス名'
    required: true
    default: 'backend'

runs:
  using: composite
  steps:
  - name: Golang Version
    id: set-version
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      GO_VERSION=$(cat .tool-versions | grep -E '^golang [1-9.]+$' | awk '{print substr($0, index($0, " ") + 1)}')
      echo "go-version=${GO_VERSION}" >> $GITHUB_OUTPUT

  - name: Setup Golang
    uses: actions/setup-go@v5
    with:
      go-version: ${{ steps.set-version.outputs.go-version }}

  - name: Cache go modules
    id: modules-cache
    uses: actions/cache@v4
    with:
      path: |
        ~/.cache/go-build
        ~/go/pkg/mod
      key: ${{ inputs.service }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

  - name: Download modules
    if: steps.modules-cache.outputs.cache-hit != 'true'
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: go mod download
