name: setup golang
description: 'Golangのセットアップ'

inputs:
  working-directory:
    description: '作業ディレクトリ'
    required: false
    default: '.'
  service:
    description: 'サービス名'
    required: true
    default: 'backend'

runs:
  using: composite
  steps:
  - name: Setup Golang
    uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
    with:
      go-version-file: ${{ inputs.working-directory }}/go.mod
      cache: true
      cache-dependency-path: ${{ inputs.working-directory }}/go.sum
    env:
      GOCACHE: /home/runner/.cache/go-build

  - name: Cache go build cache
    id: build-cache
    uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
    with:
      path: |
        /home/runner/.cache/go-build
      key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/*.go') }}
      restore-keys: |
        ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}-
        ${{ runner.os }}-go-build-


  - name: Download modules
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: |
      go mod download
      go mod tidy
    env:
      GOCACHE: /home/runner/.cache/go-build

  - name: Install tools
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: go get tool
    env:
      GOCACHE: /home/runner/.cache/go-build

  - name: Generate
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: go generate ./...
    env:
      GOCACHE: /home/runner/.cache/go-build
