productResponse:
  type: object
  properties:
    product:
      $ref: './../../../openapi.yaml#/components/schemas/product'
    coordinator:
      $ref: './../../../openapi.yaml#/components/schemas/coordinator'
    producer:
      $ref: './../../../openapi.yaml#/components/schemas/producer'
    category:
      $ref: './../../../openapi.yaml#/components/schemas/category'
    productType:
      $ref: './../../../openapi.yaml#/components/schemas/productType'
    productTags:
      type: array
      description: 商品タグ一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/productTag'
  required:
  - product
  - coordinator
  - producer
  - category
  - productType
  - productTags
  example:
    product:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '新鮮なじゃがいも'
      description: '新鮮なじゃがいもをお届けします。'
      public: true
      status: 2
      producerId: 'kSByoE6FetnPs5Byk3a9Zx'
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      productTypeId: 'kSByoE6FetnPs5Byk3a9Zx'
      productTagIds: ['kSByoE6FetnPs5Byk3a9Zx']
      media:
      - url: 'https://and-period.jp/thumbnail01.png'
        isThumbnail: true
      - url: 'https://and-period.jp/thumbnail02.png'
        isThumbnail: false
      price: 2500
      cost: 200
      inventory: 30
      weight: 2.5
      itemUnit: '袋'
      itemDescription: '1袋あたり2.5kgのじゃがいも'
      deliveryType: 1
      recommendedPoint1: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint2: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint3: 'シャリシャリほろ苦がクセになる！'
      expirationDate: 7
      storageMethodType: 1
      box60Rate: 80
      box80Rate: 50
      box100Rate: 40
      originprefectureCode: 13
      originCity: '彦根市'
      startAt: 1640962800
      endAt: 1640962800
      createdAt: 1640962800
      updatedAt: 1640962800
    coordinator:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      status: 2
      lastname: '&.'
      firstname: '管理者'
      lastnameKana: 'あんどどっと'
      firstnameKana: 'かんりしゃ'
      storeName: '&.農園'
      email: 'test-user@and-period.jp'
      phoneNumber: '+819012345678'
      postalCode: '1000014'
      prefectureCode: 13
      city: '千代田区'
      addressLine1: '永田町1-7-1'
      addressLine2: ''
      profile: '紹介文です。'
      productTypes: ['kSByoE6FetnPs5Byk3a9Zx']
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      bonusVideoUrl: 'https://and-period.jp/bonus.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
      createdAt: 1640962800
      updatedAt: 1640962800
    producer:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      status: 2
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      lastname: '&.'
      firstname: '管理者'
      lastnameKana: 'あんどどっと'
      firstnameKana: 'かんりしゃ'
      username: '&.農園'
      email: 'test-user@and-period.jp'
      phoneNumber: '+819012345678'
      postalCode: '1000014'
      prefectureCode: 13
      city: '千代田区'
      addressLine1: '永田町1-7-1'
      addressLine2: ''
      profile: '紹介文です。'
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      bonusVideoUrl: 'https://and-period.jp/bonus.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
      createdAt: 1640962800
      updatedAt: 1640962800
    category:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '野菜'
      createdAt: 1640962800
      updatedAt: 1640962800
    productType:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: 'じゃがいも'
      iconUrl: 'https://and-period.jp/icon.png'
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      createdAt: 1640962800
      updatedAt: 1640962800
    productTags:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '贈答品'
      createdAt: 1640962800
      updatedAt: 1640962800
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '有機栽培認証'
      createdAt: 1640962800
      updatedAt: 1640962800
productsResponse:
  type: object
  properties:
    products:
      type: array
      description: 商品一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/product'
    coordinators:
      type: array
      description: コーディネータ一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/coordinator'
    producers:
      type: array
      description: 生産者一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/producer'
    categories:
      type: array
      description: 商品種別一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/category'
    productTypes:
      type: array
      description: 品目一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/productType'
    productTags:
      type: array
      description: 商品タグ一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/productTag'
    total:
      type: integer
      format: int64
      description: 合計数
  required:
  - products
  - coordinators
  - producers
  - categories
  - productTypes
  - productTags
  - total
  example:
    products:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '新鮮なじゃがいも'
      description: '新鮮なじゃがいもをお届けします。'
      public: true
      status: 2
      producerId: 'kSByoE6FetnPs5Byk3a9Zx'
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      productTypeId: 'kSByoE6FetnPs5Byk3a9Zx'
      productTagIds: ['kSByoE6FetnPs5Byk3a9Zx']
      media:
      - url: 'https://and-period.jp/thumbnail01.png'
        isThumbnail: true
      - url: 'https://and-period.jp/thumbnail02.png'
        isThumbnail: false
      price: 2500
      cost: 200
      inventory: 30
      weight: 2.5
      itemUnit: '袋'
      itemDescription: '1袋あたり2.5kgのじゃがいも'
      deliveryType: 1
      recommendedPoint1: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint2: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint3: 'シャリシャリほろ苦がクセになる！'
      expirationDate: 7
      storageMethodType: 1
      box60Rate: 80
      box80Rate: 50
      box100Rate: 40
      originprefectureCode: 13
      originCity: '彦根市'
      startAt: 1640962800
      endAt: 1640962800
      createdAt: 1640962800
      updatedAt: 1640962800
    coordinators:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      status: 2
      lastname: '&.'
      firstname: '管理者'
      lastnameKana: 'あんどどっと'
      firstnameKana: 'かんりしゃ'
      marcheName: '&.マルシェ'
      storeName: '&.農園'
      email: 'test-user@and-period.jp'
      phoneNumber: '+819012345678'
      postalCode: '1000014'
      prefectureCode: 13
      city: '千代田区'
      addressLine1: '永田町1-7-1'
      addressLine2: ''
      profile: '紹介文です。'
      productTypeIds: ['kSByoE6FetnPs5Byk3a9Zx']
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      bonusVideoUrl: 'https://and-period.jp/bonus.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
      producerTotal: 0
      createdAt: 1640962800
      updatedAt: 1640962800
    producers:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      status: 2
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      lastname: '&.'
      firstname: '管理者'
      lastnameKana: 'あんどどっと'
      firstnameKana: 'かんりしゃ'
      username: '&.農園'
      email: 'test-user@and-period.jp'
      phoneNumber: '+819012345678'
      postalCode: '1000014'
      prefectureCode: 13
      city: '千代田区'
      addressLine1: '永田町1-7-1'
      addressLine2: ''
      profile: '紹介文です。'
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      bonusVideoUrl: 'https://and-period.jp/bonus.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
      createdAt: 1640962800
      updatedAt: 1640962800
    categories:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '野菜'
      createdAt: 1640962800
      updatedAt: 1640962800
    productTypes:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: 'じゃがいも'
      iconUrl: 'https://and-period.jp/icon.png'
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      createdAt: 1640962800
      updatedAt: 1640962800
    productTags:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '贈答品'
      createdAt: 1640962800
      updatedAt: 1640962800
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '有機栽培認証'
      createdAt: 1640962800
      updatedAt: 1640962800
    total: 1
