createProducerRequest:
  type: object
  properties:
    lastname:
      type: string
      description: 姓(16文字まで)
    firstname:
      type: string
      description: 名(16文字まで)
    lastnameKana:
      type: string
      description: 姓(かな)(ひらがな,32文字まで)
    firstnameKana:
      type: string
      description: 名(かな)(ひらがな,32文字まで)
    storeName:
      type: string
      description: 店舗名(64文字まで)
    thumbnailUrl:
      type: string
      description: サムネイルURL
    headerUrl:
      type: string
      description: ヘッダー画像URL
    email:
      type: string
      format: email
      description: メールアドレス
    phoneNumber:
      type: string
      description: 電話番号 (国際番号 + 電話番号)
    postalCode:
      type: string
      description: 郵便番号(ハイフンなし)
    prefecture:
      type: string
      description: 都道府県(32文字まで)
    city:
      type: string
      description: 市区町村(32文字まで)
    addressLine1:
      type: string
      description: 町名・番地(64文字まで)
    addressLine2:
      type: string
      description: ビル名・号室など(64文字まで)
  required:
  - lastname
  - firstname
  - lastnameKana
  - firstnameKana
  - storeName
  - email
  - phoneNumber
  - postalCode
  - prefecture
  - city
  - addressLine1
  - addressLine2
  example:
    lastname: '&.'
    firstname: '管理者'
    lastnameKana: 'あんどどっと'
    firstnameKana: 'かんりしゃ'
    storeName: '&.農園'
    thumbnailUrl: 'https://and-period.jp/thumbnail.png'
    headerUrl: 'https://and-period.jp/header.png'
    email: 'test-user@and-period.jp'
    phoneNumber: '+819012345678'
    postalCode: '1000014'
    prefecture: '東京都'
    city: '千代田区'
    addressLine1: '永田町1-7-1'
    addressLine2: ''
updateProducerRequest:
  type: object
  properties:
    lastname:
      type: string
      description: 姓(16文字まで)
    firstname:
      type: string
      description: 名(16文字まで)
    lastnameKana:
      type: string
      description: 姓(かな)(ひらがな,32文字まで)
    firstnameKana:
      type: string
      description: 名(かな)(ひらがな,32文字まで)
    storeName:
      type: string
      description: 店舗名(64文字まで)
    thumbnailUrl:
      type: string
      description: サムネイルURL
    headerUrl:
      type: string
      description: ヘッダー画像URL
    phoneNumber:
      type: string
      description: 電話番号 (国際番号 + 電話番号)
    postalCode:
      type: string
      description: 郵便番号(ハイフンなし)
    prefecture:
      type: string
      description: 都道府県(32文字まで)
    city:
      type: string
      description: 市区町村(32文字まで)
    addressLine1:
      type: string
      description: 町名・番地(64文字まで)
    addressLine2:
      type: string
      description: ビル名・号室など(64文字まで)
  required:
  - lastname
  - firstname
  - lastnameKana
  - firstnameKana
  - storeName
  - phoneNumber
  - postalCode
  - prefecture
  - city
  - addressLine1
  - addressLine2
  example:
    lastname: '&.'
    firstname: '管理者'
    lastnameKana: 'あんどどっと'
    firstnameKana: 'かんりしゃ'
    storeName: '&.農園'
    thumbnailUrl: 'https://and-period.jp/thumbnail.png'
    headerUrl: 'https://and-period.jp/header.png'
    phoneNumber: '+819012345678'
    postalCode: '1000014'
    prefecture: '東京都'
    city: '千代田区'
    addressLine1: '永田町1-7-1'
    addressLine2: ''
updateProducerEmailRequest:
  type: object
  properties:
    email:
      type: string
      format: email
      description: メールアドレス
  required:
  - email
  example:
    email: 'test-user@and-period.jp'
relatedProducerRequest:
  type: object
  properties:
    coordinatorId:
      type: string
      description: 関連付ける仲介者ID
