createProductTypeRequest:
  type: object
  properties:
    name:
      type: string
      description: 品目名(32文字まで)
    iconUrl:
      type: string
      description: アイコンURL
  required:
  - name
  - iconUrl
  example:
    name: 'じゃがいも'
    iconUrl: 'https://and-period.jp/icon.png'
updateProductTypeRequest:
  type: object
  properties:
    name:
      type: string
      description: 品目名(32文字まで)
    iconUrl:
      type: string
      description: アイコンURL
  required:
  - name
  - iconUrl
  example:
    name: 'じゃがいも'
    iconUrl: 'https://and-period.jp/icon.png'
