productTypeResponse:
  type: object
  properties:
    productType:
      $ref: './../../../openapi.yaml#/components/schemas/productType'
    category:
      $ref: './../../../openapi.yaml#/components/schemas/category'
  required:
  - productType
  - category
  example:
    productType:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: 'じゃがいも'
      iconUrl: 'https://and-period.jp/icon.png'
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      createdAt: 1640962800
      updatedAt: 1640962800
    category:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '野菜'
      createdAt: 1640962800
      updatedAt: 1640962800
productTypesResponse:
  type: object
  properties:
    productTypes:
      type: array
      description: 品目一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/productType'
    categories:
      type: array
      description: 商品種別一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/category'
    total:
      type: integer
      format: int64
      description: 合計数
  required:
  - productTypes
  - categories
  - total
  example:
    productTypes:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: 'じゃがいも'
      iconUrl: 'https://and-period.jp/icon.png'
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      createdAt: 1640962800
      updatedAt: 1640962800
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: 'りんご'
      iconUrl: 'https://and-period.jp/icon.png'
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      createdAt: 1640962800
      updatedAt: 1640962800
    categories:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '野菜'
      createdAt: 1640962800
      updatedAt: 1640962800
    total: 2
