createProductTypeRequest:
  type: object
  properties:
    name:
      type: string
      description: 品目名(32文字まで)
  required:
  - name
  example:
    name: 'じゃがいも'
updateProductTypeRequest:
  type: object
  properties:
    name:
      type: string
      description: 品目名(32文字まで)
  required:
  - name
  example:
    name: 'じゃがいも'
