productTagResponse:
  type: object
  properties:
    productTag:
      $ref: './../../../openapi.yaml#/components/schemas/productTag'
  required:
  - productTag
  example:
    productTag:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '贈答品'
      createdAt: 1640962800
      updatedAt: 1640962800
productTagsResponse:
  type: object
  properties:
    productTags:
      type: array
      description: 品目一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/productTag'
    total:
      type: integer
      format: int64
      description: 合計数
  required:
  - productTags
  - total
  example:
    productTags:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '贈答品'
      createdAt: 1640962800
      updatedAt: 1640962800
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '有機栽培認証'
      createdAt: 1640962800
      updatedAt: 1640962800
    total: 2
