productTypeResponse:
  type: object
  properties:
    id:
      type: string
      description: 品目ID
    name:
      type: string
      description: 品目名
    iconUrl:
      type: string
      description: アイコンURL
    icons:
      type: array
      description: リサイズ済みアイコンURL一覧
      items:
        type: object
        properties:
          url:
            type: string
            description: リサイズ済みアイコンURL
          size:
            type: integer
            format: int32
            description: 画像サイズ(1:240px,2:675px,3:900px)
        required:
        - url
        - size
    categoryId:
      type: string
      description: 商品種別ID
    categoryName:
      type: string
      description: 商品種別名
    createdAt:
      type: integer
      format: int64
      description: 登録日時 (unixtime)
    updatedAt:
      type: integer
      format: int64
      description: 更新日時 (unixtime)
  required:
  - id
  - name
  - iconUrl
  - icons
  - categoryId
  - categoryName
  - createdAt
  - updatedAt
  example:
    id: 'kSByoE6FetnPs5Byk3a9Zx'
    name: 'じゃがいも'
    iconUrl: 'https://and-period.jp/icon.png'
    icons:
    - url: 'https://and-period.jp/icon_240.png'
      size: 1
    - url: 'https://and-period.jp/icon_675.png'
      size: 2
    - url: 'https://and-period.jp/icon_900.png'
      size: 3
    categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
    categoryName: '野菜'
    createdAt: 1640962800
    updatedAt: 1640962800
productTypesResponse:
  type: object
  properties:
    productTypes:
      type: array
      description: 品目一覧
      items:
        type: object
        properties:
          id:
            type: string
            description: 品目ID
          name:
            type: string
            description: 品目名
          iconUrl:
            type: string
            description: アイコンURL
          icons:
            type: array
            description: リサイズ済みアイコンURL一覧
            items:
              type: object
              properties:
                url:
                  type: string
                  description: リサイズ済みアイコンURL
                size:
                  type: integer
                  format: int32
                  description: 画像サイズ(1:240px,2:675px,3:900px)
              required:
              - url
              - size
          categoryId:
            type: string
            description: 商品種別ID
          categoryName:
            type: string
            description: 商品種別名
          createdAt:
            type: integer
            format: int64
            description: 登録日時 (unixtime)
          updatedAt:
            type: integer
            format: int64
            description: 更新日時 (unixtime)
        required:
        - id
        - name
        - iconUrl
        - icons
        - categoryId
        - categoryName
        - createdAt
        - updatedAt
    total:
      type: integer
      format: int64
      description: 合計数
  required:
  - productTypes
  - total
  example:
    productTypes:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: 'じゃがいも'
      iconUrl: 'https://and-period.jp/icon.png'
      icons:
      - url: 'https://and-period.jp/icon_240.png'
        size: 1
      - url: 'https://and-period.jp/icon_675.png'
        size: 2
      - url: 'https://and-period.jp/icon_900.png'
        size: 3
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      categoryName: '野菜'
      createdAt: 1640962800
      updatedAt: 1640962800
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: 'りんご'
      iconUrl: 'https://and-period.jp/icon.png'
      icons: []
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      categoryName: '果物'
      createdAt: 1640962800
      updatedAt: 1640962800
    total: 2
