createProductRequest:
  type: object
  properties:
    name:
      type: string
      description: 商品名(128文字まで)
    description:
      type: string
      description: 商品説明(20000文字まで)
    public:
      type: boolean
      description: 公開フラグ
    coordinatorId:
      type: string
      description: コーディネータID
    producerId:
      type: string
      description: 生産者ID
    productTypeId:
      type: string
      description: 品目ID
    productTagIds:
      type: array
      description: 商品タグ一覧
      items:
        type: string
        description: 商品タグID
    media:
      type: array
      description: メディア一覧(8つまで)
      items:
        type: object
        properties:
          url:
            type: string
            description: メディアURL
          isThumbnail:
            type: boolean
            description: サムネイルとして使用(1つまで)
        required:
        - url
        - isThumbnail
    price:
      type: integer
      format: int64
      description: 販売価格(税込:0以上)
    cost:
      type: integer
      format: int64
      description: 原価(税込:0以上)
    inventory:
      type: integer
      format: int64
      description: 在庫数(0以上)
    weight:
      type: number
      format: double
      description: 重量(0以上,kg単位:少数第1位まで)
    itemUnit:
      type: string
      description: 数量単位(16文字まで)
    itemDescription:
      type: string
      description: 数量単位説明(64文字まで)
    deliveryType:
      $ref: './../../../openapi.yaml#/components/schemas/deliveryType'
    recommendedPoint1:
      type: string
      description: おすすめポイント1(128文字まで)
    recommendedPoint2:
      type: string
      description: おすすめポイント1(128文字まで)
    recommendedPoint3:
      type: string
      description: おすすめポイント1(128文字まで)
    expirationDate:
      type: integer
      format: int64
      description: 賞味期限(単位:日,0以上)
    storageMethodType:
      $ref: './../../../openapi.yaml#/components/schemas/storageMethodType'
    box60Rate:
      type: integer
      format: int64
      description: 箱の占有率(サイズ:60)(0以上,100以下)
    box80Rate:
      type: integer
      format: int64
      description: 箱の占有率(サイズ:80)(0以上,100以下)
    box100Rate:
      type: integer
      format: int64
      description: 箱の占有率(サイズ:100)(0以上,100以下)
    originPrefectureCode:
      $ref: './../../../openapi.yaml#/components/schemas/prefecture'
      description: 原産地(都道府県)
    originCity:
      type: string
      description: 原産地(市区町村)(32文字まで)
    startAt:
      type: integer
      format: int64
      description: 販売開始日時 (unixtime)
    endAt:
      type: integer
      format: int64
      description: 販売終了日時 (unixtime)
  required:
  - name
  - description
  - public
  - coordinatorId
  - producerId
  - productTypeId
  - productTagIds
  - media
  - price
  - cost
  - inventory
  - weight
  - itemUnit
  - itemDescription
  - deliveryType
  - recommendedPoint1
  - recommendedPoint2
  - recommendedPoint3
  - expirationDate
  - storageMethodType
  - box60Rate
  - box80Rate
  - box100Rate
  - originPrefectureCode
  - originCity
  - startAt
  - endAt
  example:
    name: '新鮮なじゃがいも'
    description: '新鮮なじゃがいもをお届けします。'
    public: true
    coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
    producerId: 'kSByoE6FetnPs5Byk3a9Zx'
    productTypeId: 'kSByoE6FetnPs5Byk3a9Zx'
    productTagIds: ['kSByoE6FetnPs5Byk3a9Zx']
    media:
    - url: 'https://and-period.jp/thumbnail01.png'
      isThumbnail: true
    - url: 'https://and-period.jp/thumbnail02.png'
      isThumbnail: false
    price: 2500
    cost: 200
    inventory: 30
    weight: 2.5
    itemUnit: '袋'
    itemDescription: '1袋あたり2.5kgのじゃがいも'
    deliveryType: 1
    recommendedPoint1: 'シャリシャリほろ苦がクセになる！'
    recommendedPoint2: 'シャリシャリほろ苦がクセになる！'
    recommendedPoint3: 'シャリシャリほろ苦がクセになる！'
    expirationDate: 7
    storageMethodType: 1
    box60Rate: 80
    box80Rate: 50
    box100Rate: 40
    originprefectureCode: 13
    originCity: '彦根市'
    startAt: 1640962800
    endAt: 1640962800
updateProductRequest:
  type: object
  properties:
    name:
      type: string
      description: 商品名(128文字まで)
    description:
      type: string
      description: 商品説明(20000文字まで)
    public:
      type: boolean
      description: 公開フラグ
    productTypeId:
      type: string
      description: 品目ID
    productTagIds:
      type: array
      description: 商品タグ一覧
      items:
        type: string
        description: 商品タグID
    media:
      type: array
      description: メディア一覧(8つまで)
      items:
        type: object
        properties:
          url:
            type: string
            description: メディアURL
          isThumbnail:
            type: boolean
            description: サムネイルとして使用(1つまで)
        required:
        - url
        - isThumbnail
    price:
      type: integer
      format: int64
      description: 販売価格(税込:0以上)
    cost:
      type: integer
      format: int64
      description: 原価(税込:0以上)
    inventory:
      type: integer
      format: int64
      description: 在庫数(0以上)
    weight:
      type: number
      format: double
      description: 重量(0以上,kg単位:少数第1位まで)
    itemUnit:
      type: string
      description: 数量単位(16文字まで)
    itemDescription:
      type: string
      description: 数量単位説明(64文字まで)
    deliveryType:
      $ref: './../../../openapi.yaml#/components/schemas/deliveryType'
    recommendedPoint1:
      type: string
      description: おすすめポイント1(128文字まで)
    recommendedPoint2:
      type: string
      description: おすすめポイント1(128文字まで)
    recommendedPoint3:
      type: string
      description: おすすめポイント1(128文字まで)
    expirationDate:
      type: integer
      format: int64
      description: 賞味期限(単位:日,0以上)
    storageMethodType:
      $ref: './../../../openapi.yaml#/components/schemas/storageMethodType'
    box60Rate:
      type: integer
      format: int64
      description: 箱の占有率(サイズ:60)(0以上,100以下)
    box80Rate:
      type: integer
      format: int64
      description: 箱の占有率(サイズ:80)(0以上,100以下)
    box100Rate:
      type: integer
      format: int64
      description: 箱の占有率(サイズ:100)(0以上,100以下)
    originPrefectureCode:
      $ref: './../../../openapi.yaml#/components/schemas/prefecture'
    originCity:
      type: string
      description: 原産地(市区町村)(32文字まで)
    startAt:
      type: integer
      format: int64
      description: 販売開始日時 (unixtime)
    endAt:
      type: integer
      format: int64
      description: 販売終了日時 (unixtime)
  required:
  - name
  - description
  - public
  - productTypeId
  - productTagIds
  - media
  - price
  - cost
  - inventory
  - weight
  - itemUnit
  - itemDescription
  - deliveryType
  - recommendedPoint1
  - recommendedPoint2
  - recommendedPoint3
  - expirationDate
  - storageMethodType
  - box60Rate
  - box80Rate
  - box100Rate
  - originPrefectureCode
  - originCity
  - startAt
  - endAt
  example:
    name: '新鮮なじゃがいも'
    description: '新鮮なじゃがいもをお届けします。'
    public: true
    productTypeId: 'kSByoE6FetnPs5Byk3a9Zx'
    productTagIds: ['kSByoE6FetnPs5Byk3a9Zx']
    media:
    - url: 'https://and-period.jp/thumbnail01.png'
      isThumbnail: true
    - url: 'https://and-period.jp/thumbnail02.png'
      isThumbnail: false
    price: 2500
    cost: 200
    inventory: 30
    weight: 2.5
    itemUnit: '袋'
    itemDescription: '1袋あたり2.5kgのじゃがいも'
    deliveryType: 1
    recommendedPoint1: 'シャリシャリほろ苦がクセになる！'
    recommendedPoint2: 'シャリシャリほろ苦がクセになる！'
    recommendedPoint3: 'シャリシャリほろ苦がクセになる！'
    expirationDate: 7
    storageMethodType: 1
    box60Rate: 80
    box80Rate: 50
    box100Rate: 40
    originprefectureCode: 13
    originCity: '彦根市'
    startAt: 1640962800
    endAt: 1640962800
