producerResponse:
  type: object
  properties:
    producer:
      $ref: './../../../openapi.yaml#/components/schemas/producer'
    shops:
      type: array
      description: 店舗一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/shop'
    coordinators:
      type: array
      description: 担当コーディネータ一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/coordinator'
  required:
  - producer
  - shops
  - coordinators
  example:
    producer:
      id: 'kSByoE6FetnPs5Byk3a9Zx'
      status: 2
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      coordinatorName: '&.コーディネータ'
      lastname: '&.'
      firstname: '管理者'
      lastnameKana: 'あんどどっと'
      firstnameKana: 'かんりしゃ'
      username: '&.農園'
      email: 'test-user@and-period.jp'
      phoneNumber: '+819012345678'
      postalCode: '1000014'
      prefectureCode: 13
      city: '千代田区'
      addressLine1: '永田町1-7-1'
      addressLine2: ''
      profile: '紹介文です。'
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      bonusVideoUrl: 'https://and-period.jp/bonus.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
      createdAt: 1640962800
      updatedAt: 1640962800
    shops:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: 'テスト店舗'
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      producerIds: ['kSByoE6FetnPs5Byk3a9Zx']
      productTypeIds: ['kSByoE6FetnPs5Byk3a9Zx']
      businessDays: [1,2,3,4,5]
      createdAt: 1640962800
      updatedAt: 1640962800
    coordinators:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      status: 2
      lastname: '&.'
      firstname: '管理者'
      lastnameKana: 'あんどどっと'
      firstnameKana: 'かんりしゃ'
      storeName: '&.農園'
      email: 'test-user@and-period.jp'
      phoneNumber: '+819012345678'
      postalCode: '1000014'
      prefectureCode: 13
      city: '千代田区'
      addressLine1: '永田町1-7-1'
      addressLine2: ''
      profile: '紹介文です。'
      productTypes: ['kSByoE6FetnPs5Byk3a9Zx']
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      bonusVideoUrl: 'https://and-period.jp/bonus.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
      createdAt: 1640962800
      updatedAt: 1640962800
producersResponse:
  type: object
  properties:
    producers:
      type: array
      description: 生産者一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/producer'
    shops:
      type: array
      description: 店舗一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/shop'
    coordinators:
      type: array
      description: 担当コーディネータ一覧
      items:
        $ref: './../../../openapi.yaml#/components/schemas/coordinator'
    total:
      type: integer
      format: int64
      description: 合計数
  required:
  - producers
  - shops
  - coordinators
  - total
  example:
    producers:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      status: 2
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      coordinatorName: '&.コーディネータ'
      lastname: '&.'
      firstname: '管理者'
      lastnameKana: 'あんどどっと'
      firstnameKana: 'かんりしゃ'
      username: '&.農園'
      email: 'test-user@and-period.jp'
      phoneNumber: '+819012345678'
      postalCode: '1000014'
      prefectureCode: 13
      city: '千代田区'
      addressLine1: '永田町1-7-1'
      addressLine2: ''
      profile: '紹介文です。'
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      bonusVideoUrl: 'https://and-period.jp/bonus.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
      createdAt: 1640962800
      updatedAt: 1640962800
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      status: 2
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      coordinatorName: '&.コーディネータ'
      lastname: '&.'
      firstname: '管理者'
      lastnameKana: 'あんどどっと'
      firstnameKana: 'かんりしゃ'
      username: '&.農園'
      email: 'test-user@and-period.jp'
      phoneNumber: '+819012345678'
      postalCode: '1000014'
      prefectureCode: 13
      city: '千代田区'
      addressLine1: '永田町1-7-1'
      addressLine2: ''
      profile: '紹介文です。'
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      promotionVideoUrl: ''
      bonusVideoUrl: ''
      createdAt: 1640962800
      updatedAt: 1640962800
    shops:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: 'テスト店舗'
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      producerIds: ['kSByoE6FetnPs5Byk3a9Zx']
      productTypeIds: ['kSByoE6FetnPs5Byk3a9Zx']
      businessDays: [1,2,3,4,5]
      createdAt: 1640962800
      updatedAt: 1640962800
    coordinators:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      status: 2
      lastname: '&.'
      firstname: '管理者'
      lastnameKana: 'あんどどっと'
      firstnameKana: 'かんりしゃ'
      storeName: '&.農園'
      email: 'test-user@and-period.jp'
      phoneNumber: '+819012345678'
      postalCode: '1000014'
      prefectureCode: 13
      city: '千代田区'
      addressLine1: '永田町1-7-1'
      addressLine2: ''
      profile: '紹介文です。'
      productTypes: ['kSByoE6FetnPs5Byk3a9Zx']
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
      bonusVideoUrl: 'https://and-period.jp/bonus.mp4'
      instagramId: 'instagram-id'
      facebookId: 'facebook-id'
      createdAt: 1640962800
      updatedAt: 1640962800
    total: 2
