createProductTagRequest:
  type: object
  properties:
    name:
      type: string
      description: 商品タグ名(32文字まで)
  required:
  - name
  example:
    name: '贈答品'
updateProductTagRequest:
  type: object
  properties:
    name:
      type: string
      description: 商品タグ名(32文字まで)
  required:
  - name
  example:
    name: '贈答品'
