producerResponse:
  type: object
  properties:
    id:
      type: string
      description: 生産者ID
    coordinatorId:
      type: string
      description: 担当仲介者ID
    lastname:
      type: string
      description: 姓
    firstname:
      type: string
      description: 名
    lastnameKana:
      type: string
      description: 姓(かな)
    firstnameKana:
      type: string
      description: 名(かな)
    storeName:
      type: string
      description: 店舗名
    thumbnailUrl:
      type: string
      description: サムネイルURL
    headerUrl:
      type: string
      description: ヘッダー画像URL
    email:
      type: string
      description: メールアドレス
    phoneNumber:
      type: string
      description: 電話番号 (国際番号 + 電話番号)
    postalCode:
      type: string
      description: 郵便番号
    prefecture:
      type: string
      description: 都道府県
    city:
      type: string
      description: 市区町村
    addressLine1:
      type: string
      description: 町名・番地
    addressLine2:
      type: string
      description: ビル名・号室など
    createdAt:
      type: integer
      format: int64
      description: 登録日時 (unixtime)
    updatedAt:
      type: integer
      format: int64
      description: 更新日時 (unixtime)
  required:
  - id
  - coordinatorId
  - lastname
  - firstname
  - lastnameKana
  - firstnameKana
  - storeName
  - thumbnailUrl
  - headerUrl
  - email
  - phoneNumber
  - postalCode
  - prefecture
  - city
  - addressLine1
  - addressLine2
  - createdAt
  - updatedAt
  example:
    id: 'kSByoE6FetnPs5Byk3a9Zx'
    coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
    lastname: '&.'
    firstname: '管理者'
    lastnameKana: 'あんどどっと'
    firstnameKana: 'かんりしゃ'
    storeName: '&.農園'
    thumbnailUrl: 'https://and-period.jp/thumbnail.png'
    headerUrl: 'https://and-period.jp/header.png'
    email: 'test-user@and-period.jp'
    phoneNumber: '+819012345678'
    postalCode: '1000014'
    prefecture: '東京都'
    city: '千代田区'
    addressLine1: '永田町1-7-1'
    addressLine2: ''
    createdAt: 1640962800
    updatedAt: 1640962800
producersResponse:
  type: object
  properties:
    producers:
      type: array
      description: 生産者一覧
      items:
        type: object
        properties:
          id:
            type: string
            description: システム管理者ID
          coordinatorId:
            type: string
            description: 担当仲介者ID
          lastname:
            type: string
            description: 姓
          firstname:
            type: string
            description: 名
          lastnameKana:
            type: string
            description: 姓(かな)
          firstnameKana:
            type: string
            description: 名(かな)
          storeName:
            type: string
            description: 店舗名
          headerUrl:
            type: string
            description: ヘッダー画像URL
          thumbnailUrl:
            type: string
            description: サムネイルURL
          email:
            type: string
            description: メールアドレス
          phoneNumber:
            type: string
            description: 電話番号 (国際番号 + 電話番号)
          postalCode:
            type: string
            description: 郵便番号
          prefecture:
            type: string
            description: 都道府県
          city:
            type: string
            description: 市区町村
          addressLine1:
            type: string
            description: 町名・番地
          addressLine2:
            type: string
            description: ビル名・号室など
          createdAt:
            type: integer
            format: int64
            description: 登録日時 (unixtime)
          updatedAt:
            type: integer
            format: int64
            description: 更新日時 (unixtime)
        required:
        - id
        - coordinatorId
        - lastname
        - firstname
        - lastnameKana
        - firstnameKana
        - storeName
        - thumbnailUrl
        - headerUrl
        - email
        - phoneNumber
        - postalCode
        - prefecture
        - city
        - addressLine1
        - addressLine2
        - createdAt
        - updatedAt
    total:
      type: integer
      format: int64
      description: 合計数
  required:
  - producers
  - total
  example:
    producers:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      lastname: '&.'
      firstname: '管理者'
      lastnameKana: 'あんどどっと'
      firstnameKana: 'かんりしゃ'
      storeName: '&.農園'
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      email: 'test-user@and-period.jp'
      phoneNumber: '+819012345678'
      postalCode: '1000014'
      prefecture: '東京都'
      city: '千代田区'
      addressLine1: '永田町1-7-1'
      addressLine2: ''
      createdAt: 1640962800
      updatedAt: 1640962800
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
      lastname: '&.'
      firstname: '管理者'
      lastnameKana: 'あんどどっと'
      firstnameKana: 'かんりしゃ'
      storeName: '&.農園'
      thumbnailUrl: 'https://and-period.jp/thumbnail.png'
      headerUrl: 'https://and-period.jp/header.png'
      email: 'test-user@and-period.jp'
      phoneNumber: '+819012345678'
      postalCode: '1000014'
      prefecture: '東京都'
      city: '千代田区'
      addressLine1: '永田町1-7-1'
      addressLine2: ''
      createdAt: 1640962800
      updatedAt: 1640962800
    total: 2
