productResponse:
  type: object
  properties:
    id:
      type: string
      description: 商品ID
    name:
      type: string
      description: 商品名
    description:
      type: string
      description: 商品説明
    public:
      type: boolean
      description: 公開フラグ
    producerId:
      type: string
      description: 生産者ID
    producerName:
      type: string
      description: 生産者名
    categoryId:
      type: string
      description: 商品種別ID
    categoryName:
      type: string
      description: 商品種別名
    productTypeId:
      type: string
      description: 品目ID
    productTypeName:
      type: string
      description: 品目名
    productTypeIconUrl:
      type: string
      description: 品目アイコンURL
    productTypeIcons:
      type: array
      description: リサイズ済み品目アイコンURL一覧
      items:
        type: object
        properties:
          url:
            type: string
            description: リサイズ済み品目アイコンURL
          size:
            $ref: './../../../openapi.yaml#/components/schemas/imageSize'
        required:
        - url
        - size
    productTagIds:
      type: array
      description: 商品タグ一覧
      items:
        type: string
        description: 商品タグID
    media:
      type: array
      items:
        type: object
        properties:
          url:
            type: string
            description: メディアURL
          isThumbnail:
            type: boolean
            description: サムネイルとして使用(1つまで)
          images:
            type: array
            description: リサイズ済み画像URL一覧
            items:
              type: object
              properties:
                url:
                  type: string
                  description: リサイズ済み画像URL
                size:
                  $ref: './../../../openapi.yaml#/components/schemas/imageSize'
              required:
              - url
              - size
        required:
        - url
        - isThumbnail
        - images
    price:
      type: integer
      format: int64
      description: 販売価格
    cost:
      type: integer
      format: int64
      description: 原価
    inventory:
      type: integer
      format: int64
      description: 在庫数
    weight:
      type: number
      format: double
      description: 重量(kg:少数第1位まで)
    itemUnit:
      type: string
      description: 数量単位
    itemDescription:
      type: string
      description: 数量単位説明
    deliveryType:
      $ref: './../../../openapi.yaml#/components/schemas/deliveryType'
    recommendedPoint1:
      type: string
      description: おすすめポイント1(128文字まで)
    recommendedPoint2:
      type: string
      description: おすすめポイント2(128文字まで)
    recommendedPoint3:
      type: string
      description: おすすめポイント3(128文字まで)
    expirationDate:
      type: integer
      format: int64
      description: 賞味期限(単位:日)
    storageMethodType:
      $ref: './../../../openapi.yaml#/components/schemas/storageMethodType'
    box60Rate:
      type: integer
      format: int64
      description: 箱の占有率(サイズ:60)
    box80Rate:
      type: integer
      format: int64
      description: 箱の占有率(サイズ:80)
    box100Rate:
      type: integer
      format: int64
      description: 箱の占有率(サイズ:100)
    originPrefecture:
      $ref: './../../../openapi.yaml#/components/schemas/prefecture'
    originCity:
      type: string
      description: 原産地(市区町村)
    createdAt:
      type: integer
      format: int64
      description: 登録日時 (unixtime)
    updatedAt:
      type: integer
      format: int64
      description: 更新日時 (unixtime)
  required:
  - id
  - name
  - description
  - public
  - producerId
  - producerName
  - categoryId
  - categoryName
  - productTypeId
  - productTypeName
  - productTypeIconUrl
  - productTypeIcons
  - productTagIds
  - media
  - price
  - cost
  - inventory
  - weight
  - itemUnit
  - itemDescription
  - deliveryType
  - recommendedPoint1
  - recommendedPoint2
  - recommendedPoint3
  - expirationDate
  - storageMethodType
  - box60Rate
  - box80Rate
  - box100Rate
  - originPrefecture
  - originCity
  - createdAt
  - updatedAt
  example:
    id: 'kSByoE6FetnPs5Byk3a9Zx'
    name: '新鮮なじゃがいも'
    description: '新鮮なじゃがいもをお届けします。'
    public: true
    producerId: 'kSByoE6FetnPs5Byk3a9Zx'
    producerName: '&.農園'
    categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
    categoryName: '野菜'
    productTypeId: 'kSByoE6FetnPs5Byk3a9Zx'
    productTypeName: 'じゃがいも'
    productTypeIconUrl: 'https://and-period.jp/icon.png'
    productTypeIcons:
    - url: 'https://and-period.jp/icon_240.png'
      size: 1
    - url: 'https://and-period.jp/icon_675.png'
      size: 2
    - url: 'https://and-period.jp/icon_900.png'
      size: 3
    productTagIds: ['kSByoE6FetnPs5Byk3a9Zx']
    media:
    - url: 'https://and-period.jp/thumbnail01.png'
      isThumbnail: true
      images:
      - url: 'https://and-period.jp/thumbnail_240.png'
        size: 1
      - url: 'https://and-period.jp/thumbnail_675.png'
        size: 2
      - url: 'https://and-period.jp/thumbnail_900.png'
        size: 3
    - url: 'https://and-period.jp/thumbnail02.png'
      isThumbnail: false
      images: []
    price: 2500
    cost: 200
    inventory: 30
    weight: 2.5
    itemUnit: '袋'
    itemDescription: '1袋あたり2.5kgのじゃがいも'
    deliveryType: 1
    recommendedPoint1: 'シャリシャリほろ苦がクセになる！'
    recommendedPoint2: 'シャリシャリほろ苦がクセになる！'
    recommendedPoint3: 'シャリシャリほろ苦がクセになる！'
    expirationDate: 7
    storageMethodType: 1
    box60Rate: 80
    box80Rate: 50
    box100Rate: 40
    originPrefecture: 'tokyo'
    originCity: '彦根市'
    createdAt: 1640962800
    updatedAt: 1640962800
productsResponse:
  type: object
  properties:
    products:
      type: array
      description: 商品一覧
      items:
        type: object
        properties:
          id:
            type: string
            description: 商品ID
          name:
            type: string
            description: 商品名
          description:
            type: string
            description: 商品説明
          public:
            type: boolean
            description: 公開フラグ
          producerId:
            type: string
            description: 生産者ID
          producerName:
            type: string
            description: 生産者名
          categoryId:
            type: string
            description: 商品種別ID
          categoryName:
            type: string
            description: 商品種別名
          productTypeId:
            type: string
            description: 品目ID
          productTypeName:
            type: string
            description: 品目名
          productTypeIconUrl:
            type: string
            description: 品目アイコンURL
          productTypeIcons:
            type: array
            description: リサイズ済み品目アイコンURL一覧
            items:
              type: object
              properties:
                url:
                  type: string
                  description: リサイズ済み品目アイコンURL
                size:
                  $ref: './../../../openapi.yaml#/components/schemas/imageSize'
              required:
              - url
              - size
          productTagIds:
            type: array
            description: 商品タグ一覧
            items:
              type: string
              description: 商品タグID
          media:
            type: array
            items:
              type: object
              properties:
                url:
                  type: string
                  description: メディアURL
                isThumbnail:
                  type: boolean
                  description: サムネイルとして使用(1つまで)
                images:
                  type: array
                  description: リサイズ済み画像URL一覧
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                        description: リサイズ済み画像URL
                      size:
                        $ref: './../../../openapi.yaml#/components/schemas/imageSize'
                    required:
                    - url
                    - size
              required:
              - url
              - isThumbnail
              - images
          price:
            type: integer
            format: int64
            description: 販売価格
          cost:
            type: integer
            format: int64
            description: 原価
          inventory:
            type: integer
            format: int64
            description: 在庫数
          weight:
            type: number
            format: double
            description: 重量(kg:少数第1位まで)
          itemUnit:
            type: string
            description: 数量単位
          itemDescription:
            type: string
            description: 数量単位説明
          deliveryType:
            $ref: './../../../openapi.yaml#/components/schemas/deliveryType'
          recommendedPoint1:
            type: string
            description: おすすめポイント1(128文字まで)
          recommendedPoint2:
            type: string
            description: おすすめポイント2(128文字まで)
          recommendedPoint3:
            type: string
            description: おすすめポイント3(128文字まで)
          expirationDate:
            type: integer
            format: int64
            description: 賞味期限(単位:日)
          storageMethodType:
            $ref: './../../../openapi.yaml#/components/schemas/storageMethodType'
          box60Rate:
            type: integer
            format: int64
            description: 箱の占有率(サイズ:60)
          box80Rate:
            type: integer
            format: int64
            description: 箱の占有率(サイズ:80)
          box100Rate:
            type: integer
            format: int64
            description: 箱の占有率(サイズ:100)
          originPrefecture:
            $ref: './../../../openapi.yaml#/components/schemas/prefecture'
          originCity:
            type: string
            description: 原産地(市区町村)
          createdAt:
            type: integer
            format: int64
            description: 登録日時 (unixtime)
          updatedAt:
            type: integer
            format: int64
            description: 更新日時 (unixtime)
        required:
        - id
        - name
        - description
        - public
        - producerId
        - producerName
        - categoryId
        - categoryName
        - productTypeId
        - productTypeName
        - productTypeIconUrl
        - productTypeIcons
        - productTagIds
        - media
        - price
        - cost
        - inventory
        - weight
        - itemUnit
        - itemDescription
        - deliveryType
        - recommendedPoint1
        - recommendedPoint2
        - recommendedPoint3
        - expirationDate
        - storageMethodType
        - box60Rate
        - box80Rate
        - box100Rate
        - originPrefecture
        - originCity
        - createdAt
        - updatedAt
    total:
      type: integer
      format: int64
      description: 合計数
  required:
  - products
  - total
  example:
    products:
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '新鮮なじゃがいも'
      description: '新鮮なじゃがいもをお届けします。'
      public: true
      producerId: 'kSByoE6FetnPs5Byk3a9Zx'
      producerName: '&.農園'
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      categoryName: '野菜'
      productTypeId: 'kSByoE6FetnPs5Byk3a9Zx'
      productTypeName: 'じゃがいも'
      productTypeIconUrl: 'https://and-period.jp/icon.png'
      productTypeIcons:
      - url: 'https://and-period.jp/icon_240.png'
        size: 1
      - url: 'https://and-period.jp/icon_675.png'
        size: 2
      - url: 'https://and-period.jp/icon_900.png'
        size: 3
      productTagIds: ['kSByoE6FetnPs5Byk3a9Zx']
      media:
      - url: 'https://and-period.jp/thumbnail01.png'
        isThumbnail: true
        images:
        - url: 'https://and-period.jp/thumbnail_240.png'
          size: 1
        - url: 'https://and-period.jp/thumbnail_675.png'
          size: 2
        - url: 'https://and-period.jp/thumbnail_900.png'
          size: 3
      - url: 'https://and-period.jp/thumbnail02.png'
        isThumbnail: false
        images: []
      price: 2500
      cost: 200
      inventory: 30
      weight: 2.5
      itemUnit: '袋'
      itemDescription: '1袋あたり2.5kgのじゃがいも'
      deliveryType: 1
      recommendedPoint1: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint2: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint3: 'シャリシャリほろ苦がクセになる！'
      expirationDate: 7
      storageMethodType: 1
      box60Rate: 80
      box80Rate: 50
      box100Rate: 40
      originPrefecture: 'tokyo'
      originCity: '彦根市'
      createdAt: 1640962800
      updatedAt: 1640962800
    - id: 'kSByoE6FetnPs5Byk3a9Zx'
      name: '新鮮なじゃがいも'
      description: '新鮮なじゃがいもをお届けします。'
      public: true
      producerId: 'kSByoE6FetnPs5Byk3a9Zx'
      producerName: '&.農園'
      categoryId: 'kSByoE6FetnPs5Byk3a9Zx'
      categoryName: '野菜'
      productTypeId: 'kSByoE6FetnPs5Byk3a9Zx'
      productTypeName: 'じゃがいも'
      productTypeIconUrl: 'https://and-period.jp/icon.png'
      productTypeIcons: []
      productTagIds: ['kSByoE6FetnPs5Byk3a9Zx']
      media:
      - url: 'https://and-period.jp/thumbnail01.png'
        isThumbnail: true
        images: []
      - url: 'https://and-period.jp/thumbnail02.png'
        isThumbnail: false
        images: []
      price: 2500
      cost: 200
      inventory: 30
      weight: 2.5
      itemUnit: '袋'
      itemDescription: '1袋あたり2.5kgのじゃがいも'
      deliveryType: 1
      recommendedPoint1: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint2: 'シャリシャリほろ苦がクセになる！'
      recommendedPoint3: 'シャリシャリほろ苦がクセになる！'
      expirationDate: 7
      storageMethodType: 1
      box60Rate: 80
      box80Rate: 50
      box100Rate: 40
      originPrefecture: 'tokyo'
      originCity: '彦根市'
      createdAt: 1640962800
      updatedAt: 1640962800
