createProducerRequest:
  type: object
  properties:
    coordinatorId:
      type: string
      description: コーディネータID
    lastname:
      type: string
      description: 姓(16文字まで)
    firstname:
      type: string
      description: 名(16文字まで)
    lastnameKana:
      type: string
      description: 姓(かな)(ひらがな,32文字まで)
    firstnameKana:
      type: string
      description: 名(かな)(ひらがな,32文字まで)
    username:
      type: string
      description: 生産者名(64文字まで)
    email:
      type: string
      format: email
      description: メールアドレス
    phoneNumber:
      type: string
      description: 電話番号 (国際番号 + 電話番号)
    postalCode:
      type: string
      description: 郵便番号(ハイフンなし)
    prefectureCode:
      $ref: './../../../openapi.yaml#/components/schemas/prefecture'
    city:
      type: string
      description: 市区町村(32文字まで)
    addressLine1:
      type: string
      description: 町名・番地(64文字まで)
    addressLine2:
      type: string
      description: ビル名・号室など(64文字まで)
    profile:
      type: string
      description: プロフィール(2000文字まで)
    thumbnailUrl:
      type: string
      description: サムネイルURL
    headerUrl:
      type: string
      description: ヘッダー画像URL
    promotionVideoUrl:
      type: string
      description: 紹介動画URL
    bonusVideoUrl:
      type: string
      description: 購入者動画URL
    instagramId:
      type: string
      description: Instagramアカウント(30文字まで)
    facebookId:
      type: string
      description: Facebookアカウント(50文字まで)
  required:
  - coordinatorId
  - lastname
  - firstname
  - lastnameKana
  - firstnameKana
  - username
  - email
  - phoneNumber
  - postalCode
  - prefectureCode
  - city
  - addressLine1
  - addressLine2
  - profile
  - thumbnailUrl
  - headerUrl
  - promotionVideoUrl
  - bonusVideoUrl
  - instagramId
  - facebookId
  example:
    coordinatorId: 'kSByoE6FetnPs5Byk3a9Zx'
    lastname: '&.'
    firstname: '管理者'
    lastnameKana: 'あんどどっと'
    firstnameKana: 'かんりしゃ'
    username: '&.農園'
    email: 'test-user@and-period.jp'
    phoneNumber: '+819012345678'
    postalCode: '1000014'
    prefectureCode: 13
    city: '千代田区'
    addressLine1: '永田町1-7-1'
    addressLine2: ''
    profile: '紹介文です。'
    thumbnailUrl: 'https://and-period.jp/thumbnail.png'
    headerUrl: 'https://and-period.jp/header.png'
    promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
    bonusVideoUrl: 'https://and-period.jp/bonus.mp4'
    instagramId: 'instagram-id'
    facebookId: 'facebook-id'
updateProducerRequest:
  type: object
  properties:
    lastname:
      type: string
      description: 姓(16文字まで)
    firstname:
      type: string
      description: 名(16文字まで)
    lastnameKana:
      type: string
      description: 姓(かな)(ひらがな,32文字まで)
    firstnameKana:
      type: string
      description: 名(かな)(ひらがな,32文字まで)
    username:
      type: string
      description: 生産者名(64文字まで)
    email:
      type: string
      format: email
      description: メールアドレス
    phoneNumber:
      type: string
      description: 電話番号 (国際番号 + 電話番号)
    postalCode:
      type: string
      description: 郵便番号(ハイフンなし)
    prefectureCode:
      $ref: './../../../openapi.yaml#/components/schemas/prefecture'
    city:
      type: string
      description: 市区町村(32文字まで)
    addressLine1:
      type: string
      description: 町名・番地(64文字まで)
    addressLine2:
      type: string
      description: ビル名・号室など(64文字まで)
    profile:
      type: string
      description: プロフィール(2000文字まで)
    thumbnailUrl:
      type: string
      description: サムネイルURL
    headerUrl:
      type: string
      description: ヘッダー画像URL
    promotionVideoUrl:
      type: string
      description: 紹介動画URL
    bonusVideoUrl:
      type: string
      description: 購入者動画URL
    instagramId:
      type: string
      description: Instagramアカウント(30文字まで)
    facebookId:
      type: string
      description: Facebookアカウント(50文字まで)
  required:
  - lastname
  - firstname
  - lastnameKana
  - firstnameKana
  - username
  - email
  - phoneNumber
  - postalCode
  - prefectureCode
  - city
  - addressLine1
  - addressLine2
  - profile
  - thumbnailUrl
  - headerUrl
  - promotionVideoUrl
  - bonusVideoUrl
  - instagramId
  - facebookId
  example:
    lastname: '&.'
    firstname: '管理者'
    lastnameKana: 'あんどどっと'
    firstnameKana: 'かんりしゃ'
    username: '&.農園'
    email: 'test-user@and-period.jp'
    phoneNumber: '+819012345678'
    postalCode: '1000014'
    prefectureCode: 13
    city: '千代田区'
    addressLine1: '永田町1-7-1'
    addressLine2: ''
    profile: '紹介文です。'
    thumbnailUrl: 'https://and-period.jp/thumbnail.png'
    headerUrl: 'https://and-period.jp/header.png'
    promotionVideoUrl: 'https://and-period.jp/promotion.mp4'
    bonusVideoUrl: 'https://and-period.jp/bonus.mp4'
    instagramId: 'instagram-id'
    facebookId: 'facebook-id'
