/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * デフォルト設定の住所情報
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 住所ID
     * @type {string}
     * @memberof Address
     */
    addressId: string;
    /**
     * 町名・番地
     * @type {string}
     * @memberof Address
     */
    addressLine1: string;
    /**
     * ビル名・号室など
     * @type {string}
     * @memberof Address
     */
    addressLine2: string;
    /**
     * 市区町村
     * @type {string}
     * @memberof Address
     */
    city: string;
    /**
     * 氏名（名）
     * @type {string}
     * @memberof Address
     */
    firstname: string;
    /**
     * 氏名(名:かな)
     * @type {string}
     * @memberof Address
     */
    firstnameKana: string;
    /**
     * 氏名（姓）
     * @type {string}
     * @memberof Address
     */
    lastname: string;
    /**
     * 氏名(姓:かな)
     * @type {string}
     * @memberof Address
     */
    lastnameKana: string;
    /**
     * 電話番号
     * @type {string}
     * @memberof Address
     */
    phoneNumber: string;
    /**
     * 郵便番号
     * @type {string}
     * @memberof Address
     */
    postalCode: string;
    /**
     * 都道府県
     * @type {string}
     * @memberof Address
     */
    prefecture: string;
    /**
     * 都道府県コード
     * @type {number}
     * @memberof Address
     */
    prefectureCode: number;
}

/**
 * Check if a given object implements the Address interface.
 */
export function instanceOfAddress(value: object): value is Address {
    if (!('addressId' in value) || value['addressId'] === undefined) return false;
    if (!('addressLine1' in value) || value['addressLine1'] === undefined) return false;
    if (!('addressLine2' in value) || value['addressLine2'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('firstname' in value) || value['firstname'] === undefined) return false;
    if (!('firstnameKana' in value) || value['firstnameKana'] === undefined) return false;
    if (!('lastname' in value) || value['lastname'] === undefined) return false;
    if (!('lastnameKana' in value) || value['lastnameKana'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('prefecture' in value) || value['prefecture'] === undefined) return false;
    if (!('prefectureCode' in value) || value['prefectureCode'] === undefined) return false;
    return true;
}

export function AddressFromJSON(json: any): Address {
    return AddressFromJSONTyped(json, false);
}

export function AddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): Address {
    if (json == null) {
        return json;
    }
    return {
        
        'addressId': json['addressId'],
        'addressLine1': json['addressLine1'],
        'addressLine2': json['addressLine2'],
        'city': json['city'],
        'firstname': json['firstname'],
        'firstnameKana': json['firstnameKana'],
        'lastname': json['lastname'],
        'lastnameKana': json['lastnameKana'],
        'phoneNumber': json['phoneNumber'],
        'postalCode': json['postalCode'],
        'prefecture': json['prefecture'],
        'prefectureCode': json['prefectureCode'],
    };
}

export function AddressToJSON(json: any): Address {
    return AddressToJSONTyped(json, false);
}

export function AddressToJSONTyped(value?: Address | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addressId': value['addressId'],
        'addressLine1': value['addressLine1'],
        'addressLine2': value['addressLine2'],
        'city': value['city'],
        'firstname': value['firstname'],
        'firstnameKana': value['firstnameKana'],
        'lastname': value['lastname'],
        'lastnameKana': value['lastnameKana'],
        'phoneNumber': value['phoneNumber'],
        'postalCode': value['postalCode'],
        'prefecture': value['prefecture'],
        'prefectureCode': value['prefectureCode'],
    };
}

