/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 対応者情報
 * @export
 * @interface Admin
 */
export interface Admin {
    /**
     * 登録日時
     * @type {number}
     * @memberof Admin
     */
    createdAt: number;
    /**
     * メールアドレス
     * @type {string}
     * @memberof Admin
     */
    email: string;
    /**
     * 名
     * @type {string}
     * @memberof Admin
     */
    firstname: string;
    /**
     * 名(かな)
     * @type {string}
     * @memberof Admin
     */
    firstnameKana: string;
    /**
     * 管理者ID
     * @type {string}
     * @memberof Admin
     */
    id: string;
    /**
     * 姓
     * @type {string}
     * @memberof Admin
     */
    lastname: string;
    /**
     * 姓(かな)
     * @type {string}
     * @memberof Admin
     */
    lastnameKana: string;
    /**
     * 管理者種別
     * @type {number}
     * @memberof Admin
     */
    role: number;
    /**
     * 更新日時
     * @type {number}
     * @memberof Admin
     */
    updateAt: number;
}

/**
 * Check if a given object implements the Admin interface.
 */
export function instanceOfAdmin(value: object): value is Admin {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstname' in value) || value['firstname'] === undefined) return false;
    if (!('firstnameKana' in value) || value['firstnameKana'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('lastname' in value) || value['lastname'] === undefined) return false;
    if (!('lastnameKana' in value) || value['lastnameKana'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('updateAt' in value) || value['updateAt'] === undefined) return false;
    return true;
}

export function AdminFromJSON(json: any): Admin {
    return AdminFromJSONTyped(json, false);
}

export function AdminFromJSONTyped(json: any, ignoreDiscriminator: boolean): Admin {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'],
        'email': json['email'],
        'firstname': json['firstname'],
        'firstnameKana': json['firstnameKana'],
        'id': json['id'],
        'lastname': json['lastname'],
        'lastnameKana': json['lastnameKana'],
        'role': json['role'],
        'updateAt': json['updateAt'],
    };
}

export function AdminToJSON(json: any): Admin {
    return AdminToJSONTyped(json, false);
}

export function AdminToJSONTyped(value?: Admin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'],
        'email': value['email'],
        'firstname': value['firstname'],
        'firstnameKana': value['firstnameKana'],
        'id': value['id'],
        'lastname': value['lastname'],
        'lastnameKana': value['lastnameKana'],
        'role': value['role'],
        'updateAt': value['updateAt'],
    };
}

