/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProductTypeRequest
 */
export interface CreateProductTypeRequest {
    /**
     * アイコンURL
     * @type {string}
     * @memberof CreateProductTypeRequest
     */
    iconUrl: string;
    /**
     * 品目名
     * @type {string}
     * @memberof CreateProductTypeRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateProductTypeRequest interface.
 */
export function instanceOfCreateProductTypeRequest(value: object): value is CreateProductTypeRequest {
    if (!('iconUrl' in value) || value['iconUrl'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateProductTypeRequestFromJSON(json: any): CreateProductTypeRequest {
    return CreateProductTypeRequestFromJSONTyped(json, false);
}

export function CreateProductTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProductTypeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iconUrl': json['iconUrl'],
        'name': json['name'],
    };
}

export function CreateProductTypeRequestToJSON(json: any): CreateProductTypeRequest {
    return CreateProductTypeRequestToJSONTyped(json, false);
}

export function CreateProductTypeRequestToJSONTyped(value?: CreateProductTypeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iconUrl': value['iconUrl'],
        'name': value['name'],
    };
}

