/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAdministratorRequest
 */
export interface CreateAdministratorRequest {
    /**
     * メールアドレス
     * @type {string}
     * @memberof CreateAdministratorRequest
     */
    email: string;
    /**
     * 名
     * @type {string}
     * @memberof CreateAdministratorRequest
     */
    firstname: string;
    /**
     * 名(かな)
     * @type {string}
     * @memberof CreateAdministratorRequest
     */
    firstnameKana: string;
    /**
     * 姓
     * @type {string}
     * @memberof CreateAdministratorRequest
     */
    lastname: string;
    /**
     * 姓(かな)
     * @type {string}
     * @memberof CreateAdministratorRequest
     */
    lastnameKana: string;
    /**
     * 電話番号
     * @type {string}
     * @memberof CreateAdministratorRequest
     */
    phoneNumber: string;
}

/**
 * Check if a given object implements the CreateAdministratorRequest interface.
 */
export function instanceOfCreateAdministratorRequest(value: object): value is CreateAdministratorRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstname' in value) || value['firstname'] === undefined) return false;
    if (!('firstnameKana' in value) || value['firstnameKana'] === undefined) return false;
    if (!('lastname' in value) || value['lastname'] === undefined) return false;
    if (!('lastnameKana' in value) || value['lastnameKana'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    return true;
}

export function CreateAdministratorRequestFromJSON(json: any): CreateAdministratorRequest {
    return CreateAdministratorRequestFromJSONTyped(json, false);
}

export function CreateAdministratorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAdministratorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'firstname': json['firstname'],
        'firstnameKana': json['firstnameKana'],
        'lastname': json['lastname'],
        'lastnameKana': json['lastnameKana'],
        'phoneNumber': json['phoneNumber'],
    };
}

export function CreateAdministratorRequestToJSON(json: any): CreateAdministratorRequest {
    return CreateAdministratorRequestToJSONTyped(json, false);
}

export function CreateAdministratorRequestToJSONTyped(value?: CreateAdministratorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'firstname': value['firstname'],
        'firstnameKana': value['firstnameKana'],
        'lastname': value['lastname'],
        'lastnameKana': value['lastnameKana'],
        'phoneNumber': value['phoneNumber'],
    };
}

