/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeWeekday } from './TimeWeekday';
import {
    TimeWeekdayFromJSON,
    TimeWeekdayFromJSONTyped,
    TimeWeekdayToJSON,
    TimeWeekdayToJSONTyped,
} from './TimeWeekday';

/**
 * 
 * @export
 * @interface CreateCoordinatorRequest
 */
export interface CreateCoordinatorRequest {
    /**
     * 町名・番地
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    addressLine1: string;
    /**
     * ビル名・号室など
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    addressLine2: string;
    /**
     * 購入特典映像URL
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    bonusVideoUrl: string;
    /**
     * 営業曜日(発送可能日)
     * @type {Array<TimeWeekday>}
     * @memberof CreateCoordinatorRequest
     */
    businessDays: Array<TimeWeekday>;
    /**
     * 市区町村
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    city: string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    email: string;
    /**
     * Facebookアカウント
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    facebookId: string;
    /**
     * 名
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    firstname: string;
    /**
     * 名(かな)
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    firstnameKana: string;
    /**
     * ヘッダー画像URL
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    headerUrl: string;
    /**
     * Instagramアカウント
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    instagramId: string;
    /**
     * 姓
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    lastname: string;
    /**
     * 姓(かな)
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    lastnameKana: string;
    /**
     * マルシェ名
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    marcheName: string;
    /**
     * 電話番号
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    phoneNumber: string;
    /**
     * 郵便番号
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    postalCode: string;
    /**
     * 都道府県
     * @type {number}
     * @memberof CreateCoordinatorRequest
     */
    prefectureCode: number;
    /**
     * 取り扱い品目一覧
     * @type {Array<string>}
     * @memberof CreateCoordinatorRequest
     */
    productTypeIds: Array<string>;
    /**
     * 紹介文
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    profile: string;
    /**
     * 紹介映像URL
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    promotionVideoUrl: string;
    /**
     * サムネイルURL
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    thumbnailUrl: string;
    /**
     * 表示名
     * @type {string}
     * @memberof CreateCoordinatorRequest
     */
    username: string;
}

/**
 * Check if a given object implements the CreateCoordinatorRequest interface.
 */
export function instanceOfCreateCoordinatorRequest(value: object): value is CreateCoordinatorRequest {
    if (!('addressLine1' in value) || value['addressLine1'] === undefined) return false;
    if (!('addressLine2' in value) || value['addressLine2'] === undefined) return false;
    if (!('bonusVideoUrl' in value) || value['bonusVideoUrl'] === undefined) return false;
    if (!('businessDays' in value) || value['businessDays'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('facebookId' in value) || value['facebookId'] === undefined) return false;
    if (!('firstname' in value) || value['firstname'] === undefined) return false;
    if (!('firstnameKana' in value) || value['firstnameKana'] === undefined) return false;
    if (!('headerUrl' in value) || value['headerUrl'] === undefined) return false;
    if (!('instagramId' in value) || value['instagramId'] === undefined) return false;
    if (!('lastname' in value) || value['lastname'] === undefined) return false;
    if (!('lastnameKana' in value) || value['lastnameKana'] === undefined) return false;
    if (!('marcheName' in value) || value['marcheName'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('prefectureCode' in value) || value['prefectureCode'] === undefined) return false;
    if (!('productTypeIds' in value) || value['productTypeIds'] === undefined) return false;
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('promotionVideoUrl' in value) || value['promotionVideoUrl'] === undefined) return false;
    if (!('thumbnailUrl' in value) || value['thumbnailUrl'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function CreateCoordinatorRequestFromJSON(json: any): CreateCoordinatorRequest {
    return CreateCoordinatorRequestFromJSONTyped(json, false);
}

export function CreateCoordinatorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCoordinatorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'addressLine1': json['addressLine1'],
        'addressLine2': json['addressLine2'],
        'bonusVideoUrl': json['bonusVideoUrl'],
        'businessDays': ((json['businessDays'] as Array<any>).map(TimeWeekdayFromJSON)),
        'city': json['city'],
        'email': json['email'],
        'facebookId': json['facebookId'],
        'firstname': json['firstname'],
        'firstnameKana': json['firstnameKana'],
        'headerUrl': json['headerUrl'],
        'instagramId': json['instagramId'],
        'lastname': json['lastname'],
        'lastnameKana': json['lastnameKana'],
        'marcheName': json['marcheName'],
        'phoneNumber': json['phoneNumber'],
        'postalCode': json['postalCode'],
        'prefectureCode': json['prefectureCode'],
        'productTypeIds': json['productTypeIds'],
        'profile': json['profile'],
        'promotionVideoUrl': json['promotionVideoUrl'],
        'thumbnailUrl': json['thumbnailUrl'],
        'username': json['username'],
    };
}

export function CreateCoordinatorRequestToJSON(json: any): CreateCoordinatorRequest {
    return CreateCoordinatorRequestToJSONTyped(json, false);
}

export function CreateCoordinatorRequestToJSONTyped(value?: CreateCoordinatorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addressLine1': value['addressLine1'],
        'addressLine2': value['addressLine2'],
        'bonusVideoUrl': value['bonusVideoUrl'],
        'businessDays': ((value['businessDays'] as Array<any>).map(TimeWeekdayToJSON)),
        'city': value['city'],
        'email': value['email'],
        'facebookId': value['facebookId'],
        'firstname': value['firstname'],
        'firstnameKana': value['firstnameKana'],
        'headerUrl': value['headerUrl'],
        'instagramId': value['instagramId'],
        'lastname': value['lastname'],
        'lastnameKana': value['lastnameKana'],
        'marcheName': value['marcheName'],
        'phoneNumber': value['phoneNumber'],
        'postalCode': value['postalCode'],
        'prefectureCode': value['prefectureCode'],
        'productTypeIds': value['productTypeIds'],
        'profile': value['profile'],
        'promotionVideoUrl': value['promotionVideoUrl'],
        'thumbnailUrl': value['thumbnailUrl'],
        'username': value['username'],
    };
}

