/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLiveRequest
 */
export interface CreateLiveRequest {
    /**
     * コメント
     * @type {string}
     * @memberof CreateLiveRequest
     */
    comment: string;
    /**
     * 配信終了日時
     * @type {number}
     * @memberof CreateLiveRequest
     */
    endAt: number;
    /**
     * 生産者ID
     * @type {string}
     * @memberof CreateLiveRequest
     */
    producerId: string;
    /**
     * 商品ID一覧
     * @type {Array<string>}
     * @memberof CreateLiveRequest
     */
    productIds: Array<string>;
    /**
     * 配信開始日時
     * @type {number}
     * @memberof CreateLiveRequest
     */
    startAt: number;
}

/**
 * Check if a given object implements the CreateLiveRequest interface.
 */
export function instanceOfCreateLiveRequest(value: object): value is CreateLiveRequest {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('endAt' in value) || value['endAt'] === undefined) return false;
    if (!('producerId' in value) || value['producerId'] === undefined) return false;
    if (!('productIds' in value) || value['productIds'] === undefined) return false;
    if (!('startAt' in value) || value['startAt'] === undefined) return false;
    return true;
}

export function CreateLiveRequestFromJSON(json: any): CreateLiveRequest {
    return CreateLiveRequestFromJSONTyped(json, false);
}

export function CreateLiveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLiveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'],
        'endAt': json['endAt'],
        'producerId': json['producerId'],
        'productIds': json['productIds'],
        'startAt': json['startAt'],
    };
}

export function CreateLiveRequestToJSON(json: any): CreateLiveRequest {
    return CreateLiveRequestToJSONTyped(json, false);
}

export function CreateLiveRequestToJSONTyped(value?: CreateLiveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': value['comment'],
        'endAt': value['endAt'],
        'producerId': value['producerId'],
        'productIds': value['productIds'],
        'startAt': value['startAt'],
    };
}

