/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProducerRequest
 */
export interface CreateProducerRequest {
    /**
     * 町名・番地
     * @type {string}
     * @memberof CreateProducerRequest
     */
    addressLine1: string;
    /**
     * ビル名・号室など
     * @type {string}
     * @memberof CreateProducerRequest
     */
    addressLine2: string;
    /**
     * 購入特典映像URL
     * @type {string}
     * @memberof CreateProducerRequest
     */
    bonusVideoUrl: string;
    /**
     * 市区町村
     * @type {string}
     * @memberof CreateProducerRequest
     */
    city: string;
    /**
     * 担当コーディネータ名
     * @type {string}
     * @memberof CreateProducerRequest
     */
    coordinatorId: string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof CreateProducerRequest
     */
    email: string;
    /**
     * Facebookアカウント
     * @type {string}
     * @memberof CreateProducerRequest
     */
    facebookId: string;
    /**
     * 名
     * @type {string}
     * @memberof CreateProducerRequest
     */
    firstname: string;
    /**
     * 名(かな)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    firstnameKana: string;
    /**
     * ヘッダー画像URL
     * @type {string}
     * @memberof CreateProducerRequest
     */
    headerUrl: string;
    /**
     * Instagramアカウント
     * @type {string}
     * @memberof CreateProducerRequest
     */
    instagramId: string;
    /**
     * 姓
     * @type {string}
     * @memberof CreateProducerRequest
     */
    lastname: string;
    /**
     * 姓(かな)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    lastnameKana: string;
    /**
     * 電話番号
     * @type {string}
     * @memberof CreateProducerRequest
     */
    phoneNumber: string;
    /**
     * 郵便番号
     * @type {string}
     * @memberof CreateProducerRequest
     */
    postalCode: string;
    /**
     * 都道府県
     * @type {number}
     * @memberof CreateProducerRequest
     */
    prefectureCode: number;
    /**
     * 紹介文
     * @type {string}
     * @memberof CreateProducerRequest
     */
    profile: string;
    /**
     * 紹介映像URL
     * @type {string}
     * @memberof CreateProducerRequest
     */
    promotionVideoUrl: string;
    /**
     * サムネイルURL
     * @type {string}
     * @memberof CreateProducerRequest
     */
    thumbnailUrl: string;
    /**
     * 表示名
     * @type {string}
     * @memberof CreateProducerRequest
     */
    username: string;
}

/**
 * Check if a given object implements the CreateProducerRequest interface.
 */
export function instanceOfCreateProducerRequest(value: object): value is CreateProducerRequest {
    if (!('addressLine1' in value) || value['addressLine1'] === undefined) return false;
    if (!('addressLine2' in value) || value['addressLine2'] === undefined) return false;
    if (!('bonusVideoUrl' in value) || value['bonusVideoUrl'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('coordinatorId' in value) || value['coordinatorId'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('facebookId' in value) || value['facebookId'] === undefined) return false;
    if (!('firstname' in value) || value['firstname'] === undefined) return false;
    if (!('firstnameKana' in value) || value['firstnameKana'] === undefined) return false;
    if (!('headerUrl' in value) || value['headerUrl'] === undefined) return false;
    if (!('instagramId' in value) || value['instagramId'] === undefined) return false;
    if (!('lastname' in value) || value['lastname'] === undefined) return false;
    if (!('lastnameKana' in value) || value['lastnameKana'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('prefectureCode' in value) || value['prefectureCode'] === undefined) return false;
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('promotionVideoUrl' in value) || value['promotionVideoUrl'] === undefined) return false;
    if (!('thumbnailUrl' in value) || value['thumbnailUrl'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function CreateProducerRequestFromJSON(json: any): CreateProducerRequest {
    return CreateProducerRequestFromJSONTyped(json, false);
}

export function CreateProducerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProducerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'addressLine1': json['addressLine1'],
        'addressLine2': json['addressLine2'],
        'bonusVideoUrl': json['bonusVideoUrl'],
        'city': json['city'],
        'coordinatorId': json['coordinatorId'],
        'email': json['email'],
        'facebookId': json['facebookId'],
        'firstname': json['firstname'],
        'firstnameKana': json['firstnameKana'],
        'headerUrl': json['headerUrl'],
        'instagramId': json['instagramId'],
        'lastname': json['lastname'],
        'lastnameKana': json['lastnameKana'],
        'phoneNumber': json['phoneNumber'],
        'postalCode': json['postalCode'],
        'prefectureCode': json['prefectureCode'],
        'profile': json['profile'],
        'promotionVideoUrl': json['promotionVideoUrl'],
        'thumbnailUrl': json['thumbnailUrl'],
        'username': json['username'],
    };
}

export function CreateProducerRequestToJSON(json: any): CreateProducerRequest {
    return CreateProducerRequestToJSONTyped(json, false);
}

export function CreateProducerRequestToJSONTyped(value?: CreateProducerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'addressLine1': value['addressLine1'],
        'addressLine2': value['addressLine2'],
        'bonusVideoUrl': value['bonusVideoUrl'],
        'city': value['city'],
        'coordinatorId': value['coordinatorId'],
        'email': value['email'],
        'facebookId': value['facebookId'],
        'firstname': value['firstname'],
        'firstnameKana': value['firstnameKana'],
        'headerUrl': value['headerUrl'],
        'instagramId': value['instagramId'],
        'lastname': value['lastname'],
        'lastnameKana': value['lastnameKana'],
        'phoneNumber': value['phoneNumber'],
        'postalCode': value['postalCode'],
        'prefectureCode': value['prefectureCode'],
        'profile': value['profile'],
        'promotionVideoUrl': value['promotionVideoUrl'],
        'thumbnailUrl': value['thumbnailUrl'],
        'username': value['username'],
    };
}

