/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Coordinator } from './Coordinator';
import {
    CoordinatorFromJSON,
    CoordinatorFromJSONTyped,
    CoordinatorToJSON,
    CoordinatorToJSONTyped,
} from './Coordinator';
import type { Promotion } from './Promotion';
import {
    PromotionFromJSON,
    PromotionFromJSONTyped,
    PromotionToJSON,
    PromotionToJSONTyped,
} from './Promotion';

/**
 * 
 * @export
 * @interface OrdersResponse
 */
export interface OrdersResponse {
    /**
     * コーディネータ一覧
     * @type {Array<Coordinator>}
     * @memberof OrdersResponse
     */
    coordinators: Array<Coordinator>;
    /**
     * 注文履歴一覧
     * @type {Array<Order>}
     * @memberof OrdersResponse
     */
    orders: Array<Order>;
    /**
     * プロモーション一覧
     * @type {Array<Promotion>}
     * @memberof OrdersResponse
     */
    promotions: Array<Promotion>;
    /**
     * 注文履歴合計数
     * @type {number}
     * @memberof OrdersResponse
     */
    total: number;
    /**
     * 購入者一覧
     * @type {Array<User>}
     * @memberof OrdersResponse
     */
    users: Array<User>;
}

/**
 * Check if a given object implements the OrdersResponse interface.
 */
export function instanceOfOrdersResponse(value: object): value is OrdersResponse {
    if (!('coordinators' in value) || value['coordinators'] === undefined) return false;
    if (!('orders' in value) || value['orders'] === undefined) return false;
    if (!('promotions' in value) || value['promotions'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function OrdersResponseFromJSON(json: any): OrdersResponse {
    return OrdersResponseFromJSONTyped(json, false);
}

export function OrdersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrdersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinators': ((json['coordinators'] as Array<any>).map(CoordinatorFromJSON)),
        'orders': ((json['orders'] as Array<any>).map(OrderFromJSON)),
        'promotions': ((json['promotions'] as Array<any>).map(PromotionFromJSON)),
        'total': json['total'],
        'users': ((json['users'] as Array<any>).map(UserFromJSON)),
    };
}

export function OrdersResponseToJSON(json: any): OrdersResponse {
    return OrdersResponseToJSONTyped(json, false);
}

export function OrdersResponseToJSONTyped(value?: OrdersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coordinators': ((value['coordinators'] as Array<any>).map(CoordinatorToJSON)),
        'orders': ((value['orders'] as Array<any>).map(OrderToJSON)),
        'promotions': ((value['promotions'] as Array<any>).map(PromotionToJSON)),
        'total': value['total'],
        'users': ((value['users'] as Array<any>).map(UserToJSON)),
    };
}

