/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document:
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 決済プロバイダー種別
 * @export
 */
export const PaymentProviderType = {
    /**
    * 不明
    */
    PaymentProviderTypeUnknown: 0,
    /**
    * KOMOJU
    */
    PaymentProviderTypeKomoju: 1,
    /**
    * Stripe
    */
    PaymentProviderTypeStripe: 2
} as const;
export type PaymentProviderType = typeof PaymentProviderType[keyof typeof PaymentProviderType];


export function instanceOfPaymentProviderType(value: any): boolean {
    for (const key in PaymentProviderType) {
        if (Object.prototype.hasOwnProperty.call(PaymentProviderType, key)) {
            if (PaymentProviderType[key as keyof typeof PaymentProviderType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PaymentProviderTypeFromJSON(json: any): PaymentProviderType {
    return PaymentProviderTypeFromJSONTyped(json, false);
}

export function PaymentProviderTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentProviderType {
    return json as PaymentProviderType;
}

export function PaymentProviderTypeToJSON(value?: PaymentProviderType | null): any {
    return value as any;
}

export function PaymentProviderTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): PaymentProviderType {
    return value as PaymentProviderType;
}
