/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpotType } from './SpotType';
import {
    SpotTypeFromJSON,
    SpotTypeFromJSONTyped,
    SpotTypeToJSON,
    SpotTypeToJSONTyped,
} from './SpotType';

/**
 * 
 * @export
 * @interface SpotTypeResponse
 */
export interface SpotTypeResponse {
    /**
     * 
     * @type {SpotType}
     * @memberof SpotTypeResponse
     */
    spotType: SpotType;
}

/**
 * Check if a given object implements the SpotTypeResponse interface.
 */
export function instanceOfSpotTypeResponse(value: object): value is SpotTypeResponse {
    if (!('spotType' in value) || value['spotType'] === undefined) return false;
    return true;
}

export function SpotTypeResponseFromJSON(json: any): SpotTypeResponse {
    return SpotTypeResponseFromJSONTyped(json, false);
}

export function SpotTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpotTypeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'spotType': SpotTypeFromJSON(json['spotType']),
    };
}

export function SpotTypeResponseToJSON(json: any): SpotTypeResponse {
    return SpotTypeResponseToJSONTyped(json, false);
}

export function SpotTypeResponseToJSONTyped(value?: SpotTypeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spotType': SpotTypeToJSON(value['spotType']),
    };
}

