/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateLiveCommentRequest
 */
export interface UpdateLiveCommentRequest {
    /**
     * コメント無効フラグ
     * @type {boolean}
     * @memberof UpdateLiveCommentRequest
     */
    disabled: boolean;
}

/**
 * Check if a given object implements the UpdateLiveCommentRequest interface.
 */
export function instanceOfUpdateLiveCommentRequest(value: object): value is UpdateLiveCommentRequest {
    if (!('disabled' in value) || value['disabled'] === undefined) return false;
    return true;
}

export function UpdateLiveCommentRequestFromJSON(json: any): UpdateLiveCommentRequest {
    return UpdateLiveCommentRequestFromJSONTyped(json, false);
}

export function UpdateLiveCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLiveCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'disabled': json['disabled'],
    };
}

export function UpdateLiveCommentRequestToJSON(json: any): UpdateLiveCommentRequest {
    return UpdateLiveCommentRequestToJSONTyped(json, false);
}

export function UpdateLiveCommentRequestToJSONTyped(value?: UpdateLiveCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'disabled': value['disabled'],
    };
}

