/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateNotificationRequest
 */
export interface UpdateNotificationRequest {
    /**
     * 本文
     * @type {string}
     * @memberof UpdateNotificationRequest
     */
    body: string;
    /**
     * 備考
     * @type {string}
     * @memberof UpdateNotificationRequest
     */
    note: string;
    /**
     * 掲載開始日
     * @type {number}
     * @memberof UpdateNotificationRequest
     */
    publishedAt: number;
    /**
     * 掲載対象一覧
     * @type {Array<number>}
     * @memberof UpdateNotificationRequest
     */
    targets: Array<number>;
    /**
     * タイトル
     * @type {string}
     * @memberof UpdateNotificationRequest
     */
    title: string;
}

/**
 * Check if a given object implements the UpdateNotificationRequest interface.
 */
export function instanceOfUpdateNotificationRequest(value: object): value is UpdateNotificationRequest {
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('note' in value) || value['note'] === undefined) return false;
    if (!('publishedAt' in value) || value['publishedAt'] === undefined) return false;
    if (!('targets' in value) || value['targets'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function UpdateNotificationRequestFromJSON(json: any): UpdateNotificationRequest {
    return UpdateNotificationRequestFromJSONTyped(json, false);
}

export function UpdateNotificationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNotificationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'note': json['note'],
        'publishedAt': json['publishedAt'],
        'targets': json['targets'],
        'title': json['title'],
    };
}

export function UpdateNotificationRequestToJSON(json: any): UpdateNotificationRequest {
    return UpdateNotificationRequestToJSONTyped(json, false);
}

export function UpdateNotificationRequestToJSONTyped(value?: UpdateNotificationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'note': value['note'],
        'publishedAt': value['publishedAt'],
        'targets': value['targets'],
        'title': value['title'],
    };
}

