/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProductMedia
 */
export interface UpdateProductMedia {
    /**
     * サムネイルとして使用
     * @type {boolean}
     * @memberof UpdateProductMedia
     */
    isThumbnail: boolean;
    /**
     * メディアURL
     * @type {string}
     * @memberof UpdateProductMedia
     */
    url: string;
}

/**
 * Check if a given object implements the UpdateProductMedia interface.
 */
export function instanceOfUpdateProductMedia(value: object): value is UpdateProductMedia {
    if (!('isThumbnail' in value) || value['isThumbnail'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function UpdateProductMediaFromJSON(json: any): UpdateProductMedia {
    return UpdateProductMediaFromJSONTyped(json, false);
}

export function UpdateProductMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProductMedia {
    if (json == null) {
        return json;
    }
    return {
        
        'isThumbnail': json['isThumbnail'],
        'url': json['url'],
    };
}

export function UpdateProductMediaToJSON(json: any): UpdateProductMedia {
    return UpdateProductMediaToJSONTyped(json, false);
}

export function UpdateProductMediaToJSONTyped(value?: UpdateProductMedia | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isThumbnail': value['isThumbnail'],
        'url': value['url'],
    };
}

