/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyAuthEmailRequest
 */
export interface VerifyAuthEmailRequest {
    /**
     * 検証コード
     * @type {string}
     * @memberof VerifyAuthEmailRequest
     */
    verifyCode: string;
}

/**
 * Check if a given object implements the VerifyAuthEmailRequest interface.
 */
export function instanceOfVerifyAuthEmailRequest(value: object): value is VerifyAuthEmailRequest {
    if (!('verifyCode' in value) || value['verifyCode'] === undefined) return false;
    return true;
}

export function VerifyAuthEmailRequestFromJSON(json: any): VerifyAuthEmailRequest {
    return VerifyAuthEmailRequestFromJSONTyped(json, false);
}

export function VerifyAuthEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAuthEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'verifyCode': json['verifyCode'],
    };
}

export function VerifyAuthEmailRequestToJSON(json: any): VerifyAuthEmailRequest {
    return VerifyAuthEmailRequestToJSONTyped(json, false);
}

export function VerifyAuthEmailRequestToJSONTyped(value?: VerifyAuthEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verifyCode': value['verifyCode'],
    };
}

