/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ管理者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 管理者権限
 * @export
 */
export const AdminRole = {
    UNKNOWN: 0,
    ADMINISTRATOR: 1,
    COORDINATOR: 2,
    PRODUCER: 3
} as const;
export type AdminRole = typeof AdminRole[keyof typeof AdminRole];


export function AdminRoleFromJSON(json: any): AdminRole {
    return AdminRoleFromJSONTyped(json, false);
}

export function AdminRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminRole {
    return json as AdminRole;
}

export function AdminRoleToJSON(value?: AdminRole | null): any {
    return value as any;
}

