/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ管理者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CategoriesResponseCategoriesInner } from './CategoriesResponseCategoriesInner';
import {
    CategoriesResponseCategoriesInnerFromJSON,
    CategoriesResponseCategoriesInnerFromJSONTyped,
    CategoriesResponseCategoriesInnerToJSON,
} from './CategoriesResponseCategoriesInner';

/**
 * 
 * @export
 * @interface CategoriesResponse
 */
export interface CategoriesResponse {
    /**
     * 商品種別一覧
     * @type {Array<CategoriesResponseCategoriesInner>}
     * @memberof CategoriesResponse
     */
    categories: Array<CategoriesResponseCategoriesInner>;
    /**
     * 合計数
     * @type {number}
     * @memberof CategoriesResponse
     */
    total: number;
}

/**
 * Check if a given object implements the CategoriesResponse interface.
 */
export function instanceOfCategoriesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "categories" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function CategoriesResponseFromJSON(json: any): CategoriesResponse {
    return CategoriesResponseFromJSONTyped(json, false);
}

export function CategoriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoriesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'categories': ((json['categories'] as Array<any>).map(CategoriesResponseCategoriesInnerFromJSON)),
        'total': json['total'],
    };
}

export function CategoriesResponseToJSON(value?: CategoriesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'categories': ((value.categories as Array<any>).map(CategoriesResponseCategoriesInnerToJSON)),
        'total': value.total,
    };
}

