/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ管理者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContactsResponseContactsInner } from './ContactsResponseContactsInner';
import {
    ContactsResponseContactsInnerFromJSON,
    ContactsResponseContactsInnerFromJSONTyped,
    ContactsResponseContactsInnerToJSON,
} from './ContactsResponseContactsInner';

/**
 * 
 * @export
 * @interface ContactsResponse
 */
export interface ContactsResponse {
    /**
     * お問い合わせ一覧
     * @type {Array<ContactsResponseContactsInner>}
     * @memberof ContactsResponse
     */
    contacts: Array<ContactsResponseContactsInner>;
    /**
     * 合計数
     * @type {number}
     * @memberof ContactsResponse
     */
    total: number;
}

/**
 * Check if a given object implements the ContactsResponse interface.
 */
export function instanceOfContactsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "contacts" in value;
    isInstance = isInstance && "total" in value;

    return isInstance;
}

export function ContactsResponseFromJSON(json: any): ContactsResponse {
    return ContactsResponseFromJSONTyped(json, false);
}

export function ContactsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contacts': ((json['contacts'] as Array<any>).map(ContactsResponseContactsInnerFromJSON)),
        'total': json['total'],
    };
}

export function ContactsResponseToJSON(value?: ContactsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contacts': ((value.contacts as Array<any>).map(ContactsResponseContactsInnerToJSON)),
        'total': value.total,
    };
}

