/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ管理者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiscountType } from './DiscountType';
import {
    DiscountTypeFromJSON,
    DiscountTypeFromJSONTyped,
    DiscountTypeToJSON,
} from './DiscountType';

/**
 * 
 * @export
 * @interface CreatePromotionRequest
 */
export interface CreatePromotionRequest {
    /**
     * タイトル(200文字まで)
     * @type {string}
     * @memberof CreatePromotionRequest
     */
    title: string;
    /**
     * 説明(2000文字まで)
     * @type {string}
     * @memberof CreatePromotionRequest
     */
    description: string;
    /**
     * 公開フラグ
     * @type {boolean}
     * @memberof CreatePromotionRequest
     */
    _public: boolean;
    /**
     * 公開日時(unixtime)
     * @type {number}
     * @memberof CreatePromotionRequest
     */
    publishedAt: number;
    /**
     * 
     * @type {DiscountType}
     * @memberof CreatePromotionRequest
     */
    discountType: DiscountType;
    /**
     * 割引額(単位:円/%,0以上)
     * @type {number}
     * @memberof CreatePromotionRequest
     */
    discountRate: number;
    /**
     * クーポンコード(8文字,使用可能文字:半角英数字)
     * @type {string}
     * @memberof CreatePromotionRequest
     */
    code: string;
    /**
     * クーポン利用可能開始日時(unixtime)
     * @type {number}
     * @memberof CreatePromotionRequest
     */
    startAt: number;
    /**
     * クーポン利用可能終了日時(unixtime)
     * @type {number}
     * @memberof CreatePromotionRequest
     */
    endAt: number;
}

/**
 * Check if a given object implements the CreatePromotionRequest interface.
 */
export function instanceOfCreatePromotionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "_public" in value;
    isInstance = isInstance && "publishedAt" in value;
    isInstance = isInstance && "discountType" in value;
    isInstance = isInstance && "discountRate" in value;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "startAt" in value;
    isInstance = isInstance && "endAt" in value;

    return isInstance;
}

export function CreatePromotionRequestFromJSON(json: any): CreatePromotionRequest {
    return CreatePromotionRequestFromJSONTyped(json, false);
}

export function CreatePromotionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePromotionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        '_public': json['public'],
        'publishedAt': json['publishedAt'],
        'discountType': DiscountTypeFromJSON(json['discountType']),
        'discountRate': json['discountRate'],
        'code': json['code'],
        'startAt': json['startAt'],
        'endAt': json['endAt'],
    };
}

export function CreatePromotionRequestToJSON(value?: CreatePromotionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'public': value._public,
        'publishedAt': value.publishedAt,
        'discountType': DiscountTypeToJSON(value.discountType),
        'discountRate': value.discountRate,
        'code': value.code,
        'startAt': value.startAt,
        'endAt': value.endAt,
    };
}

