/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ管理者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Prefecture } from './Prefecture';
import {
    PrefectureFromJSON,
    PrefectureFromJSONTyped,
    PrefectureToJSON,
} from './Prefecture';

/**
 * 
 * @export
 * @interface CreateShippingRate
 */
export interface CreateShippingRate {
    /**
     * 配送料金設定名
     * @type {string}
     * @memberof CreateShippingRate
     */
    name: string;
    /**
     * 配送料金(100万未満)
     * @type {number}
     * @memberof CreateShippingRate
     */
    price: number;
    /**
     * 対象都道府県コード一覧
     * @type {Array<Prefecture>}
     * @memberof CreateShippingRate
     */
    prefectures: Array<Prefecture>;
}

/**
 * Check if a given object implements the CreateShippingRate interface.
 */
export function instanceOfCreateShippingRate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "prefectures" in value;

    return isInstance;
}

export function CreateShippingRateFromJSON(json: any): CreateShippingRate {
    return CreateShippingRateFromJSONTyped(json, false);
}

export function CreateShippingRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShippingRate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'price': json['price'],
        'prefectures': ((json['prefectures'] as Array<any>).map(PrefectureFromJSON)),
    };
}

export function CreateShippingRateToJSON(value?: CreateShippingRate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'price': value.price,
        'prefectures': ((value.prefectures as Array<any>).map(PrefectureToJSON)),
    };
}

