/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ管理者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProducerRequest
 */
export interface CreateProducerRequest {
    /**
     * 姓(16文字まで)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    lastname: string;
    /**
     * 名(16文字まで)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    firstname: string;
    /**
     * 姓(かな)(ひらがな,32文字まで)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    lastnameKana: string;
    /**
     * 名(かな)(ひらがな,32文字まで)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    firstnameKana: string;
    /**
     * 店舗名(64文字まで)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    storeName: string;
    /**
     * サムネイルURL
     * @type {string}
     * @memberof CreateProducerRequest
     */
    thumbnailUrl?: string;
    /**
     * ヘッダー画像URL
     * @type {string}
     * @memberof CreateProducerRequest
     */
    headerUrl?: string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof CreateProducerRequest
     */
    email: string;
    /**
     * 電話番号 (国際番号 + 電話番号)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    phoneNumber: string;
    /**
     * 郵便番号(ハイフンなし)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    postalCode: string;
    /**
     * 都道府県(32文字まで)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    prefecture: string;
    /**
     * 市区町村(32文字まで)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    city: string;
    /**
     * 町名・番地(64文字まで)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    addressLine1: string;
    /**
     * ビル名・号室など(64文字まで)
     * @type {string}
     * @memberof CreateProducerRequest
     */
    addressLine2: string;
}

/**
 * Check if a given object implements the CreateProducerRequest interface.
 */
export function instanceOfCreateProducerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lastname" in value;
    isInstance = isInstance && "firstname" in value;
    isInstance = isInstance && "lastnameKana" in value;
    isInstance = isInstance && "firstnameKana" in value;
    isInstance = isInstance && "storeName" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "phoneNumber" in value;
    isInstance = isInstance && "postalCode" in value;
    isInstance = isInstance && "prefecture" in value;
    isInstance = isInstance && "city" in value;
    isInstance = isInstance && "addressLine1" in value;
    isInstance = isInstance && "addressLine2" in value;

    return isInstance;
}

export function CreateProducerRequestFromJSON(json: any): CreateProducerRequest {
    return CreateProducerRequestFromJSONTyped(json, false);
}

export function CreateProducerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProducerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastname': json['lastname'],
        'firstname': json['firstname'],
        'lastnameKana': json['lastnameKana'],
        'firstnameKana': json['firstnameKana'],
        'storeName': json['storeName'],
        'thumbnailUrl': !exists(json, 'thumbnailUrl') ? undefined : json['thumbnailUrl'],
        'headerUrl': !exists(json, 'headerUrl') ? undefined : json['headerUrl'],
        'email': json['email'],
        'phoneNumber': json['phoneNumber'],
        'postalCode': json['postalCode'],
        'prefecture': json['prefecture'],
        'city': json['city'],
        'addressLine1': json['addressLine1'],
        'addressLine2': json['addressLine2'],
    };
}

export function CreateProducerRequestToJSON(value?: CreateProducerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastname': value.lastname,
        'firstname': value.firstname,
        'lastnameKana': value.lastnameKana,
        'firstnameKana': value.firstnameKana,
        'storeName': value.storeName,
        'thumbnailUrl': value.thumbnailUrl,
        'headerUrl': value.headerUrl,
        'email': value.email,
        'phoneNumber': value.phoneNumber,
        'postalCode': value.postalCode,
        'prefecture': value.prefecture,
        'city': value.city,
        'addressLine1': value.addressLine1,
        'addressLine2': value.addressLine2,
    };
}

