/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ管理者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateShippingRate } from './CreateShippingRate';
import {
    CreateShippingRateFromJSON,
    CreateShippingRateFromJSONTyped,
    CreateShippingRateToJSON,
} from './CreateShippingRate';

/**
 * 
 * @export
 * @interface UpdateShippingRequest
 */
export interface UpdateShippingRequest {
    /**
     * 配送設定名(64文字まで)
     * @type {string}
     * @memberof UpdateShippingRequest
     */
    name: string;
    /**
     * 箱サイズ60の通常配送料一覧(すべての都道府県の設定が必須)
     * @type {Array<CreateShippingRate>}
     * @memberof UpdateShippingRequest
     */
    box60Rates: Array<CreateShippingRate>;
    /**
     * 箱サイズ60の冷蔵便追加配送料(100万未満)
     * @type {number}
     * @memberof UpdateShippingRequest
     */
    box60Refrigerated: number;
    /**
     * 箱サイズ60の冷凍便追加配送料(100万未満)
     * @type {number}
     * @memberof UpdateShippingRequest
     */
    box60Frozen: number;
    /**
     * 箱サイズ80の通常配送料一覧(すべての都道府県の設定が必須)
     * @type {Array<CreateShippingRate>}
     * @memberof UpdateShippingRequest
     */
    box80Rates: Array<CreateShippingRate>;
    /**
     * 箱サイズ80の冷蔵便追加配送料(100万未満)
     * @type {number}
     * @memberof UpdateShippingRequest
     */
    box80Refrigerated: number;
    /**
     * 箱サイズ80の冷凍便追加配送料(100万未満)
     * @type {number}
     * @memberof UpdateShippingRequest
     */
    box80Frozen: number;
    /**
     * 箱サイズ100の通常配送料一覧(すべての都道府県の設定が必須)
     * @type {Array<CreateShippingRate>}
     * @memberof UpdateShippingRequest
     */
    box100Rates: Array<CreateShippingRate>;
    /**
     * 箱サイズ100の冷蔵便追加配送料(100万未満)
     * @type {number}
     * @memberof UpdateShippingRequest
     */
    box100Refrigerated: number;
    /**
     * 箱サイズ100の冷凍便追加配送料(100万未満)
     * @type {number}
     * @memberof UpdateShippingRequest
     */
    box100Frozen: number;
    /**
     * 送料無料オプションの有無
     * @type {boolean}
     * @memberof UpdateShippingRequest
     */
    hasFreeShipping: boolean;
    /**
     * 送料無料になる金額(100万未満)
     * @type {number}
     * @memberof UpdateShippingRequest
     */
    freeShippingRates: number;
}

/**
 * Check if a given object implements the UpdateShippingRequest interface.
 */
export function instanceOfUpdateShippingRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "box60Rates" in value;
    isInstance = isInstance && "box60Refrigerated" in value;
    isInstance = isInstance && "box60Frozen" in value;
    isInstance = isInstance && "box80Rates" in value;
    isInstance = isInstance && "box80Refrigerated" in value;
    isInstance = isInstance && "box80Frozen" in value;
    isInstance = isInstance && "box100Rates" in value;
    isInstance = isInstance && "box100Refrigerated" in value;
    isInstance = isInstance && "box100Frozen" in value;
    isInstance = isInstance && "hasFreeShipping" in value;
    isInstance = isInstance && "freeShippingRates" in value;

    return isInstance;
}

export function UpdateShippingRequestFromJSON(json: any): UpdateShippingRequest {
    return UpdateShippingRequestFromJSONTyped(json, false);
}

export function UpdateShippingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateShippingRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'box60Rates': ((json['box60Rates'] as Array<any>).map(CreateShippingRateFromJSON)),
        'box60Refrigerated': json['box60Refrigerated'],
        'box60Frozen': json['box60Frozen'],
        'box80Rates': ((json['box80Rates'] as Array<any>).map(CreateShippingRateFromJSON)),
        'box80Refrigerated': json['box80Refrigerated'],
        'box80Frozen': json['box80Frozen'],
        'box100Rates': ((json['box100Rates'] as Array<any>).map(CreateShippingRateFromJSON)),
        'box100Refrigerated': json['box100Refrigerated'],
        'box100Frozen': json['box100Frozen'],
        'hasFreeShipping': json['hasFreeShipping'],
        'freeShippingRates': json['freeShippingRates'],
    };
}

export function UpdateShippingRequestToJSON(value?: UpdateShippingRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'box60Rates': ((value.box60Rates as Array<any>).map(CreateShippingRateToJSON)),
        'box60Refrigerated': value.box60Refrigerated,
        'box60Frozen': value.box60Frozen,
        'box80Rates': ((value.box80Rates as Array<any>).map(CreateShippingRateToJSON)),
        'box80Refrigerated': value.box80Refrigerated,
        'box80Frozen': value.box80Frozen,
        'box100Rates': ((value.box100Rates as Array<any>).map(CreateShippingRateToJSON)),
        'box100Refrigerated': value.box100Refrigerated,
        'box100Frozen': value.box100Frozen,
        'hasFreeShipping': value.hasFreeShipping,
        'freeShippingRates': value.freeShippingRates,
    };
}

