/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  PromotionResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    PromotionResponseFromJSON,
    PromotionResponseToJSON,
} from '../models/index';

export interface V1GetPromotionRequest {
    code: string;
    coordinatorId?: string;
}

/**
 * 
 */
export class PromotionApi extends runtime.BaseAPI {

    /**
     * プロモーション情報取得
     */
    async v1GetPromotionRaw(requestParameters: V1GetPromotionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromotionResponse>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling v1GetPromotion().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['coordinatorId'] != null) {
            queryParameters['coordinatorId'] = requestParameters['coordinatorId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/promotions/{code}`.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromotionResponseFromJSON(jsonValue));
    }

    /**
     * プロモーション情報取得
     */
    async v1GetPromotion(requestParameters: V1GetPromotionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromotionResponse> {
        const response = await this.v1GetPromotionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
