/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 管理者向け
 * 管理者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TopOrdersResponse,
} from '../models/index';
import {
    TopOrdersResponseFromJSON,
    TopOrdersResponseToJSON,
} from '../models/index';

export interface V1TopOrdersGetRequest {
    startAt?: number;
    endAt?: number;
    periodType?: string;
    shopId?: string;
}

/**
 * 
 */
export class TopApi extends runtime.BaseAPI {

    /**
     * 指定期間の注文統計情報（注文数、売上、決済手段別集計、推移）を取得します。
     * 注文集計取得
     */
    async v1TopOrdersGetRaw(requestParameters: V1TopOrdersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TopOrdersResponse>> {
        const queryParameters: any = {};

        if (requestParameters['startAt'] != null) {
            queryParameters['startAt'] = requestParameters['startAt'];
        }

        if (requestParameters['endAt'] != null) {
            queryParameters['endAt'] = requestParameters['endAt'];
        }

        if (requestParameters['periodType'] != null) {
            queryParameters['periodType'] = requestParameters['periodType'];
        }

        if (requestParameters['shopId'] != null) {
            queryParameters['shopId'] = requestParameters['shopId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerauth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/top/orders`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TopOrdersResponseFromJSON(jsonValue));
    }

    /**
     * 指定期間の注文統計情報（注文数、売上、決済手段別集計、推移）を取得します。
     * 注文集計取得
     */
    async v1TopOrdersGet(requestParameters: V1TopOrdersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TopOrdersResponse> {
        const response = await this.v1TopOrdersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
