import type { ValidationArgs } from "@vuelidate/core";
import { maxLength, maxLengthArray, maxValue, minValue, required } from '~/lib/validations'

export const CreateExperienceValidationRules: ValidationArgs = {
  title: { required, maxLength: maxLength(128) },
  description: { required, maxLength: maxLength(20000) },
  public: {},
  soldOut: {},
  producerId: { required },
  experienceTypeId: { required },
  media: { maxLengthArray: maxLengthArray(8) },
  priceAdult: { required, minValue: minValue(0) },
  priceJuniorHighSchool: { required, minValue: minValue(0) },
  priceElementarySchool: { required, minValue: minValue(0) },
  pricePreschool: { required, minValue: minValue(0) },
  priceSenior: { required, minValue: minValue(0) },
  recommendedPoint1: { maxLength: maxLength(128) },
  recommendedPoint2: { maxLength: maxLength(128) },
  recommendedPoint3: { maxLength: maxLength(128) },
  hostPostalCode: { required },
  hostPrefectureCode: { required },
  hostCity: { required },
  hostAddressLine1: { required },
  duration: { required },
  direction: { required, maxLength: maxLength(20000) },
  businessOpenTime: { required },
  businessCloseTime: { required },
}

export const UpdateExperienceValidationRules: ValidationArgs = {
  title: { required, maxLength: maxLength(128) },
  description: { required, maxLength: maxLength(20000) },
  public: {},
  soldOut: {},
  producerId: { required },
  experienceTypeId: { required },
  media: { maxLengthArray: maxLengthArray(8) },
  priceAdult: { required, minValue: minValue(0) },
  priceJuniorHighSchool: { required, minValue: minValue(0) },
  priceElementarySchool: { required, minValue: minValue(0) },
  pricePreschool: { required, minValue: minValue(0) },
  priceSenior: { required, minValue: minValue(0) },
  recommendedPoint1: { maxLength: maxLength(128) },
  recommendedPoint2: { maxLength: maxLength(128) },
  recommendedPoint3: { maxLength: maxLength(128) },
  hostPostalCode: { required },
  hostPrefectureCode: { required },
  hostCity: { required },
  hostAddressLine1: { required },
  duration: { required },
  direction: { required, maxLength: maxLength(20000) },
  businessOpenTime: { required },
  businessCloseTime: { required },
}
