CREATE TABLE IF NOT EXISTS `users`.`audit_logs` (
  `id`              VARCHAR(22)   NOT NULL,
  `created_at`      DATETIME(3)   NOT NULL,
  `admin_id`        VARCHAR(22)   NOT NULL DEFAULT '',
  `admin_type`      INT           NOT NULL DEFAULT 0,
  `action`          INT           NOT NULL DEFAULT 0,
  `resource_type`   VARCHAR(64)   NOT NULL DEFAULT '',
  `resource_id`     VARCHAR(64)   NOT NULL DEFAULT '',
  `result`          INT           NOT NULL DEFAULT 0,
  `result_detail`   VARCHAR(512)  NOT NULL DEFAULT '',
  `http_method`     VARCHAR(10)   NOT NULL DEFAULT '',
  `http_path`       VARCHAR(512)  NOT NULL DEFAULT '',
  `http_route`      VARCHAR(256)  NOT NULL DEFAULT '',
  `http_status`     INT           NOT NULL DEFAULT 0,
  `client_ip`       VARCHAR(45)   NOT NULL DEFAULT '',
  `user_agent`      TEXT          NOT NULL,
  `request_id`      VARCHAR(64)   NOT NULL DEFAULT '',
  `duration_ms`     INT           NOT NULL DEFAULT 0,
  `changed_fields`  JSON          NULL DEFAULT NULL,
  `metadata`        JSON          NULL DEFAULT NULL,
  `updated_at`      DATETIME(3)   NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_audit_logs_admin_id_created_at` (`admin_id`, `created_at` DESC),
  KEY `idx_audit_logs_resource_created_at` (`resource_type`, `resource_id`, `created_at` DESC),
  KEY `idx_audit_logs_created_at` (`created_at` DESC),
  KEY `idx_audit_logs_action_result` (`action`, `result`, `created_at` DESC)
);
