productStatus:
  type: integer
  format: int32
  description: 商品販売ステータス
  nullable: false
  enum:
  - 0
  - 1
  - 2
  - 3
  x-enum-varnames:
  - UNKNOWN
  - PRESALE
  - FOR_SALE
  - OUT_OF_SALES
  x-enum-descriptions:
  - 不明
  - 予約受付中
  - 販売中
  - 販売期間外
deliveryType:
  type: integer
  format: int32
  description: 配送方法
  nullable: false
  enum:
  - 0
  - 1
  - 2
  - 3
  x-enum-varnames:
  - UNKNOWN
  - NORMAL
  - REFRIGERATED
  - FROZEN
  x-enum-descriptions:
  - 不明
  - 常温便
  - 冷蔵便
  - 冷凍便
storageMethodType:
  type: integer
  format: int32
  description: 保管方法
  nullable: false
  enum:
  - 0
  - 1
  - 2
  - 3
  - 4
  x-enum-varnames:
  - UNKNOWN
  - NORMAL
  - COOL_DARK_PLACE
  - REFRIGERATED
  - FROZEN
  x-enum-descriptions:
  - 不明
  - 常温保存
  - 冷暗所保存
  - 冷蔵保存
  - 冷凍保存
