name: generate ecr url
description: 'ECRリポジトリ・イメージURLを生成する'

inputs:
  ecr-registry:
    description: 'ECRレジストリ名'
    required: true
  ecr-repository:
    description: 'ECRリポジトリ名'
    required: true
  image-tag:
    description: 'ECRイメージタグ'
    required: false
    default: 'latest'
outputs:
  ecr-repository-url:
    description: 'ECRリポジトリURL'
    value: ${{ steps.set-output.outputs.ecr-repository-url }}
  ecr-image-url:
    description: 'ECRイメージURL'
    value: ${{ steps.set-output.outputs.ecr-image-uri }}

runs:
  using: composite
  steps:
  - name: Set output
    id: set-output
    shell: bash
    run: |
      echo "ecr-repository-url=${ECR_REPOSITORY_URL}" >> $GITHUB_OUTPUT
      echo "ecr-image-url=${ECR_REPOSITORY_URL}:${IMAGE_TAG}" >> $GITHUB_OUTPUT
    env:
      ECR_REPOSITORY_URL: ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}
      IMAGE_TAG: ${{ inputs.image-tag }}
