/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RequestCheckoutExperienceRequest,
  RequestCheckoutProductRequest,
  ResponseCheckoutResponse,
  ResponseCheckoutStateResponse,
  ResponsePreCheckoutExperienceResponse,
  UtilErrorResponse,
} from '../models/index';
import {
    RequestCheckoutExperienceRequestFromJSON,
    RequestCheckoutExperienceRequestToJSON,
    RequestCheckoutProductRequestFromJSON,
    RequestCheckoutProductRequestToJSON,
    ResponseCheckoutResponseFromJSON,
    ResponseCheckoutResponseToJSON,
    ResponseCheckoutStateResponseFromJSON,
    ResponseCheckoutStateResponseToJSON,
    ResponsePreCheckoutExperienceResponseFromJSON,
    ResponsePreCheckoutExperienceResponseToJSON,
    UtilErrorResponseFromJSON,
    UtilErrorResponseToJSON,
} from '../models/index';

export interface CheckoutsExperiencesExperienceIdGetRequest {
    experienceId: string;
}

export interface CheckoutsExperiencesExperienceIdPostRequest {
    experienceId: string;
    requestCheckoutExperienceRequest: RequestCheckoutExperienceRequest;
}

export interface CheckoutsProductsPostRequest {
    requestCheckoutProductRequest: RequestCheckoutProductRequest;
}

export interface CheckoutsTransactionIdGetRequest {
    transactionId: string;
}

/**
 * 
 */
export class CheckoutApi extends runtime.BaseAPI {

    /**
     * 体験を決済する前に必要な情報を取得します。
     * 体験事前決済情報取得
     */
    async checkoutsExperiencesExperienceIdGetRaw(requestParameters: CheckoutsExperiencesExperienceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponsePreCheckoutExperienceResponse>> {
        if (requestParameters['experienceId'] == null) {
            throw new runtime.RequiredError(
                'experienceId',
                'Required parameter "experienceId" was null or undefined when calling checkoutsExperiencesExperienceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerauth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/checkouts/experiences/{experienceId}`.replace(`{${"experienceId"}}`, encodeURIComponent(String(requestParameters['experienceId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsePreCheckoutExperienceResponseFromJSON(jsonValue));
    }

    /**
     * 体験を決済する前に必要な情報を取得します。
     * 体験事前決済情報取得
     */
    async checkoutsExperiencesExperienceIdGet(requestParameters: CheckoutsExperiencesExperienceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponsePreCheckoutExperienceResponse> {
        const response = await this.checkoutsExperiencesExperienceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 体験の決済を実行し、予約を作成します。
     * 体験決済
     */
    async checkoutsExperiencesExperienceIdPostRaw(requestParameters: CheckoutsExperiencesExperienceIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseCheckoutResponse>> {
        if (requestParameters['experienceId'] == null) {
            throw new runtime.RequiredError(
                'experienceId',
                'Required parameter "experienceId" was null or undefined when calling checkoutsExperiencesExperienceIdPost().'
            );
        }

        if (requestParameters['requestCheckoutExperienceRequest'] == null) {
            throw new runtime.RequiredError(
                'requestCheckoutExperienceRequest',
                'Required parameter "requestCheckoutExperienceRequest" was null or undefined when calling checkoutsExperiencesExperienceIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerauth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/checkouts/experiences/{experienceId}`.replace(`{${"experienceId"}}`, encodeURIComponent(String(requestParameters['experienceId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestCheckoutExperienceRequestToJSON(requestParameters['requestCheckoutExperienceRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseCheckoutResponseFromJSON(jsonValue));
    }

    /**
     * 体験の決済を実行し、予約を作成します。
     * 体験決済
     */
    async checkoutsExperiencesExperienceIdPost(requestParameters: CheckoutsExperiencesExperienceIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseCheckoutResponse> {
        const response = await this.checkoutsExperiencesExperienceIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 商品の決済を実行し、注文を作成します。
     * 商品決済
     */
    async checkoutsProductsPostRaw(requestParameters: CheckoutsProductsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseCheckoutResponse>> {
        if (requestParameters['requestCheckoutProductRequest'] == null) {
            throw new runtime.RequiredError(
                'requestCheckoutProductRequest',
                'Required parameter "requestCheckoutProductRequest" was null or undefined when calling checkoutsProductsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerauth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/checkouts/products`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestCheckoutProductRequestToJSON(requestParameters['requestCheckoutProductRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseCheckoutResponseFromJSON(jsonValue));
    }

    /**
     * 商品の決済を実行し、注文を作成します。
     * 商品決済
     */
    async checkoutsProductsPost(requestParameters: CheckoutsProductsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseCheckoutResponse> {
        const response = await this.checkoutsProductsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 決済トランザクションの状態を取得します。
     * 決済状態取得
     */
    async checkoutsTransactionIdGetRaw(requestParameters: CheckoutsTransactionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseCheckoutStateResponse>> {
        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling checkoutsTransactionIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerauth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/checkouts/{transactionId}`.replace(`{${"transactionId"}}`, encodeURIComponent(String(requestParameters['transactionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseCheckoutStateResponseFromJSON(jsonValue));
    }

    /**
     * 決済トランザクションの状態を取得します。
     * 決済状態取得
     */
    async checkoutsTransactionIdGet(requestParameters: CheckoutsTransactionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseCheckoutStateResponse> {
        const response = await this.checkoutsTransactionIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
