/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaymentSystemsResponse,
} from '../models/index';
import {
    PaymentSystemsResponseFromJSON,
    PaymentSystemsResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class StatusApi extends runtime.BaseAPI {

    /**
     * 利用可能な支払手段の一覧を取得します。
     * 支払手段一覧取得
     */
    async statusesPaymentsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentSystemsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/statuses/payments`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentSystemsResponseFromJSON(jsonValue));
    }

    /**
     * 利用可能な支払手段の一覧を取得します。
     * 支払手段一覧取得
     */
    async statusesPaymentsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentSystemsResponse> {
        const response = await this.statusesPaymentsGetRaw(initOverrides);
        return await response.value();
    }

}
