openapi: 3.0.3
info:
  title: Marche Online
  description: マルシェ管理者用API
  version: 0.1.0
servers:
- url: http://localhost:18010
  description: 開発環境
tags:
- name: Auth
  description: 認証関連
- name: Administrator
  description: システム管理者関連
- name: Coordinator
  description: 仲介者関連
- name: Producer
  description: 生産者関連
- name: Category
  description: 商品種別関連
- name: ProductType
  description: 品目関連
- name: Product
  description: 商品関連
- name: Contact
  description: お問い合わせ関連
- name: Notification
  description: お知らせ関連
paths:
  # Auth
  /v1/auth:
    $ref: './paths/v1/auth/index.yaml'
  /v1/auth/refresh-token:
    $ref: './paths/v1/auth/refresh-token.yaml'
  /v1/auth/email:
    $ref: './paths/v1/auth/email/index.yaml'
  /v1/auth/email/verified:
    $ref: './paths/v1/auth/email/verified.yaml'
  /v1/auth/password:
    $ref: './paths/v1/auth/password.yaml'
  # Administrator
  /v1/administrators:
    $ref: './paths/v1/administrators/index.yaml'
  /v1/administrators/{adminId}:
    $ref: './paths/v1/administrators/_adminId/index.yaml'
  # Producer
  /v1/producers:
    $ref: './paths/v1/producers/index.yaml'
  /v1/producers/{producerId}:
    $ref: './paths/v1/producers/_producerId/index.yaml'
  # Category
  /v1/categories:
    $ref: './paths/v1/categories/index.yaml'
  /v1/categories/{categoryId}:
    $ref: './paths/v1/categories/_categoryId/index.yaml'
  # ProductType
  /v1/categories/-/product-types:
    $ref: './paths/v1/categories/-/product-types/index.yaml'
  /v1/categories/{categoryId}/product-types:
    $ref: './paths/v1/categories/_categoryId/product-types/index.yaml'
  /v1/categories/{categoryId}/product-types/{productTypeId}:
    $ref: './paths/v1/categories/_categoryId/product-types/_productTypeId/index.yaml'
  /v1/products:
    $ref: './paths/v1/products/index.yaml'
  /v1/products/{productId}:
    $ref: './paths/v1/products/_productId/index.yaml'
  # Contact
  /v1/contacts:
    $ref: './paths/v1/contacts/index.yaml'
  /v1/contacts/{contactId}:
    $ref: './paths/v1/contacts/_contactId/index.yaml'
  # Notification
  /v1/notifications:
    $ref: './paths/v1/notifications/index.yaml'
  # Upload
  /v1/upload/coordinators/header:
    $ref: './paths/v1/upload/coordinators/header.yaml'
  /v1/upload/coordinators/thumbnail:
    $ref: './paths/v1/upload/coordinators/thumbnail.yaml'
  /v1/upload/producers/header:
    $ref: './paths/v1/upload/producers/header.yaml'
  /v1/upload/producers/thumbnail:
    $ref: './paths/v1/upload/producers/thumbnail.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    # Common
    errorResponse:
      $ref: './components/schemas/common.yaml#/errorResponse'
    # Request
    v1SignInRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/signInRequest'
    v1RefreshAuthTokenRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/refreshAuthTokenRequest'
    v1UpdateAuthEmailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthEmailRequest'
    v1VerifyAuthEmailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/verifyAuthEmailRequest'
    v1UpdateAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthPasswordRequest'
    v1CreateAdministratorRequest:
      $ref: './components/schemas/v1/administrator.request.yaml#/createAdministratorRequest'
    v1CreateProducerRequest:
      $ref: './components/schemas/v1/producer.request.yaml#/createProducerRequest'
    v1CreateCategoryRequest:
      $ref: './components/schemas/v1/category.request.yaml#/createCategoryRequest'
    v1UpdateCategoryRequest:
      $ref: './components/schemas/v1/category.request.yaml#/updateCategoryRequest'
    v1CreateProductTypeRequest:
      $ref: './components/schemas/v1/product_type.request.yaml#/createProductTypeRequest'
    v1UpdateProductTypeRequest:
      $ref: './components/schemas/v1/product_type.request.yaml#/updateProductTypeRequest'
    v1CreateProductRequest:
      $ref: './components/schemas/v1/product.request.yaml#/createProductRequest'
    v1UpdateProductRequest:
      $ref: './components/schemas/v1/product.request.yaml#/updateProductRequest'
    v1UpdateContactRequest:
      $ref: './components/schemas/v1/contact.request.yaml#/updateContactRequest'
    v1CreateNotificationRequest:
      $ref: './components/schemas/v1/notification.request.yaml#/createNotificationRequest'
    v1UploadCoordinatorThumbnailRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadCoordinatorThumbnailRequest'
    v1UploadCoordinatorHeaderRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadCoordinatorHeaderRequest'
    v1UploadProducerThumbnailRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadProducerThumbnailRequest'
    v1UploadProducerHeaderRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadProducerHeaderRequest'
    # Response
    v1AuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authResponse'
    v1AdministratorResponse:
      $ref: './components/schemas/v1/administrator.response.yaml#/administratorResponse'
    v1AdministratorsResponse:
      $ref: './components/schemas/v1/administrator.response.yaml#/administratorsResponse'
    v1ProducerResponse:
      $ref: './components/schemas/v1/producer.response.yaml#/producerResponse'
    v1ProducersResponse:
      $ref: './components/schemas/v1/producer.response.yaml#/producersResponse'
    v1CategoryResponse:
      $ref: './components/schemas/v1/category.response.yaml#/categoryResponse'
    v1CategoriesResponse:
      $ref: './components/schemas/v1/category.response.yaml#/categoriesResponse'
    v1ProductTypeResponse:
      $ref: './components/schemas/v1/product_type.response.yaml#/productTypeResponse'
    v1ProductTypesResponse:
      $ref: './components/schemas/v1/product_type.response.yaml#/productTypesResponse'
    v1ProductResponse:
      $ref: './components/schemas/v1/product.response.yaml#/productResponse'
    v1ProductsResponse:
      $ref: './components/schemas/v1/product.response.yaml#/productsResponse'
    v1ContactResponse:
      $ref: './components/schemas/v1/contact.response.yaml#/contactResponse'
    v1ContactsResponse:
      $ref: './components/schemas/v1/contact.response.yaml#/contactsResponse'
    v1NotificationResponse:
      $ref: './components/schemas/v1/notification.response.yaml#/notificationResponse'
    v1UploadImageResponse:
      $ref: './components/schemas/v1/upload.response.yaml#/uploadImageResponse'
