openapi: 3.0.3
info:
  title: Marche Online
  description: マルシェ管理者用API
  version: 0.1.0
servers:
- url: http://localhost:18010
  description: 開発環境
tags:
- name: Auth
  description: 認証関連
- name: Admin
  description: システム管理者関連
- name: Coordinator
  description: 仲介者関連
- name: Producer
  description: 生産者関連
paths:
  # Auth
  /v1/auth:
    $ref: './paths/v1/auth/index.yaml'
  /v1/auth/refresh-token:
    $ref: './paths/v1/auth/refresh-token.yaml'
  /v1/auth/email:
    $ref: './paths/v1/auth/email/index.yaml'
  /v1/auth/email/verified:
    $ref: './paths/v1/auth/email/verified.yaml'
  /v1/auth/password:
    $ref: './paths/v1/auth/password.yaml'
  /v1/auth/user:
    $ref: './paths/v1/auth/user.yaml'
  # Admin
  /v1/admins:
    $ref: './paths/v1/admins/index.yaml'
  /v1/admins/{adminId}:
    $ref: './paths/v1/admins/_adminId/index.yaml'
  # Upload
  /v1/upload/coordinators/thumbnail:
    $ref: './paths/v1/upload/coordinators/thumbnail.yaml'
  /v1/upload/producers/thumbnail:
    $ref: './paths/v1/upload/producers/thumbnail.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    # Common
    errorResponse:
      $ref: './components/schemas/common.yaml#/errorResponse'
    # Request
    v1SignInRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/signInRequest'
    v1RefreshAuthTokenRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/refreshAuthTokenRequest'
    v1UpdateAuthEmailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthEmailRequest'
    v1VerifyAuthEmailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/verifyAuthEmailRequest'
    v1UpdateAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthPasswordRequest'
    v1CreateAdminRequest:
      $ref: './components/schemas/v1/admins.request.yaml#/createAdminRequest'
    v1UploadCoordinatorThumbnailRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadCoordinatorThumbnailRequest'
    v1UploadProducerThumbnailRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadProducerThumbnailRequest'
    # Response
    v1AuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authResponse'
    v1AuthUserResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authUserResponse'
    v1AdminResponse:
      $ref: './components/schemas/v1/admins.response.yaml#/adminResponse'
    v1AdminsResponse:
      $ref: './components/schemas/v1/admins.response.yaml#/adminsResponse'
    v1UploadImageResponse:
      $ref: './components/schemas/v1/upload.response.yaml#/uploadImageResponse'
