openapi: 3.0.3
info:
  title: Marche Online
  description: マルシェ管理者用API
  version: 0.1.0
servers:
- url: http://localhost:18020
  description: 開発環境
tags:
- name: Auth
  description: 認証関連
- name: Admin
  description: 管理者関連
paths:
  # Auth
  /v1/auth:
    $ref: './paths/v1/auth/index.yaml'
  /v1/auth/refresh-token:
    $ref: './paths/v1/auth/refresh-token.yaml'
  # Admin
  /v1/admins/me:
    $ref: './paths/v1/admins/me/index.yaml'
  /v1/admins/me/email:
    $ref: './paths/v1/admins/me/email/index.yaml'
  /v1/admins/me/email/verified:
    $ref: './paths/v1/admins/me/email/verified.yaml'
  /v1/admins/me/password:
    $ref: './paths/v1/admins/me/password.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    # Common
    errorResponse:
      $ref: './components/schemas/common.yaml#/errorResponse'
    # Request
    v1SignInRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/signInRequest'
    v1RefreshAuthTokenRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/refreshAuthTokenRequest'
    v1UpdateAdminEmailRequest:
      $ref: './components/schemas/v1/admins.request.yaml#/updateAdminEmailRequest'
    v1VerifyAdminEmailRequest:
      $ref: './components/schemas/v1/admins.request.yaml#/verifyAdminEmailRequest'
    v1UpdateAdminPasswordRequest:
      $ref: './components/schemas/v1/admins.request.yaml#/updateAdminPasswordRequest'
    # Response
    v1AuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authResponse'
    v1AdminMeResponse:
      $ref: './components/schemas/v1/admins.response.yaml#/adminMeResponse'
