openapi: 3.0.3
info:
  title: Marche Online
  description: マルシェ管理者用API
  version: 0.1.0
servers:
- url: http://localhost:18010
  description: 開発環境
- url: https://admin-api.furumaru-stg.and-period.work
  description: 検証環境
tags:
- name: Auth
  description: 認証関連
- name: Administrator
  description: システム管理者関連
- name: Coordinator
  description: コーディネータ関連
- name: Producer
  description: 生産者関連
- name: Category
  description: 商品種別関連
- name: ProductType
  description: 品目関連
- name: Product
  description: 商品関連
- name: Shipping
  description: 配送設定関連
- name: Promotion
  description: プロモーション関連
- name: Schedule
  description: スケジュール関連
- name: Live
  description: 配信関連
- name: Order
  description: 注文関連
- name: User
  description: 購入者関連
- name: Address
  description: 住所関連
- name: Contact
  description: お問い合わせ関連
- name: Notification
  description: お知らせ関連
- name: Message
  description: メッセージ関連
paths:
  # Auth
  /v1/auth:
    $ref: './paths/v1/auth/index.yaml'
  /v1/auth/refresh-token:
    $ref: './paths/v1/auth/refresh-token.yaml'
  /v1/auth/device:
    $ref: './paths/v1/auth/device.yaml'
  /v1/auth/email:
    $ref: './paths/v1/auth/email/index.yaml'
  /v1/auth/email/verified:
    $ref: './paths/v1/auth/email/verified.yaml'
  /v1/auth/password:
    $ref: './paths/v1/auth/password.yaml'
  # Administrator
  /v1/administrators:
    $ref: './paths/v1/administrators/index.yaml'
  /v1/administrators/{adminId}:
    $ref: './paths/v1/administrators/_adminId/index.yaml'
  /v1/administrators/{adminId}/email:
    $ref: './paths/v1/administrators/_adminId/email.yaml'
  /v1/administrators/{adminId}/password:
    $ref: './paths/v1/administrators/_adminId/password.yaml'
  # Coordinator
  /v1/coordinators:
    $ref: './paths/v1/coordinators/index.yaml'
  /v1/coordinators/{coordinatorId}:
    $ref: './paths/v1/coordinators/_coordinatorId/index.yaml'
  /v1/coordinators/{coordinatorId}/email:
    $ref: './paths/v1/coordinators/_coordinatorId/email.yaml'
  /v1/coordinators/{coordinatorId}/password:
    $ref: './paths/v1/coordinators/_coordinatorId/password.yaml'
  /v1/coordinators/{coordinatorId}/producers:
    $ref: './paths/v1/coordinators/_coordinatorId/producers/index.yaml'
  /v1/coordinators/{coordinatorId}/producers/{producerId}:
    $ref: './paths/v1/coordinators/_coordinatorId/producers/_producerId/index.yaml'
  # Producer
  /v1/producers:
    $ref: './paths/v1/producers/index.yaml'
  /v1/producers/{producerId}:
    $ref: './paths/v1/producers/_producerId/index.yaml'
  /v1/producers/{producerId}/email:
    $ref: './paths/v1/producers/_producerId/email.yaml'
  /v1/producers/{producerId}/password:
    $ref: './paths/v1/producers/_producerId/password.yaml'
  # Category
  /v1/categories:
    $ref: './paths/v1/categories/index.yaml'
  /v1/categories/{categoryId}:
    $ref: './paths/v1/categories/_categoryId/index.yaml'
  # ProductType
  /v1/categories/-/product-types:
    $ref: './paths/v1/categories/-/product-types/index.yaml'
  /v1/categories/{categoryId}/product-types:
    $ref: './paths/v1/categories/_categoryId/product-types/index.yaml'
  /v1/categories/{categoryId}/product-types/{productTypeId}:
    $ref: './paths/v1/categories/_categoryId/product-types/_productTypeId/index.yaml'
  /v1/products:
    $ref: './paths/v1/products/index.yaml'
  /v1/products/{productId}:
    $ref: './paths/v1/products/_productId/index.yaml'
  # Shipping
  /v1/shippings:
    $ref: './paths/v1/shippings/index.yaml'
  /v1/shippings/{shippingId}:
    $ref: './paths/v1/shippings/_shippingId/index.yaml'
  # Promotion
  /v1/promotions:
    $ref: './paths/v1/promotions/index.yaml'
  /v1/promotions/{promotionId}:
    $ref: './paths/v1/promotions/_promotionId/index.yaml'
  # Contact
  /v1/contacts:
    $ref: './paths/v1/contacts/index.yaml'
  /v1/contacts/{contactId}:
    $ref: './paths/v1/contacts/_contactId/index.yaml'
  # Notification
  /v1/notifications:
    $ref: './paths/v1/notifications/index.yaml'
  /v1/notifications/{notificationId}:
    $ref: './paths/v1/notifications/_notificationId/index.yaml'
  # Message
  /v1/messages:
    $ref: './paths/v1/messages/index.yaml'
  /v1/messages/{messageId}:
    $ref: './paths/v1/messages/_messageId/index.yaml'
  # Schedule
  /v1/schedules:
    $ref: './paths/v1/schedules/index.yaml'
  /v1/schedules/{scheduleId}:
    $ref: './paths/v1/schedules/_scheduleId/index.yaml'
  # Live
  /v1/schedules/{scheduleId}/Lives/{liveId}:
    $ref: './paths/v1/schedules/_scheduleId/lives/_liveId/index.yaml'
  # Order
  /v1/orders:
    $ref: './paths/v1/orders/index.yaml'
  /v1/orders/{orderId}:
    $ref: './paths/v1/orders/_orderId/index.yaml'
  # User
  /v1/users:
    $ref: './paths/v1/users/index.yaml'
  /v1/users/{userId}:
    $ref: './paths/v1/users/_userId/index.yaml'
  # Address
  /v1/postal-codes/{postalCode}:
    $ref: './paths/v1/postal-codes/_postalCode.yaml'
  # Upload
  /v1/upload/coordinators/header:
    $ref: './paths/v1/upload/coordinators/header.yaml'
  /v1/upload/coordinators/thumbnail:
    $ref: './paths/v1/upload/coordinators/thumbnail.yaml'
  /v1/upload/producers/header:
    $ref: './paths/v1/upload/producers/header.yaml'
  /v1/upload/producers/thumbnail:
    $ref: './paths/v1/upload/producers/thumbnail.yaml'
  /v1/upload/products/image:
    $ref: './paths/v1/upload/products/image.yaml'
  /v1/upload/products/video:
    $ref: './paths/v1/upload/products/video.yaml'
  /v1/upload/product-types/icon:
    $ref: './paths/v1/upload/product-types/icon.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    # Common
    adminRole:
      $ref: './components/schemas/codes/auth.yaml#/adminRole'
    prefecture:
      $ref: './components/schemas/codes/common.yaml#/prefecture'
    contactStatus:
      $ref: './components/schemas/codes/contact.yaml#/contactStatus'
    contactPriority:
      $ref: './components/schemas/codes/contact.yaml#/contactPriority'
    imageSize:
      $ref: './components/schemas/codes/image.yaml#/imageSize'
    liveStatus:
      $ref: './components/schemas/codes/live.yaml#/liveStatus'
    messageType:
      $ref: './components/schemas/codes/message.yaml#/messageType'
    notificationTargetType:
      $ref: './components/schemas/codes/notification.yaml#/notificationTargetType'
    fulfillmentStatus:
      $ref: './components/schemas/codes/order_fulfillment.yaml#/fulfillmentStatus'
    shippingCarrier:
      $ref: './components/schemas/codes/order_fulfillment.yaml#/shippingCarrier'
    shippingSize:
      $ref: './components/schemas/codes/order_fulfillment.yaml#/shippingSize'
    paymentMethodType:
      $ref: './components/schemas/codes/order_payment.yaml#/paymentMethodType'
    paymentStatus:
      $ref: './components/schemas/codes/order_payment.yaml#/paymentStatus'
    orderRefundType:
      $ref: './components/schemas/codes/order_refund.yaml#/orderRefundType'
    deliveryType:
      $ref: './components/schemas/codes/product.yaml#/deliveryType'
    discountType:
      $ref: './components/schemas/codes/promotion.yaml#/discountType'
    errorResponse:
      $ref: './components/schemas/common.yaml#/errorResponse'
    # Request
    v1SignInRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/signInRequest'
    v1RefreshAuthTokenRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/refreshAuthTokenRequest'
    v1RegisterAuthDeviceRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/registerAuthDeviceRequest'
    v1UpdateAuthEmailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthEmailRequest'
    v1VerifyAuthEmailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/verifyAuthEmailRequest'
    v1UpdateAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthPasswordRequest'
    v1CreateAdministratorRequest:
      $ref: './components/schemas/v1/administrator.request.yaml#/createAdministratorRequest'
    v1UpdateAdministratorRequest:
      $ref: './components/schemas/v1/administrator.request.yaml#/updateAdministratorRequest'
    v1UpdateAdministratorEmailRequest:
      $ref: './components/schemas/v1/administrator.request.yaml#/updateAdministratorEmailRequest'
    v1CreateCoordinatorRequest:
      $ref: './components/schemas/v1/coordinator.request.yaml#/createCoordinatorRequest'
    v1UpdateCoordinatorRequest:
      $ref: './components/schemas/v1/coordinator.request.yaml#/updateCoordinatorRequest'
    v1UpdateCoordinatorEmailRequest:
      $ref: './components/schemas/v1/coordinator.request.yaml#/updateCoordinatorEmailRequest'
    v1CreateProducerRequest:
      $ref: './components/schemas/v1/producer.request.yaml#/createProducerRequest'
    v1UpdateProducerRequest:
      $ref: './components/schemas/v1/producer.request.yaml#/updateProducerRequest'
    v1UpdateProducerEmailRequest:
      $ref: './components/schemas/v1/producer.request.yaml#/updateProducerEmailRequest'
    v1RelateProducersRequest:
      $ref: './components/schemas/v1/producer.request.yaml#/relateProducersRequest'
    v1CreateCategoryRequest:
      $ref: './components/schemas/v1/category.request.yaml#/createCategoryRequest'
    v1UpdateCategoryRequest:
      $ref: './components/schemas/v1/category.request.yaml#/updateCategoryRequest'
    v1CreateProductTypeRequest:
      $ref: './components/schemas/v1/product_type.request.yaml#/createProductTypeRequest'
    v1UpdateProductTypeRequest:
      $ref: './components/schemas/v1/product_type.request.yaml#/updateProductTypeRequest'
    v1CreateProductRequest:
      $ref: './components/schemas/v1/product.request.yaml#/createProductRequest'
    v1UpdateProductRequest:
      $ref: './components/schemas/v1/product.request.yaml#/updateProductRequest'
    v1CreateShippingRequest:
      $ref: './components/schemas/v1/shipping.request.yaml#/createShippingRequest'
    v1UpdateShippingRequest:
      $ref: './components/schemas/v1/shipping.request.yaml#/updateShippingRequest'
    v1CreatePromotionRequest:
      $ref: './components/schemas/v1/promotion.request.yaml#/createPromotionRequest'
    v1UpdatePromotionRequest:
      $ref: './components/schemas/v1/promotion.request.yaml#/updatePromotionRequest'
    v1UpdateContactRequest:
      $ref: './components/schemas/v1/contact.request.yaml#/updateContactRequest'
    v1CreateNotificationRequest:
      $ref: './components/schemas/v1/notification.request.yaml#/createNotificationRequest'
    v1UpdateNotificationRequest:
      $ref: './components/schemas/v1/notification.request.yaml#/updateNotificationRequest'
    v1CreateScheduleRequest:
      $ref: './components/schemas/v1/schedule.request.yaml#/createScheduleRequest'
    v1UploadCoordinatorThumbnailRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadCoordinatorThumbnailRequest'
    v1UploadCoordinatorHeaderRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadCoordinatorHeaderRequest'
    v1UploadProducerThumbnailRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadProducerThumbnailRequest'
    v1UploadProducerHeaderRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadProducerHeaderRequest'
    v1UploadProductImageRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadProductImageRequest'
    v1UploadProductVideoRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadProductVideoRequest'
    v1UploadProductTypeIconRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadProductTypeIconRequest'
    # Response
    v1AuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authResponse'
    v1AdministratorResponse:
      $ref: './components/schemas/v1/administrator.response.yaml#/administratorResponse'
    v1AdministratorsResponse:
      $ref: './components/schemas/v1/administrator.response.yaml#/administratorsResponse'
    v1CoordinatorResponse:
      $ref: './components/schemas/v1/coordinator.response.yaml#/coordinatorResponse'
    v1CoordinatorsResponse:
      $ref: './components/schemas/v1/coordinator.response.yaml#/coordinatorsResponse'
    v1ProducerResponse:
      $ref: './components/schemas/v1/producer.response.yaml#/producerResponse'
    v1ProducersResponse:
      $ref: './components/schemas/v1/producer.response.yaml#/producersResponse'
    v1CategoryResponse:
      $ref: './components/schemas/v1/category.response.yaml#/categoryResponse'
    v1CategoriesResponse:
      $ref: './components/schemas/v1/category.response.yaml#/categoriesResponse'
    v1ProductTypeResponse:
      $ref: './components/schemas/v1/product_type.response.yaml#/productTypeResponse'
    v1ProductTypesResponse:
      $ref: './components/schemas/v1/product_type.response.yaml#/productTypesResponse'
    v1ProductResponse:
      $ref: './components/schemas/v1/product.response.yaml#/productResponse'
    v1ProductsResponse:
      $ref: './components/schemas/v1/product.response.yaml#/productsResponse'
    v1ShippingResponse:
      $ref: './components/schemas/v1/shipping.response.yaml#/shippingResponse'
    v1ShippingsResponse:
      $ref: './components/schemas/v1/shipping.response.yaml#/shippingsResponse'
    v1PromotionResponse:
      $ref: './components/schemas/v1/promotion.response.yaml#/promotionResponse'
    v1PromotionsResponse:
      $ref: './components/schemas/v1/promotion.response.yaml#/promotionsResponse'
    v1ContactResponse:
      $ref: './components/schemas/v1/contact.response.yaml#/contactResponse'
    v1ContactsResponse:
      $ref: './components/schemas/v1/contact.response.yaml#/contactsResponse'
    v1NotificationResponse:
      $ref: './components/schemas/v1/notification.response.yaml#/notificationResponse'
    v1NotificationsResponse:
      $ref: './components/schemas/v1/notification.response.yaml#/notificationsResponse'
    v1MessageResponse:
      $ref: './components/schemas/v1/message.response.yaml#/messageResponse'
    v1MessagesResponse:
      $ref: './components/schemas/v1/message.response.yaml#/messagesResponse'
    v1ScheduleResponse:
      $ref: './components/schemas/v1/schedule.response.yaml#/scheduleResponse'
    v1LiveResponse:
      $ref: './components/schemas/v1/live.response.yaml#/liveResponse'
    v1OrderResponse:
      $ref: './components/schemas/v1/order.response.yaml#/orderResponse'
    v1OrdersResponse:
      $ref: './components/schemas/v1/order.response.yaml#/ordersResponse'
    v1UserResponse:
      $ref: './components/schemas/v1/user.response.yaml#/userResponse'
    v1UsersResponse:
      $ref: './components/schemas/v1/user.response.yaml#/usersResponse'
    v1PostalCodeResponse:
      $ref: './components/schemas/v1/postal_code.response.yaml#/postalCodeResponse'
    v1UploadImageResponse:
      $ref: './components/schemas/v1/upload.response.yaml#/uploadImageResponse'
    v1UploadVideoResponse:
      $ref: './components/schemas/v1/upload.response.yaml#/uploadVideoResponse'
