openapi: 3.0.3
info:
  title: Marche Online
  description: マルシェ管理者用API
  version: 0.1.0
servers:
- url: http://localhost:18010
  description: 開発環境
tags:
- name: Auth
  description: 認証関連
- name: Administrator
  description: システム管理者関連
- name: Coordinator
  description: 仲介者関連
- name: Producer
  description: 生産者関連
paths:
  # Auth
  /v1/auth:
    $ref: './paths/v1/auth/index.yaml'
  /v1/auth/refresh-token:
    $ref: './paths/v1/auth/refresh-token.yaml'
  /v1/auth/email:
    $ref: './paths/v1/auth/email/index.yaml'
  /v1/auth/email/verified:
    $ref: './paths/v1/auth/email/verified.yaml'
  /v1/auth/password:
    $ref: './paths/v1/auth/password.yaml'
  /v1/auth/user:
    $ref: './paths/v1/auth/user.yaml'
  # Administrator
  /v1/administrators:
    $ref: './paths/v1/administrators/index.yaml'
  /v1/administrators/{adminId}:
    $ref: './paths/v1/administrators/_adminId/index.yaml'
  # Producer
  /v1/producers:
    $ref: './paths/v1/producers/index.yaml'
  /v1/producers/{adminId}:
    $ref: './paths/v1/producers/_producerId/index.yaml'
  # Upload
  /v1/upload/coordinators/thumbnail:
    $ref: './paths/v1/upload/coordinators/thumbnail.yaml'
  /v1/upload/producers/thumbnail:
    $ref: './paths/v1/upload/producers/thumbnail.yaml'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    # Common
    errorResponse:
      $ref: './components/schemas/common.yaml#/errorResponse'
    # Request
    v1SignInRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/signInRequest'
    v1RefreshAuthTokenRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/refreshAuthTokenRequest'
    v1UpdateAuthEmailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthEmailRequest'
    v1VerifyAuthEmailRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/verifyAuthEmailRequest'
    v1UpdateAuthPasswordRequest:
      $ref: './components/schemas/v1/auth.request.yaml#/updateAuthPasswordRequest'
    v1CreateAdministratorRequest:
      $ref: './components/schemas/v1/administrators.request.yaml#/createAdministratorRequest'
    v1CreateProducerRequest:
      $ref: './components/schemas/v1/producers.request.yaml#/createProducerRequest'
    v1UploadCoordinatorThumbnailRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadCoordinatorThumbnailRequest'
    v1UploadProducerThumbnailRequest:
      $ref: './components/schemas/v1/upload.request.yaml#/uploadProducerThumbnailRequest'
    # Response
    v1AuthResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authResponse'
    v1AuthUserResponse:
      $ref: './components/schemas/v1/auth.response.yaml#/authUserResponse'
    v1AdministratorResponse:
      $ref: './components/schemas/v1/administrators.response.yaml#/administratorResponse'
    v1AdministratorsResponse:
      $ref: './components/schemas/v1/administrators.response.yaml#/administratorsResponse'
    v1ProducerResponse:
      $ref: './components/schemas/v1/producers.response.yaml#/producerResponse'
    v1ProducersResponse:
      $ref: './components/schemas/v1/producers.response.yaml#/producersResponse'
    v1UploadImageResponse:
      $ref: './components/schemas/v1/upload.response.yaml#/uploadImageResponse'
