/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAuthUserResponse
 */
export interface CreateAuthUserResponse {
    /**
     * ユーザーID
     * @type {string}
     * @memberof CreateAuthUserResponse
     */
    id: string;
}

/**
 * Check if a given object implements the CreateAuthUserResponse interface.
 */
export function instanceOfCreateAuthUserResponse(value: object): value is CreateAuthUserResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CreateAuthUserResponseFromJSON(json: any): CreateAuthUserResponse {
    return CreateAuthUserResponseFromJSONTyped(json, false);
}

export function CreateAuthUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAuthUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CreateAuthUserResponseToJSON(json: any): CreateAuthUserResponse {
    return CreateAuthUserResponseToJSONTyped(json, false);
}

export function CreateAuthUserResponseToJSONTyped(value?: CreateAuthUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

