/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiveComment
 */
export interface LiveComment {
    /**
     * アカウントID
     * @type {string}
     * @memberof LiveComment
     */
    accountId?: string;
    /**
     * コメント
     * @type {string}
     * @memberof LiveComment
     */
    comment?: string;
    /**
     * 投稿日時
     * @type {number}
     * @memberof LiveComment
     */
    publishedAt?: number;
    /**
     * サムネイルURL
     * @type {string}
     * @memberof LiveComment
     */
    thumbnailUrl?: string;
    /**
     * ユーザーID
     * @type {string}
     * @memberof LiveComment
     */
    userId?: string;
    /**
     * ユーザー名
     * @type {string}
     * @memberof LiveComment
     */
    username?: string;
}

/**
 * Check if a given object implements the LiveComment interface.
 */
export function instanceOfLiveComment(value: object): value is LiveComment {
    return true;
}

export function LiveCommentFromJSON(json: any): LiveComment {
    return LiveCommentFromJSONTyped(json, false);
}

export function LiveCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveComment {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'publishedAt': json['publishedAt'] == null ? undefined : json['publishedAt'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function LiveCommentToJSON(value?: LiveComment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountId': value['accountId'],
        'comment': value['comment'],
        'publishedAt': value['publishedAt'],
        'thumbnailUrl': value['thumbnailUrl'],
        'userId': value['userId'],
        'username': value['username'],
    };
}

