/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LiveComment } from './LiveComment';
import {
    LiveCommentFromJSON,
    LiveCommentFromJSONTyped,
    LiveCommentToJSON,
} from './LiveComment';

/**
 * 
 * @export
 * @interface LiveCommentsResponse
 */
export interface LiveCommentsResponse {
    /**
     * コメント一覧
     * @type {Array<LiveComment>}
     * @memberof LiveCommentsResponse
     */
    comments?: Array<LiveComment>;
    /**
     * 次の取得開始位置
     * @type {string}
     * @memberof LiveCommentsResponse
     */
    nextToken?: string;
}

/**
 * Check if a given object implements the LiveCommentsResponse interface.
 */
export function instanceOfLiveCommentsResponse(value: object): value is LiveCommentsResponse {
    return true;
}

export function LiveCommentsResponseFromJSON(json: any): LiveCommentsResponse {
    return LiveCommentsResponseFromJSONTyped(json, false);
}

export function LiveCommentsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveCommentsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': json['comments'] == null ? undefined : ((json['comments'] as Array<any>).map(LiveCommentFromJSON)),
        'nextToken': json['nextToken'] == null ? undefined : json['nextToken'],
    };
}

export function LiveCommentsResponseToJSON(value?: LiveCommentsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comments': value['comments'] == null ? undefined : ((value['comments'] as Array<any>).map(LiveCommentToJSON)),
        'nextToken': value['nextToken'],
    };
}

