/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
} from './Order';
import type { Experience } from './Experience';
import {
    ExperienceFromJSON,
    ExperienceFromJSONTyped,
    ExperienceToJSON,
} from './Experience';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';
import type { Coordinator } from './Coordinator';
import {
    CoordinatorFromJSON,
    CoordinatorFromJSONTyped,
    CoordinatorToJSON,
} from './Coordinator';
import type { Promotion } from './Promotion';
import {
    PromotionFromJSON,
    PromotionFromJSONTyped,
    PromotionToJSON,
} from './Promotion';

/**
 * 
 * @export
 * @interface OrdersResponse
 */
export interface OrdersResponse {
    /**
     * コーディネータ一覧
     * @type {Array<Coordinator>}
     * @memberof OrdersResponse
     */
    coordinators?: Array<Coordinator>;
    /**
     * 体験一覧
     * @type {Array<Experience>}
     * @memberof OrdersResponse
     */
    experiences?: Array<Experience>;
    /**
     * 注文履歴一覧
     * @type {Array<Order>}
     * @memberof OrdersResponse
     */
    orders?: Array<Order>;
    /**
     * 商品一覧
     * @type {Array<Product>}
     * @memberof OrdersResponse
     */
    products?: Array<Product>;
    /**
     * プロモーション一覧
     * @type {Array<Promotion>}
     * @memberof OrdersResponse
     */
    promotions?: Array<Promotion>;
    /**
     * 合計数
     * @type {number}
     * @memberof OrdersResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the OrdersResponse interface.
 */
export function instanceOfOrdersResponse(value: object): value is OrdersResponse {
    return true;
}

export function OrdersResponseFromJSON(json: any): OrdersResponse {
    return OrdersResponseFromJSONTyped(json, false);
}

export function OrdersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrdersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinators': json['coordinators'] == null ? undefined : ((json['coordinators'] as Array<any>).map(CoordinatorFromJSON)),
        'experiences': json['experiences'] == null ? undefined : ((json['experiences'] as Array<any>).map(ExperienceFromJSON)),
        'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(OrderFromJSON)),
        'products': json['products'] == null ? undefined : ((json['products'] as Array<any>).map(ProductFromJSON)),
        'promotions': json['promotions'] == null ? undefined : ((json['promotions'] as Array<any>).map(PromotionFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function OrdersResponseToJSON(value?: OrdersResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'coordinators': value['coordinators'] == null ? undefined : ((value['coordinators'] as Array<any>).map(CoordinatorToJSON)),
        'experiences': value['experiences'] == null ? undefined : ((value['experiences'] as Array<any>).map(ExperienceToJSON)),
        'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(OrderToJSON)),
        'products': value['products'] == null ? undefined : ((value['products'] as Array<any>).map(ProductToJSON)),
        'promotions': value['promotions'] == null ? undefined : ((value['promotions'] as Array<any>).map(PromotionToJSON)),
        'total': value['total'],
    };
}

