/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Experience } from './Experience';
import {
    ExperienceFromJSON,
    ExperienceFromJSONTyped,
    ExperienceToJSON,
} from './Experience';
import type { Promotion } from './Promotion';
import {
    PromotionFromJSON,
    PromotionFromJSONTyped,
    PromotionToJSON,
} from './Promotion';

/**
 * 
 * @export
 * @interface PreCheckoutExperienceResponse
 */
export interface PreCheckoutExperienceResponse {
    /**
     * 割引金額(税込)
     * @type {number}
     * @memberof PreCheckoutExperienceResponse
     */
    discount?: number;
    /**
     * 
     * @type {Experience}
     * @memberof PreCheckoutExperienceResponse
     */
    experience?: Experience;
    /**
     * 
     * @type {Promotion}
     * @memberof PreCheckoutExperienceResponse
     */
    promotion?: Promotion;
    /**
     * 支払い時にAPIへ送信するキー(重複判定用)
     * @type {string}
     * @memberof PreCheckoutExperienceResponse
     */
    requestId?: string;
    /**
     * 購入金額(税込)
     * @type {number}
     * @memberof PreCheckoutExperienceResponse
     */
    subtotal?: number;
    /**
     * 合計金額(税込)
     * @type {number}
     * @memberof PreCheckoutExperienceResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the PreCheckoutExperienceResponse interface.
 */
export function instanceOfPreCheckoutExperienceResponse(value: object): value is PreCheckoutExperienceResponse {
    return true;
}

export function PreCheckoutExperienceResponseFromJSON(json: any): PreCheckoutExperienceResponse {
    return PreCheckoutExperienceResponseFromJSONTyped(json, false);
}

export function PreCheckoutExperienceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreCheckoutExperienceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'discount': json['discount'] == null ? undefined : json['discount'],
        'experience': json['experience'] == null ? undefined : ExperienceFromJSON(json['experience']),
        'promotion': json['promotion'] == null ? undefined : PromotionFromJSON(json['promotion']),
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'subtotal': json['subtotal'] == null ? undefined : json['subtotal'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function PreCheckoutExperienceResponseToJSON(value?: PreCheckoutExperienceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'discount': value['discount'],
        'experience': ExperienceToJSON(value['experience']),
        'promotion': PromotionToJSON(value['promotion']),
        'requestId': value['requestId'],
        'subtotal': value['subtotal'],
        'total': value['total'],
    };
}

