/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestCreateAuthUserRequest
 */
export interface RequestCreateAuthUserRequest {
    /**
     * ユーザーID(検索名)
     * @type {string}
     * @memberof RequestCreateAuthUserRequest
     */
    accountId?: string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof RequestCreateAuthUserRequest
     */
    email?: string;
    /**
     * 名
     * @type {string}
     * @memberof RequestCreateAuthUserRequest
     */
    firstname?: string;
    /**
     * 名（かな）
     * @type {string}
     * @memberof RequestCreateAuthUserRequest
     */
    firstnameKana?: string;
    /**
     * 姓
     * @type {string}
     * @memberof RequestCreateAuthUserRequest
     */
    lastname?: string;
    /**
     * 姓（かな）
     * @type {string}
     * @memberof RequestCreateAuthUserRequest
     */
    lastnameKana?: string;
    /**
     * パスワード
     * @type {string}
     * @memberof RequestCreateAuthUserRequest
     */
    password?: string;
    /**
     * パスワード (確認用)
     * @type {string}
     * @memberof RequestCreateAuthUserRequest
     */
    passwordConfirmation?: string;
    /**
     * 電話番号
     * @type {string}
     * @memberof RequestCreateAuthUserRequest
     */
    phoneNumber?: string;
    /**
     * ユーザー名(表示名)
     * @type {string}
     * @memberof RequestCreateAuthUserRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the RequestCreateAuthUserRequest interface.
 */
export function instanceOfRequestCreateAuthUserRequest(value: object): value is RequestCreateAuthUserRequest {
    return true;
}

export function RequestCreateAuthUserRequestFromJSON(json: any): RequestCreateAuthUserRequest {
    return RequestCreateAuthUserRequestFromJSONTyped(json, false);
}

export function RequestCreateAuthUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestCreateAuthUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstname': json['firstname'] == null ? undefined : json['firstname'],
        'firstnameKana': json['firstnameKana'] == null ? undefined : json['firstnameKana'],
        'lastname': json['lastname'] == null ? undefined : json['lastname'],
        'lastnameKana': json['lastnameKana'] == null ? undefined : json['lastnameKana'],
        'password': json['password'] == null ? undefined : json['password'],
        'passwordConfirmation': json['passwordConfirmation'] == null ? undefined : json['passwordConfirmation'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function RequestCreateAuthUserRequestToJSON(value?: RequestCreateAuthUserRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountId': value['accountId'],
        'email': value['email'],
        'firstname': value['firstname'],
        'firstnameKana': value['firstnameKana'],
        'lastname': value['lastname'],
        'lastnameKana': value['lastnameKana'],
        'password': value['password'],
        'passwordConfirmation': value['passwordConfirmation'],
        'phoneNumber': value['phoneNumber'],
        'username': value['username'],
    };
}

