/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseLive
 */
export interface ResponseLive {
    /**
     * コメント
     * @type {string}
     * @memberof ResponseLive
     */
    comment?: string;
    /**
     * ライブ配信終了日時
     * @type {number}
     * @memberof ResponseLive
     */
    endAt?: number;
    /**
     * 生産者ID
     * @type {string}
     * @memberof ResponseLive
     */
    producerId?: string;
    /**
     * 商品ID一覧
     * @type {Array<string>}
     * @memberof ResponseLive
     */
    productIds?: Array<string>;
    /**
     * マルシェ開催スケジュールID
     * @type {string}
     * @memberof ResponseLive
     */
    scheduleId?: string;
    /**
     * ライブ配信開始日時
     * @type {number}
     * @memberof ResponseLive
     */
    startAt?: number;
}

/**
 * Check if a given object implements the ResponseLive interface.
 */
export function instanceOfResponseLive(value: object): value is ResponseLive {
    return true;
}

export function ResponseLiveFromJSON(json: any): ResponseLive {
    return ResponseLiveFromJSONTyped(json, false);
}

export function ResponseLiveFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseLive {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        'endAt': json['endAt'] == null ? undefined : json['endAt'],
        'producerId': json['producerId'] == null ? undefined : json['producerId'],
        'productIds': json['productIds'] == null ? undefined : json['productIds'],
        'scheduleId': json['scheduleId'] == null ? undefined : json['scheduleId'],
        'startAt': json['startAt'] == null ? undefined : json['startAt'],
    };
}

export function ResponseLiveToJSON(value?: ResponseLive | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comment': value['comment'],
        'endAt': value['endAt'],
        'producerId': value['producerId'],
        'productIds': value['productIds'],
        'scheduleId': value['scheduleId'],
        'startAt': value['startAt'],
    };
}

