/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseLiveSummary } from './ResponseLiveSummary';
import {
    ResponseLiveSummaryFromJSON,
    ResponseLiveSummaryFromJSONTyped,
    ResponseLiveSummaryToJSON,
} from './ResponseLiveSummary';
import type { ResponseCoordinator } from './ResponseCoordinator';
import {
    ResponseCoordinatorFromJSON,
    ResponseCoordinatorFromJSONTyped,
    ResponseCoordinatorToJSON,
} from './ResponseCoordinator';

/**
 * 
 * @export
 * @interface ResponseLiveSchedulesResponse
 */
export interface ResponseLiveSchedulesResponse {
    /**
     * コーディネータ一覧
     * @type {Array<ResponseCoordinator>}
     * @memberof ResponseLiveSchedulesResponse
     */
    coordinators?: Array<ResponseCoordinator>;
    /**
     * 配信中・配信予定のマルシェ一覧
     * @type {Array<ResponseLiveSummary>}
     * @memberof ResponseLiveSchedulesResponse
     */
    lives?: Array<ResponseLiveSummary>;
    /**
     * 配信中・配信予定のマルシェ合計数
     * @type {number}
     * @memberof ResponseLiveSchedulesResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the ResponseLiveSchedulesResponse interface.
 */
export function instanceOfResponseLiveSchedulesResponse(value: object): value is ResponseLiveSchedulesResponse {
    return true;
}

export function ResponseLiveSchedulesResponseFromJSON(json: any): ResponseLiveSchedulesResponse {
    return ResponseLiveSchedulesResponseFromJSONTyped(json, false);
}

export function ResponseLiveSchedulesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseLiveSchedulesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinators': json['coordinators'] == null ? undefined : ((json['coordinators'] as Array<any>).map(ResponseCoordinatorFromJSON)),
        'lives': json['lives'] == null ? undefined : ((json['lives'] as Array<any>).map(ResponseLiveSummaryFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ResponseLiveSchedulesResponseToJSON(value?: ResponseLiveSchedulesResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'coordinators': value['coordinators'] == null ? undefined : ((value['coordinators'] as Array<any>).map(ResponseCoordinatorToJSON)),
        'lives': value['lives'] == null ? undefined : ((value['lives'] as Array<any>).map(ResponseLiveSummaryToJSON)),
        'total': value['total'],
    };
}

