/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponsePromotion } from './ResponsePromotion';
import {
    ResponsePromotionFromJSON,
    ResponsePromotionFromJSONTyped,
    ResponsePromotionToJSON,
} from './ResponsePromotion';

/**
 * 
 * @export
 * @interface ResponsePromotionResponse
 */
export interface ResponsePromotionResponse {
    /**
     * 
     * @type {ResponsePromotion}
     * @memberof ResponsePromotionResponse
     */
    promotion?: ResponsePromotion;
}

/**
 * Check if a given object implements the ResponsePromotionResponse interface.
 */
export function instanceOfResponsePromotionResponse(value: object): value is ResponsePromotionResponse {
    return true;
}

export function ResponsePromotionResponseFromJSON(json: any): ResponsePromotionResponse {
    return ResponsePromotionResponseFromJSONTyped(json, false);
}

export function ResponsePromotionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsePromotionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'promotion': json['promotion'] == null ? undefined : ResponsePromotionFromJSON(json['promotion']),
    };
}

export function ResponsePromotionResponseToJSON(value?: ResponsePromotionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'promotion': ResponsePromotionToJSON(value['promotion']),
    };
}

