/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * オンデマンド動画情報
 * @export
 * @interface ResponseVideo
 */
export interface ResponseVideo {
    /**
     * コーディネータID
     * @type {string}
     * @memberof ResponseVideo
     */
    coordinatorId?: string;
    /**
     * 説明
     * @type {string}
     * @memberof ResponseVideo
     */
    description?: string;
    /**
     * 体験ID一覧
     * @type {Array<string>}
     * @memberof ResponseVideo
     */
    experienceIds?: Array<string>;
    /**
     * オンデマンド動画ID
     * @type {string}
     * @memberof ResponseVideo
     */
    id?: string;
    /**
     * 商品ID一覧
     * @type {Array<string>}
     * @memberof ResponseVideo
     */
    productIds?: Array<string>;
    /**
     * 公開日時
     * @type {number}
     * @memberof ResponseVideo
     */
    publishedAt?: number;
    /**
     * サムネイルURL
     * @type {string}
     * @memberof ResponseVideo
     */
    thumbnailUrl?: string;
    /**
     * タイトル
     * @type {string}
     * @memberof ResponseVideo
     */
    title?: string;
    /**
     * 動画URL
     * @type {string}
     * @memberof ResponseVideo
     */
    videoUrl?: string;
}

/**
 * Check if a given object implements the ResponseVideo interface.
 */
export function instanceOfResponseVideo(value: object): value is ResponseVideo {
    return true;
}

export function ResponseVideoFromJSON(json: any): ResponseVideo {
    return ResponseVideoFromJSONTyped(json, false);
}

export function ResponseVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseVideo {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinatorId': json['coordinatorId'] == null ? undefined : json['coordinatorId'],
        'description': json['description'] == null ? undefined : json['description'],
        'experienceIds': json['experienceIds'] == null ? undefined : json['experienceIds'],
        'id': json['id'] == null ? undefined : json['id'],
        'productIds': json['productIds'] == null ? undefined : json['productIds'],
        'publishedAt': json['publishedAt'] == null ? undefined : json['publishedAt'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'title': json['title'] == null ? undefined : json['title'],
        'videoUrl': json['videoUrl'] == null ? undefined : json['videoUrl'],
    };
}

export function ResponseVideoToJSON(value?: ResponseVideo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'coordinatorId': value['coordinatorId'],
        'description': value['description'],
        'experienceIds': value['experienceIds'],
        'id': value['id'],
        'productIds': value['productIds'],
        'publishedAt': value['publishedAt'],
        'thumbnailUrl': value['thumbnailUrl'],
        'title': value['title'],
        'videoUrl': value['videoUrl'],
    };
}

