/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseExperienceReview } from './ResponseExperienceReview';
import {
    ResponseExperienceReviewFromJSON,
    ResponseExperienceReviewFromJSONTyped,
    ResponseExperienceReviewToJSON,
} from './ResponseExperienceReview';

/**
 * 
 * @export
 * @interface ResponseExperienceReviewResponse
 */
export interface ResponseExperienceReviewResponse {
    /**
     * 
     * @type {ResponseExperienceReview}
     * @memberof ResponseExperienceReviewResponse
     */
    review?: ResponseExperienceReview;
}

/**
 * Check if a given object implements the ResponseExperienceReviewResponse interface.
 */
export function instanceOfResponseExperienceReviewResponse(value: object): value is ResponseExperienceReviewResponse {
    return true;
}

export function ResponseExperienceReviewResponseFromJSON(json: any): ResponseExperienceReviewResponse {
    return ResponseExperienceReviewResponseFromJSONTyped(json, false);
}

export function ResponseExperienceReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseExperienceReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'review': json['review'] == null ? undefined : ResponseExperienceReviewFromJSON(json['review']),
    };
}

export function ResponseExperienceReviewResponseToJSON(value?: ResponseExperienceReviewResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'review': ResponseExperienceReviewToJSON(value['review']),
    };
}

