/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 品目情報
 * @export
 * @interface ResponseProductType
 */
export interface ResponseProductType {
    /**
     * 商品種別ID
     * @type {string}
     * @memberof ResponseProductType
     */
    categoryId?: string;
    /**
     * アイコンURL
     * @type {string}
     * @memberof ResponseProductType
     */
    iconUrl?: string;
    /**
     * 品目ID
     * @type {string}
     * @memberof ResponseProductType
     */
    id?: string;
    /**
     * 品目名
     * @type {string}
     * @memberof ResponseProductType
     */
    name?: string;
}

/**
 * Check if a given object implements the ResponseProductType interface.
 */
export function instanceOfResponseProductType(value: object): value is ResponseProductType {
    return true;
}

export function ResponseProductTypeFromJSON(json: any): ResponseProductType {
    return ResponseProductTypeFromJSONTyped(json, false);
}

export function ResponseProductTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseProductType {
    if (json == null) {
        return json;
    }
    return {
        
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'iconUrl': json['iconUrl'] == null ? undefined : json['iconUrl'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ResponseProductTypeToJSON(value?: ResponseProductType | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'categoryId': value['categoryId'],
        'iconUrl': value['iconUrl'],
        'id': value['id'],
        'name': value['name'],
    };
}

