/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Spot } from './Spot';
import {
    SpotFromJSON,
    SpotFromJSONTyped,
    SpotToJSON,
    SpotToJSONTyped,
} from './Spot';
import type { SpotType } from './SpotType';
import {
    SpotTypeFromJSON,
    SpotTypeFromJSONTyped,
    SpotTypeToJSON,
    SpotTypeToJSONTyped,
} from './SpotType';

/**
 * 
 * @export
 * @interface SpotResponse
 */
export interface SpotResponse {
    /**
     * 
     * @type {Spot}
     * @memberof SpotResponse
     */
    spot: Spot;
    /**
     * 
     * @type {SpotType}
     * @memberof SpotResponse
     */
    spotType: SpotType;
}

/**
 * Check if a given object implements the SpotResponse interface.
 */
export function instanceOfSpotResponse(value: object): value is SpotResponse {
    if (!('spot' in value) || value['spot'] === undefined) return false;
    if (!('spotType' in value) || value['spotType'] === undefined) return false;
    return true;
}

export function SpotResponseFromJSON(json: any): SpotResponse {
    return SpotResponseFromJSONTyped(json, false);
}

export function SpotResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpotResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'spot': SpotFromJSON(json['spot']),
        'spotType': SpotTypeFromJSON(json['spotType']),
    };
}

export function SpotResponseToJSON(json: any): SpotResponse {
    return SpotResponseToJSONTyped(json, false);
}

export function SpotResponseToJSONTyped(value?: SpotResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spot': SpotToJSON(value['spot']),
        'spotType': SpotTypeToJSON(value['spotType']),
    };
}

