/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Spot } from './Spot';
import {
    SpotFromJSON,
    SpotFromJSONTyped,
    SpotToJSON,
    SpotToJSONTyped,
} from './Spot';
import type { SpotType } from './SpotType';
import {
    SpotTypeFromJSON,
    SpotTypeFromJSONTyped,
    SpotTypeToJSON,
    SpotTypeToJSONTyped,
} from './SpotType';

/**
 * 
 * @export
 * @interface SpotsResponse
 */
export interface SpotsResponse {
    /**
     * スポット種別一覧
     * @type {Array<SpotType>}
     * @memberof SpotsResponse
     */
    spotTypes: Array<SpotType>;
    /**
     * スポット一覧
     * @type {Array<Spot>}
     * @memberof SpotsResponse
     */
    spots: Array<Spot>;
}

/**
 * Check if a given object implements the SpotsResponse interface.
 */
export function instanceOfSpotsResponse(value: object): value is SpotsResponse {
    if (!('spotTypes' in value) || value['spotTypes'] === undefined) return false;
    if (!('spots' in value) || value['spots'] === undefined) return false;
    return true;
}

export function SpotsResponseFromJSON(json: any): SpotsResponse {
    return SpotsResponseFromJSONTyped(json, false);
}

export function SpotsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpotsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'spotTypes': ((json['spotTypes'] as Array<any>).map(SpotTypeFromJSON)),
        'spots': ((json['spots'] as Array<any>).map(SpotFromJSON)),
    };
}

export function SpotsResponseToJSON(json: any): SpotsResponse {
    return SpotsResponseToJSONTyped(json, false);
}

export function SpotsResponseToJSONTyped(value?: SpotsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spotTypes': ((value['spotTypes'] as Array<any>).map(SpotTypeToJSON)),
        'spots': ((value['spots'] as Array<any>).map(SpotToJSON)),
    };
}

