/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesCreateExperienceReviewRequest
 */
export interface TypesCreateExperienceReviewRequest {
    /**
     * コメント
     * @type {string}
     * @memberof TypesCreateExperienceReviewRequest
     */
    comment: string;
    /**
     * 評価
     * @type {number}
     * @memberof TypesCreateExperienceReviewRequest
     */
    rate?: number;
    /**
     * タイトル
     * @type {string}
     * @memberof TypesCreateExperienceReviewRequest
     */
    title: string;
}

/**
 * Check if a given object implements the TypesCreateExperienceReviewRequest interface.
 */
export function instanceOfTypesCreateExperienceReviewRequest(value: object): value is TypesCreateExperienceReviewRequest {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TypesCreateExperienceReviewRequestFromJSON(json: any): TypesCreateExperienceReviewRequest {
    return TypesCreateExperienceReviewRequestFromJSONTyped(json, false);
}

export function TypesCreateExperienceReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesCreateExperienceReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'],
        'rate': json['rate'] == null ? undefined : json['rate'],
        'title': json['title'],
    };
}

export function TypesCreateExperienceReviewRequestToJSON(value?: TypesCreateExperienceReviewRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comment': value['comment'],
        'rate': value['rate'],
        'title': value['title'],
    };
}

