/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesUpdateAuthUserThumbnailRequest
 */
export interface TypesUpdateAuthUserThumbnailRequest {
    /**
     * サムネイルURL
     * @type {string}
     * @memberof TypesUpdateAuthUserThumbnailRequest
     */
    thumbnailUrl?: string;
}

/**
 * Check if a given object implements the TypesUpdateAuthUserThumbnailRequest interface.
 */
export function instanceOfTypesUpdateAuthUserThumbnailRequest(value: object): value is TypesUpdateAuthUserThumbnailRequest {
    return true;
}

export function TypesUpdateAuthUserThumbnailRequestFromJSON(json: any): TypesUpdateAuthUserThumbnailRequest {
    return TypesUpdateAuthUserThumbnailRequestFromJSONTyped(json, false);
}

export function TypesUpdateAuthUserThumbnailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesUpdateAuthUserThumbnailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
    };
}

export function TypesUpdateAuthUserThumbnailRequestToJSON(value?: TypesUpdateAuthUserThumbnailRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'thumbnailUrl': value['thumbnailUrl'],
    };
}

