/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesCheckoutStateResponse
 */
export interface TypesCheckoutStateResponse {
    /**
     * 注文履歴ID
     * @type {string}
     * @memberof TypesCheckoutStateResponse
     */
    orderId?: string;
    /**
     * 注文ステータス
     * @type {number}
     * @memberof TypesCheckoutStateResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the TypesCheckoutStateResponse interface.
 */
export function instanceOfTypesCheckoutStateResponse(value: object): value is TypesCheckoutStateResponse {
    return true;
}

export function TypesCheckoutStateResponseFromJSON(json: any): TypesCheckoutStateResponse {
    return TypesCheckoutStateResponseFromJSONTyped(json, false);
}

export function TypesCheckoutStateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesCheckoutStateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesCheckoutStateResponseToJSON(value?: TypesCheckoutStateResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'orderId': value['orderId'],
        'status': value['status'],
    };
}

