/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesResetAuthPasswordRequest
 */
export interface TypesResetAuthPasswordRequest {
    /**
     * メールアドレス
     * @type {string}
     * @memberof TypesResetAuthPasswordRequest
     */
    email: string;
    /**
     * パスワード
     * @type {string}
     * @memberof TypesResetAuthPasswordRequest
     */
    password?: string;
    /**
     * パスワード (確認用)
     * @type {string}
     * @memberof TypesResetAuthPasswordRequest
     */
    passwordConfirmation: string;
    /**
     * 検証コード
     * @type {string}
     * @memberof TypesResetAuthPasswordRequest
     */
    verifyCode: string;
}

/**
 * Check if a given object implements the TypesResetAuthPasswordRequest interface.
 */
export function instanceOfTypesResetAuthPasswordRequest(value: object): value is TypesResetAuthPasswordRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('passwordConfirmation' in value) || value['passwordConfirmation'] === undefined) return false;
    if (!('verifyCode' in value) || value['verifyCode'] === undefined) return false;
    return true;
}

export function TypesResetAuthPasswordRequestFromJSON(json: any): TypesResetAuthPasswordRequest {
    return TypesResetAuthPasswordRequestFromJSONTyped(json, false);
}

export function TypesResetAuthPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResetAuthPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'passwordConfirmation': json['passwordConfirmation'],
        'verifyCode': json['verifyCode'],
    };
}

export function TypesResetAuthPasswordRequestToJSON(value?: TypesResetAuthPasswordRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
        'passwordConfirmation': value['passwordConfirmation'],
        'verifyCode': value['verifyCode'],
    };
}

