/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesLiveProduct
 */
export interface TypesLiveProduct {
    /**
     * 商品ID
     * @type {string}
     * @memberof TypesLiveProduct
     */
    id?: string;
    /**
     * 在庫数
     * @type {number}
     * @memberof TypesLiveProduct
     */
    inventory?: number;
    /**
     * 商品名
     * @type {string}
     * @memberof TypesLiveProduct
     */
    name?: string;
    /**
     * 販売価格(税込)
     * @type {number}
     * @memberof TypesLiveProduct
     */
    price?: number;
    /**
     * サムネイルURL
     * @type {string}
     * @memberof TypesLiveProduct
     */
    thumbnailUrl?: string;
}

/**
 * Check if a given object implements the TypesLiveProduct interface.
 */
export function instanceOfTypesLiveProduct(value: object): value is TypesLiveProduct {
    return true;
}

export function TypesLiveProductFromJSON(json: any): TypesLiveProduct {
    return TypesLiveProductFromJSONTyped(json, false);
}

export function TypesLiveProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesLiveProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'inventory': json['inventory'] == null ? undefined : json['inventory'],
        'name': json['name'] == null ? undefined : json['name'],
        'price': json['price'] == null ? undefined : json['price'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
    };
}

export function TypesLiveProductToJSON(value?: TypesLiveProduct | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'inventory': value['inventory'],
        'name': value['name'],
        'price': value['price'],
        'thumbnailUrl': value['thumbnailUrl'],
    };
}

