/* tslint:disable */
/* eslint-disable */
/**
 * ふるマル API - 購入者向け
 * 購入者向けのふるマルAPIです。
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypesAddress } from './TypesAddress';
import {
    TypesAddressFromJSON,
    TypesAddressFromJSONTyped,
    TypesAddressToJSON,
} from './TypesAddress';
import type { TypesOrderExperience } from './TypesOrderExperience';
import {
    TypesOrderExperienceFromJSON,
    TypesOrderExperienceFromJSONTyped,
    TypesOrderExperienceToJSON,
} from './TypesOrderExperience';
import type { TypesOrderItem } from './TypesOrderItem';
import {
    TypesOrderItemFromJSON,
    TypesOrderItemFromJSONTyped,
    TypesOrderItemToJSON,
} from './TypesOrderItem';
import type { TypesOrderFulfillment } from './TypesOrderFulfillment';
import {
    TypesOrderFulfillmentFromJSON,
    TypesOrderFulfillmentFromJSONTyped,
    TypesOrderFulfillmentToJSON,
} from './TypesOrderFulfillment';
import type { TypesOrderRefund } from './TypesOrderRefund';
import {
    TypesOrderRefundFromJSON,
    TypesOrderRefundFromJSONTyped,
    TypesOrderRefundToJSON,
} from './TypesOrderRefund';
import type { TypesOrderPayment } from './TypesOrderPayment';
import {
    TypesOrderPaymentFromJSON,
    TypesOrderPaymentFromJSONTyped,
    TypesOrderPaymentToJSON,
} from './TypesOrderPayment';

/**
 * 注文履歴情報
 * @export
 * @interface TypesOrder
 */
export interface TypesOrder {
    /**
     * 
     * @type {TypesAddress}
     * @memberof TypesOrder
     */
    billingAddress?: TypesAddress;
    /**
     * コーディネータID
     * @type {string}
     * @memberof TypesOrder
     */
    coordinatorId?: string;
    /**
     * 
     * @type {TypesOrderExperience}
     * @memberof TypesOrder
     */
    experience?: TypesOrderExperience;
    /**
     * 配送情報一覧
     * @type {Array<TypesOrderFulfillment>}
     * @memberof TypesOrder
     */
    fulfillments?: Array<TypesOrderFulfillment>;
    /**
     * 注文履歴ID
     * @type {string}
     * @memberof TypesOrder
     */
    id?: string;
    /**
     * 注文商品一覧
     * @type {Array<TypesOrderItem>}
     * @memberof TypesOrder
     */
    items?: Array<TypesOrderItem>;
    /**
     * 
     * @type {TypesOrderPayment}
     * @memberof TypesOrder
     */
    payment?: TypesOrderPayment;
    /**
     * プロモーションID
     * @type {string}
     * @memberof TypesOrder
     */
    promotionId?: string;
    /**
     * 
     * @type {TypesOrderRefund}
     * @memberof TypesOrder
     */
    refund?: TypesOrderRefund;
    /**
     * 
     * @type {TypesAddress}
     * @memberof TypesOrder
     */
    shippingAddress?: TypesAddress;
    /**
     * 注文ステータス
     * @type {number}
     * @memberof TypesOrder
     */
    status?: number;
    /**
     * 注文種別
     * @type {number}
     * @memberof TypesOrder
     */
    type?: number;
}

/**
 * Check if a given object implements the TypesOrder interface.
 */
export function instanceOfTypesOrder(value: object): value is TypesOrder {
    return true;
}

export function TypesOrderFromJSON(json: any): TypesOrder {
    return TypesOrderFromJSONTyped(json, false);
}

export function TypesOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'billingAddress': json['billingAddress'] == null ? undefined : TypesAddressFromJSON(json['billingAddress']),
        'coordinatorId': json['coordinatorId'] == null ? undefined : json['coordinatorId'],
        'experience': json['experience'] == null ? undefined : TypesOrderExperienceFromJSON(json['experience']),
        'fulfillments': json['fulfillments'] == null ? undefined : ((json['fulfillments'] as Array<any>).map(TypesOrderFulfillmentFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TypesOrderItemFromJSON)),
        'payment': json['payment'] == null ? undefined : TypesOrderPaymentFromJSON(json['payment']),
        'promotionId': json['promotionId'] == null ? undefined : json['promotionId'],
        'refund': json['refund'] == null ? undefined : TypesOrderRefundFromJSON(json['refund']),
        'shippingAddress': json['shippingAddress'] == null ? undefined : TypesAddressFromJSON(json['shippingAddress']),
        'status': json['status'] == null ? undefined : json['status'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function TypesOrderToJSON(value?: TypesOrder | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'billingAddress': TypesAddressToJSON(value['billingAddress']),
        'coordinatorId': value['coordinatorId'],
        'experience': TypesOrderExperienceToJSON(value['experience']),
        'fulfillments': value['fulfillments'] == null ? undefined : ((value['fulfillments'] as Array<any>).map(TypesOrderFulfillmentToJSON)),
        'id': value['id'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(TypesOrderItemToJSON)),
        'payment': TypesOrderPaymentToJSON(value['payment']),
        'promotionId': value['promotionId'],
        'refund': TypesOrderRefundToJSON(value['refund']),
        'shippingAddress': TypesAddressToJSON(value['shippingAddress']),
        'status': value['status'],
        'type': value['type'],
    };
}

