/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CartItem
 */
export interface CartItem {
    /**
     * 商品ID
     * @type {string}
     * @memberof CartItem
     */
    productId?: string;
    /**
     * 数量
     * @type {number}
     * @memberof CartItem
     */
    quantity: number;
}

/**
 * Check if a given object implements the CartItem interface.
 */
export function instanceOfCartItem(value: object): value is CartItem {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function CartItemFromJSON(json: any): CartItem {
    return CartItemFromJSONTyped(json, false);
}

export function CartItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItem {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'] == null ? undefined : json['productId'],
        'quantity': json['quantity'],
    };
}

export function CartItemToJSON(value?: CartItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'productId': value['productId'],
        'quantity': value['quantity'],
    };
}

