/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLiveCommentRequest
 */
export interface CreateLiveCommentRequest {
    /**
     * コメント
     * @type {string}
     * @memberof CreateLiveCommentRequest
     */
    comment: string;
}

/**
 * Check if a given object implements the CreateLiveCommentRequest interface.
 */
export function instanceOfCreateLiveCommentRequest(value: object): value is CreateLiveCommentRequest {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function CreateLiveCommentRequestFromJSON(json: any): CreateLiveCommentRequest {
    return CreateLiveCommentRequestFromJSONTyped(json, false);
}

export function CreateLiveCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLiveCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'],
    };
}

export function CreateLiveCommentRequestToJSON(value?: CreateLiveCommentRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comment': value['comment'],
    };
}

