/* tslint:disable */
/* eslint-disable */
/**
 * Marche Online
 * マルシェ購入者用API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddCartItemRequest,
  CalcCartResponse,
  CartResponse,
  ErrorResponse,
} from '../models/index';
import {
    AddCartItemRequestFromJSON,
    AddCartItemRequestToJSON,
    CalcCartResponseFromJSON,
    CalcCartResponseToJSON,
    CartResponseFromJSON,
    CartResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface V1AddCartItemRequest {
    body: AddCartItemRequest;
}

export interface V1CalcCartRequest {
    coordinatorId: string;
    number?: number;
    prefecture?: number;
    promotion?: string;
}

export interface V1RemoveCartItemRequest {
    productId: string;
    number?: number;
}

/**
 * 
 */
export class CartApi extends runtime.BaseAPI {

    /**
     * 買い物かごへ商品を追加
     */
    async v1AddCartItemRaw(requestParameters: V1AddCartItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling v1AddCartItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/carts/-/items`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 買い物かごへ商品を追加
     */
    async v1AddCartItem(requestParameters: V1AddCartItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1AddCartItemRaw(requestParameters, initOverrides);
    }

    /**
     * 買い物かごの金額計算
     */
    async v1CalcCartRaw(requestParameters: V1CalcCartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CalcCartResponse>> {
        if (requestParameters['coordinatorId'] == null) {
            throw new runtime.RequiredError(
                'coordinatorId',
                'Required parameter "coordinatorId" was null or undefined when calling v1CalcCart().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['number'] != null) {
            queryParameters['number'] = requestParameters['number'];
        }

        if (requestParameters['prefecture'] != null) {
            queryParameters['prefecture'] = requestParameters['prefecture'];
        }

        if (requestParameters['promotion'] != null) {
            queryParameters['promotion'] = requestParameters['promotion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/carts/{coordinatorId}`.replace(`{${"coordinatorId"}}`, encodeURIComponent(String(requestParameters['coordinatorId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CalcCartResponseFromJSON(jsonValue));
    }

    /**
     * 買い物かごの金額計算
     */
    async v1CalcCart(requestParameters: V1CalcCartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CalcCartResponse> {
        const response = await this.v1CalcCartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 買い物かご取得
     */
    async v1GetCartRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CartResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/carts`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartResponseFromJSON(jsonValue));
    }

    /**
     * 買い物かご取得
     */
    async v1GetCart(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CartResponse> {
        const response = await this.v1GetCartRaw(initOverrides);
        return await response.value();
    }

    /**
     * 買い物かごから商品を削除
     */
    async v1RemoveCartItemRaw(requestParameters: V1RemoveCartItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling v1RemoveCartItem().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['number'] != null) {
            queryParameters['number'] = requestParameters['number'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/carts/-/items/{productId}`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 買い物かごから商品を削除
     */
    async v1RemoveCartItem(requestParameters: V1RemoveCartItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1RemoveCartItemRaw(requestParameters, initOverrides);
    }

}
