run:
  timeout: 10m

linters:
  disable-all: true
  enable:
  - asasalint
  - bidichk
  - bodyclose
  - containedctx
  - contextcheck
  - decorder
  - dogsled
  - dupl
  - dupword
  - errcheck
  - exportloopref
  - forbidigo
  - gci
  - ginkgolinter
  - gocheckcompilerdirectives
  - gocritic
  - gofumpt
  - goimports
  - gomoddirectives
  - gomodguard
  - gosec
  - gosimple
  - govet
  - grouper
  - ineffassign
  - lll
  - loggercheck
  - maintidx
  - nakedret
  - nestif
  - nilnil
  - noctx
  - nolintlint
  - prealloc
  - promlinter
  - protogetter
  - reassign
  - revive
  - rowserrcheck
  - sloglint
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - tagalign
  - tenv
  - testifylint
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace
  # - wrapcheck

linters-settings:
  funlen:
    lines: 100
    statements: 50
  lll:
    line-length: 140

issues:
  exclude:
  - Using the variable on range scope .* in function literal
  - func name will be used as * by other packages, and that stutters; consider calling this
  - lines are duplicate of
  - a blank import should be only in a main or test package, or have a comment justifying it
  - use strings.ReplaceAll method in
  exclude-dirs:
  - bin
  - hack
  - mock
  - proto
  - third_party
  - tmp
  exclude-files:
  - '.*_test.go'
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
    - dupl
    - gosec
