run:
  skip-dirs:
  - bin
  - hack
  - mock
  - proto
  - third_party
  - tmp
  skip-files:
  - '.*_test.go'
  timeout: 10m

linters:
  disable-all: true
  enable:
  - bodyclose
  - dogsled
  - dupl
  - errcheck
  - exportloopref
  - gochecknoinits
  - goconst
  - gocritic
  - gocyclo
  - goimports
  - gosimple
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - revive
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace

linters-settings:
  funlen:
    lines: 100
    statements: 50
  lll:
    line-length: 140

issues:
  exclude:
  - Using the variable on range scope .* in function literal
  - func name will be used as * by other packages, and that stutters; consider calling this
  - lines are duplicate of
  - a blank import should be only in a main or test package, or have a comment justifying it
  - use strings.ReplaceAll method in
  exclude-rules:
  - path: _test\.go
    linters:
    - dupl
