version: '2'

run:
  timeout: 10m

linters:
  default: all # standard/all/none/fast
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 100
      statements: 50
    lll:
      line-length: 140
  exclusions:
    rules:
    - path: .*\.go
      linters:
      - depguard
      - err113
      - exhaustruct
      - gochecknoglobals
      - godot
      - godox
      - golines
      - gosec
      - gosmopolitan
      - ireturn
      - mnd
      - nlreturn
      - revive
      - unparam
      - varnamelen
      - wsl
    - path: .*_test\.go
      linters:
      - dupl
      - errcheck
      - forcetypeassert
      - gocritic
      - gocyclo
      - gomnd
      - lll
      - tagalign
      - testpackage
      - thelper
    - path: hack/.*\.go
      linters:
      - errcheck
    - path: database/tidb/.*_test\.go
      linters:
      - paralleltest
    - path: service/.*_test\.go
      linters:
      - paralleltest

formatters:
  enable:
  - gci
  - gofmt
  - gofumpt
  - goimports
  - golines

issues:
  exclude:
  - Using the variable on range scope .* in function literal
  - func name will be used as * by other packages, and that stutters; consider calling this
  - lines are duplicate of
  - a blank import should be only in a main or test package, or have a comment justifying it
  - use strings.ReplaceAll method in
  exclude-dirs:
  - bin
  - mock
  - tmp
  exclude-files:
  - '.*_test\.go'
  exclude-rules:
  - path: '_test\.go'
    linters:
    - dupl
    - errcheck
    - gosec