version: '2'

run:
  timeout: 10m

linters:
  default: all # standard/all/none/fast
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 200
      statements: 80
    lll:
      line-length: 120
  exclusions:
    rules:
    - path: .*\.go
      linters:
      - contextcheck
      - depguard
      - dupl   #########
      - err113
      - exhaustive #########
      - exhaustruct
      - gochecknoglobals
      - goconst
      - godot
      - godox
      - golines
      - gosec
      - gosmopolitan
      - interfacebloat
      - ireturn
      - mnd
      - nlreturn
      - revive
      - unparam
      - varnamelen
      - wsl
    - path: .*_test\.go
      linters:
      - bodyclose
      - containedctx
      - errcheck
      - forbidigo
      - forcetypeassert
      - funlen
      - gocritic
      - gocyclo
      - gomnd
      - lll
      - maintidx
      - tagalign
      - testpackage
      - thelper
    - path: hack/.*\.go
      linters:
      - errcheck
      - forbidigo
      - funlen
      - gocritic
    - path: database/tidb/.*_test\.go
      linters:
      - paralleltest
    - path: service/.*_test\.go
      linters:
      - paralleltest

formatters:
  enable:
  - gci
  - gofmt
  - gofumpt
  - goimports
  - golines
