name: deploy ecs

on:
  workflow_call:
    inputs:
      environment:
        description: '環境名'
        type: string
        required: true
      ecr-registry:
        description: 'ECRレジストリ名'
        type: string
        required: true
      ecr-repository:
        description: 'ECRリポジトリ名'
        type: string
        required: true
      ecs-cluster-name:
        description: 'ECSクラスタ名'
        type: string
        required: true
      ecs-task-definition:
        description: 'ECSタスク定義名'
        type: string
        required: true
      ecs-service-name:
        description: 'ECSサービス名'
        type: string
        required: true
      ecs-container-name:
        description: 'ECSコンテナ名'
        type: string
        required: true
      image-tag:
        description: 'ECRイメージタグ'
        type: string
        required: false
        default: 'latest'

jobs:
  deploy_ecs:
    name: deploy ecs
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Setup AWS
      uses: ./.github/actions/setup-aws
      with:
        aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get ECR repository and image url
      id: get-ecr-url
      uses: ./.github/actions/generate-ecr-url
      with:
        ecr-registry: ${{ inputs.ecr-registry }}
        ecr-repository: ${{ inputs.ecr-repository }}
        image-tag: ${{ inputs.image-tag }}

    - name: Fetch task definition
      run: |
        aws ecs describe-task-definition --region ${AWS_REGION} --task-definition ${ECS_TASK_DEFINITION} | \
          jq '.taskDefinition | del(.compatibilities, .registeredAt, .registeredBy, .requiresAttributes, .revision, .status, .taskDefinitionArn)' \
          > ./task-definition.json
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ECS_TASK_DEFINITION: ${{ inputs.ecs-task-definition }}

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@5cb8c74c1b1ecaec4c8ea82eff82c009333509ce # v1.8.0
      with:
        task-definition: ./task-definition.json
        container-name: ${{ inputs.ecs-container-name }}
        image: ${{ steps.get-ecr-url.outputs.ecr-image-url }}:${{ steps.get-ecr-url.outputs.ecr-image-tag }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@1beffbdddb3eb5f83c7a746c3e9bafeccdccbbaa # v2.4.0
      with:
        cluster: ${{ inputs.ecs-cluster-name }}
        service: ${{ inputs.ecs-service-name }}
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        wait-for-service-stability: true
