name: deploy lambda

on:
  workflow_call:
    inputs:
      environment:
        description: '環境名'
        type: string
        required: true
      ecr-registry:
        description: 'ECRレジストリ名'
        type: string
        required: true
      ecr-repository:
        description: 'ECRリポジトリ名'
        type: string
        required: true
      lambda-function-name:
        description: 'Lambda関数名'
        type: string
        required: true
      image-tag:
        description: 'ECRイメージタグ'
        type: string
        required: false
        default: 'latest'

jobs:
  deploy_lambda:
    name: deploy lambda
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Setup AWS
      uses: ./.github/actions/setup-aws
      with:
        aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Get ECR repository and image url
      id: get-ecr-url
      uses: ./.github/actions/generate-ecr-url
      with:
        ecr-registry: ${{ inputs.ecr-registry }}
        ecr-repository: ${{ inputs.ecr-repository }}
        image-tag: ${{ inputs.image-tag }}

    - name: Deploy AWS Lambda function
      run: |
        aws lambda update-function-code \
          --region ${AWS_REGION} \
          --function-name="${LAMBDA_FUNCTION_NAME}" \
          --architectures="arm64" \
          --image-uri="${ECR_REPOSITORY_URL}:${ECR_IMAGE_TAG}" \
        | jq '. | del(.Environment)'
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        LAMBDA_FUNCTION_NAME: ${{ inputs.lambda-function-name }}
        ECR_REPOSITORY_URL: ${{ steps.get-ecr-url.outputs.ecr-image-url }}
        ECR_IMAGE_TAG: ${{ steps.get-ecr-url.outputs.ecr-image-tag }}
