name: tag version

on:
  workflow_call:
    outputs:
      tag-version:
        description: 'タグバージョン'
        value: ${{ jobs.get_tag_version.outputs.tag-version }}

permissions:
  id-token: write
  contents: read

jobs:
  get_tag_version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    outputs:
      tag-version: ${{ steps.set-tag-version.outputs.tag-version }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set tag version
      id: set-tag-version
      run: |
        if [[ ! "$GITHUB_REF" =~ refs/tags/v[0-9]+(\.[0-9]+)* ]]; then
          echo "Error: GITHUB_REF does not match the expected format (refs/tags/vX.Y.Z)."
          exit 1
        fi
        echo "tag-version=${GITHUB_REF##*/v}" >> $GITHUB_OUTPUT
