on:
  workflow_call:
    outputs:
      tag-version:
        description: 'タグバージョン'
        type: string
        value: ${{ jobs.get_tag_version.outputs.tag-version }}

permissions:
  id-token: write
  contents: read

jobs:
  get_tag_version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    outputs:
      tag-version: ${{ steps.set-tag-version.outputs.tag-version }}

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set tag version
      id: set-tag-version
      run: |
        echo "tag-version=${GITHUB_REF##*/v}" >> $GITHUB_OUTPUT
