name: '[Backend] Deploy Gateway for stg'
on:
  push:
    branches:
    - 'main'
    paths:
    - '.github/workflows/cd-gateway-for-stg.yaml'
    - '.github/workflows/_backend_build_and_push.yaml'
    - '.github/workflows/_backend_deploy_ecr.yaml'
    - 'api/config/gateway/**'
    - 'api/internal/**'
    - 'api/pkg/**'
    - 'api/go.mod'
    - 'infra/docker/api/**'

env:
  TZ: 'Asia/Tokyo'

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    name: build and push
    uses: ./.github/workflows/_backend_build_and_push.yaml
    with:
      service: gateway
      image-path: ./infra/docker/api/Dockerfile
      image-tag: latest
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      ecr-registry: ${{ secrets.ECR_REGISTRY }}
      ecr-repository: ${{ secrets.ECR_REPOSITORY_GATEWAY }}

  deploy_admin:
    name: deploy admin
    needs: build_and_push
    uses: ./.github/workflows/_backend_deploy_ecr.yaml
    with:
      ecr-image-uri: ${{ needs.build_and_push.outputs.ecr-image-uri }}
      ecs-service-name: user
      ecs-container-name: server
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      ecs-cluster-name: ${{ secrets.STG_ECS_CLUSTER }}
      ecs-task-definition: ${{ secrets.STG_ECS_TASK_DEFINITION_ADMIN }}

  deploy_user:
    name: deploy user
    needs: build_and_push
    uses: ./.github/workflows/_backend_deploy_ecr.yaml
    with:
      ecr-image-uri: ${{ needs.build_and_push.outputs.ecr-image-uri }}
      ecs-service-name: admin
      ecs-container-name: server
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      ecs-cluster-name: ${{ secrets.STG_ECS_CLUSTER }}
      ecs-task-definition: ${{ secrets.STG_ECS_TASK_DEFINITION_USER }}
