name: '[Backend] Deploy Gateway for stg'
on:
  push:
    branches:
    - 'main'
    paths:
    - '.github/actions/**'
    - '.github/workflows/_build_and_push.yaml'
    - '.github/workflows/_database_migrate.yaml'
    - '.github/workflows/_deploy_ecs.yaml'
    - '.github/workflows/cd-gateway-for-stg.yaml'
    - 'api/config/gateway/**'
    - 'api/internal/**'
    - 'api/pkg/**'
    - 'api/go.mod'
    - 'infra/docker/api/**'

env:
  TZ: 'Asia/Tokyo'

permissions:
  id-token: write
  contents: read

jobs:
  set_output:
    name: set output
    environment: stg
    runs-on: ubuntu-latest
    outputs:
      ecr-registry: ${{ vars.ECR_REGISTRY }}
      ecr-repository: ${{ vars.ECR_REPOSITORY_GATEWAY }}
      ecs-cluster-name: ${{ vars.ECS_CLUSTER }}
      ecs-task-definition-admin: ${{ vars.ECS_TASK_DEFINITION_ADMIN }}
      ecs-task-definition-user: ${{ vars.ECS_TASK_DEFINITION_USER }}
      db-secret-name: ${{ vars.DB_SECRET_NAME }}
    steps:
    - name: Check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

  database_migrate:
    name: database migrate
    needs:
    - set_output
    uses: ./.github/workflows/_database_migrate.yaml
    secrets: inherit
    with:
      environment: stg
      db-secret-name: ${{ needs.set_output.outputs.db-secret-name }}

  build_and_push:
    name: build and push
    needs:
    - set_output
    uses: ./.github/workflows/_build_and_push.yaml
    secrets: inherit
    with:
      environment: stg
      ecr-registry: ${{ needs.set_output.outputs.ecr-registry }}
      ecr-repository: ${{ needs.set_output.outputs.ecr-repository }}
      service: gateway
      image-path: ./infra/docker/api/Dockerfile
      image-tag: latest

  deploy_admin:
    name: deploy admin
    needs:
    - set_output
    - build_and_push
    uses: ./.github/workflows/_deploy_ecs.yaml
    secrets: inherit
    with:
      environment: stg
      ecr-registry: ${{ needs.set_output.outputs.ecr-registry }}
      ecr-repository: ${{ needs.set_output.outputs.ecr-repository }}
      ecs-cluster-name: ${{ needs.set_output.outputs.ecs-cluster-name }}
      ecs-task-definition: ${{ needs.set_output.outputs.ecs-task-definition-admin }}
      ecs-service-name: admin
      ecs-container-name: server

  deploy_user:
    name: deploy user
    needs:
    - set_output
    - build_and_push
    uses: ./.github/workflows/_deploy_ecs.yaml
    secrets: inherit
    with:
      environment: stg
      ecr-registry: ${{ needs.set_output.outputs.ecr-registry }}
      ecr-repository: ${{ needs.set_output.outputs.ecr-repository }}
      ecs-cluster-name: ${{ needs.set_output.outputs.ecs-cluster-name }}
      ecs-task-definition: ${{ needs.set_output.outputs.ecs-task-definition-user }}
      ecs-service-name: user
      ecs-container-name: server
