name: '[Backend] Deploy Messenger for prd'
on:
  push:
    tags:
    - 'v*'
    paths:
    - '.github/actions/**'
    - '.github/workflows/_build_and_push.yaml'
    - '.github/workflows/_deploy_lambda.yaml'
    - '.github/workflows/_get_tag_version.yaml'
    - '.github/workflows/cd-messenger-for-prd.yaml'
    - 'api/config/messenger/**'
    - 'api/internal/messenger/**'
    - 'api/pkg/**'
    - 'api/go.mod'
    - 'infra/docker/api/**'

env:
  TZ: 'Asia/Tokyo'

permissions:
  id-token: write
  contents: read

jobs:
  get_image_tag:
    name: get image tag
    uses: ./.github/workflows/_tag_version.yaml
    secrets: inherit

  build_and_push:
    name: build and push
    needs:
    - get_image_tag
    uses: ./.github/workflows/_build_and_push.yaml
    with:
      service: messenger
      image-path: ./infra/docker/api/Dockerfile
      image-tag: ${{ needs.get_image_tag.outputs.tag-version }}
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      ecr-registry: ${{ vars.ECR_REGISTRY }}
      ecr-repository: ${{ vars.ECR_REPOSITORY_MESSENGER }}

  deploy_scheduler:
    name: deploy scheduler
    needs:
    - get_image_tag
    - build_and_push
    uses: ./.github/workflows/_deploy_lambda.yaml
    with:
      image-tag: ${{ needs.get_image_tag.outputs.tag-version }}
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      ecr-registry: ${{ vars.ECR_REGISTRY }}
      ecr-repository: ${{ vars.ECR_REPOSITORY_MESSENGER }}
      lambda-function-name: ${{ vars.PRD_LAMBDA_FUNCTION_MESSENGER_SCHEDULER }}

  deploy_worker:
    name: deploy worker
    needs:
    - get_image_tag
    - build_and_push
    uses: ./.github/workflows/_deploy_lambda.yaml
    with:
      image-tag: ${{ needs.get_image_tag.outputs.tag-version }}
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      ecr-registry: ${{ vars.ECR_REGISTRY }}
      ecr-repository: ${{ vars.ECR_REPOSITORY_MESSENGER }}
      lambda-function-name: ${{ vars.PRD_LAMBDA_FUNCTION_MESSENGER_WORKER }}
