name: '[Backend] Deploy Messenger for stg'
on:
  push:
    branches:
    - 'main'
    paths:
    - '.github/actions/setup-aws/**'
    - '.github/workflows/cd-messenger-for-stg.yaml'
    - 'api/config/messenger/**'
    - 'api/internal/messenger/**'
    - 'api/pkg/**'
    - 'api/go.mod'
    - 'infra/docker/api/**'

env:
  TZ: 'Asia/Tokyo'
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY_MESSENGER }}
  LAMBDA_FUNCTION_SCHEDULER: ${{ vars.STG_LAMBDA_FUNCTION_MESSENGER_SCHEDULER }}
  LAMBDA_FUNCTION_WORKER: ${{ vars.STG_LAMBDA_FUNCTION_MESSENGER_WORKER }}
  IMAGE_PATH: ./infra/docker/api/Dockerfile
  SERVICE: messenger

permissions:
  id-token: write
  contents: read

jobs:
  build_and_push:
    name: build and push
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - uses: ./.github/actions/setup-aws
      with:
        aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set ECR_REPOSITORY_URL
      run: |
        echo "ECR_REPOSITORY_URL=${ECR_REGISTRY}/${ECR_REPOSITORY}" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        docker build -f ${IMAGE_PATH} --build-arg SERVICE=${SERVICE} -t ${ECR_REPOSITORY_URL} .
        docker tag ${ECR_REPOSITORY_URL} ${ECR_REPOSITORY_URL}:latest
        docker push -a ${ECR_REPOSITORY_URL}

  deploy_scheduler:
    name: deploy scheduler
    needs: build_and_push
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - uses: ./.github/actions/setup-aws
      with:
        aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set ECR_REPOSITORY_URL
      run: |
        echo "ECR_REPOSITORY_URL=${ECR_REGISTRY}/${ECR_REPOSITORY}" >> $GITHUB_ENV

    - name: Deploy AWS Lambda function
      run: |
        aws lambda update-function-code \
          --function-name="${LAMBDA_FUNCTION_SCHEDULER}" \
          --image-uri="${ECR_REPOSITORY_URL}:latest" \
        | jq '. | del(.Environment)'

  deploy_worker:
    name: deploy worker
    needs: build_and_push
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - uses: ./.github/actions/setup-aws
      with:
        aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set ECR_REPOSITORY_URL
      run: |
        echo "ECR_REPOSITORY_URL=${ECR_REGISTRY}/${ECR_REPOSITORY}" >> $GITHUB_ENV

    - name: Deploy AWS Lambda function
      run: |
        aws lambda update-function-code \
          --function-name="${LAMBDA_FUNCTION_WORKER}" \
          --image-uri="${ECR_REPOSITORY_URL}:latest" \
        | jq '. | del(.Environment)'
