name: '[Frontend] Deploy User Web for prd'
on:
  push:
    tags:
    - 'v*'
    paths:
    - '.github/workflows/cd-web-user-for-prd.yaml'
    - 'web/user/**'
    - 'infra/docker/web/uer/**'

env:
  TZ: 'Asia/Tokyo'
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  APP_ID: ${{ secrets.PRD_AMPLIFY_USER_APP_ID }}
  BRANCH_NAME: main

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    name: build_and_deploy
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./web/user
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - uses: .github/actions/setup-aws
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to Amplify
      run: |
        aws amplify start-job \
          --app-id=${APP_ID} \
          --region=${AWS_REGION} \
          --job-type RELEASE \
          --branch-name=${BRANCH_NAME}
