name: '[Frontend] Deploy Admin Web for prd'
on:
  push:
    tags:
    - 'v*'
    paths:
    - '.github/actions/**'
    - '.github/workflows/_deploy_amplify.yaml'
    - '.github/workflows/cd-web-admin-for-prd.yaml'
    - 'web/admin/**'
    - 'infra/docker/web/admin/**'

env:
  TZ: 'Asia/Tokyo'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: deploy
    uses: ./.github/workflows/_deploy_amplify.yaml
    with:
      branch-name: main
      working-directory: ./web/admin
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      aws-region: ${{ secrets.AWS_REGION }}
      app-id: ${{ vars.PRD_AMPLIFY_ADMIN_APP_ID }}
