name: '[Docs] Build and Test'
on:
  push:
    paths:
    - '.github/workflows/ci-docs-for-all.yaml'
    - 'docs/swagger/**'

env:
  SERVICE: docs
  TZ: 'Asia/Tokyo'

jobs:
  setup:
    name: setup
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./docs/swagger
    strategy:
      matrix:
        os: [ubuntu-latest] # exclude: macos-latest, windows-latest
        node: ['18.0.0']
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: |
          **/node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ env.SERVICE }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Install
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn --check-files --frozen-lockfile --non-interactive

  lint:
    name: lint
    needs: setup
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./docs/swagger
    strategy:
      matrix:
        os: [ubuntu-latest] # exclude: macos-latest, windows-latest
        node: ['18.0.0']
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          **/node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ env.SERVICE }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Install
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn --check-files --frozen-lockfile --non-interactive

    - name: Lint
      run: yarn lint

  build:
    name: build
    needs: setup
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./docs/swagger
    strategy:
      matrix:
        os: [ubuntu-latest] # exclude: macos-latest, windows-latest
        node: ['18.0.0']
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          **/node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ env.SERVICE }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Install
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn --check-files --frozen-lockfile --non-interactive

    - name: Build
      run: yarn generate
