name: '[Docs] Build and Test'
on:
  push:
    paths:
    - '.github/workflows/ci-docs-for-all.yaml'
    - 'docs/swagger/**'

env:
  SERVICE: docs
  TZ: 'Asia/Tokyo'
  NODE_VERSION: 18.14.1

jobs:
  setup:
    name: setup
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./docs/swagger
    strategy:
      matrix:
        os: [ubuntu-latest] # exclude: macos-latest, windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: |
          **/node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ env.SERVICE }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Install
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn --check-files --frozen-lockfile --non-interactive

  lint:
    name: lint
    needs: setup
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./docs/swagger
    strategy:
      matrix:
        os: [ubuntu-latest] # exclude: macos-latest, windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          **/node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ env.SERVICE }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Install
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn --check-files --frozen-lockfile --non-interactive

    - name: Lint
      run: yarn lint

  build:
    name: build
    needs: setup
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./docs/swagger
    strategy:
      matrix:
        os: [ubuntu-latest] # exclude: macos-latest, windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          **/node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ env.SERVICE }}-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    - name: Install
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn --check-files --frozen-lockfile --non-interactive

    - name: Build
      run: yarn generate

  diff:
    name: diff
    needs: build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: .
    strategy:
      matrix:
        os: [ubuntu-latest] # exclude: macos-latest, windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install
      run: docker compose run --rm swagger_generator yarn

    - name: Build
      run: make swagger

    - name: Diff
      run: |
        git add -A
        if [ $(git diff HEAD | wc -l) != '0' ]; then exit 1; fi
