name: '[Frontend] Build and Test (Admin Web)'
on:
  push:
    paths:
    - '.github/actions/setup-node/**'
    - '.github/workflows/ci-web-admin.yaml'
    - 'web/admin/**'
    - 'infra/docker/web/admin/**'

env:
  SERVICE: admin-web
  TZ: 'Asia/Tokyo'

jobs:
  setup:
    name: setup
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./web/admin
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: ./.github/actions/setup-node
      with:
        working-directory: ./web/admin
        service: ${{ env.SERVICE }}

  lint:
    name: lint
    needs: setup
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./web/admin
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: ./.github/actions/setup-node
      with:
        working-directory: ./web/admin
        service: ${{ env.SERVICE }}

    - name: Lint
      run: yarn lint

  build:
    name: build
    needs: setup
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./web/admin
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: ./.github/actions/setup-node
      with:
        working-directory: ./web/admin
        service: ${{ env.SERVICE }}

    - name: Postinstall
      shell: bash
      run: yarn postinstall

    - name: Build
      run: yarn build

#   test:
#     name: test
#     needs: setup
#     runs-on: ${{ matrix.os }}
#     defaults:
#       run:
#         shell: bash
#         working-directory: ./web/admin
#     strategy:
#       matrix:
#         os: [ubuntu-latest]
#
#     steps:
#     - name: Check out code
#       uses: actions/checkout@v4
#
#     - uses: ./.github/actions/setup-node
#       with:
#         working-directory: ./web/admin
#         service: ${{ env.SERVICE }}
#
#     - name: Postinstall
#       shell: bash
#       run: yarn postinstall
#
#     - name: Test
#       run: yarn test
#
#     - uses: codecov/codecov-action@v3
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
#         fail_ci_if_error: true
#         flags: admin-web
#         verbose: true
