name: Pull Request Labeler
on:
- pull_request_target

jobs:
  add_labeler:
    name: add labeler when create pul request
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/labeler@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yaml
